### ISSUE TITLE
Watchdog t-rex 0.8.0 crash ubuntu

### ISSUE THREAD

**Issue by toptim** [trexminer/T-Rex#1]
Can you check?
t-rex file work fine
`20181122 17:10:10 
20181122 17:10:10 
20181122 17:10:11 T-Rex NVIDIA GPU miner v0.8.0  -  [CUDA v9.20]
20181122 17:10:11 
20181122 17:10:11 NVIDIA Driver v396.44
20181122 17:10:11 CUDA devices available: 12
20181122 17:10:11 
20181122 17:10:11 URL : stratum+tcp://rvn-pool.beepool.org:9531
20181122 17:10:11 USER: RRpoESGMjdfMEJ73GLLhU5hkSBKQZMXdmT.rig1
20181122 17:10:11 PASS: x
20181122 17:10:11 
20181122 17:10:11 WARN: Temperature limit is activated. Limit is set to 70C.
20181122 17:10:11 
20181122 17:10:11 Starting on: rvn-pool.beepool.org:9531
20181122 17:10:11 WARN: GPU #0: ASUS GeForce GTX 1070 Ti, intensity set to 20
20181122 17:10:11 WARN: GPU #1: ASUS GeForce GTX 1070 Ti, intensity set to 20
20181122 17:10:12 WARN: GPU #2: ASUS GeForce GTX 1070 Ti, intensity set to 20
20181122 17:10:12 WARN: GPU #3: ASUS GeForce GTX 1070 Ti, intensity set to 20
20181122 17:10:12 WARN: WATCHDOG: inuse sign disappeared, restart T-Rex
20181122 17:10:12 WATCHDOG: terminating process 7769
20181122 17:10:12 WARN: WATCHDOG: T-Rex was killed
20181122 17:10:12 WARN: WATCHDOG: detected crash on start. Watchdog deactivated. 
20181122 17:10:12 WATCHDOG: watchdog finished
`

**Comment by trexminer** [comment]
Thanks. We're aware of this problem. Will be fixed in future releases of watchdog.

**Comment by toptim** [comment]
Fix now

**Comment by trexminer** [comment]
Linux watchdog is now available. Download at https://github.com/trexminer/T-Rex-Watchdog/releases/tag/0.4.1
