### ISSUE TITLE
Invalid Shares

### ISSUE THREAD

**Issue by arditretkoceri** [trexminer/T-Rex#100]
All my rigs have 100% invalid shares what to do ?
![63BBD3CA-D369-4F56-B35C-D31EAB3C1509](https://user-images.githubusercontent.com/75205631/100540978-2df18c80-3241-11eb-8bf7-b3f94faf151f.png)

**Comment by arditretkoceri** [comment]
![Uploading 74A08787-8A62-438A-97D9-E055CA5B3840.png…]()

**Comment by trexminer** [comment]
ETC forked and their algorithm is now `etchash`

**Comment by arditretkoceri** [comment]
thanks 🙏🏻
