### ISSUE TITLE
Abrupt shutdown: T-rex instance wasn't validated

### ISSUE THREAD

**Issue by mr3j** [trexminer/T-Rex#1009]
So, my breaker sometimes trips and the miner of course abruptly powers down. Well, I gave it a few minutes to rest and powered back up to discover that T-Rex miner isn't working properly.

It opens command prompt to load up and then pauses and hangs after starting DAG and whatever else, "T-rex instance wasn't validated."

Went ahead and rebooted the miner and that did not fix it.
Next, I directed the config at a new mining pool and that did not work. (E.g. switched from us1 to us2 ethermine.)

**Comment by mondychan** [comment]
same error started popping
https://srv1.trex-miner.com/
i think the certificate has some problem?

**Comment by chaotixdk** [comment]
I just took one of my miners offline for maintenance and I'm getting this same error. Never seen it before. Could trex's servers be experiencing issues?

**Comment by raymondkpwong** [comment]
Same here.

```
$ curl -k  https://srv1.trex-miner.com
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to srv1.trex-miner.com:443 
$ _
```

**Comment by chrisdahalo** [comment]
a workaround was given here https://github.com/trexminer/T-Rex/issues/984

**Comment by chaotixdk** [comment]
Pool connections appear to be fine, it's the connection to the trex dev server. The miner will restart within 30 seconds of initialization, so you'd just be continually restarting every 30 seconds.

**Comment by trexminer** [comment]
There was a problem with the dev fee servers, it should be fixed now. I'm really sorry for the inconvenience.

**Comment by Konageski** [comment]
I'm getting these errors when I use the ASUS AG-AC53U router, if I access using the modem I don't have this problem. It keeps restarting every 1 minute. With other miners this does not happen. Would there be a solution to this problem?

**Comment by Konageski** [comment]
curl -verbose -k https://trex-miner.com
*   Trying 54.36.103.55:443...
* Connected to trex-miner.com (54.36.103.55) port 443 (#0)
* schannel: disabled automatic use of client certificate
* schannel: ALPN, offering http/1.1

The conection stop in this part.

**Comment by hoangtnm** [comment]
This issue has just happened again since today.
