### ISSUE TITLE
please help how to fix this issue i have 7 3060 but i found this issue in one card only!!!

### ISSUE THREAD

**Issue by ROCKET0101** [trexminer/T-Rex#1014]
![ssss](https://user-images.githubusercontent.com/92781808/150732661-6eb38b9c-d0bd-4dea-b961-2b155ef5a7ce.PNG)

I replace the 5 riser's but issue is not fix please help me t-rex.. also change the overclock setting only one card give me this probem

**Comment by trexminer** [comment]
https://github.com/trexminer/T-Rex/wiki/FAQ#what-are-error-codes-15-and-999
