### ISSUE TITLE
GPU sensor info missing

### ISSUE THREAD

**Issue by dmallor** [trexminer/T-Rex#1018]
Once I started running multiple cards I noticed power, temp, fan speed no longer show up in t-rex web page.  Checking manually with nvidia-smi and all of the data is there.  Was not working on previous version nor on latest 0.24.8. 

![screenshot1](https://user-images.githubusercontent.com/44278448/151202827-bf2db7e0-a0e4-4c14-817f-561f5c35ff17.png)
![screenshot1](https://user-images.githubusercontent.com/44278448/151202796-a435f22e-55b5-4e97-956d-6177e31c6020.png)

**Comment by dmallor** [comment]
![screenshot2](https://user-images.githubusercontent.com/44278448/151202934-a591a9cf-015a-4c4c-a549-fbe31c2cd77e.png)

**Comment by dmallor** [comment]
> 
20220126 10:57:51 
20220126 10:57:51 WARN: Can't load NVML library, dlopen(2): failed to load libnvidia-ml.so, libnvidia-ml.so: cannot open shared object file: No such file or directory
20220126 10:57:51 WARN: NVML error, code 12
20220126 10:57:51 WARN: Can't initialize NVML. GPU monitoring will be disabled.

find ./|grep libnvidia-ml.so
./etc/alternatives/nvidia--libnvidia-ml.so.1-x86_64-linux-gnu
./usr/lib/x86_64-linux-gnu/nvidia/current/libnvidia-ml.so
./usr/lib/x86_64-linux-gnu/nvidia/current/libnvidia-ml.so.418.211.00
./usr/lib/x86_64-linux-gnu/nvidia/current/libnvidia-ml.so.1
./usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1

**Comment by trexminer** [comment]
No prob
