### ISSUE TITLE
Memory tweak mode on GDDR6X

### ISSUE THREAD

**Issue by nils-trubkin** [trexminer/T-Rex#102]
Hi, I have a question.

Does this feature do anything useful? Is it working on GDDR6X cards like RTX3080 or completely unsupported?

`--mt                       Memory tweak mode (default: 0 - disabled). Range from 0 to 6. General recommendation
                                   is to start with 1, and then increase only if the GPU is stable.
                                   The effect is similar to that of ETHlargementPill.
                                   Supported on graphics cards with GDDR5 or GDDR5X memory only.
                                   Requires running the miner with administrative privileges.
                                   Can be set to a comma separated list to apply different values to different cards.
                                   Example: --mt 4 (applies tweak mode #4 to all cards that support this functionality)
                                            --mt 3,3,3,0 (applies tweak mode #3 to all cards except the last one)`

**Comment by trexminer** [comment]
As mentioned in the help info you copied, memory tweaks only work with GDDR5 and GDDR5X cards. GDDR6X is not supported.
