### ISSUE TITLE
ERROR: Invalid extranonce2 size when run autolykos2 algo with NiceHash pool

### ISSUE THREAD

**Issue by amdsys** [trexminer/T-Rex#1020]
I'm using T-Rex 0.24.8, and this issue occurred since last week.

20220104 00:50:21 autolykos2 [FAIL] 5505/5703 - Invalid extranonce2 size., 173ms ... GPU #0

I'm now recieving this error full bore and getting 100 percent failure rate on mining ERGO on nicehash. Can T-Rex team PLEASE work on this issue?

I tried NBminer today and they don't have this error. Trex problem is still persist.

**Comment by angelbbs** [comment]
+1

**Comment by BitMaci** [comment]
Please add extranonce support for NIcehash, NBminer and Nanominer doesn't show that issue.

**Comment by eblieb** [comment]
Haing teh same Issue

**Comment by i1itione** [comment]
It seems that this issue still exists in T-Rex 0.25.9, and it causes about 1%~1.3% rejected shares.

**Comment by IordX** [comment]
tested on 0.25.9 , same problem autolykos2 + nicehash + trex = fail 
lots of Invalid extranonce2 size

**Comment by Miiichal** [comment]
0.26.4
RTX 3070 rigs
the same error - about 30-70pct invalid extranonce size

**Comment by jelegend** [comment]
@Miiichal did you find a workaround yet ? NBminer does not work for meas it keeps crashing after few hours giving error illegal memory access even though i have lowered the OC.

**Comment by Miiichal** [comment]
Using NBminer gives me a chance to mine Autolykos.
TRex has got a better hashrate (for about 1.5 MH/s with the same OC
settings) and better efficiency. So for me "the solution" was another
excavator. But of course - id like to have TRex again.

Odesláno z telefonu Sony Xperia 10 III

Dne ne 3. 7. 2022 8:13 uživatel jelegend ***@***.***> napsal:

**Comment by zarovavelfed** [comment]
Still have this problem on T-Rex NVIDIA GPU miner v0.26.5  -  [Windows]
