### ISSUE TITLE
FAQ should specify that memory temps are Windows only

### ISSUE THREAD

**Issue by ad1344** [trexminer/T-Rex#1025]
Title pretty much says it all. I switched to T-rex because of the memory temp feature only to find out it doesn't work on Linux. And I found that in an issue, would have been useful if it's more prominent in the readme/wiki

**Comment by trexminer** [comment]
Thanks. Done.

**Comment by FMEM** [comment]
请问如何解决，T-REX内存占用得问题？W10

**Comment by FMEM** [comment]
readme中得指令是？
