### ISSUE TITLE
Hash rate drops and doesn't restart.

### ISSUE THREAD

**Issue by mattfaraday** [trexminer/T-Rex#1029]
I have a box that has two cards in it. One is a 1080 Ti. 

Every now and then I see my hash rate drop by the amount this card puts in, so I go log into the host and I see that this card is doing like 1 or 2 MH/s (instead of it's usual 40) and when I restart t-rex it goes back up again. If I leave it, it will stay working at 1 or 2 MH/s until I restart it. 

Shouldn't the built in watchdog catch this? 

Would it be possible to add some sort of restart on low hash rate option ? 

Box: Ryzen 7 5700G/32GB
GPUs: MSI RTX 3060 Ti + Asus 1080 Ti 
OS: Windows 11 
T-rex: v.0.24.8

**Comment by trexminer** [comment]
Check out `--script-low-hash` parameter, you can implement your own logic in the custom script, including killing a process, starting a new one, etc.

**Comment by mattfaraday** [comment]
exactly what i needed. thanks.
