### ISSUE TITLE
Can't handle stratum method in payload + Only GPU#0 Detected

### ISSUE THREAD

**Issue by adiel91** [trexminer/T-Rex#1031]
Trying to switch over from clay miner to trex. Using configuration file, and unable to mine.
"Custom" JSON file settings i've applied:

`"url": "stratum+tcp://asia2.ethermine.org:4444", // pool url`
`"coin" : "eth"`
`"dag-build-mode": 2`

Yet log shows only warnings and also detects only single GPU.
To clarify: In clayminer i'm able to detect and mine through both GPUs.
I have rtx 3090 and rtx 3070 in this rig.

log start: (Notice minus sign on 2nd GPU + Can't handle stratum method in payload)

`20220203 17:24:40 NVIDIA Driver v497.29
20220203 17:24:40 
20220203 17:24:40 + GPU #0: [00:01.0|2204] GeForce RTX 3090, 24575 MB
20220203 17:24:40 - GPU #1: [00:02.0|2484] GeForce RTX 3070, 8191 MB
20220203 17:24:40 
20220203 17:24:40 WARN: DevFee 1% (kawpow)
20220203 17:24:40 
20220203 17:24:40 === MAIN POOL === | back to main in 10 mins |
20220203 17:24:40 URL : asia2.ethermine.org:4444
20220203 17:24:40 USER: 0x61bb3E2Db6d6B69108D332455AD32EFf036915B4
20220203 17:24:40 PASS: x
20220203 17:24:40 WRK : BidaniEth.Trex1
20220203 17:24:40 
20220203 17:24:40 URL : asia1.ethermine.org:4444
20220203 17:24:40 USER: 0x61bb3E2Db6d6B69108D332455AD32EFf036915B4
20220203 17:24:40 PASS: x
20220203 17:24:40 WRK : BidaniEth.Trex2
20220203 17:24:40 
20220203 17:24:40 Starting on: asia2.ethermine.org:4444
20220203 17:24:40 Using protocol: stratum3.
20220203 17:24:40 Authorizing...
20220203 17:24:40 Authorized successfully.
20220203 17:24:40 ApiServer: HTTP server started on 127.0.0.1:4067
20220203 17:24:40 ---------------------------------------------------
20220203 17:24:40 For control navigate to: http://127.0.0.1:4067/trex
20220203 17:24:40 ---------------------------------------------------
20220203 17:24:40 GPU #0: intensity 20
20220203 17:24:42 WARN: Can't handle stratum method in payload {"id":6,"jsonrpc":"2.0","method":"mining.notify","params":["d4f79c4fde6b1e43a3583e3892c26f8cd0c023cf2223207f129132fb5e336d73","d4f79c4fde6b1e43a3583e3892c26f8cd0c023cf2223207f129132fb5e336d73","81bac9757acc0362aabbb7dcf54902ae4037caf614aabe357f5a0d94dadc2302","00000000ffff00000000ffff00000000ffff00000000ffff00000000ffff0000",false]}
, Value is not convertible to Int64.`

**Comment by trexminer** [comment]
Looks like you haven't modified the algorithm (it's a set to `kawpow`, but you need `ethash` for ETH) and a bunch of other parameters set in the json config.

**Comment by adiel91** [comment]
> Looks like you haven't modified the algorithm (it's set to `kawpow`, but you need `ethash` for ETH) and a bunch of other parameters set in the json config.

Hi,
According to the README.md the only param for setting algorithm is --lhr-algo, which is relevant to LHR Cards as far as i understand.
my cards are not LHR, but i'll try to set this regardless. i thought by specifying coin eth should be enough.
what bunch of other parameters should i set?

Thank you for your help

**Comment by adiel91** [comment]
@trexminer thank you - i've missed the "algo" parameter! now its mining. but still i see it doesn't use 2nd GPU. what am i missing?
Thanks

**Comment by trexminer** [comment]
Glad you figured it out.
`config_example` contains all parameters T-Rex supports, and typically you only need to use a small subset of them, so I'd recommend creating a new config file from scratch (you can see what parameters are necessary in the bat files that come with the miner) and only put in the parameters you actually need.
