### ISSUE TITLE
Windows 10 trojan:win32/Detplok

### ISSUE THREAD

**Issue by aaleeshaikh** [trexminer/T-Rex#1033]
windows 10 is not letting me run this file and showing this virus info. how lethal is this and pls help me what to do?

**Comment by aaleeshaikh** [comment]
![Screenshot 2022-02-03 221246](https://user-images.githubusercontent.com/94249965/152393574-f07a7601-d01a-4eb1-9b0c-662995955ea6.png)

**Comment by trexminer** [comment]
https://github.com/trexminer/T-Rex#antivirus-alerts
You need to add T-Rex to the exception list of your antivirus
