### ISSUE TITLE
0.25.2 is much worse on the 3080 12GB LHR

### ISSUE THREAD

**Issue by GenCodeInc** [trexminer/T-Rex#1034]
0.25.2 is much worse on the 3080 12GB 
It now sees its LHR but the hash rate dropped from 62 way down to 51 :-(

EVGA 3080 12GB FTW

**Comment by rayven96** [comment]
same problem

**Comment by GenCodeInc** [comment]
> same problem
No one supports 3080 12GB yet :(

**Comment by trexminer** [comment]
@GenCodeInc Set `--lhr-tune` to `0` for your 3080 to get the hashrate back to 62.

**Comment by GenCodeInc** [comment]
> @GenCodeInc Set `--lhr-tune` to `0` for your 3080 to get the hashrate back to 62.
That worked, thanks for all your hard work and help.  Hopefully next version 3080 12GB is supported,  I cant wait to see what it can unlock once supported.

**Comment by marcioaneves** [comment]
Same problem in 3080 TI 12Gb. :-(

**Comment by trexminer** [comment]
@marcioaneves see my reply above

**Comment by shlcyi** [comment]
> @GenCodeInc Set `--lhr-tune` to `0` for your 3080 to get the hashrate back to 62.

when will miner support lhr mode on 3080 12g？
We're looking forward to it.

**Comment by marcioaneves** [comment]
> @marcioaneves see my reply above. I assume you meant 3080 12GB.

My GPU model is 3080 **TI** 12GB and its gets mhs 70 hashrate. If I apply the  "--lhr-tune to 0",  Can GPU can increase the hashrate ?

**Comment by daveygm** [comment]
> 0.25.2 is much worse on the 3080 12GB It now sees its LHR but the hash rate dropped from 62 way down to 51 :-(

Same for me on Asus Strix 3080 12GB.
