### ISSUE TITLE
T-Rex 0.25.2 dual mining on hiveos with ETH + ALPH doesn't work

### ISSUE THREAD

**Issue by flyeric777** [trexminer/T-Rex#1036]
Hello,

I've tried to dual mining ETH + ALPH specifiying Woolypooly or Herominers and trying also different arguments, it doesn't work.
I've always have N/A beside the GPU.

Could you give an example of the parameters required to work please?

Thank you.

**Comment by StormVoid** [comment]
3080 ti is always crashing when iam connecting on rdp on default setting, same problem at all settings witch was work on solo eth, also crashing after ~30 minutes of mining

**Comment by tjayz** [comment]
t-rex.exe --lhr-tune 68.9 --lhr-autotune-mode off --lhr-autotune-interval 15 --lhr-autotune-step-size 0.2 --lock-cclock 1155 --fan 75 --lock-cv 715 --mclock 1650 --kernel 4 --dag-build-mode 2 --ab-indexing -a ethash --lhr-algo blake3 -o stratum+ssl://pool -u wallet  --url2 stratum+ssl://pool.woolypooly.com:3106 --user2 wallet -d 1 --pstate p0

EVGA 3080 10GB black series stable on those settings. Trex needs to be set to run as admin. Have lhr-autotune-mode full till find sweet spot then set to off. At current crypto prices I sacrifice 6mhs of eth for 415mhs of alph for 0.40 USD more profit per day. Temps on vram 10c lower on the dual mine.

**Comment by flyeric777** [comment]
Thank you very much tjayz for your help and the arguments.
I keep it with me.
My problem is that for the moment hiveos does not accept arguments so, gonna work on it and try to find a solution.
Many thanks again for the help and get back as soon as i will have solve it :-)

**Comment by Lee5331** [comment]
I had the same issue to fix it I put "lhr-algo": "blake3" in the Extra config arguments section inside the miner config section in Hiveos.

**Comment by flyeric777** [comment]
Many thanks for your feedback Lee5331,

Please, could you show more parameters for the extra arguments because from my side, it still doesn't work.

I have this and nothing more:

"devices": "1"
"lhr-algo": "blake3"

Do ihave to specify the wallet address (normally it is already specified inn the wallet section for my case).

Thank you very much.

**Comment by Lee5331** [comment]
Yup will do, also under version manually choose version 0.25.2, for some reason HiveOS was choosing 0.24.8 for me when I had the latest selected.

**Comment by Lee5331** [comment]
Also set the second coin intensity to 68
![image](https://user-images.githubusercontent.com/91811864/152667340-35757c44-d151-4d38-bfa5-534b27a2cb49.png)

**Comment by flyeric777** [comment]
Yesssssssssssss,

Fantastic Lee, it works !

Thank you so much for your precious help.

Have a great day Lee :-) :-) :-)

**Comment by Lee5331** [comment]
Your welcome, glad to help. Happy mining!

**Comment by flyeric777** [comment]
Thank you very much Lee, yessssss :-)
