### ISSUE TITLE
What is the difference between version 0.25.1 to 0.25.2 ?

### ISSUE THREAD

**Issue by francisco-preto** [trexminer/T-Rex#1038]
Hi, can you inform what is the difference between version 0.25.1 to 0.25.2 ?

**Comment by trexminer** [comment]
0.25.1 had a bug where the miner was sending invalid shares when mining in ETH+ALPH dual mode. 0.25.2 fixes it.

**Comment by francisco-preto** [comment]
Thanks a lot

Em sex., 4 de fev. de 2022 às 13:43, trexminer ***@***.***>
escreveu:
