### ISSUE TITLE
Your competitor has been updated.

### ISSUE THREAD

**Issue by buxstore** [trexminer/T-Rex#104]
optimize: ethash Improve hashrate 1% on certain Nvidia GPUs

optimize: octopus Minor improvement on certain 20 & 30 series Nvidia GPUs

feature: -mt More effective and compatibility on Geforce Pascal GPUs

fix: kawpow progpow_sero Fix crash on certain AMD & Nvidia rigs

**Comment by buxstore** [comment]
https://github.com/NebuTech/NBMiner/releases/tag/v34.5

**Comment by trexminer** [comment]
Thanks for letting us know.
There are a lot of mining apps out there, and all developers update their software. I'm not sure how that makes it an issue we need to track in Github though?

**Comment by buxstore** [comment]
Your hashrate is lower than that nbminer. Catch up

**Comment by trexminer** [comment]
Creating a github issue for that just doesn't make any sense
