### ISSUE TITLE
can't start T-rex. second mining algo wasn't set, use --lhr-algo

### ISSUE THREAD

**Issue by saipavan1223** [trexminer/T-Rex#1046]
<img width="1173" alt="Screen Shot 2022-02-05 at 11 10 59 AM" src="https://user-images.githubusercontent.com/13970630/152652076-e2a820ea-ac90-499d-a68b-b3e4bc86f1cc.png">

**Comment by saipavan1223** [comment]
I'm using hiveos and when I try to dual mine in my flight sheet it did select second hash algorithm as "blake3" but I still get this error and can't mine, please help

**Comment by Lee5331** [comment]
I had the same issue to fix it I put "lhr-algo": "blake3" in the Extra config arguments section inside the miner config section in Hiveos.
