### ISSUE TITLE
Error “can’t adjust autofan since 0.24.8 error code -137

### ISSUE THREAD

**Issue by Stigz-19** [trexminer/T-Rex#1047]
Hey. I can’t update my trex from 0.24.7 due to “can’t adjust autofan error” code -137
I’m using this release and works fine but when update to 0.24.8 or the new 0.25.2 the miner won’t work fine because of this error. I’m using the same setting, tried remove all settings just leaving the autofan but the same error all the time “- -fan tn:88[80-100]
anyone knows how to fix it? I really wanna try dual mining

**Comment by trexminer** [comment]
Running the miner with admin privileges should fix it
