### ISSUE TITLE
 Can't handle stratum method in payload , can't parse json - mining Alephium using t-rex

### ISSUE THREAD

**Issue by jeromeinfotech** [trexminer/T-Rex#1048]
C:\windows\system32>C:\Mining\t-rex-0.25.2-win\t-rex.exe -a blake3 -o stratum+tcp://us.alephium.herominers.com:1199 -u 13.....................mzdrczijznNUt -p x -w rig0
20220205 22:09:47 T-Rex NVIDIA GPU miner v0.25.2  -  [Windows]
20220205 22:09:47 r.779ea9fe653f
20220205 22:09:47
20220205 22:09:47
20220205 22:09:47 NVIDIA Driver v471.41
20220205 22:09:47
20220205 22:09:47 + GPU #0: [00:06.0|2216] HP GeForce RTX 3080, 10240 MB
20220205 22:09:47
20220205 22:09:47 WARN: DevFee 1% (blake3)
20220205 22:09:47
20220205 22:09:47 URL : stratum+tcp://us.alephium.herominers.com:1199
20220205 22:09:47 USER: 13h.....................mzdrczijznNUt
20220205 22:09:47 PASS: x
20220205 22:09:47 WRK : rig0
20220205 22:09:47
20220205 22:09:47 Starting on: us.alephium.herominers.com:1199
20220205 22:09:47 ApiServer: HTTP server started on 127.0.0.1:4067
20220205 22:09:47 ---------------------------------------------------
20220205 22:09:47 For control navigate to: http://127.0.0.1:4067/trex
20220205 22:09:47 ---------------------------------------------------
20220205 22:09:47 GPU #0: intensity 26.5
20220205 22:09:47 Authorizing...
20220205 22:10:06 WARN: Can't handle stratum method in payload , can't parse json:
* Line 1, Column 1
  Syntax error: value, object or array expected.

20220205 22:10:57 Authorized successfully.
-------------------20220205 22:10:57 --------------------
Mining at us.alephium.herominers.com:1199 [no connection]
20220205 22:10:57 WARN: Connection with pool us.alephium.herominers.com:1199 timed out. Trying to reconnect...
GPU #0: HP RTX 3080 - 0.00 H/s, [T:24/30C, P:20W, F:70%, E:0.00H/W]
Shares/min: 0
Uptime: 1 min 10 secs | Algo: blake3 | T-Rex v0.25.2

20220205 22:10:57 Authorizing...

Any suggestion on how to resolve the above error ? I tried with different pools similar outcome.

**Comment by trexminer** [comment]
It's working fine for me. Perhaps a firewall issue?

**Comment by Lui-SB** [comment]
Any solutions on this? I got same issues on this..

**Comment by jeromeinfotech** [comment]
For anyone looking at this  thread ... 

use stratum+ssl rather than stratum+tcp which will fix the issue

**Comment by jeromeinfotech** [comment]
Thanks for the support
