### ISSUE TITLE
0 H/s on aleph+eth mining

### ISSUE THREAD

**Issue by Omartara** [trexminer/T-Rex#1051]
I think I have set up succesfully but I see 0 hashrate for both eth and aleph on hiveos.  

![Screenshot 2022-02-06 224144](https://user-images.githubusercontent.com/61665305/152698491-9a3d2747-5b9c-40f3-9445-ea6a250e2e4a.png)

![Screenshot 2022-02-06 224211](https://user-images.githubusercontent.com/61665305/152698493-bd271fcf-e58b-4c1c-84a8-ea6286a633e3.png)

**Comment by trexminer** [comment]
Could you post the full log please?

**Comment by Omartara** [comment]
sure. I have restarted the algorithm. here is logs and I am getting the below error while starting.
![Screenshot 2022-02-07 110604](https://user-images.githubusercontent.com/61665305/152749005-e87ea031-8266-487c-b45b-9996b9cf26ad.png)
![Screenshot 2022-02-07 110226](https://user-images.githubusercontent.com/61665305/152749021-cff49974-6e82-43f3-a233-f37294219334.png)
![Screenshot 2022-02-07 110548](https://user-images.githubusercontent.com/61665305/152749026-323746a9-8097-4032-8f16-4e427576d6d1.png)

**Comment by hannsu** [comment]
Same here, have met the exactly issue.

**Comment by GrzegorzWo** [comment]
As I can see, you have incorrectly configured ALPH wallet. Address visible in log, you forward to Alph mining pool looks like Eth wallet address (starting from 0x, 40-chars long). Alph wallet is without 0x prefix and is 45-chars long.
Correct Alph wallet configuration and try again.

**Comment by Omartara** [comment]
it worked. thanks
