### ISSUE TITLE
Count of failed shares in summary

### ISSUE THREAD

**Issue by OverchenkoDev** [trexminer/T-Rex#106]
There is no information about failed shares in the answer from summary request.  Is there a way to know it?

**Comment by trexminer** [comment]
Actually this information exists(stat_by_gpu[].rejected_count). Here is the full /summary output.

{
	"accepted_count": 2,
	"active_pool": {
		"difficulty": "215.59 Mh",
		"ping": 59,
		"retries": 0,
		"url": "stratum+tcp://europe.kawpow-hub.miningpoolhub.com:20611",
		"user": "somaton.ryzen"
	},
	"algorithm": "kawpow",
	"api": "3.3",
	"build_date": "Dec 11 2020 07:18:57",
	"coin": "",
	"cuda": "11.10",
	"description": "T-Rex NVIDIA GPU miner",
	"difficulty": 0.055050000000000002,
	"driver": "455.32.00",
	"gpu_total": 1,
	"gpus": [{
		"device_id": 0,
		"efficiency": "108kH/W",
		"gpu_id": 0,
		"gpu_user_id": 0,
		"hashrate": 12464884,
		"hashrate_day": 0,
		"hashrate_hour": 0,
		"hashrate_instant": 12067406,
		"hashrate_minute": 12464884,
		"intensity": 20.0,
		"low_load": false,
		"mtweak": 0,
		"name": "GTX 1070",
		"power": 121,
		"power_avr": 115,
		"temperature": 73,
		"vendor": "NVIDIA"
	}],
	"hashrate": 12464884,
	"hashrate_day": 0,
	"hashrate_hour": 0,
	"hashrate_minute": 12464884,
	"name": "t-rex",
	"os": "linux",
	"rejected_count": 0,
	"revision": "3697491896ff",
	"sharerate": 2.0,
	"sharerate_average": 2.2669999999999999,
	"solved_count": 0,
	"stat_by_gpu": [{
		"accepted_count": 2,
		"rejected_count": 0,
		"solved_count": 0
	}],
	"success": 1,
	"ts": 1607666549,
	"uptime": 73,
	"velocities": {
		"hashrate": [
			[1607666547, 12469439]
		],
		"power": [
			[1607666547, 121]
		]
	},
	"version": "0.19.1",
	"watchdog_stat": {
		"built_in": true,
		"startup_ts": 1607666476190141,
		"total_restarts": 0,
		"uptime": 73,
		"wd_version": "0.19.1"
	}
}

**Comment by OverchenkoDev** [comment]
@trexminer but failed shares and rejected shares are two different types. It seems that they must be divided in summary response like other miners do it.

**Comment by trexminer** [comment]
What do you mean by "failed" shares? From the miner perspective, all submissions get either accepted or rejected by the mining pool. The exact error messages sent by pools vary a lot though.

**Comment by trexminer** [comment]
Invalid and rejected shares are now separated if the miner is launched with `--validate-shares`
