### ISSUE TITLE
NVIDIA Driver 511.65 cuts hashrates in half (ETH) (3070ti-LHR)

### ISSUE THREAD

**Issue by tmesiss** [trexminer/T-Rex#1060]
I'm mining in Windows 10 with T.Rex v0.25.2

Using a EVGA 3070ti. Once I upgraded my nvidia driver from 511.23 to 511.65 the hashrates dropped to as low as 6mh/s and stabilized around ~22mh/s. 

SOLUTION: 
I had to use DDU to uninstall 511.65 and reinstall 511.23. Once back on 511.23 the hashrates are back to high 50mh/s for the 3070ti.

**Comment by tjayz** [comment]
Drivers 472.39/47 I am able to get LHR stable in 75-76.1 range depending on card. 511.65 all went down to LHR 73-74 range which lowered hashrate a lot but not as much as you reported. Much more stability from those older versions may want to test em out.

**Comment by spcambo** [comment]
> 

I'm using Auros 3070ti I got 59-60Mh/s. Lock cclock 900, mem 1450 - 1500. U should try it
