### ISSUE TITLE
Nvidia GTX 3090 not working

### ISSUE THREAD

**Issue by kgunfun** [trexminer/T-Rex#1061]
I have been mining as a hobbyist with this card for almost a year and it just suddenly stopped working.  Here is what is happening:

![image](https://user-images.githubusercontent.com/99229105/152903223-7fb56642-bc48-4a2f-b903-f89f46746d12.png)

**Comment by kgunfun** [comment]
![image](https://user-images.githubusercontent.com/99229105/152903181-c654d383-0cfe-479d-ba7a-ab942f8a770b.png)

**Comment by GrzegorzWo** [comment]
Please verify if your nvidia driver was not updated automatically by Windows Update - this would explain why suddenly miner stopped to work.
From the other hand - I can see, you are using old t-rex miner (version 0.21.5, release in July 2021). I would recommend to update to latest t-rex version.

**Comment by trexminer** [comment]
Running the miner with admin privileges should fix the issue.
