### ISSUE TITLE
Feature to set LHR hash rate targets

### ISSUE THREAD

**Issue by sggoodson** [trexminer/T-Rex#1062]
relating to #996 

Adding the ability to set LHR hash rate targets.

Targets for 3080 12GB are current set to a normal 3080, when perhaps they should be closer to the 3080ti

**Comment by trexminer** [comment]
You can "change" hashrate targets by changing LHR tune value (`--lhr-tune`).
The miner benchmarks the GPU and then multiplies the result by LHR tune value divided by 100.
