### ISSUE TITLE
Spelling mistake in "Hôte inconnu"

### ISSUE THREAD

**Issue by Whitole** [trexminer/T-Rex#1065]
Spelling mistake in the word "Hôte inconnu"

![image](https://user-images.githubusercontent.com/80005002/153042597-e70f85a0-3a1b-4464-ae92-6c9e5c4589aa.png)

T-Rex 0.25.2
Operating System: Windows 11 Professionnel 64-bit (10.0, Build 22000) (22000.co_release.210604-1628)
Language: French (Regional Setting: French)
System Manufacturer: ASUS
System Model: System Product Name
BIOS: 1203 (type: UEFI)
Processor: 11th Gen Intel(R) Core(TM) i7-11700KF @ 3.60GHz (16 CPUs), ~3.6GHz
Memory: 32768MB RAM

**Comment by trexminer** [comment]
Thanks for reporting, but we can't fix it. Localisation is handled by third party libraries we use.
