### ISSUE TITLE
Mining problem 

### ISSUE THREAD

**Issue by awesome483435** [trexminer/T-Rex#1066]
Thi

20220208 11:16:31 T-Rex NVIDIA GPU miner v8.21.6 - [Windows]

20220208 11:16:31

r.3ea03a096378 20220208 11:16:31

20220208 11:16:31 NVIDIA Driver v432.00

20220208 11:16:31 CUDA devices available: 2

20220208

11:16:31

20220208 11:16:31 20220208 11:16:31

WARN: DevFee 1% (ethash)

20220208 11:16:31 URL: stratum+tcp://ethash.poolbinance.com:1800

20220208 11:16:31 USER: RASEL2211

20220208

11:16:31 PASS: x 20220208 11:16:31 WRK: rasel

Recyc20220208 11:16:31

20220208 11:16:31 Starting on: ethash.poolbinance.com: 1800 20220208 11:16:31 Using protocol: stratumi.

20220208 11:16:31 Authorizing...

20220208 11:16:31 ERROR: Can't start miner, GeForce GTX 650 Ti BOOST (CC 3) is not supported 20220208 11:16:31 WARN: failed to ethproxy-subscribe on ethash.poolbinance.com:1800: can't parse json: Contro Line 1, Column 1

Syntax error: value, object or array expected.

20220208 11:16:31 ERROR: No connection, retry after 10 seconds 20220208 11:16:31 GPU #0(000100): ASUS GeForce GTX 1070, intensity 22

Goe20220288 11:16:32 T-Rex finished.

Chr

C:\Users\RASEL\Desktop\t-rex>pause
![IMG_20220208_221701](https://user-images.githubusercontent.com/99287671/153061089-7fca35ab-9ee5-4dde-b137-9a21ed5cc21e.jpg)

**Comment by trexminer** [comment]
Your GPU (GTX 650 Ti) is too old and is not supported. You can exclude it by running the miner with `--devices 0`.
