### ISSUE TITLE
Setting api_key gives authorization error

### ISSUE THREAD

**Issue by TomislavHorvat1** [trexminer/T-Rex#1068]
Use case:
 1. Set the `api_key` in the `config` to string `5r4e3w2q1`
 2. Run the miner from console with `./t-rex -c config.json`
 3. Go to `http://127.0.0.1:4067/trex` from browser

Expected:
- enter the dashboard by providing `5r4e3w2q1` when asked for the password

Observed:
- the login returns an authorization error for the exact string (even copied from the config file directly)

T-Rex version: T-Rex NVIDIA GPU miner v0.25.2  -  [Linux]
OS: Pop!_OS 21.10

**Comment by trexminer** [comment]
API key is not the password, it is generated from it. See https://github.com/trexminer/T-Rex/wiki/WebUI#security.
