### ISSUE TITLE
ETH+ALPH % Percentage change ?

### ISSUE THREAD

**Issue by solidddsnake** [trexminer/T-Rex#1070]
Hello, in the [T-Rex 0.25.2] Release page, it says : "Add ETH+ALPH dual mining mode for LHR cards (**ETH 68% / ALPH 32% by default**)" Can we change this percentage ? if so, how ?

Thanks !

**Comment by Volkann1234** [comment]
Use --lhr-tune to set the percentage of ETH percentage
--lhr-tune 70 for ETH 70% / ALPH 30
--lhr-tune 65 for ETH 65% / ALPH 35
