### ISSUE TITLE
NVM code error 1 Since 0.19.3

### ISSUE THREAD

**Issue by killasaika** [trexminer/T-Rex#108]
The version 0.19.3 Fix the problems with drivers 460.79
But for me it creat a new problem:

20201211 21:00:17 T-Rex NVIDIA GPU miner v0.19.3  -  [CUDA v11.10 | Windows]
20201211 21:00:17 r.ce2401a4e806
20201211 21:00:17
20201211 21:00:17 WARN: NVML error, code 1
20201211 21:00:17 NVIDIA Driver version N/A
20201211 21:00:17 CUDA devices available: 1
20201211 21:00:17
20201211 21:00:17 WARN: DevFee 1% (ethash)
20201211 21:00:17
20201211 21:00:17
20201211 21:00:17 WARN: NVML is disabled. You won't see GPUs stats.
20201211 21:00:17
20201211 21:00:17 WARN: Can't initialize NVML. GPU monitoring will be disabled.

But i can mine without problem i just can't have info on GPU (Degres, power etc)

**Comment by trexminer** [comment]
NVML is broken in v460.79, waiting for the fix from NVIDIA

**Comment by trexminer** [comment]
Fixed in 0.19.4
