### ISSUE TITLE
Then ETH + TON for LHR cards

### ISSUE THREAD

**Issue by DMX555** [trexminer/T-Rex#1084]
Good day!

Then ETH + TON for LHR cards?

**Comment by servaldsl** [comment]
lolminer did +alph and +ton
I'm a t-rex maximalist, hope a new version with TON will be released. Don't want to change my miner

**Comment by vruva** [comment]
+1

**Comment by brawnman** [comment]
+1

**Comment by trexminer** [comment]
Duplicate of https://github.com/trexminer/T-Rex/issues/1035
