### ISSUE TITLE
problem in dual mining eth+alph in ring 12 GPU 1660 super

### ISSUE THREAD

**Issue by jrchico** [trexminer/T-Rex#1089]
I have a problem in dual mining eth + alph I have a ring of 12 graphics cards 1660 super and when I start mining the alph hash rate does not show up on some cards only in 8, the eth hash rate is perfect

**Comment by trexminer** [comment]
Try increasing your power limit or run with `--dual-algo-mode a12:r1`. Follow the tuning guide at https://github.com/trexminer/T-Rex/wiki/Dual-mining.

**Comment by jrchico** [comment]
thank you very much increase the powerlimit to 90 and it is working very well

**Comment by AngelRamMen** [comment]
Would you mundo to  share you're OC settings plz?
