### ISSUE TITLE
[FAIL]  - Didn't subscribe

### ISSUE THREAD

**Issue by boreeth** [trexminer/T-Rex#1094]
I have been dual mining Eth+Alph on 25.2 and everything has been going great. Switched to 25.6 and after a short while I get "[FAIL] 13/14 - Didn't subscribe".   Any ideas? If I restart Trex it works fine again but sooner or later I get the failure again.

[trex-[1645204104].log](https://github.com/trexminer/T-Rex/files/8099312/trex-.1645204104.log)

**Comment by trexminer** [comment]
I contacted herominers and they advised that this issue occurs due to the miner not sending any shares for more than 10 minutes. The recommendation is to use low static difficulty.
