### ISSUE TITLE
DELETE

### ISSUE THREAD

**Issue by jayvysson** [trexminer/T-Rex#1098]

**Comment by jayvysson** [comment]
![image](https://user-images.githubusercontent.com/22245132/154804532-41e1f3cc-59ef-4541-8738-1b33a7bd6e5a.png)

**Comment by jayvysson** [comment]
![image](https://user-images.githubusercontent.com/22245132/154804571-510312e4-2035-49bc-a118-27d7d9000a5b.png)

**Comment by jayvysson** [comment]
![image](https://user-images.githubusercontent.com/22245132/154804720-6bb2a20b-7a5f-4128-8520-7d3960eed33a.png)

**Comment by jayvysson** [comment]
![image](https://user-images.githubusercontent.com/22245132/154812569-0fff2743-9d24-4208-a62b-5aca1bd98ef4.png)

**Comment by FMEM** [comment]
一样得情况，3台使用T-REX都是这个问题，其他得则不会。内存占用会一点点变高。直到崩溃。

**Comment by jayvysson** [comment]
I tested using gminer for 48 hours and it didn't consume more than 500mb, please optimize memory consumption on windows, because I love mining with T-rex! <3

**Comment by FMEM** [comment]
T-REX就是这样吃内存无法解决吗？

**Comment by jayvysson** [comment]
![image](https://user-images.githubusercontent.com/22245132/155628081-e8c45e46-f50b-4f8d-a6ae-149c8b0e4345.png)
Another rig of mine with two 3080's, after 4 days mining, will soon restart, because it will consume 100% of memory.

**Comment by jayvysson** [comment]
![image](https://user-images.githubusercontent.com/22245132/155628695-a5367d91-969f-4b96-a17f-eef3473e2af6.png)

**Comment by jayvysson** [comment]
![essa](https://user-images.githubusercontent.com/22245132/155855155-199e4814-fcf4-48c0-a785-e2de45e05bde.png)
In windows need to change the power management.

**Comment by jayvysson** [comment]
![image](https://user-images.githubusercontent.com/22245132/155901919-715c82a3-7654-48b5-aaa2-96065d42b56c.png)
My rig with two 3080 restarted after 7 days mining, i will post the logs.

**Comment by jayvysson** [comment]
![image](https://user-images.githubusercontent.com/22245132/155901984-1da5d265-01f4-4e9d-8681-052e8fe84114.png)

**Comment by jayvysson** [comment]
![image](https://user-images.githubusercontent.com/22245132/155902028-b3ccc780-5e90-4555-a4aa-2f5b5de04932.png)

**Comment by jayvysson** [comment]
![image](https://user-images.githubusercontent.com/22245132/155902075-95e66691-3a5a-4e55-99ce-a29ac94d8b66.png)

**Comment by FMEM** [comment]
windows更改电源设置可以解决内存占用问题？

**Comment by jayvysson** [comment]
I still couldn't solve it, I think it's developers need to optimize memory consumption in windows, otherwise it will restart after consuming 100% of memory.

**Comment by FMEM** [comment]
听说W10专业版可以解决这个问题。看你得标题已经是专业版了。看来是错误得信息了，但是也有很多人没有遇到这种情况，很奇妙

**Comment by FMEM** [comment]
你的矿机上都有3060吗？是否使用了470.05得显卡驱动？

**Comment by FMEM** [comment]
可能是470.05得驱动有内存得泄露问题

**Comment by FMEM** [comment]
470.05显卡驱动

**Comment by jayvysson** [comment]
Everything you asked me, I have already shown in the photos.
Let's wait for a developer to respond!
