### ISSUE TITLE
TREX: Can't initialize device [ID=0, GPU #0], can't lock core clock, can't set gpu lock clocks: error code 4

### ISSUE THREAD

**Issue by ddfault** [trexminer/T-Rex#1102]
I finally updated your excellent software and finally moving all my power limits, memory speeds, fan control, and clocks over to your product from Precision X1.

I had no issues with Fans, Memory, or power limits, but ran into this issue locked the core clock.
When I change the config to 0 on the first gpu, but leave second locked I get:
TREX: Can't initialize device [ID=1, GPU #1], can't lock core clock, can't set gpu lock clocks: error code 4

Google didn't find an article for this issue but similar ones that weren't applicable in my case.

Turns out my issue was the fact I wasn't running t-rex.exe with admin rights. 
Settings t-rex.exe to only run as administrator fixed the issue and now your products is running will all settings in place.

Thanks you for all the work you do on this excellent piece of software!

**Comment by ddfault** [comment]
I unfortunately cannot target fan speeds on the 3070 founders edition based on memory temps as theirs no sensor. Is it possible to add (support) adjusting fan speeds based on Hot Spot temperature?

Thanks!

**Comment by trexminer** [comment]
Error code 4 translates into `NVML_ERROR_NO_PERMISSION`, so yes, running under admin should solve the issue.
Reading hotspot temperatures isn't supported by T-Rex.
