### ISSUE TITLE
"Authorization error (wrong password)" 

### ISSUE THREAD

**Issue by Croldfish** [trexminer/T-Rex#1105]
Basically, I am following this guide (https://github.com/trexminer/T-Rex/wiki/WebUI#security) and I am trying to enter in the passoword to access the Web UI (i think that's what it's called) and it isn't working. As in, the exact password from step 2 typed in doesn't log me in.

**Comment by trexminer** [comment]
Please double check every step you've done to set up the access. We haven't had a single report of passwords not being accepted.

**Comment by Croldfish** [comment]
I just made a new password
Sorry, still kinda new
