### ISSUE TITLE
0.25.8 - 3060 v1 and v2 ALPH quite hashrate reduction in dual ETH mining

### ISSUE THREAD

**Issue by danielmoralesdev** [trexminer/T-Rex#1112]
0.25.6
Each card was about 250 Mh/s

0.25.6
Each card is about 50 MH/s

Same settings. So what's going on, release says "Improve ETH+ALPH dual mining performance for LHR cards"??

**Comment by tjayz** [comment]
Read the trex log when the miner starts or the miner itself when it starts in 25.8, the number assigned to LHR ratio is automatic regardless of settings indicated by 'r" or 'h' command under dual-algo-mode per README.md. In 25.8 this ratio is viewable in the miner whereas in 25.6 it is not. It clearly has a strong impact on watts somehow as well. Hopefully this setting can be tweaked manually in a later version.

**Comment by danielmoralesdev** [comment]
@tjayz thanks for commenting, what you had said makes a lot of sense. I read documentation and looks like there is a formula to define lhr ratio but no idea how to apply it, so better explanation from trex team side would be appreciated

**Comment by danielmoralesdev** [comment]
It has to do with oc, I just followed https://hashrate.no/ settings based on my cards, then ran 25.8 and it worked (ALPH good improvement).
