### ISSUE TITLE
Version 0.19.4 not solve Base64 encoding problem

### ISSUE THREAD

**Issue by bekman1** [trexminer/T-Rex#112]
Hi, after upgrade on 0.19.4 the problem with Base64 encoding was not solved. Please check.
My rig on HiveOS Linux Build, last version.
I try to start T-rex miner from AwesomeMiner program and get strange string TREX: xxxx
but if i start T-Rex from terminal window on the same machine with the same command line and params like generated from AwesomeMiner, miner started without problem. Where is a problem? On AwesomeMiner or T-rex side? Use Awesome and T-Rex different base64 libs?

**Comment by bekman1** [comment]
AwesomeMiner is Windows program, HiveOS is Linux. If base64 lib was upgraded recently on Linux or Windows, then looks like base64 lib is not compatible on different OS.

**Comment by voyagerft** [comment]
with ethos l version 0.19.4 now works correctly and fixed base64 encode error

**Comment by bekman1** [comment]
in my situation run command string will be generated on Windows machine and sent to Linux rig. And proplem persist.
Or Windows wrong encoded this string, or Linux decoded wrong.
I use Win 10 pro 20H2 with all latest updates. Linux (HiveOS ver 181)

**Comment by bekman1** [comment]
Got responce from Awesome Miner developer, looks like he found some bug in his software.
