### ISSUE TITLE
Manual set for LHR

### ISSUE THREAD

**Issue by Hkharip** [trexminer/T-Rex#1120]
There is any code to set a manual limit for dual mining like 65:35 or 60:40

**Comment by Jeresones** [comment]
> There is any code to set a manual limit for dual mining like 65:35 or 60:40

You can always use, for example, --lhr-tune 71 --lhr-autotune-step-size 0.1 --lhr-autotune-interval 2. Let the miner run and test what's your GPU LHR limit on specific algo. Then just change the --lhr-tune value to your liking. I'm just testing new 0.25.8  ETH + ALPH and it seems to allow my 3080 Ti run 73%+ ETH and 27% ALPH. So ended up using --lhr-tune 73 --lhr-autotune-step-size 0.1 --lhr-autotune-interval 10. Now if the system runs 10 min with those settings miner will try 73.1.

**Comment by Hkharip** [comment]
Thanks bro
