### ISSUE TITLE
Lhr unlock v2

### ISSUE THREAD

**Issue by gigabyteminer** [trexminer/T-Rex#1121]
https://github.com/BySergeyDev/NvidiaRTX-LHRv2Unlocker

**Comment by basking-in-the-sun2000** [comment]
won't be out for a few days, but I'm also curious. I've seen a lot of people claiming it is a scam or malware without it having been out. I would be dubious as well, but my experience of having a card reach fhr makes me wonder if they found a way to kick an lhr card into fhr. 

Probably people will be posting more by the end of the month. However, his publishing his code before release does make it look suspicious

**Comment by gigabyteminer** [comment]
Do not install it!!! Its some malware or more dangerous. Open fail and read codes. Its very intresting :D
