### ISSUE TITLE
Wont mine with more than 3 cards :/

### ISSUE THREAD

**Issue by Juolupuki** [trexminer/T-Rex#113]
Hi,
Hope I can find some advice here.
Suddenly the miner won't run with 5 cards. From the beginning mining Ravencoin there weren't any issues, but now just don't want to mine full rig :/
I have tested with 1,2 or 3 cards it runs without any problems. If connect 4th or 5th it just brings red lines with message 

![fail](https://user-images.githubusercontent.com/75947653/102020239-c6266000-3d6f-11eb-8ef2-1554ecf2442b.JPG)

Updated with last Nvidia Drivers (457.30-desktop-win10-64bit-international-nsd-dch-whql) and runing on last version of (T-Rex-0.19.4-win-cuda11.1)

System set up:
Motherboard - B250 Mining expert
Intel Celeron CPU G3930 2.9Ghz
8192 RAM
x5 GTX 1070ti 8Gb
Win 10 Enterprise 64-bit (10.0, Build 19042)

Any advice please would be appreciated.
Thanks

**Comment by trexminer** [comment]
This was reported as solved in our Discord channel. The solution was to increase virtual memory size.
