### ISSUE TITLE
[check_if_cuda_really_exists, 237]

### ISSUE THREAD

**Issue by GraverErmitage** [trexminer/T-Rex#114]
![image](https://user-images.githubusercontent.com/34091165/102099865-0eee1f80-3e29-11eb-8db3-f4ab9eeec92f.png)

**Comment by trexminer** [comment]
Could you try CUDA 10.0 build please? 11.1 is only supposed to work with drivers v455+

**Comment by GraverErmitage** [comment]
> Could you try CUDA 10.0 build please? 11.1 is only supposed to work with drivers v455+

Please see the result
![image](https://user-images.githubusercontent.com/34091165/102261189-9c0ca380-3f11-11eb-9c54-10ea9e3cc9cf.png)

**Comment by trexminer** [comment]
Thanks. Seems to be a bug.

**Comment by trexminer** [comment]
Could you please try 0.20.1 and let me know if the issue still occurs?

**Comment by GraverErmitage** [comment]
Sorry, I don't have that machine anymore. It was rented GPU in the Cloud.
