### ISSUE TITLE
Firo Solopool disconnects

### ISSUE THREAD

**Issue by JackDeRke** [trexminer/T-Rex#1150]
I´ve been having this problem for a while now were I´m solomining Firo and the Rig constantly loses connection and rebuilds it, while abandoning mining for ~3min in the meantime.
A Firo Discord member suggested it´s something to do with the dev fee switch.
Timeintervals are super random, so I´m not so sure of that.
I´ve seen the typical dev fee mined so not sure it´s the actual problem.
![Firo](https://user-images.githubusercontent.com/92853366/156853225-a34e947d-a498-4c48-81dd-a5c2595654f6.PNG)
![firo3](https://user-images.githubusercontent.com/92853366/156853249-076206df-dc02-475a-bb6c-b3f7f3fd8db6.PNG)

**Comment by trexminer** [comment]
You must've set network timeout to 180 seconds (it is 300 by default), see `--timeout` in readme.

**Comment by JackDeRke** [comment]
It's whatever HiveOS has as standard. I didn't put any setting there. I'm
averaging 1.3 shares a minute, how can it be this often then?

trexminer ***@***.***> schrieb am Sa., 5. März 2022, 13:23:

**Comment by trexminer** [comment]
You should be able to override whatever HiveOS is setting by `"timeout": 300`
> averaging 1.3 shares a minute, how can it be this often then?

finding shares is a random process, they aren't uniformly distributed over time
