### ISSUE TITLE
EPIC Cash - ProgPowEPIC

### ISSUE THREAD

**Issue by toogle93** [trexminer/T-Rex#1152]
its possible to mine EPIC? or to add there progpow algo? 
https://epic.tech/
would be perfect ^^ i love trex :P its awesome with a RTX 2070 Super to mine ETH with 44 MH/s at 89W 🤣 but all have to use this shit TT-Miner to mine EPIC and ETH an this is a shity buggy thing 🤣 please add it or help us EPIC miners xD

**Comment by trexminer** [comment]
Duplicate of https://github.com/trexminer/T-Rex/issues/911
