### ISSUE TITLE
cuda exception: CUDA_ERROR_ILLEGAL_ADDRESS error

### ISSUE THREAD

**Issue by Headache3D** [trexminer/T-Rex#1158]
Does anyone know how to solve this error? I did reduce overclock, change virtual memory, reinstall different driver versions, running on different T-Rex versions, but still have this error, now, I am mining TonCoin without any error, but I am keen to run T-Rex, anyone please help.

![Screenshot_20220311-095143_Gallery](https://user-images.githubusercontent.com/101364121/157753860-7b74d03b-9897-483b-a4af-60421262b097.jpg)

**Comment by trexminer** [comment]
Check your power supply, cables, risers https://github.com/trexminer/T-Rex/wiki/FAQ#im-getting-a-code--6
