### ISSUE TITLE
-d not working well

### ISSUE THREAD

**Issue by brankoads** [trexminer/T-Rex#116]
Hi, I am start using t-rex miner. On my rig GPU 3 not working well, and want to turn it off. Use -d 0,1,2,4,5 command line but, when start to mine, see that gpu 5 was turned off. Try to add line --pci-indexing but same results...
Is this a bug, or I’m not doing something good? 
Thanks
![smos](https://user-images.githubusercontent.com/76038645/102193267-2e825800-3ebc-11eb-8957-c0742bb4b5a6.jpg)

**Comment by trexminer** [comment]
From the power consumption data on your screenshot GPU#5 appears to be ON and GPU#3 is OFF. That contradicts the hashrate data.
Could you post the miner console output?
