### ISSUE TITLE
3060ti LHR GA103, not detected as LHR, thus cannot LHR unlock

### ISSUE THREAD

**Issue by allenultra** [trexminer/T-Rex#1166]
Bought 4 of the latest Zotac 3060ti LHR, apparently come with GA103 chipset with hynix ram. 
Tried with T-rex 0.25.8, it doesn't detect the card as LHR, thus not to perform any LHR unlock. 

I have a total of 8x 3060ti LHR, the older 4x 3060ti LHR do not have this issues. Refer to the photo attached.
Not sure it is the nvidia driver issues, or the cards revision just too new.
Older driver of 472.12 not able to detect that 4 particular cards, need to use the latest nvidia drivers to get it recognised in windows.
Not sure its the windows issue or I shall give it a try in linux ?

![T-Rex](https://user-images.githubusercontent.com/100591128/158424720-2d649c2a-a548-4189-92af-a122515338f1.jpg)

**Comment by trexminer** [comment]
Try setting `--lhr-tune` manually to force the miner into recognising them as LHR.

**Comment by allenultra** [comment]
Works like a charm, thanks.

Able to force the miner to recognise it as LHR cards now :)

**Comment by trexminer** [comment]
No worries :) Could you please tell me what Device ID for those 3060Tis is so that we automatically recognise them? You can see it in GPU-Z:
![image](https://user-images.githubusercontent.com/44735836/158443992-0f011fd3-c897-4e78-abbb-fc19b6291b13.png)

**Comment by allenultra** [comment]
![Screenshot_2022-03-16-13-39-02-964_com.anydesk.anydeskandroid.jpg](https://user-images.githubusercontent.com/100591128/158523864-0e3da96a-fa5c-4b4d-a608-1c0faef63264.jpg)

**Comment by trexminer** [comment]
Thanks very much.

**Comment by trexminer** [comment]
T-Rex 0.25.9 should recognise these 3060ti as LHR automatically
