### ISSUE TITLE
I want to mine the sero coin in trex with ssl! But always fail!Can somebody help me?

### ISSUE THREAD

**Issue by alixeking** [trexminer/T-Rex#1172]
I bought a domain  and used niginx for SSL encryption! forwarded by server
Here is the code ,can u tell me what is wrong with it?
t-rex.exe -a progpow --coin sero -o stratum+ssl://ssl.XXXX.cn:8808 -u hxW5ap1fzKc2XXXXXXXXXXXXXXEBH8ey5Xr5PqrqqQF9jod6BEQEnzkUD4fD3fjH5uoueoCHpzZEhtFS58PQdhhYT5KEDJJCmvfpXT8hzv93g7fZ6eiyMRj5iaRqMGjCVBg -p x -w rig0
pause --no-strict-ssl
 
Is the text is right?
by the way ,how to mine cfx eth  rvn  with ssl in trex

![微信图片_20220318192318](https://user-images.githubusercontent.com/101870529/158995276-abe57a8e-0b0b-4d65-8dab-c78ca6382ca5.png)

**Comment by trexminer** [comment]
Your SSL certificate may not be strictly valid. Have you tried running with `--no-strict-ssl` like the miner suggested?

**Comment by pdieppa** [comment]
Looking at your command line, it looks like the --no-strict-ssl is after the pause
t-rex.exe -a progpow --coin sero -o stratum+ssl://ssl.XXXX.cn:8808 -u hxW5ap1fzKc2XXXXXXXXXXXXXXEBH8ey5Xr5PqrqqQF9jod6BEQEnzkUD4fD3fjH5uoueoCHpzZEhtFS58PQdhhYT5KEDJJCmvfpXT8hzv93g7fZ6eiyMRj5iaRqMGjCVBg -p x -w rig0
pause **--no-strict-ssl**

I needs to be before like this

t-rex.exe -a progpow --coin sero -o stratum+ssl://ssl.XXXX.cn:8808 -u hxW5ap1fzKc2XXXXXXXXXXXXXXEBH8ey5Xr5PqrqqQF9jod6BEQEnzkUD4fD3fjH5uoueoCHpzZEhtFS58PQdhhYT5KEDJJCmvfpXT8hzv93g7fZ6eiyMRj5iaRqMGjCVBg -p x -w rig0 **--no-strict-ssl**
pause

**Comment by trexminer** [comment]
I've completely missed that, thanks @pdieppa !

**Comment by alixeking** [comment]
thanks for trexminer and pdieppa! i have slove it! due to i am blocked from the net in china, so i can not reply  soon!
