### ISSUE TITLE
Trex Eth+Ton Please !!!!

### ISSUE THREAD

**Issue by Ricco59163** [trexminer/T-Rex#1175]
Hi all , can you update the T-rex version for Dual mining  Eth+Ton ?

thx

**Comment by zhanko73** [comment]
> Hi all , can you update the T-rex version for Dual mining Eth+Ton ?
> 
> thx

What about the lolminer? It has ETH+TON. Have you tried already?

**Comment by samy63** [comment]
Hello

yes please to include dual mining ETH+TON

i prefer trex than lolminer. 

thank you in advance

**Comment by trexminer** [comment]
Duplicate of https://github.com/trexminer/T-Rex/issues/1035
