### ISSUE TITLE
ETC + ALPH (and TONCOIN)

### ISSUE THREAD

**Issue by sacredland** [trexminer/T-Rex#1177]
Would be nice to be able to dual mine something else then eth, like lolminer does. Like mining etc and alephium or toncoin

**Comment by BitMaci** [comment]
> Would be nice to be able to dual mine something else then eth, like lolminer does. Like mining etc and alephium or toncoin

Sure, I mine ETC+ALPH with lolMiner and it goes great. It would be great T-Rex could do the same, I already suggested this in Discord but Dev Team didn't answer at all.

**Comment by trexminer** [comment]
Added in 0.26.6
