### ISSUE TITLE
Minimum driver version needed for 0.19.4

### ISSUE THREAD

**Issue by peterwillis** [trexminer/T-Rex#118]
I see an error in windows:

> The procedure entry point cuDevicePrimaryCtxReset_v2 could not be located in the dynamic link library nvcuda.dll

Does this mean there is a specific driver version required?

**Comment by trexminer** [comment]
Most likely. What's the current driver version and what CUDA version build of t-rex are you trying to run?

**Comment by peterwillis** [comment]
Sorry I think this was my mistake, I was trying to run the cuda 11.1 version on a device that doesn't support it. Thank you for your quick response here!
