### ISSUE TITLE
Latest TRex Dual mining ETH+Ergo with Nvidia 3090 is not working

### ISSUE THREAD

**Issue by Dzony1606** [trexminer/T-Rex#1181]
When i start dual mining i have only eth mining...Ergo mhs is 0.0mh/s always...What i can do? 

This is my bat file:
t-rex.exe -a ethash --dual-algo autolykos2 -o stratum+tcp://eu1.ethermine.org:4444 -u "0xmy eth wallet" -p x -w rig --url2 stratum+tcp://stratum-ergo.flypool.org:3333 --user2 "myErgowallet".rig --pass2 x --dual-algo-mode a12
pause
-------------------
I tried without this on the end "--dual-algo-mode a12" it is not relevant...miner works the same...only eth working
I dont know what to do?
![Capture](https://user-images.githubusercontent.com/102165658/159503889-681d9f9e-3eb4-453e-954f-9c778cd0e054.JPG)

**Comment by trexminer** [comment]
ETH+ERGO is not supported on non-LHR cards (by default), you can force it with `--lhr-tune <whatever ETH percentage you like>`

**Comment by Dzony1606** [comment]
> ETH+ERGO is not supported on non-LHR cards (by default), you can force it with `--lhr-tune <whatever ETH percentage you like>`

Thank you man

**Comment by shmox75** [comment]
For me even with --lhr-tune it's still not working
