### ISSUE TITLE
I cannot launch the 6 gpu

### ISSUE THREAD

**Issue by woofsid** [trexminer/T-Rex#119]
![Capture](https://user-images.githubusercontent.com/58686127/102689546-3a915100-41ff-11eb-884c-627e8ed9b17e.PNG)
![Captur2e](https://user-images.githubusercontent.com/58686127/102689555-4b41c700-41ff-11eb-89d0-d476b7153899.PNG)

hello I am configuring TREX for 6 gpu my problem is that I always have 2 gpu which does not work, at each restart the gpu which does not launch its random, I can not find the solution can you please me please help?

I apologize if the subject has already been posted but I do not speak English it's very complicated, long live the translator :+)

**Comment by trexminer** [comment]
Hi. What's the amount of virtual memory configured in your system? Try increasing it.

**Comment by woofsid** [comment]
I had configured some time ago from 16gb to 26gb I had forgotten that for some algo we needed more 16 / 47gb thank you problem solved
![Captu2re](https://user-images.githubusercontent.com/58686127/102691816-9ebc1100-420f-11eb-806d-ea8fc7cacf53.PNG)
