### ISSUE TITLE
Not enough GPU memory DAG epoch

### ISSUE THREAD

**Issue by omarov10** [trexminer/T-Rex#120]
The miner works fine for the first 10 to 12 hours, but then it crashes, the error is Not enough GPU memory DAG epoch

The miner was working fine before the latest Nvidia drivers 

I have 16 GB DDR4 and 6 1080ti's 

I also increased VRAM but still, the miner crashed hours later

**Comment by trexminer** [comment]
Could you post a screenshot with the error or a log file? T-Rex will create a log file if you run it with `-l trex.log` parameter.
Thanks.

**Comment by omarov10** [comment]
It happens this time on my second rig 
here's the log events

20201220 19:57:24 Mining at us-eth.2miners.com:2020, diff: 8.59 Gh
20201220 19:57:24 GPU #0: EVGA GTX 1080 Ti - 49.65 MH/s, [T:56C, P:233W, F:66%, E:214kH/W], 175/175 R:0%
20201220 19:57:24 GPU #1: EVGA GTX 1080 Ti - 49.16 MH/s, [T:52C, P:225W, F:62%, E:218kH/W], 146/146 R:0%
20201220 19:57:24 GPU #2: EVGA GTX 1080 Ti - 48.86 MH/s, [T:55C, P:239W, F:65%, E:208kH/W], 157/163 R:3.68%
20201220 19:57:24 GPU #3: MSI GTX 1080 Ti  - 49.08 MH/s, [T:58C, P:237W, F:68%, E:207kH/W], 136/140 R:2.86%
20201220 19:57:24 GPU #4: EVGA GTX 1080    - 39.14 MH/s, [T:50C, P:170W, F:61%, E:230kH/W], 125/125 R:0%
20201220 19:57:24 GPU #5: MSI GTX 1070 Ti  - 31.87 MH/s, [T:49C, P:154W, F:59%, E:208kH/W], 107/107 R:0%
20201220 19:57:24 Hashrate: 267.76 MH/s, Shares/min: 1.392 (Avr. 1.473) R: 1.168%, Avr.P: 1252W, Avr.E: 214kH/W
20201220 19:57:24 Uptime: 3 mins 31 secs | Algo: ethash | T-Rex v0.19.4
20201220 19:57:24 WD: 7 hours 48 mins 8 secs, shares 846/856, restarts 1
20201220 19:57:24 
20201220 19:57:38 WARN: WATCHDOG: T-Rex does not exist anymore, restarting...
20201220 19:57:42 T-Rex NVIDIA GPU miner v0.19.4  -  [CUDA v11.10 | Windows]
20201220 19:57:42 r.ef7197621723
20201220 19:57:42 
20201220 19:57:42 NVIDIA Driver v460.89
20201220 19:57:42 CUDA devices available: 6
20201220 19:57:42 
20201220 19:57:42 WARN: DevFee 1% (ethash)
20201220 19:57:42 
20201220 19:57:42 URL : stratum+tcp://us-eth.2miners.com:2020
20201220 19:57:42 USER: 0x2783c77819f5c55d6101f3a398bdab9959b2763e
20201220 19:57:42 PASS: x
20201220 19:57:42 WRK : GPU
20201220 19:57:42 
20201220 19:57:42 Starting on: us-eth.2miners.com:2020
20201220 19:57:42 Using protocol: stratum1.
20201220 19:57:42 Authorizing...
20201220 19:57:42 Authorized successfully.
20201220 19:57:42 ApiServer: HTTP server started on 0.0.0.0:4067
20201220 19:57:42 -------------------------------------------------------
20201220 19:57:42 For control navigate to: http://192.168.0.109:4067/trex
20201220 19:57:42 -------------------------------------------------------
20201220 19:57:42 ApiServer: Telnet server started on 0.0.0.0:4068
20201220 19:57:42 ethash epoch: 383, diff: 8.59 Gh
20201220 19:57:42 WARN: GPU #0(000400): EVGA GeForce GTX 1080 Ti, intensity set to 22
20201220 19:57:42 WARN: GPU #1(000600): EVGA GeForce GTX 1080 Ti, intensity set to 22
20201220 19:57:42 WARN: GPU #2(000800): EVGA GeForce GTX 1080 Ti, intensity set to 22
20201220 19:57:43 WARN: GPU #3(000900): MSI GeForce GTX 1080 Ti, intensity set to 22
20201220 19:57:43 WARN: GPU #4(000200): EVGA GeForce GTX 1080, intensity set to 22
20201220 19:57:43 WARN: GPU #5(000100): MSI GeForce GTX 1070 Ti, intensity set to 22
20201220 19:57:46 GPU #2: generating DAG 3.99 GB for epoch 383 ...
20201220 19:57:46 GPU #4: generating DAG 3.99 GB for epoch 383 ...
20201220 19:57:46 GPU #3: generating DAG 3.99 GB for epoch 383 ...
20201220 19:57:46 GPU #0: generating DAG 3.99 GB for epoch 383 ...
20201220 19:57:46 GPU #5: generating DAG 3.99 GB for epoch 383 ...
20201220 19:57:50 GPU #0: DAG generated [time: 4965 ms], memory left: 5.99 GB
20201220 19:57:51 GPU #3: DAG generated [time: 5467 ms], memory left: 5.99 GB
20201220 19:57:51 GPU #2: DAG generated [time: 5477 ms], memory left: 5.99 GB
20201220 19:57:53 GPU #4: DAG generated [time: 7193 ms], memory left: 3.05 GB
20201220 19:57:54 GPU #5: DAG generated [time: 8953 ms], memory left: 3.05 GB
20201220 19:58:03 WARN: GPU #1: EVGA GeForce GTX 1080 Ti is idle, last activity was 20 secs ago
20201220 19:58:06 GPU #0: using kernel #5
20201220 19:58:07 GPU #3: using kernel #4
20201220 19:58:07 GPU #2: using kernel #1
20201220 19:58:08 WARN: GPU #1: EVGA GeForce GTX 1080 Ti is idle, last activity was 25 secs ago
20201220 19:58:09 GPU #4: using kernel #2
20201220 19:58:11 GPU #5: using kernel #2
20201220 19:58:13 WARN: GPU #1: EVGA GeForce GTX 1080 Ti is idle, last activity was 30 secs ago
20201220 19:58:18 WARN: GPU #1: EVGA GeForce GTX 1080 Ti is idle, last activity was 35 secs ago
20201220 19:58:24 WARN: GPU #1: EVGA GeForce GTX 1080 Ti is idle, last activity was 40 secs ago
20201220 19:58:29 WARN: GPU #1: EVGA GeForce GTX 1080 Ti is idle, last activity was 45 secs ago
20201220 19:58:29 WARN: WATCHDOG: T-Rex has a problem with GPU, terminating...
20201220 19:58:30 WARN: WATCHDOG: recovering T-Rex
20201220 19:58:33 T-Rex NVIDIA GPU miner v0.19.4  -  [CUDA v11.10 | Windows]
20201220 19:58:33 r.ef7197621723
20201220 19:58:33 
20201220 19:58:33 NVIDIA Driver v460.89
20201220 19:58:33 CUDA devices available: 6
20201220 19:58:33 
20201220 19:58:33 WARN: DevFee 1% (ethash)
20201220 19:58:33 
20201220 19:58:33 URL : stratum+tcp://us-eth.2miners.com:2020
20201220 19:58:33 USER: 0x2783c77819f5c55d6101f3a398bdab9959b2763e
20201220 19:58:33 PASS: x
20201220 19:58:33 WRK : GPU
20201220 19:58:33 
20201220 19:58:33 Starting on: us-eth.2miners.com:2020
20201220 19:58:33 Using protocol: stratum1.
20201220 19:58:33 Authorizing...
20201220 19:58:33 Authorized successfully.
20201220 19:58:33 ethash epoch: 383, diff: 8.59 Gh
20201220 19:58:33 ApiServer: HTTP server started on 0.0.0.0:4067
20201220 19:58:33 -------------------------------------------------------
20201220 19:58:33 For control navigate to: http://192.168.0.109:4067/trex
20201220 19:58:33 -------------------------------------------------------
20201220 19:58:33 ApiServer: Telnet server started on 0.0.0.0:4068
20201220 19:58:33 WARN: GPU #0(000400): EVGA GeForce GTX 1080 Ti, intensity set to 22
20201220 19:58:33 WARN: GPU #1(000600): EVGA GeForce GTX 1080 Ti, intensity set to 22
20201220 19:58:33 WARN: GPU #2(000800): EVGA GeForce GTX 1080 Ti, intensity set to 22
20201220 19:58:34 WARN: GPU #3(000900): MSI GeForce GTX 1080 Ti, intensity set to 22
20201220 19:58:34 WARN: GPU #4(000200): EVGA GeForce GTX 1080, intensity set to 22
20201220 19:58:34 WARN: GPU #5(000100): MSI GeForce GTX 1070 Ti, intensity set to 22
20201220 19:58:37 GPU #0: generating DAG 3.99 GB for epoch 383 ...
20201220 19:58:37 GPU #2: generating DAG 3.99 GB for epoch 383 ...
20201220 19:58:37 GPU #3: generating DAG 3.99 GB for epoch 383 ...
20201220 19:58:37 GPU #5: generating DAG 3.99 GB for epoch 383 ...
20201220 19:58:37 GPU #1: generating DAG 3.99 GB for epoch 383 ...
20201220 19:58:41 GPU #0: DAG generated [time: 4955 ms], memory left: 5.99 GB
20201220 19:58:42 GPU #3: DAG generated [time: 5462 ms], memory left: 5.99 GB
20201220 19:58:42 GPU #2: DAG generated [time: 5474 ms], memory left: 5.99 GB
20201220 19:58:42 GPU #1: DAG generated [time: 5650 ms], memory left: 5.99 GB
20201220 19:58:45 GPU #5: DAG generated [time: 8942 ms], memory left: 3.05 GB
20201220 19:58:54 WARN: GPU #4: EVGA GeForce GTX 1080 is idle, last activity was 20 secs ago
20201220 19:58:57 GPU #0: using kernel #1
20201220 19:58:58 GPU #2: using kernel #5
20201220 19:58:58 GPU #3: using kernel #4
20201220 19:58:58 GPU #1: using kernel #1
20201220 19:58:59 WARN: GPU #4: EVGA GeForce GTX 1080 is idle, last activity was 25 secs ago
20201220 19:59:02 GPU #5: using kernel #2
20201220 19:59:04 WARN: GPU #4: EVGA GeForce GTX 1080 is idle, last activity was 30 secs ago
20201220 19:59:10 WARN: GPU #4: EVGA GeForce GTX 1080 is idle, last activity was 35 secs ago
20201220 19:59:15 WARN: GPU #4: EVGA GeForce GTX 1080 is idle, last activity was 40 secs ago
20201220 19:59:19 WARN: WATCHDOG: T-Rex has a problem with GPU, terminating...
20201220 19:59:20 WARN: WATCHDOG: recovering T-Rex
20201220 19:59:23 T-Rex NVIDIA GPU miner v0.19.4  -  [CUDA v11.10 | Windows]
20201220 19:59:23 r.ef7197621723
20201220 19:59:23 
20201220 19:59:23 NVIDIA Driver v460.89
20201220 19:59:23 CUDA devices available: 6
20201220 19:59:23 
20201220 19:59:23 WARN: DevFee 1% (ethash)
20201220 19:59:23 
20201220 19:59:23 URL : stratum+tcp://us-eth.2miners.com:2020
20201220 19:59:23 USER: 0x2783c77819f5c55d6101f3a398bdab9959b2763e
20201220 19:59:23 PASS: x
20201220 19:59:23 WRK : GPU
20201220 19:59:23 
20201220 19:59:23 Starting on: us-eth.2miners.com:2020
20201220 19:59:23 Using protocol: stratum1.
20201220 19:59:23 Authorizing...
20201220 19:59:23 Authorized successfully.
20201220 19:59:23 ethash epoch: 383, diff: 8.59 Gh
20201220 19:59:23 ApiServer: HTTP server started on 0.0.0.0:4067
20201220 19:59:23 -------------------------------------------------------
20201220 19:59:23 For control navigate to: http://192.168.0.109:4067/trex
20201220 19:59:23 -------------------------------------------------------
20201220 19:59:23 ApiServer: Telnet server started on 0.0.0.0:4068
20201220 19:59:23 WARN: GPU #0(000400): EVGA GeForce GTX 1080 Ti, intensity set to 22
20201220 19:59:23 WARN: GPU #1(000600): EVGA GeForce GTX 1080 Ti, intensity set to 22
20201220 19:59:24 WARN: GPU #2(000800): EVGA GeForce GTX 1080 Ti, intensity set to 22
20201220 19:59:24 WARN: GPU #3(000900): MSI GeForce GTX 1080 Ti, intensity set to 22
20201220 19:59:24 WARN: GPU #4(000200): EVGA GeForce GTX 1080, intensity set to 22
20201220 19:59:24 WARN: GPU #5(000100): MSI GeForce GTX 1070 Ti, intensity set to 22
20201220 19:59:27 GPU #1: generating DAG 3.99 GB for epoch 383 ...
20201220 19:59:27 GPU #2: generating DAG 3.99 GB for epoch 383 ...
20201220 19:59:27 GPU #0: generating DAG 3.99 GB for epoch 383 ...
20201220 19:59:27 GPU #4: generating DAG 3.99 GB for epoch 383 ...
20201220 19:59:27 GPU #3: generating DAG 3.99 GB for epoch 383 ...
20201220 19:59:31 GPU #0: DAG generated [time: 4964 ms], memory left: 5.99 GB
20201220 19:59:32 GPU #1: DAG generated [time: 5476 ms], memory left: 5.99 GB
20201220 19:59:32 GPU #2: DAG generated [time: 5479 ms], memory left: 5.99 GB
20201220 19:59:32 GPU #3: DAG generated [time: 5623 ms], memory left: 5.99 GB
20201220 19:59:34 GPU #4: DAG generated [time: 7197 ms], memory left: 3.05 GB
20201220 19:59:44 WARN: GPU #5: MSI GeForce GTX 1070 Ti is idle, last activity was 20 secs ago
20201220 19:59:48 GPU #0: using kernel #5
20201220 19:59:48 GPU #1: using kernel #5
20201220 19:59:48 GPU #2: using kernel #4
20201220 19:59:48 GPU #3: using kernel #5
20201220 19:59:49 WARN: GPU #5: MSI GeForce GTX 1070 Ti is idle, last activity was 25 secs ago
20201220 19:59:50 GPU #4: using kernel #2
20201220 19:59:55 WARN: GPU #5: MSI GeForce GTX 1070 Ti is idle, last activity was 30 secs ago
20201220 20:00:00 WARN: GPU #5: MSI GeForce GTX 1070 Ti is idle, last activity was 35 secs ago
20201220 20:00:05 WARN: GPU #5: MSI GeForce GTX 1070 Ti is idle, last activity was 40 secs ago
20201220 20:00:09 WARN: WATCHDOG: T-Rex has a problem with GPU, terminating...
20201220 20:00:10 WARN: WATCHDOG: recovering T-Rex
20201220 20:00:13 T-Rex NVIDIA GPU miner v0.19.4  -  [CUDA v11.10 | Windows]
20201220 20:00:13 r.ef7197621723
20201220 20:00:13 
20201220 20:00:13 NVIDIA Driver v460.89
20201220 20:00:13 CUDA devices available: 6
20201220 20:00:13 
20201220 20:00:13 WARN: DevFee 1% (ethash)
20201220 20:00:13 
20201220 20:00:13 URL : stratum+tcp://us-eth.2miners.com:2020
20201220 20:00:13 USER: 0x2783c77819f5c55d6101f3a398bdab9959b2763e
20201220 20:00:13 PASS: x
20201220 20:00:13 WRK : GPU
20201220 20:00:13 
20201220 20:00:13 Starting on: us-eth.2miners.com:2020
20201220 20:00:13 Using protocol: stratum1.
20201220 20:00:13 Authorizing...
20201220 20:00:13 Authorized successfully.
20201220 20:00:13 ApiServer: HTTP server started on 0.0.0.0:4067
20201220 20:00:13 ethash epoch: 383, diff: 8.59 Gh
20201220 20:00:13 -------------------------------------------------------
20201220 20:00:13 For control navigate to: http://192.168.0.109:4067/trex
20201220 20:00:13 -------------------------------------------------------
20201220 20:00:13 ApiServer: Telnet server started on 0.0.0.0:4068
20201220 20:00:13 WARN: GPU #0(000400): EVGA GeForce GTX 1080 Ti, intensity set to 22
20201220 20:00:13 WARN: GPU #1(000600): EVGA GeForce GTX 1080 Ti, intensity set to 22
20201220 20:00:14 WARN: GPU #2(000800): EVGA GeForce GTX 1080 Ti, intensity set to 22
20201220 20:00:14 WARN: GPU #3(000900): MSI GeForce GTX 1080 Ti, intensity set to 22
20201220 20:00:14 WARN: GPU #4(000200): EVGA GeForce GTX 1080, intensity set to 22
20201220 20:00:14 WARN: GPU #5(000100): MSI GeForce GTX 1070 Ti, intensity set to 22
20201220 20:00:17 GPU #1: generating DAG 3.99 GB for epoch 383 ...
20201220 20:00:17 GPU #2: generating DAG 3.99 GB for epoch 383 ...
20201220 20:00:17 GPU #0: generating DAG 3.99 GB for epoch 383 ...
20201220 20:00:17 GPU #4: generating DAG 3.99 GB for epoch 383 ...
20201220 20:00:17 GPU #3: generating DAG 3.99 GB for epoch 383 ...
20201220 20:00:22 GPU #0: DAG generated [time: 4961 ms], memory left: 5.99 GB
20201220 20:00:22 GPU #3: DAG generated [time: 5469 ms], memory left: 5.99 GB
20201220 20:00:22 GPU #2: DAG generated [time: 5474 ms], memory left: 5.99 GB
20201220 20:00:22 GPU #1: DAG generated [time: 5476 ms], memory left: 5.99 GB
20201220 20:00:24 GPU #4: DAG generated [time: 7194 ms], memory left: 3.05 GB
20201220 20:00:34 WARN: GPU #5: MSI GeForce GTX 1070 Ti is idle, last activity was 20 secs ago
20201220 20:00:38 GPU #0: using kernel #1
20201220 20:00:38 GPU #2: using kernel #5
20201220 20:00:38 GPU #1: using kernel #5
20201220 20:00:38 GPU #3: using kernel #1
20201220 20:00:40 WARN: GPU #5: MSI GeForce GTX 1070 Ti is idle, last activity was 25 secs ago
20201220 20:00:40 GPU #4: using kernel #2
20201220 20:00:45 WARN: GPU #0: EVGA GeForce GTX 1080 Ti is idle, last activity was 23 secs ago
20201220 20:00:45 WARN: GPU #5: MSI GeForce GTX 1070 Ti is idle, last activity was 30 secs ago
20201220 20:00:50 WARN: GPU #0: EVGA GeForce GTX 1080 Ti is idle, last activity was 28 secs ago
20201220 20:00:50 WARN: GPU #5: MSI GeForce GTX 1070 Ti is idle, last activity was 35 secs ago
20201220 20:00:55 WARN: GPU #0: EVGA GeForce GTX 1080 Ti is idle, last activity was 33 secs ago
20201220 20:00:55 WARN: GPU #5: MSI GeForce GTX 1070 Ti is idle, last activity was 40 secs ago
20201220 20:01:00 WARN: GPU #0: EVGA GeForce GTX 1080 Ti is idle, last activity was 38 secs ago
20201220 20:01:00 WARN: GPU #5: MSI GeForce GTX 1070 Ti is idle, last activity was 45 secs ago
20201220 20:01:00 WARN: WATCHDOG: T-Rex has a problem with GPU, terminating...
20201220 20:01:01 WARN: WATCHDOG: recovering T-Rex
20201220 20:01:04 T-Rex NVIDIA GPU miner v0.19.4  -  [CUDA v11.10 | Windows]
20201220 20:01:04 r.ef7197621723
20201220 20:01:04 
20201220 20:01:04 NVIDIA Driver v460.89
20201220 20:01:04 CUDA devices available: 6
20201220 20:01:04 
20201220 20:01:04 WARN: DevFee 1% (ethash)
20201220 20:01:04 
20201220 20:01:04 URL : stratum+tcp://us-eth.2miners.com:2020
20201220 20:01:04 USER: 0x2783c77819f5c55d6101f3a398bdab9959b2763e
20201220 20:01:04 PASS: x
20201220 20:01:04 WRK : GPU
20201220 20:01:04 
20201220 20:01:04 Starting on: us-eth.2miners.com:2020
20201220 20:01:04 Using protocol: stratum1.
20201220 20:01:04 Authorizing...
20201220 20:01:04 Authorized successfully.
20201220 20:01:04 ethash epoch: 383, diff: 8.59 Gh
20201220 20:01:04 ApiServer: HTTP server started on 0.0.0.0:4067
20201220 20:01:04 -------------------------------------------------------
20201220 20:01:04 For control navigate to: http://192.168.0.109:4067/trex
20201220 20:01:04 -------------------------------------------------------
20201220 20:01:04 ApiServer: Telnet server started on 0.0.0.0:4068
20201220 20:01:04 WARN: GPU #0(000400): EVGA GeForce GTX 1080 Ti, intensity set to 22
20201220 20:01:05 WARN: GPU #1(000600): EVGA GeForce GTX 1080 Ti, intensity set to 22
20201220 20:01:05 WARN: GPU #2(000800): EVGA GeForce GTX 1080 Ti, intensity set to 22
20201220 20:01:05 WARN: GPU #3(000900): MSI GeForce GTX 1080 Ti, intensity set to 22
20201220 20:01:05 WARN: GPU #4(000200): EVGA GeForce GTX 1080, intensity set to 22
20201220 20:01:05 WARN: GPU #5(000100): MSI GeForce GTX 1070 Ti, intensity set to 22
20201220 20:01:08 GPU #2: generating DAG 3.99 GB for epoch 383 ...
20201220 20:01:08 GPU #5: generating DAG 3.99 GB for epoch 383 ...
20201220 20:01:08 GPU #4: generating DAG 3.99 GB for epoch 383 ...
20201220 20:01:08 GPU #1: generating DAG 3.99 GB for epoch 383 ...
20201220 20:01:08 WARN: GPU #3: not enough memory to hold the full DAG for epoch 383.
20201220 20:01:08 WARN: GPU #3: effective hashrate will be ~99.6% of its usual value
20201220 20:01:08 GPU #3: generating DAG 3.99 GB (99.99% of full size) for epoch 383 ...
20201220 20:01:13 GPU #2: DAG generated [time: 5464 ms], memory left: 5.99 GB
20201220 20:01:13 GPU #1: DAG generated [time: 5471 ms], memory left: 5.99 GB
20201220 20:01:14 GPU #3: DAG generated [time: 5817 ms], memory left: 5.99 GB
20201220 20:01:15 GPU #4: DAG generated [time: 7214 ms], memory left: 3.05 GB
20201220 20:01:17 GPU #5: DAG generated [time: 8967 ms], memory left: 3.05 GB
20201220 20:01:26 WARN: GPU #0: EVGA GeForce GTX 1080 Ti is idle, last activity was 20 secs ago
20201220 20:01:29 GPU #2: using kernel #5
20201220 20:01:29 GPU #1: using kernel #5
20201220 20:01:31 WARN: GPU #0: EVGA GeForce GTX 1080 Ti is idle, last activity was 25 secs ago
20201220 20:01:31 GPU #4: using kernel #2
20201220 20:01:33 GPU #5: using kernel #2
20201220 20:01:36 WARN: GPU #0: EVGA GeForce GTX 1080 Ti is idle, last activity was 30 secs ago
20201220 20:01:41 WARN: GPU #0: EVGA GeForce GTX 1080 Ti is idle, last activity was 35 secs ago
20201220 20:01:46 WARN: GPU #0: EVGA GeForce GTX 1080 Ti is idle, last activity was 40 secs ago
20201220 20:01:51 WARN: GPU #0: EVGA GeForce GTX 1080 Ti is idle, last activity was 45 secs ago
20201220 20:01:51 WARN: WATCHDOG: T-Rex has a problem with GPU, terminating...
20201220 20:01:52 WARN: WATCHDOG: recovering T-Rex
20201220 20:01:55 T-Rex NVIDIA GPU miner v0.19.4  -  [CUDA v11.10 | Windows]
20201220 20:01:55 r.ef7197621723
20201220 20:01:55 
20201220 20:01:55 NVIDIA Driver v460.89
20201220 20:01:55 CUDA devices available: 6
20201220 20:01:55 
20201220 20:01:55 WARN: DevFee 1% (ethash)
20201220 20:01:55 
20201220 20:01:55 URL : stratum+tcp://us-eth.2miners.com:2020
20201220 20:01:55 USER: 0x2783c77819f5c55d6101f3a398bdab9959b2763e
20201220 20:01:55 PASS: x
20201220 20:01:55 WRK : GPU
20201220 20:01:55 
20201220 20:01:55 Starting on: us-eth.2miners.com:2020
20201220 20:01:55 Using protocol: stratum1.
20201220 20:01:55 Authorizing...
20201220 20:01:55 Authorized successfully.
20201220 20:01:55 ethash epoch: 383, diff: 8.59 Gh
20201220 20:01:55 ApiServer: HTTP server started on 0.0.0.0:4067
20201220 20:01:55 -------------------------------------------------------
20201220 20:01:55 For control navigate to: http://192.168.0.109:4067/trex
20201220 20:01:55 -------------------------------------------------------
20201220 20:01:55 ApiServer: Telnet server started on 0.0.0.0:4068
20201220 20:01:55 WARN: GPU #0(000400): EVGA GeForce GTX 1080 Ti, intensity set to 22
20201220 20:01:56 WARN: GPU #1(000600): EVGA GeForce GTX 1080 Ti, intensity set to 22
20201220 20:01:56 WARN: GPU #2(000800): EVGA GeForce GTX 1080 Ti, intensity set to 22
20201220 20:01:56 WARN: GPU #3(000900): MSI GeForce GTX 1080 Ti, intensity set to 22
20201220 20:01:56 WARN: GPU #4(000200): EVGA GeForce GTX 1080, intensity set to 22
20201220 20:01:57 WARN: GPU #5(000100): MSI GeForce GTX 1070 Ti, intensity set to 22
20201220 20:01:59 GPU #4: generating DAG 3.99 GB for epoch 383 ...
20201220 20:01:59 GPU #0: generating DAG 3.99 GB for epoch 383 ...
20201220 20:01:59 GPU #2: generating DAG 3.99 GB for epoch 383 ...
20201220 20:01:59 GPU #5: generating DAG 3.99 GB for epoch 383 ...
20201220 20:01:59 GPU #3: generating DAG 3.99 GB for epoch 383 ...
20201220 20:02:04 GPU #0: DAG generated [time: 4989 ms], memory left: 5.99 GB
20201220 20:02:05 GPU #2: DAG generated [time: 5720 ms], memory left: 5.99 GB
20201220 20:02:05 GPU #3: DAG generated [time: 5738 ms], memory left: 5.99 GB
20201220 20:02:06 GPU #4: DAG generated [time: 7218 ms], memory left: 3.05 GB
20201220 20:02:08 GPU #5: DAG generated [time: 9192 ms], memory left: 3.05 GB
20201220 20:02:17 WARN: GPU #1: EVGA GeForce GTX 1080 Ti is idle, last activity was 20 secs ago
20201220 20:02:20 GPU #0: using kernel #5
20201220 20:02:21 GPU #2: using kernel #4
20201220 20:02:21 GPU #3: using kernel #1
20201220 20:02:22 WARN: GPU #1: EVGA GeForce GTX 1080 Ti is idle, last activity was 25 secs ago
20201220 20:02:22 GPU #4: using kernel #2
20201220 20:02:25 GPU #5: using kernel #2
20201220 20:02:27 WARN: GPU #1: EVGA GeForce GTX 1080 Ti is idle, last activity was 30 secs ago
20201220 20:02:32 WARN: GPU #1: EVGA GeForce GTX 1080 Ti is idle, last activity was 35 secs ago
20201220 20:02:37 WARN: GPU #1: EVGA GeForce GTX 1080 Ti is idle, last activity was 40 secs ago
20201220 20:02:42 WARN: GPU #1: EVGA GeForce GTX 1080 Ti is idle, last activity was 45 secs ago
20201220 20:02:43 WARN: WATCHDOG: T-Rex has a problem with GPU, terminating...
20201220 20:02:43 WARN: WATCHDOG: recovering T-Rex
20201220 20:02:46 T-Rex NVIDIA GPU miner v0.19.4  -  [CUDA v11.10 | Windows]
20201220 20:02:46 r.ef7197621723
20201220 20:02:46 
20201220 20:02:46 NVIDIA Driver v460.89
20201220 20:02:46 CUDA devices available: 6
20201220 20:02:46 
20201220 20:02:46 WARN: DevFee 1% (ethash)
20201220 20:02:46 
20201220 20:02:46 URL : stratum+tcp://us-eth.2miners.com:2020
20201220 20:02:46 USER: 0x2783c77819f5c55d6101f3a398bdab9959b2763e
20201220 20:02:46 PASS: x
20201220 20:02:46 WRK : GPU
20201220 20:02:46 
20201220 20:02:46 Starting on: us-eth.2miners.com:2020
20201220 20:02:46 Using protocol: stratum1.
20201220 20:02:46 Authorizing...
20201220 20:02:46 Authorized successfully.
20201220 20:02:46 ApiServer: HTTP server started on 0.0.0.0:4067
20201220 20:02:46 -------------------------------------------------------
20201220 20:02:46 For control navigate to: http://192.168.0.109:4067/trex
20201220 20:02:46 -------------------------------------------------------
20201220 20:02:46 ApiServer: Telnet server started on 0.0.0.0:4068
20201220 20:02:46 ethash epoch: 383, diff: 8.59 Gh
20201220 20:02:47 WARN: GPU #0(000400): EVGA GeForce GTX 1080 Ti, intensity set to 22
20201220 20:02:47 WARN: GPU #1(000600): EVGA GeForce GTX 1080 Ti, intensity set to 22
20201220 20:02:47 WARN: GPU #2(000800): EVGA GeForce GTX 1080 Ti, intensity set to 22
20201220 20:02:47 WARN: GPU #3(000900): MSI GeForce GTX 1080 Ti, intensity set to 22
20201220 20:02:47 WARN: GPU #4(000200): EVGA GeForce GTX 1080, intensity set to 22
20201220 20:02:48 WARN: GPU #5(000100): MSI GeForce GTX 1070 Ti, intensity set to 22
20201220 20:02:50 GPU #1: generating DAG 3.99 GB for epoch 383 ...
20201220 20:02:50 GPU #5: generating DAG 3.99 GB for epoch 383 ...
20201220 20:02:50 GPU #4: generating DAG 3.99 GB for epoch 383 ...
20201220 20:02:50 GPU #3: generating DAG 3.99 GB for epoch 383 ...
**20201220 20:02:51 WARN: GPU #2: ****not enough memory to hold the full DAG for epoch 383.******
20201220 20:02:51 WARN: GPU #2: effective hashrate will be ~99.6% of its usual value
20201220 20:02:51 GPU #2: generating DAG 3.99 GB (99.99% of full size) for epoch 383 ...
20201220 20:02:55 GPU #3: DAG generated [time: 5557 ms], memory left: 5.99 GB
20201220 20:02:55 GPU #1: DAG generated [time: 5566 ms], memory left: 5.99 GB
20201220 20:02:56 GPU #2: DAG generated [time: 5839 ms], memory left: 5.99 GB
20201220 20:02:57 GPU #4: DAG generated [time: 7316 ms], memory left: 3.05 GB
20201220 20:02:59 GPU #5: DAG generated [time: 9076 ms], memory left: 3.05 GB
20201220 20:03:08 WARN: GPU #0: EVGA GeForce GTX 1080 Ti is idle, last activity was 20 secs ago
20201220 20:03:12 GPU #1: using kernel #1
20201220 20:03:12 GPU #3: using kernel #5
20201220 20:03:13 WARN: GPU #0: EVGA GeForce GTX 1080 Ti is idle, last activity was 25 secs ago
20201220 20:03:14 GPU #4: using kernel #2
20201220 20:03:16 GPU #5: using kernel #2
20201220 20:03:18 WARN: GPU #0: EVGA GeForce GTX 1080 Ti is idle, last activity was 30 secs ago
20201220 20:03:23 WARN: GPU #0: EVGA GeForce GTX 1080 Ti is idle, last activity was 35 secs ago
20201220 20:03:28 WARN: GPU #0: EVGA GeForce GTX 1080 Ti is idle, last activity was 40 secs ago
20201220 20:03:33 WARN: GPU #0: EVGA GeForce GTX 1080 Ti is idle, last activity was 45 secs ago
20201220 20:03:34 WARN: WATCHDOG: T-Rex has a problem with GPU, terminating...
20201220 20:03:34 WARN: WATCHDOG: recovering T-Rex
20201220 20:03:37 T-Rex NVIDIA GPU miner v0.19.4  -  [CUDA v11.10 | Windows]
20201220 20:03:37 r.ef7197621723

**Comment by trexminer** [comment]
It may be a long shot, but could you try increasing the paging file size? It should be at least 60GB for your configuration.

**Comment by vfncomp** [comment]
Bumped the pagefile to 60GB and seems to work with 4 gpu setup - was at 3GB /w 8GB physical - all gpu's functional

**Comment by robielord** [comment]
Hi.
I have a very similar problem, could you please help me?

**Comment by omarov10** [comment]
Hi

I didn't succeed in resolving the problem, i have noticed that the miner
crashes every 13 to 14 hours of straight mining, so what i did, is to
create a Windows Schedule job that restart the computer every 12hours, and
launches the miner on startup

I hope this helps you

Le ven. 16 juil. 2021 à 09:39, robielord ***@***.***> a
écrit :
