### ISSUE TITLE
TREX: Can't initialize device [ID=1, GPU #1], can't lock core clock, can't set gpu lock clocks: error code 3

### ISSUE THREAD

**Issue by Vounts** [trexminer/T-Rex#1204]
Title says, using config : 1070 GTX
--fan 100 --pl 68 --lock-cclock 1035--mclock 584

**Comment by TeeCeeCrypto** [comment]
Hi. I don't think you can use --lock-cclock on Pascal cards (especially the 1060 6GB / 1070). I think it only works with RTX 1660, 2000 and 3000 series.

**Comment by trexminer** [comment]
Correct, it's not supported on Pascal GPUs.
