### ISSUE TITLE
Updated to lhr unlock

### ISSUE THREAD

**Issue by Lama012** [trexminer/T-Rex#1206]
Lol miner lauch 78% lhr unluck so when you trex gonna lauch the this unlock plz we are waiting so so realse the new version like lol miner thank you

**Comment by Shano592** [comment]
It's bad form to ask a developer of any software to hurry up, for any reason.

The next version of T-Rex will be released, when it is released.  

Be thankful for the excellent software that we have now.

**Comment by grenelt** [comment]
@Shano592 Maybe you missed we are paying for it? So it's quite appropriate to make claims...

**Comment by zulu1905** [comment]
> @Shano592 Maybe you missed we are paying for it? So it's quite appropriate to make claims...

These people are not your salaried employees, so don't put yourself in the position of the boss here. Whenever they make an improvement then they release a new version. you just have to wait.

**Comment by Miiichal** [comment]
He pleased for it :)
i think he want the same thing as the others - to move for a few percent more, closer to 80 :)
We all know, that developers are overworked.
So this was something like "**please if u have time, it would be great to use YOUR excavator with the same possibilities, like the LolMiner has got!**"
:))

**Comment by Lama012** [comment]
> > @grenelt Maybe you missed we are paying for it? So it's quite appropriate to make claims...
> 
> These people are not your salaried employees, so don't put yourself in the position of the boss here. Whenever they make an improvement then they release a new version. you just have to wait.

Yes they are salaried my our mining percentage broo chill we are regular user we expected more from it other do better then we also want more better from it and we all miner are boss dude #thinkbigger muji

**Comment by trexminer** [comment]
Please try 0.25.12 with improved LHR unlocker
