### ISSUE TITLE
Error: Can't stop device (ID=1, GPU #1).  cuda exception: CUDA_ERROR_UNKNOWN

### ISSUE THREAD

**Issue by IamOldBoy** [trexminer/T-Rex#1207]
Hi folks!

Any idea about the following error received on a 2060?? 

"Error: Can't stop device (ID=1, GPU #1).  cuda exception: CUDA_ERROR_UNKNOWN"

This causes the GPU to crash and Trex to restart.

Previously I had the nonce error, which I resolved by reducing the memory clock to 0.  I am undervolting the card still due to the temp increase.

To note:  Rig is 8X2060.  VRAM is 80000.

If anyone has seen this or has any suggestions, please let me know.  Thanks!

Image #1 - 
![image](https://user-images.githubusercontent.com/94426927/162575145-3f7608bc-1c2f-4f18-bee8-47d86d943e95.png)

UPDATE - 

I received multiple warnings on the most recent crash.  Please see pictured.  I am going to pull the card, but any input would be appreciated.  Thanks again.

![image](https://user-images.githubusercontent.com/94426927/162575374-b9cbbf1b-6686-49e1-ad2a-f10d6b1b8514.png)

**Comment by trexminer** [comment]
See https://github.com/trexminer/T-Rex/wiki/FAQ#what-are-error-codes-15-and-999
