### ISSUE TITLE
Separate bad shares: incorrect, stale and rejected

### ISSUE THREAD

**Issue by megalolka** [trexminer/T-Rex#121]
Hello!
Is it possible to make T-Rex show incorrect shares, stale shares and rejected by the pool shares separately?
Like the PhoenixMiner does this.
Because incorrect shares are mostly caused by overclocking and miners should see that the overclocking should be adjusted.
And the other types of bad shared (stale or rejected by pool) doesn't require to make overlocking changes.

**Comment by kamesen99** [comment]
Updoot. I'm seeing stale shares sent to the pool (on the pool dashboard), but I cant tell which GPU they're coming from. TY

**Comment by trexminer** [comment]
Implemented the requested functionality when `--validate-shares` is set, check out the latest version.
