### ISSUE TITLE
 i testing the t-rex  0.25.10 for mining eth and find the hasprate is lower!how to set the ccl and mcl?

### ISSUE THREAD

**Issue by alixeking** [trexminer/T-Rex#1212]
![Uploading trex.jpg…]()

**Comment by trexminer** [comment]
if you wish to overclock your GPU through T-Rex, you can use `--mclock` and `--cclock` parameters (see readme for details)

**Comment by alixeking** [comment]
![trex1](https://user-images.githubusercontent.com/101870529/163415170-042806d7-93ce-46f6-85f0-3cd262e04150.jpg)

**Comment by alixeking** [comment]
what ccl and mcl to set for 3080

**Comment by alixeking** [comment]
t-rex.exe -a ethash -o stratum+ssl://eth-us-east.flexpool.io:5555 -u 0x1f75eccd8fbddf057495b96669ac15f8e296c2cd -p x -w rig0  --device 0,1,3  --cclock 100,200,300  --mclock 1100,1200,1300 --fan tm:90,90,90
pause
is the format right?

**Comment by sign1818** [comment]
I woukd like to test the new version too

**Comment by trexminer** [comment]
> what ccl and mcl to set for 3080

cclock can be left at 0, mclock is the highest your cards are still stable at - this will improve ethash performance

**Comment by trexminer** [comment]
> I woukd like to test the new version too

download 0.25.12 from the releases page

**Comment by alixeking** [comment]
why&nbsp; always&nbsp; 68.5hashrate?

**Comment by alixeking** [comment]
I have&nbsp; an&nbsp; issue that&nbsp; .when&nbsp; I&nbsp; set&nbsp; the&nbsp; oc&nbsp; setting&nbsp; in&nbsp; the&nbsp; t-rex！c clock for 1000,&nbsp; m clock&nbsp; for&nbsp; 1500 in t-rex!&nbsp; if&nbsp; iI change&nbsp; to&nbsp; MSI afterburner&nbsp; what&nbsp; values&nbsp; should&nbsp; i&nbsp; set for&nbsp; the&nbsp; c clock and m clock!&nbsp; in the Afterburner&nbsp; the&nbsp; cclock&nbsp; only&nbsp; set&nbsp; 959 for the max!

**Comment by alixeking** [comment]
what does&nbsp; 999 mean

**Comment by alixeking** [comment]
why&nbsp; there's a !

**Comment by alixeking** [comment]
where&nbsp; can&nbsp; I&nbsp; download the&nbsp; newest ver
