### ISSUE TITLE
Auto calibration doesn't do anything

### ISSUE THREAD

**Issue by grenelt** [trexminer/T-Rex#1214]
> Make sure you remove any --lhr-tune settings you may have in your existing configuration. The miner will calibrate the unlocker and the hashrate should go up to its normal level in about a minute after the miner displays calibration finished message.

With my rig with 2 3060TI LHR (and several other non-LHR Nvidia gpus) the auto calibration does absolutely nothing. Starts with 74 (and the "target hashrate for unlocker" message) and doesn't move anywhere. After 10 minutes (--lhr-autotune-interval 10) the regular "autotune" kicks in and sometimes crashes the miner...  There is never a "calibration finished" message...

`20220415 13:42:09 WARN: WATCHDOG: T-Rex has a problem with GPU, terminating...`

Miner start was @ 13:32:08

Windows 10, Driver 472.12, V0.25.12, Dual Mining Alephium without Algo-Mode-Settings.

The 3060TI were really shitty ones with Hynix V1 running --lock-cclock 1266, 1300 --mclock 800, 825

If i'm starting with higher LHR numbers, a lot of the LHR locks and unlocks lead to a crash. Often i can't see the LHR lock/unlock but i get a message like:

`20220415 14:43:34 TREX: thread terminated, error code 999`

For me it's the worst version for some time, i had a hard time to get the rig stable again... The LHR factor sits around 75.5 to 76 @ 42 MH/s. That the 3060TI LHR Hynix V1 are as shitty as they are is not T-Rex' fault - but with this version nearly nothing works as expected, it doesn't show the source of errors and for me it delivers absolutely no improvement by numbers.

**Comment by trexminer** [comment]
Could you post the log file please?

**Comment by grenelt** [comment]
[trex_0.25.12_nocalibration.log](https://github.com/trexminer/T-Rex/files/8497500/trex_0.25.12_nocalibration.log)

**Comment by trexminer** [comment]
Thanks.
Dual mining is not affected by the recent change, I've clearly stated that in the release notes, so don't expect any improvements. Also, default value for `--lhr-autotune-mode` is now `down`, not `full`, so if you want the miner to try and increase LHR tune you need to set it to `full` explicitly.
`T-Rex has a problem with GPU, terminating` along with error code 999 usually indicates a hardware related problem, see FAQ for possible reasons.

**Comment by grenelt** [comment]
To clarify: All LHR improvements apply only with single mining ethereum? I didn't understand "dual modes and autolykos2 LHR performance is unchanged" this way... Maybe i misunderstood because of the lack of understanding how different code paths for the different modes are.

The thing with code 999 is, if it wasn't a thing with prior versions but is now and the hardware is unchanged - it's still hardware related?

**Comment by setab001** [comment]
same problem eror 9999 newer i haw so was
