### ISSUE TITLE
Linux Driver 460.39 for Hiveos not working on 0.25.12

### ISSUE THREAD

**Issue by Rishmage** [trexminer/T-Rex#1219]
I have 6 3060 rev 1 graphics cards and I have been using 460.39 on Hiveos for all of the miners including up to T-rex 0.25.9 and now once I updated my GPU is giving me an error saying to update the driver if it is LHR. What is the driver for 3060 v1 cards now?

**Comment by Antxj** [comment]
Same here

**Comment by dedizones** [comment]
See Changelog :/ ```
Recommended drivers:
Linux - 470.xx or newer
Windows - 512.xx (although 472.xx works fine too)

```
