### ISSUE TITLE
T-Rex 0.19.5 octopus result

### ISSUE THREAD

**Issue by EvgeniyKorepov** [trexminer/T-Rex#122]
The new version has increased

- RTX 2070 Super 42 MH/s -> 52 MH/s
- RTX 3070 47 MH/s -> 57 MH/s
- RTX 3090 85 MH/s -> 107 MH/s

Excellent work! Thank you very much

**Comment by liudongjia** [comment]
Why is my 2070super only 46mh? How to set it up, thank you!

**Comment by EvgeniyKorepov** [comment]
I tested with 75%, Core 0, Mem +890
GIGABYTE GeForce RTX 2070 Super AORUS [GV-N207SAORUS-8GC]

**Comment by liudongjia** [comment]
Thank you very much, I will try it now

**Comment by liudongjia** [comment]
![捕获](https://user-images.githubusercontent.com/29215561/104138538-9f476200-53df-11eb-807a-1093c28b2cba.PNG)
Really, you are amazing
