### ISSUE TITLE
Lhr low power fluctuation

### ISSUE THREAD

**Issue by Chehayed** [trexminer/T-Rex#1236]
Hive OS
Trex 0.25.12
Driver 470.82.00
3 x 3070TI 
Core 1500
Memory 2700
PL 200
Fan 90

Memory temperatures peaking at 100degC in normal mode eth hashrate stable at 190mhs, power consumption stable at around 190W/GPU or 570W total.

When switching to low power mode, "lhr-low-power": true , memory temperature drops by 15 degrees which is good and hashrate drops to a stable 180mhs.

Problem is power consumption fluctuating alot. Each GPU goes to 190W then drops to around 150W for a few seconds, then repeats. Graph is crazy. How can i stabilize the power consumption.

![20220418_060447](https://user-images.githubusercontent.com/103913565/163748076-a5052a77-281c-4082-bcd3-b72ef86765cc.jpg)

**Comment by trexminer** [comment]
You can't stabilise it, that's how low power mode works, unfortunately.
