### ISSUE TITLE
What is: "WARN: Unusual clock change detected" ?

### ISSUE THREAD

**Issue by grenelt** [trexminer/T-Rex#1241]
Windows 10, V 0.25.12, Driver 472.12

OC via T-Rex, no additional software (Afterburner...)

**Comment by trexminer** [comment]
Your system clock readings have suddenly changed - usually happens during time synchronisation in OS, not a big deal, the miner log might show non-sequential log entries, that's it.

**Comment by grenelt** [comment]
ahh ic.. thx...  I was totally on gpu clocks... Maybe a "WARN: Unusual **system** clock change detected" would be more precise... ;)

**Comment by trexminer** [comment]
I agree 100%, will fix it :) Thanks.
