### ISSUE TITLE
Not enough GPU memory DAG epoch, bad allocation T-rex, eth mining

### ISSUE THREAD

**Issue by GeketteN** [trexminer/T-Rex#125]
Hello, 
I have 9 GPU Nvidia GTX 1080 and 1060 for mining eth on T-Rex, I use MSI Afterburner to control them but somehow I encounter this issue : Not enough GPU memory DAG epoch, bad allocation when I disconnect 1 GPU it works but when I add the 9th one it sends me this error  
How to sort this out ?  

not enough GPU memory to place DAG  

WARN: GPU #1: EVGA GeForce GTX 1080 Ti is idle, last activity was 30 secs ago 
20201220 20:02:32 WARN: GPU #1: EVGA GeForce GTX 1080 Ti is idle, last activity was 35 secs ago 
20201220 20:02:37 WARN: GPU #1: EVGA GeForce GTX 1080 Ti is idle, last activity was 40 secs ago 
20201220 20:02:42 WARN: GPU #1: EVGA GeForce GTX 1080 Ti is idle, last activity was 45 secs ago

**Comment by ARES666** [comment]
you should try in windows to make a bigger swap file I recomend 128GB then you are OK for long time. but if it is not this issue, may some one else help you

**Comment by trexminer** [comment]
@GeketteN What ARES666 suggested is the first thing I'd try

**Comment by GeketteN** [comment]
Yes Yes yes it worked ! I thought it was a problem with the settings of the card but no... Thanks a lot ;)
