### ISSUE TITLE
windows系统 025.12版本 LHR低功耗模式老是跳

### ISSUE THREAD

**Issue by 6542604** [trexminer/T-Rex#1256]
windows系统025.12版本LHR低功耗模式，功耗老是跳高跳低，有什么办法固定功耗不让跳！或者更新025.13版本LHR低功耗模式不让功耗跳动

**Comment by 6542604** [comment]
> windows系统025.12版本LHR低功耗模式，功耗老是跳高跳低，有什么办法固定功耗不让跳！或者更新025.13版本LHR低功耗模式不让功耗跳动 
![B5E7DC30-B662-40A9-BEBD-A9741A91234E](https://user-images.githubusercontent.com/93634152/164909623-c56eb7bd-96cd-4cbd-9b2d-94cf8acc94b6.png)

**Comment by trexminer** [comment]
Duplicate
