### ISSUE TITLE
windows系统025.12版本LHR低功耗模式，功耗老是跳高跳低，有什么办法固定功耗不让跳！或者更新025.13版本LHR低功耗模式不让功耗跳动

### ISSUE THREAD

**Issue by 6542604** [trexminer/T-Rex#1257]
windows系统025.12版本LHR低功耗模式，功耗老是跳高跳低，有什么办法固定功耗不让跳！或者更新025.13版本LHR低功耗模式不让功耗跳动
![Uploading EBEDEB66-3D41-48F7-B125-AE2F3C7DB72E.png…]()

**Comment by 6542604** [comment]
![Uploading 48622736-E81F-4FE1-B35C-2C444C20D142.png…]()

**Comment by trexminer** [comment]
No, unfortunately, that's the only to reduce power consumption without compromising too much on the hashrate.
