### ISSUE TITLE
 0.19.3-0.19.5 error

### ISSUE THREAD

**Issue by bchtrue** [trexminer/T-Rex#127]
@trexminer the same problem. 0.19.1 working fine, 0.19.3-0.19.5 error
20210103 20:29:10 TREX: eyJhIjoieDVxbEJXMWhadjI2TGxWY1pXdFk0RTJNbUxRdDVsZXRhODV5eTl3Rml0Zz0iLCJiIjoiWmRvUzUrT1JPdG05WTVGdlZHSjFLZz09In0K

**Comment by trexminer** [comment]
Hi. Which OS are you using? If you use Hive, update it to the latest version. 
Try to start the miner this way:  LD_PRELOAD="" ./t-rex <your args>

**Comment by bchtrue** [comment]
It's Ubunty.
Thanks, with LD_PRELOAD it started.
