### ISSUE TITLE
Dual Mining ETHASH + KAWPOW

### ISSUE THREAD

**Issue by EliranRefaely** [trexminer/T-Rex#1275]
Hi,

I am trying to mining ethash and kawpow algos at the same time.
And it looks like T-Rex does not mining kawpow.

I have connections:
![image](https://user-images.githubusercontent.com/69577077/166405420-daf408b2-9dfa-4026-9566-2674a759dc7c.png)

And the Shares/min of kawpow (the second table) is  0
![image](https://user-images.githubusercontent.com/69577077/166405451-15c6c829-8077-4267-9e24-934cd745cea9.png)

This is the cmd code -
t-rex.exe -a ethash --dual-algo kawpow -o prohashing.com:3339 -u xxx -p xxx --url2 stratum+tcp://prohashing.com:3361 --user2 xxx --pass2 xxx
pause

Thank by advance for helping!

**Comment by trexminer** [comment]
ETH+RVN mode only works for LHR cards at the moment

**Comment by EliranRefaely** [comment]
There is an ETA for non-LHR to mining dual?

**Comment by trexminer** [comment]
You can dual mine ETH+ALPH on non-LHR cards, but there's no financial benefit in case of ETH+RVN, so it's not on our todo list.
