### ISSUE TITLE
T-Rex, how to mine 2 crypto on ethermine (ETC and ETH)

### ISSUE THREAD

**Issue by GeketteN** [trexminer/T-Rex#130]
Hi guys do you know if it's possible to mine 2 cryptos at the same time without affecting to much the Hasrates and if yes which crypto and how to set up T-Rex ?

I am currently mining ETH and wanted to add Ethereum Classic ETC ....

Thanks for your help ;)

**Comment by trexminer** [comment]
Discussion moved to https://github.com/trexminer/T-Rex/issues/135
