### ISSUE TITLE
Very happy

### ISSUE THREAD

**Issue by sign1818** [trexminer/T-Rex#1305]
Thx for the good mining software 0.26.1!!!
Me very happy with the 100% LHR  unlock.

**Comment by Bronsens** [comment]
Same! I Went from 39.14 MH/s to 49.41 MH/s on my 3060 V2.

**Comment by GRai-Github** [comment]
What overclock settings are you using on 3060 LHR?

**Comment by sign1818** [comment]
3060 V2  49.59 mh/s
mem 1300, core 1620, pl 71

**Comment by Bronsens** [comment]
Mem 1300 Core 1537 PL 72 Voltage locked at 825mv

**Comment by pawelantczak** [comment]
49 at 125W will give efficiency at 0.39+ level
44 at 100W will give efficiency as 0.44+ level.
Why to push 3060 to 125W?

**Comment by Bronsens** [comment]
> 49 at 125W will give efficiency at 0.39+ level 44 at 100W will give efficiency as 0.44+ level. Why to push 3060 to 125W?

This begs to differ from your math
![image](https://user-images.githubusercontent.com/29926234/168320040-229de1f2-1b34-4aca-b53f-6c1e7063a9b8.png)

**Comment by sd1650644** [comment]
How about Ergo? Is it 100% LHR?

**Comment by gbolcer** [comment]
Upgraded and the performance is about 25% faster.  Though, I'd like to throttle it backdown a big.   I have --low-load 0,1
as the one card doesn't get as much airflow, but any exact command line suggestions for cooler and quieter configs anyone is using would be appreciated.   

GPU #0: RTX 3060 - 37.26 MH/s, [T:62C, P:143W, F:69%, E:262kH/W]
GPU #1: RTX 3060 - 41.96 MH/s, [T:73C, P:147W, F:82%, E:287kH/W], 1/1 R:0%
Hashrate: 79.22 MH/s, Shares/min: 1 (Avg. 1.091), Avg.P: 288W, Avg.E: 275kH/W
Uptime: 3 mins | Algo: ethash | Driver: 510.60.02 | T-Rex 0.26.1
WD: 3 mins 1 sec, shares: 1/1
