### ISSUE TITLE
The latest release 0.19.7 is being flagged as Trojen.Gen.2 virus by Norton

### ISSUE THREAD

**Issue by jenishngl** [trexminer/T-Rex#132]
Is this something to be concerned about. I mean since Norton was able to find the signature of a Trojen in the file

**Comment by trexminer** [comment]
No, it's a false positive. See https://github.com/trexminer/T-Rex#antivirus-alerts

**Comment by JordanSolutions** [comment]
Not just Norton...

**Comment by jenishngl** [comment]
Not an issue then
