### ISSUE TITLE
T-Rex instance wasn't validated

### ISSUE THREAD

**Issue by morro67** [trexminer/T-Rex#1325]
`TREX: T-Rex instance wasn't validated 
WARN: Messy shutdown`
This error raising from 3 different places and 3 different provider, via proxy or tor too
https://trex-miner.com/:443 is available

**Comment by Basicqwe** [comment]
The same problem.
Do not work:
1.  --dns-https-server 1.1.1.1 --no-sni
2. win firewall exception

Error after 5 minutes.

**Comment by d1Mm** [comment]
same. started about 1-2h ago
