### ISSUE TITLE
TREX: Can't unlock GPU [ID=0, GPU #0], thread terminated, error code 15

### ISSUE THREAD

**Issue by w00txs** [trexminer/T-Rex#1327]
Hi

I get this error on HiveOS: Can't unlock GPU [ID=0, GPU #0], thread terminated, error code 15
MSI 3080Ti trio X- I have tried flashing it to EVGA 3080Ti but same issue remains. it worked "fine" for 2-3 days after the full LHR unlock but then the issues became frequent. card never seems to draw over ~250W which is very strange for a 3080Ti.
even my crappy PNY 3080Ti that is flashed to EVGA- with only two 8pin power draws ~300W

N driver:  510.60.02

 any ideas? would really appreciate any help. I have even tried downgrading to 25.15

**Comment by w00txs** [comment]
just adding that I am on a riserless MB and catched below in console

20220521 00:41:15 WARN: NVML: can't get temperature for GPU #0, error code 15                                                                                                                                                    
20220521 00:41:15 WARN: NVML: can't get fan speed for GPU #0, error code 15                                                                                                                                                      
20220521 00:41:15 WARN: NVML: can't get power for GPU #0, error code 15                                                                                                                                                          
20220521 00:41:15 WARN: NVML: can't get mem/core clock for GPU #0, error code 15                                                                                                                                                 
20220521 00:41:16 TREX: Can't unlock GPU [ID=0, GPU #0], thread terminated, error code 15

**Comment by xsoul** [comment]
I also have same issue with rtx 3060 Ti Hynix memory, the miner only able to mine for few minutes then it come out with this errors

20220525 09:39:08 [ OK ] 2/2 - 59.10 MH/s, 52ms ... GPU #2 | 5.05 G
20220525 09:39:17 TREX: Can't unlock GPU [ID=2, GPU #2], error code 15
20220525 09:39:17 WARN: Miner is going to shutdown...                                                                                                                                                              
20220525 09:39:17 Main loop finished. Cleaning up resources...                                                                                                                                                     
20220525 09:39:17 ApiServer: stopped listening on 127.0.0.1:4059                                                                                                                                                   
20220525 09:39:47 Committing suicide...

**Comment by w00txs** [comment]
![bust cable](https://user-images.githubusercontent.com/105949509/170539754-a7753343-e152-40f0-9e4e-29de8a7f8b67.jpg)

same issue, cable. I had troubleshoot all cables going into my GPUs but this sucker went into the motherboard.

**Comment by geroallue** [comment]
> I also have same issue with rtx 3060 Ti Hynix memory, the miner only able to mine for few minutes then it come out with this errors
> 
> 20220525 09:39:08 [ OK ] 2/2 - 59.10 MH/s, 52ms ... GPU #2 | 5.05 G 20220525 09:39:17 TREX: Can't unlock GPU [ID=2, GPU #2], error code 15 20220525 09:39:17 WARN: Miner is going to shutdown... 20220525 09:39:17 Main loop finished. Cleaning up resources... 20220525 09:39:17 ApiServer: stopped listening on 127.0.0.1:4059 20220525 09:39:47 Committing suicide...


how did you solve the problem ???, same issue
