### ISSUE TITLE
Can't start T-Rex

### ISSUE THREAD

**Issue by LeapingTortoise** [trexminer/T-Rex#1330]
Getting a message when attempting to start T-Rex (0.26.1 & 0.26.4):

ERROR: Can't start T-Rex, can't set LHR autotune increment interval, bad lexical cast: source type value could not be interpreted as target

Following Configs have been tried all with the same result:

t-rex.exe -a ethash -o stratum+ssl://eth-au.flexpool.io:5555 -u address -p x  --lhr-tune 73.7 --lhr-autotune-mode full --lhr-autotune-step-size 0.1 --lhr-autotune-interval 5 -w NvidiaMiner -c config.txt

t-rex.exe -a ethash -o stratum+ssl://eth-au.flexpool.io:5555 -u address -p x -w NvidiaMiner -c config.txt

Running on Windows and have tried Nvidia drivers: 512.15 and 512.77. Everything is running as Admin

**Comment by trexminer** [comment]
Removing all lhr parameters should fix the issue. T-Rex unlocks LHR GPUs by default in the recent versions.

**Comment by LeapingTortoise** [comment]
I did remove the lhr tags (as in the second line) and the error is the same.

**Comment by LeapingTortoise** [comment]
Some LHR tags were carried over to the config file causing the error. Removed them from the config file and T-Rex now starts just fine.
