### ISSUE TITLE
TREX: Can't find nonce with device [ID=1, GPU #1], cuda exception: CUDA_ERROR_UNKNOWN

### ISSUE THREAD

**Issue by andriy2011** [trexminer/T-Rex#1331]
**Doesn't really matter if overclocked or not. T-Rex keeps restarting 
Tnx**

20220522 11:30:48 T-Rex NVIDIA GPU miner v0.26.1  -  [Windows]
20220522 11:30:48 r.d56ae19915c9
20220522 11:30:48 
20220522 11:30:48 
20220522 11:30:48 NVIDIA Driver v472.12
20220522 11:30:48 
20220522 11:30:48 + GPU #0: [00:01.0|2484] EVGA GeForce RTX 3070, 8192 MB
20220522 11:30:48 + GPU #1: [00:06.0|2489] Zotac GeForce RTX 3060 Ti, 8192 MB
20220522 11:30:48 
20220522 11:30:48 WARN: DevFee 1% (ethash)
20220522 11:30:48 
20220522 11:30:48 URL : stratum+tcp://eth-us-east1.nanopool.org:9999
20220522 11:30:48 USER: *******
20220522 11:30:48 PASS: x
20220522 11:30:48 
20220522 11:30:48 Starting on: eth-us-east1.nanopool.org:9999
20220522 11:30:48 ApiServer: HTTP server started on 127.0.0.1:4067
20220522 11:30:48 ---------------------------------------------------
20220522 11:30:48 For control navigate to: http://127.0.0.1:4067/trex
20220522 11:30:48 ---------------------------------------------------
20220522 11:30:48 Using protocol: stratum1.
20220522 11:30:48 Authorizing...
20220522 11:30:48 GPU #0: intensity 22, mclock 800MHz, cclock -100MHz, pl 55%
20220522 11:30:48 GPU #1: intensity 22, mclock 400MHz, cclock -100MHz, pl 63%
20220522 11:30:49 Authorized successfully.
20220522 11:30:49 ethash epoch: 494, diff: 10.00 G
20220522 11:30:52 GPU #1: generating DAG 4.86 GB for epoch 494 ...
20220522 11:30:52 GPU #0: generating DAG 4.86 GB for epoch 494 ...
20220522 11:31:01 GPU #0: DAG generated [crc: 293082c5, time: 9132 ms], memory left: 2.10 GB
20220522 11:31:03 GPU #1: DAG generated [crc: 293082c5, time: 11068 ms], memory left: 2.13 GB
20220522 11:31:17 GPU #0: using kernel #2
20220522 11:31:19 GPU #1: using kernel #4
**20220522 11:31:30 TREX: Can't find nonce with device [ID=1, GPU #1], cuda exception: CUDA_ERROR_UNKNOWN**
20220522 11:31:30 WARN: Miner is going to shutdown...
20220522 11:31:30 Main loop finished. Cleaning up resources...
20220522 11:31:30 ApiServer: stopped listening on 127.0.0.1:4067
20220522 11:31:32 T-Rex finished.
20220522 11:31:33 WARN: WATCHDOG: T-Rex does not exist anymore, restarting...
20220522 11:31:35 T-Rex NVIDIA GPU miner v0.26.1  -  [Windows]
20220522 11:31:35 r.d56ae19915c9
20220522 11:31:35 
20220522 11:31:35 
20220522 11:31:35 NVIDIA Driver v472.12

**Comment by trexminer** [comment]
Upgrade video drivers to 512.xx or use this build https://trex-miner.com/download/test/t-rex-0.26.4-old-drivers-win.zip
