### ISSUE TITLE
0.25.15+ - lower performance for 3080 LHR card (GA102-lhr)

### ISSUE THREAD

**Issue by oldskool75** [trexminer/T-Rex#1342]
since 0.25.15, I noticed my 3080 10GB LHR (EVGA 10G-P5-3897-KL) has dropped its performance from 80MH/s to ~50MHs (when screens locked/powered down).

I tested this on 0.25.15, 0.26.1 and 0.26.4.
Rolling back to 0.25.12 returns the performance to ~80MH/s (while idle/screen locked+powered down).
This is on nvidia driver 512.95.

FWIW, I'm mining with two cards, 3060Ti (non-LHR), and the 3080 LHR.
3060Ti is constantly at 60.x MH/s, and the 3080 is changing from 80.x MH/s (ideal) to somewhere between 45-52 MH/s with t-rex miner versions 0.25.15 or higher.

The measurements are being taken after locking the screen for >5 mins (displays power down as well).

Edit: Just noticed that this was also mentioned in https://github.com/trexminer/T-Rex/issues/1289.

**Comment by sign1818** [comment]
Try driver 512.59 or 512.77. The latest driver 512.95 re-eanbles LHR!
Only 0.26... enables full unlock.

**Comment by oldskool75** [comment]
If that's true (and I'm not calling you a liar), shouldn't it be mentioned in the release notes? 
It just says v512 is required.

**Comment by sign1818** [comment]
512.95 driver release date 24/05, so...

**Comment by oldskool75** [comment]
Hah. didn't realize the driver was only a day old, I just decided to update (everything) on a whim as it's been months since I last checked.

...And confirmed!
v512.59 with t-rex v0.26.4
after a few mins idle:
3080 (LHR): 100.48 MH/s
nice!
