### ISSUE TITLE
HiveOS 11 GPU 1 LHR elfupgrade to 0.26.4 LHR card is now slower than ever

### ISSUE THREAD

**Issue by IcannotThinkOfAnymoreNames** [trexminer/T-Rex#1343]
HiveOS 
11 GPU
1 LHR
selfupgrade to 0.26.4

Previously mined on 25.9 the lhr hummed along at 76% nice work!

No over clock settings but lock-cclock

just added
"lhr-tune":"0,0,0,77,0,0,0,0,0,0,0"
on startup it says lhr 77
there is no lhr space on the miner's feed anymore thank you!

3060 lhr formerly at 75% and 30.5mh is now at 22.1 mh

I've likely done something wrong. It is otherwise mining fine. What did I do wrong?

**Comment by sign1818** [comment]
T-Rex versions 0.26.xx are LHR 100% unlock, LHR unlocker requires 512.xx version of the driver on Windows, and 510.xx on Linux.
No need to set lhr-tune anymore. 3060 LHR no easily 49 mh/s.

**Comment by IcannotThinkOfAnymoreNames** [comment]
updated hiveos to nvidia 510.xx rebooted, still mining on version 470.
ran nvidia-driver-update again it says
latest version 510
installed 470

i have 510 downloaded, do i need to install it and how?

**Comment by IcannotThinkOfAnymoreNames** [comment]
nvidia-driver-update --list
> Loading drivers list - 60
CUDA 11.2
  460   460.39  460.67  460.73.01       460.84  460.91.03
CUDA 11.3
  465   465.27  465.31
CUDA 11.4
  470   470.74  470.86  470.94  470.103.01      470.129.06
CUDA 11.5
  495   495.46
CUDA 11.6
  510   510.47.03       510.54  510.60.02       510.68.02       510.73.05
> Stable version - 510.60.02 (CUDA 11.6)
> Installed version - 470.86 (CUDA 11.4)
> Downloaded packages - 470.86  510.73.05
> Enter the version to install: 510
> Latest driver for 510 series - 510.73.05
> Installed version - 470.86 (CUDA 11.4)

> Driver package already exists
> Checking package integrity
check sums and md5 sums are ok

> Stopping services
> Unload modules failed (nvidia_modeset nvidia)


> Starting services
Starting t-rex
> Driver installation failed (1)
root@Mine03:~#

**Comment by IcannotThinkOfAnymoreNames** [comment]
41mh.... thank you @sign1818  settings for 49mh?

**Comment by sign1818** [comment]
I use; lock-cclock 0, mclock 1300 and pl 72 (win 10 settings) = 49.60

**Comment by sign1818** [comment]
You can close this issue now.

**Comment by IcannotThinkOfAnymoreNames** [comment]
Hope someday us Linux users get all those juicy Windows settings too!
