### ISSUE TITLE
T-Rex, how to mine 2 crypto 

### ISSUE THREAD

**Issue by GeketteN** [trexminer/T-Rex#135]
Hi guys do you know if it's possible to mine 2 cryptos and if yes which crypto and how to set up T-Rex on ethermine?

Thanks for your help ;)

**Comment by trexminer** [comment]
You can switch between ZIL and ETH, for example, see https://shardpool.io

example (don't forget to replace the wallet addresses with yours)
```
t-rex -a ethash -o stratum+tcp://eu1-zil.shardpool.io:3333 -u 0x1f75eccd8fbddf057495b96669ac15f8e296c2cd -p zil1yn92lnkkfsn0s2hlvfdmz6y2yhpqm98vng38s9@eu1.ethermine.org:4444 -w rig0 --extra-dag-epoch 0
```

**Comment by GeketteN** [comment]
Thank you for your answer !
So it has to be a switch right ? I can't mine both simultaneously ( For instance ETH and ETC) ?

**Comment by trexminer** [comment]
Technically you can, by running two separate instances of t-rex on the same GPU, but I very much doubt you'll see any financial benefit compared to just mining ETH.
