### ISSUE TITLE
Dual mine working only with ALPH, but not with CFX, ERGO, FIRO, RVN

### ISSUE THREAD

**Issue by megalolka** [trexminer/T-Rex#1352]
Hello!
Dual mine working only with ALPH, but not with CFX, ERGO, FIRO, RVN.
Here is the logs:

WORKING:
---------------------20220613 23:58:22 ---------------------
Mining at eth.2miners.com:2020 [141.95.35.152], diff: 8.73 G
GPU #0: ASUS RTX 3060  - 47.87 MH/s, [T:61C, P:149W, F:82%, E:321kH/W]
GPU #1: MSI RTX 3060   - 48.51 MH/s, [T:56C, P:135W, F:62%, E:362kH/W]
GPU #2: RTX 3060       - 48.26 MH/s, [T:58C, P:139W, F:70%, E:347kH/W]
GPU #3: RTX 3060       - 48.15 MH/s, [T:59C, P:143W, F:76%, E:339kH/W]
GPU #4: Zotac RTX 3060 - 47.97 MH/s, [T:55C, P:135W, F:58%, E:355kH/W]
GPU #5: RTX 3060       - 40.24 MH/s, [T:58C, P:122W, F:70%, E:333kH/W]
Hashrate: 280.99 MH/s, Shares/min: 0, Avg.P: 820W, Avg.E: 343kH/W
Uptime: 2 mins 1 sec | Algo: ethash | Driver: 512.15 | T-Rex 0.26.4

-------------------20220613 23:58:22 --------------------
Mining at de.alephium.herominers.com:1199 [88.99.164.154]
GPU #0: ASUS RTX 3060  - 526.52 MH/s, [T:61C, P:149W, F:82%, E:3.53MH/W], 2/2 R:0%
GPU #1: MSI RTX 3060   - 533.59 MH/s, [T:56C, P:135W, F:62%, E:3.98MH/W], 2/2 R:0%
GPU #2: RTX 3060       - 530.84 MH/s, [T:58C, P:139W, F:70%, E:3.82MH/W]
GPU #3: RTX 3060       - 529.61 MH/s, [T:59C, P:143W, F:76%, E:3.73MH/W], 1/1 R:0%
GPU #4: Zotac RTX 3060 - 527.65 MH/s, [T:55C, P:135W, F:58%, E:3.91MH/W], 1/1 R:0%
GPU #5: RTX 3060       - 482.91 MH/s, [T:58C, P:122W, F:70%, E:3.99MH/W]
Hashrate: 3.13 GH/s, Shares/min: 5.847 (Avg. 3.789), Avg.P: 820W, Avg.E: 3.82MH/W
Uptime: 2 mins 1 sec | Algo: blake3 | Driver: 512.15 | T-Rex 0.26.4
WD: 2 mins 2 secs, shares: 6/6

--------------------------
--------------------------

NOT WORKING:

-------------------20220614 00:06:42 -------------------
Mining at ru.ezil.me:2222 [89.208.226.146], diff: 4.29 G
GPU #0: ASUS RTX 3060  - 48.27 MH/s, [T:57C, P:115W, F: 70%, E:423kH/W], 1/1 R:0%
GPU #1: MSI RTX 3060   - 48.77 MH/s, [T:51C, P:106W, F: 46%, E:464kH/W], 3/3 R:0%
GPU #2: RTX 3060       - 48.82 MH/s, [T:53C, P:106W, F: 55%, E:461kH/W], 4/4 R:0%
GPU #3: RTX 3060       - 48.58 MH/s, [T:54C, P:110W, F: 55%, E:442kH/W], 1/1 R:0%
GPU #4: Zotac RTX 3060 - 48.38 MH/s, [T:53C, P:109W, F:100%, E:444kH/W], 2/2 R:0%
GPU #5: RTX 3060       - 41.78 MH/s, [T:54C, P: 98W, F: 52%, E:431kH/W], 3/3 R:0%
Hashrate: 284.59 MH/s, Shares/min: 6.428 (Avg. 4.828), Avg.P: 641W, Avg.E: 444kH/W
Uptime: 3 mins 3 secs | Algo: ethash | Driver: 512.15 | T-Rex 0.26.4
WD: 3 mins 4 secs, shares: 14/14
20220614 00:06:42 conn2: octopus epoch: 88, block: 46283704, diff: 999.98 M

---------------------------20220614 00:06:42 ---------------------------
Mining at ru.conflux.herominers.com:1170 [92.38.138.239], diff: 999.98 M
GPU #0: ASUS RTX 3060  - 0.00 H/s, [T:57C, P:115W, F: 70%, E:0.00H/W]
GPU #1: MSI RTX 3060   - 0.00 H/s, [T:51C, P:106W, F: 46%, E:0.00H/W]
GPU #2: RTX 3060       - 0.00 H/s, [T:53C, P:106W, F: 55%, E:0.00H/W]
GPU #3: RTX 3060       - 0.00 H/s, [T:54C, P:110W, F: 55%, E:0.00H/W]
GPU #4: Zotac RTX 3060 - 0.00 H/s, [T:53C, P:109W, F:100%, E:0.00H/W]
GPU #5: RTX 3060       - 0.00 H/s, [T:54C, P: 98W, F: 52%, E:0.00H/W]
Hashrate: 0.00 H/s, Shares/min: 0, Avg.P: 641W, Avg.E: 0.00H/W
Uptime: 3 mins 3 secs | Algo: octopus | Driver: 512.15 | T-Rex 0.26.4

***********************************

-------------------20220614 00:10:11 -------------------
Mining at ru.ezil.me:2222 [89.208.226.146], diff: 4.29 G
GPU #0: ASUS RTX 3060  - 48.31 MH/s, [T:58C, P:114W, F:70%, E:428kH/W], 4/4 R:0%
GPU #1: MSI RTX 3060   - 48.78 MH/s, [T:51C, P:106W, F:48%, E:460kH/W]
GPU #2: RTX 3060       - 48.83 MH/s, [T:54C, P:107W, F:55%, E:461kH/W], 2/2 R:0%
GPU #3: RTX 3060       - 48.59 MH/s, [T:55C, P:111W, F:58%, E:442kH/W], 2/2 R:0%
GPU #4: Zotac RTX 3060 - 48.55 MH/s, [T:53C, P:108W, F:50%, E:450kH/W], 1/1 R:0%
GPU #5: RTX 3060       - 41.80 MH/s, [T:54C, P: 98W, F:55%, E:427kH/W]
Hashrate: 284.87 MH/s, Shares/min: 3.489 (Avg. 3.051), Avg.P: 641W, Avg.E: 444kH/W
Uptime: 3 mins 1 sec | Algo: ethash | Driver: 512.15 | T-Rex 0.26.4
WD: 3 mins 3 secs, shares: 9/9

----------------------20220614 00:10:11 -----------------------
Mining at pool.woolypooly.com:3100 [5.188.168.51], diff: 8.00 G
GPU #0: ASUS RTX 3060  - 0.00 H/s, [T:58C, P:114W, F:70%, E:0.00H/W]
GPU #1: MSI RTX 3060   - 0.00 H/s, [T:51C, P:106W, F:48%, E:0.00H/W]
GPU #2: RTX 3060       - 0.00 H/s, [T:54C, P:107W, F:55%, E:0.00H/W]
GPU #3: RTX 3060       - 0.00 H/s, [T:55C, P:111W, F:58%, E:0.00H/W]
GPU #4: Zotac RTX 3060 - 0.00 H/s, [T:53C, P:108W, F:50%, E:0.00H/W]
GPU #5: RTX 3060       - 0.00 H/s, [T:54C, P: 98W, F:55%, E:0.00H/W]
Hashrate: 0.00 H/s, Shares/min: 0, Avg.P: 641W, Avg.E: 0.00H/W
Uptime: 3 mins 1 sec | Algo: autolykos2 | Driver: 512.15 | T-Rex 0.26.4

************************************************

-------------------20220614 00:13:03 -------------------
Mining at ru.ezil.me:2222 [89.208.226.147], diff: 4.29 G
GPU #0: ASUS RTX 3060  - 48.32 MH/s, [T:58C, P:113W, F:70%, E:428kH/W], 2/2 R:0%
GPU #1: MSI RTX 3060   - 48.78 MH/s, [T:52C, P:107W, F:50%, E:460kH/W]
GPU #2: RTX 3060       - 48.84 MH/s, [T:55C, P:107W, F:58%, E:456kH/W], 1/1 R:0%
GPU #3: RTX 3060       - 48.60 MH/s, [T:55C, P:111W, F:58%, E:438kH/W], 1/1 R:0%
GPU #4: Zotac RTX 3060 - 48.55 MH/s, [T:53C, P:109W, F:52%, E:450kH/W]
GPU #5: RTX 3060       - 41.80 MH/s, [T:55C, P: 98W, F:58%, E:427kH/W]
Hashrate: 284.89 MH/s, Shares/min: 3.636 (Avg. 2.637), Avg.P: 643W, Avg.E: 443kH/W
Uptime: 2 mins | Algo: ethash | Driver: 512.15 | T-Rex 0.26.4
WD: 2 mins 2 secs, shares: 4/4

---------------------20220614 00:13:03 ---------------------
Mining at firo.2miners.com:8181 [51.89.96.118], diff: 4.29 G
GPU #0: ASUS RTX 3060  - 0.00 H/s, [T:58C, P:113W, F:70%, E:0.00H/W]
GPU #1: MSI RTX 3060   - 0.00 H/s, [T:52C, P:107W, F:50%, E:0.00H/W]
GPU #2: RTX 3060       - 0.00 H/s, [T:55C, P:107W, F:58%, E:0.00H/W]
GPU #3: RTX 3060       - 0.00 H/s, [T:55C, P:111W, F:58%, E:0.00H/W]
GPU #4: Zotac RTX 3060 - 0.00 H/s, [T:53C, P:109W, F:52%, E:0.00H/W]
GPU #5: RTX 3060       - 0.00 H/s, [T:55C, P: 98W, F:58%, E:0.00H/W]
Hashrate: 0.00 H/s, Shares/min: 0, Avg.P: 643W, Avg.E: 0.00H/W
Uptime: 2 mins | Algo: firopow | Driver: 512.15 | T-Rex 0.26.4

************************************

-------------------20220614 00:16:30 -------------------
Mining at ru.ezil.me:2222 [89.208.226.147], diff: 4.29 G
GPU #0: ASUS RTX 3060  - 48.32 MH/s, [T:58C, P:113W, F:70%, E:428kH/W], 3/3 R:0%
GPU #1: MSI RTX 3060   - 48.79 MH/s, [T:52C, P:107W, F:50%, E:456kH/W], 2/2 R:0%
GPU #2: RTX 3060       - 48.85 MH/s, [T:55C, P:107W, F:58%, E:457kH/W], 2/2 R:0%
GPU #3: RTX 3060       - 48.60 MH/s, [T:55C, P:111W, F:58%, E:438kH/W], 1/1 R:0%
GPU #4: Zotac RTX 3060 - 48.55 MH/s, [T:53C, P:108W, F:52%, E:450kH/W], 1/1 R:0%
GPU #5: RTX 3060       - 41.81 MH/s, [T:55C, P: 98W, F:58%, E:427kH/W]
Hashrate: 284.92 MH/s, Shares/min: 5.185 (Avg. 3.75), Avg.P: 644W, Avg.E: 442kH/W
Uptime: 3 mins | Algo: ethash | Driver: 512.15 | T-Rex 0.26.4
WD: 3 mins 2 secs, shares: 9/9

---------------------20220614 00:16:30 ---------------------
Mining at rvn.2miners.com:6060 [141.95.34.186], diff: 4.29 G
GPU #0: ASUS RTX 3060  - 0.00 H/s, [T:58C, P:113W, F:70%, E:0.00H/W]
GPU #1: MSI RTX 3060   - 0.00 H/s, [T:52C, P:107W, F:50%, E:0.00H/W]
GPU #2: RTX 3060       - 0.00 H/s, [T:55C, P:107W, F:58%, E:0.00H/W]
GPU #3: RTX 3060       - 0.00 H/s, [T:55C, P:111W, F:58%, E:0.00H/W]
GPU #4: Zotac RTX 3060 - 0.00 H/s, [T:53C, P:108W, F:52%, E:0.00H/W]
GPU #5: RTX 3060       - 0.00 H/s, [T:55C, P: 98W, F:58%, E:0.00H/W]
Hashrate: 0.00 H/s, Shares/min: 0, Avg.P: 644W, Avg.E: 0.00H/W
Uptime: 3 mins | Algo: kawpow | Driver: 512.15 | T-Rex 0.26.4

**Comment by mikaljan** [comment]
same here, anyone got a solution?

**Comment by trexminer** [comment]
Dual modes with ERGO, CFX, FIRO, and RVN were designed for LHR cards. With 100% unlocker LHR cards are essentially non-LHR so those modes no longer apply, and don't make much sense either, to be honest.
T-Rex 0.25.15 or older will however give you what you want.
