### ISSUE TITLE
Incrase memory overclock limit (RTX A2000 Shunt modded OC)

### ISSUE THREAD

**Issue by GhostShot3** [trexminer/T-Rex#1365]
T-Rex miner is limited --mclock to -1000 and +3000, i need more than +3000 because i want to overclock RTX A2000 (Shunt modded) like this [video](https://www.youtube.com/watch?v=v7rc-gW1rSc&t=542s) (8500 Mhz on memory) is it possible? (I use W10)

**Comment by grenelt** [comment]
Afaik this is not a T-Rex limit but a Nvidia limit.

**Comment by xPatrikTwitch** [comment]
> T-Rex miner is limited --mclcok to -1000 and +3000, i need more than +3000, is possible? (I use W10)

 I just have to  ask... What card do you have that will allow +3000 or higher on memory?!

**Comment by GhostShot3** [comment]
RTX A2000 shunt moded, i need 5840 Mhz in like this [video](https://www.youtube.com/watch?v=CkxC96Qxv_8&t=632s)
