### ISSUE TITLE
3060ti LHR low target hash rate in linux

### ISSUE THREAD

**Issue by SamuelGReeder** [trexminer/T-Rex#1368]
I have run this card on windows and I was seeing around 60mh but switching to linux  (unraid, nvidia driver 510.73.05) its targeting 36mh and staying there. I have tried setting a custom LHR # but the results are even worse (18mh at 98 and doesnt lock up)

is my driver a bad version or something?

**Comment by judders** [comment]
have you set your overclocks in NVIDIA X Server settings under Powermizer?

**Comment by SamuelGReeder** [comment]
> have you set your overclocks in NVIDIA X Server settings under Powermizer?

No, I actually have no idea how to do that and I cant seem to find any good info on it

**Comment by judders** [comment]
Oh, I see your running Unraid. I think that is a headless OS with just a web interface to configure Unraid.. You will need a GUI to configure the overclocks. Try linuxmint or Ubuntu desktop? Or even more complicated run one of them in a virtual machine on unraid and pass though your GPU from the host.
You wont need to set any LHR as that's been bypassed. But in linux you will need to run t-rex in sudo to bypass the LHR lock, "sudo ./t-rex -a ......."
