### ISSUE TITLE
Was Banned from discord for reporting spam

### ISSUE THREAD

**Issue by Hotrod369** [trexminer/T-Rex#1390]
I was just banned from the t-rex discord immediately after reporting a spam message from a user that I only shared one server with. Here is the message that they sent me.

!-✯𝕲𝖍𝖔𝖘𝖙ᴶᴰ💀✯-! — Today at 4:14 PM
$1800 into $90K in the last 30 days.. If you really want to make huge profits on trading then, highly recommend everyone to follow them  Join this winning chat: https://discord.gg/xxxxxxxxx

My discord username is Allan_QuartermainSr#8386 I do not know any other way of getting in touch with the operators of the discord and hope that someone can check my post and see I was not spamming but rather reporting spam and unban me, please.

**Comment by trexminer** [comment]
Ban revoked. I'm sorry for the inconvenience, was done by mistake.

**Comment by Hotrod369** [comment]
Thank you very much.
