### ISSUE TITLE
cuda exception: CUDA_ERROR_OUT_OF_MEMORY on GTX 1050Ti 4095MB and kawpow

### ISSUE THREAD

**Issue by byte4geek** [trexminer/T-Rex#1397]
Hi all,

i have a issue with start t-rex, i'm using t-rex and previously it worked fine, but today it not starting anymore.

i have the error "cuda exception: CUDA_ERROR_OUT_OF_MEMORY GTX 1050Ti 4095MB"

i already tried to increase the virtual memory at 12GB and set to clean it at avery reboot.

Nvidia drivers was updated.

![2022-08-31_144333](https://user-images.githubusercontent.com/8666913/187681824-6afc2f8a-7d1c-4ff5-9e4f-68e77ea52e28.png)

Someone can help me?

**Comment by Bedasek** [comment]
Dude, literally 15 seconds of googling...
https://www.nicehash.com/blog/post/psa-4gb-cards-will-soon-stop-working-on-ravencoin-kawpow
