### ISSUE TITLE
i have multi gpu , but i dont want use all?

### ISSUE THREAD

**Issue by queinnec35** [trexminer/T-Rex#141]
hello, i have one gamer pc, and he have many gpu, i want play with 1 (rtx 3070) and farm eth with the other ( 2 3060ti)
i have one the t rex gpu 0,1,2, what command i need to add in the bat file for use for exemple, the 1 and 2 , not the 0 ?
i have read that on another software , but not for this t-rex.
thx you

**Comment by trexminer** [comment]
Use `-d 1,2`

**Comment by queinnec35** [comment]
> Use `-d 1,2`

thx my friend that work :)
