### ISSUE TITLE
T-Rex 0.26.6 Zilliqa mining bug

### ISSUE THREAD

**Issue by VictorWei01** [trexminer/T-Rex#1419]
t-rex.exe -a etchash --coin etс -o stratum+ssl://hk.ezil.me:24443 -u ETC wallet address.ZIL wallet address -w WORKER

display
ERROR: Can't start T-Rex, pool for Zilliqa mining wasn't set

**Comment by trexminer** [comment]
See ETC+ZIL-ezil bat file in the miner archive for the correct ETC+ZIL template

**Comment by VictorWei01** [comment]
But T-Rex 0.26.5 also supports settings in Ezil.
