### ISSUE TITLE
SHA256 mismatch for 0.26.6 and 0.26.8 on https://trexminer.info/

### ISSUE THREAD

**Issue by Leza89** [trexminer/T-Rex#1431]
Both SHA256 hashes on https://trexm      iner.info/ for the t-rex.exe file in the archives

-  t-rex-0.26.6-win.zip https://trexm      iner.info/download/0.26.6/ and
-  t-rex-0.26.8-win.zip https://trexm      iner.info/download/0.26.8/

have the SHA256 hashes values listed as the same as the t-rex.exe 0.26.5 from

- t-rex-0.26.5-win.zip https://trexm      iner.info/download/0.26.5/ :

b1f60d13e8981f55848da217cd11bdcb887a20e59370b1513707e235081f93be

### Edit: made the links unusable since they might potentially be malicious.

**Comment by rigelminer** [comment]
Please be careful downloading binaries from random websites. Our official website is https://trex-miner.com.

**Comment by trexminer** [comment]
Please be careful downloading binaries from random websites. Our official website is https://trex-miner.com.

**Comment by Leza89** [comment]
> Please be careful downloading binaries from random websites. Our official website is https://trex-miner.com.

Thank you for the warning. So you're not offering SHA256 checksums and/or PGP signed binaries/checksum lists?
I assumed the other site was official since they're stating hashes and yours doesn't. (Or I'm just too blind to see them ;) )
