### ISSUE TITLE
T-rex miner crashes after generating DAG

### ISSUE THREAD

**Issue by Asus3070** [trexminer/T-Rex#147]
After generating the DAG file, the computer immediately starts to restart. This happens if 7 cards are installed in my system.
Here is a screen after which there is a reboot immediately - https://prnt.sc/xe3kph
If I use 6 cards, mining goes well.
This error is not observed. 
My system: Windows 10, 8GB RAM, 120GB SSD.

**Comment by trexminer** [comment]
What version of t-rex are you using?
Try running the miner with `--gpu-init-mode 4` parameter and let me know if that fixes the issue.

**Comment by Asus3070** [comment]
Version is 0.19.9
Everything works fine with this parameter now.
Thanks

**Comment by Asus3070** [comment]
After I added 1 more video card, the problem returned again and again everything is the same.
Here is a screen after which there is a reboot immediately https://prnt.sc/xe3kph
