### ISSUE TITLE
Wrong version listed in debug output

### ISSUE THREAD

**Issue by feelie75** [trexminer/T-Rex#148]
startup output:

version: 0.19.9
download: https://github.com/trexminer/T-Rex/releases/download/0.19.9/t-rex-0.19.9-win-cuda11.1.zip
notes:
Stability improvements and bug fixes

....
20210121 21:29:34 Uptime: 1 min | Algo: ethash | T-Rex v0.19.7

The output shows 0.19.7 in that last line, even though the start up says 0.19.9. Minor cosmetic issue but it confused me when I was looking at the output and I thought I'd started an old version by mistake. :) Thanks!

**Comment by trexminer** [comment]
I think the first lines you copied are the update notification message. If you scroll to the very top of the log, you'll see you're actually running 0.19.7

**Comment by feelie75** [comment]
My apologies. I copied a .BAT file from my 19.7 directory into my 19.9 directory and didn't update the .BAT file. d'oh! Fixed. thanks!
