### ISSUE TITLE
t-rex-0.19.9-win-cuda10.0 with Trojan.Win64.Miner.alve

### ISSUE THREAD

**Issue by charter-x** [trexminer/T-Rex#149]
Hello,

Many thanks for updating the version! it's working good with GTX 1080 :)

Now, the issue is that this version seems to come with a trojan, and that did not happened in previous version!

hmmm not looking good... i already add exclussion and all but it keeps coming again every 5 mins.. so not sure about this version...

Any comments about this? 
![T-Rex_trojan_alarm_001](https://user-images.githubusercontent.com/77836118/105484090-1962cb00-5cab-11eb-97df-7ba9cc1a2298.jpg)
![T-Rex_trojan_alarm_002](https://user-images.githubusercontent.com/77836118/105484093-19fb6180-5cab-11eb-922d-30c1ab45f223.jpg)

Thanks in advanced!

CharterX

**Comment by trexminer** [comment]
Your antivirus tells you that T-Rex is a miner, which is no surprise because it is one! See more info here https://github.com/trexminer/T-Rex#antivirus-alerts

**Comment by charter-x** [comment]
Hello, Thanks for replying fast!

So,i know what its telling me... what does surprise me is that with the last two versions you compiled, it  did not appear as a trojan... and after adding exclusions and trusted apps in antivirus, the messages stopped appearing.. 

But with this version even when i add exclusion etc, (i even changed the object name from Trojan to Miner maybe trying to cheat the system lol jejeje) the messages appears some times... as it does not recognize the exclusions ...

Thanks for the link.. and yes thats normal procedure, not having sensitive information where you are mining... 

For the rest, it is working like a charm... Only what i mention before... im still trying to figure out how to set it up working with that comming up every x period of time, without compromising the computer as well... 

Thanks in advance for your time and help! And keep the good work your doing :)

Best Regards,

CharterX
