### ISSUE TITLE
.bat opens 2 cmd windows

### ISSUE THREAD

**Issue by jhorath** [trexminer/T-Rex#155]
Added run as admin option as received warning .. open as admin.... Now when I execute the .bat two cmd windows open up. How can I fix this?

**Comment by jhorath** [comment]
I would like to say that I only just discovered the --mt 0-6 settings while trying to read up to see if I could fix my own issue. I have been able to completely eliminate using the ETHlargement Pill with level 3-6 on every 1080 Ti. Good fucking job!!!

**Comment by trexminer** [comment]
Run the bat file as admin rather than the executable itself

**Comment by jhorath** [comment]
> Run the bat file as admin rather than the executable itself

I guess I was unclear. I am running the .bat. NOT the exe. I am running .bat as admin. Problem is it runs two cmd windows. 
This is happening for more than just me. It was fixed by a user in discord. 

Fix below:

:: Get ADMIN Privs
:-------------------------------------
mkdir "%windir%\BatchGotAdmin"
if '%errorlevel%' == '0' (
  rmdir "%windir%\BatchGotAdmin" & goto gotAdmin 
) else ( goto UACPrompt )

:UACPrompt
    echo Set UAC = CreateObject^("Shell.Application"^) > "%temp%\getadmin.vbs"
    echo UAC.ShellExecute %0, "", "", "runas", 1 >> "%temp%\getadmin.vbs"

    "%temp%\getadmin.vbs"
    exit /B

:gotAdmin
    if exist "%temp%\getadmin.vbs" ( del "%temp%\getadmin.vbs" )
    pushd "%CD%"      
    CD /D "%~dp0"
:-------------------------------------
:: End Get ADMIN Privs

**Comment by trexminer** [comment]
Great. Thanks for letting me know.
