### ISSUE TITLE
Ethash::bechmark_kernel, 58 error on gtx1080 help!!!

### ISSUE THREAD

**Issue by Wastar69** [trexminer/T-Rex#159]
![IMG_20210126_185650](https://user-images.githubusercontent.com/78043701/105888642-e6576900-6015-11eb-9c23-43fd159696d8.jpg)

**Comment by trexminer** [comment]
Like the error message says, try reducing the overclock :)

**Comment by Wastar69** [comment]
no overclock card have default setings

**Comment by trexminer** [comment]
I see. Try running with `--kernel 4` parameter then, and let me know if it helps.

**Comment by Wastar69** [comment]
![IMG_20210127_180828](https://user-images.githubusercontent.com/78043701/106019554-72779800-60cb-11eb-867b-1193213a3d69.jpg)

**Comment by Wastar69** [comment]
this with parameter  --kernel 4

**Comment by Wastar69** [comment]
i stop msi afterburner and start  one more time  with --kernel 4,4,4,4,4  and -i 21  start working but with slow hash rate 1,5MH/s for each card gtx1080 
how to increase speed to normal ???
