### ISSUE TITLE
Can't start miner, CUDA initialize error on VM

### ISSUE THREAD

**Issue by bjcsoln** [trexminer/T-Rex#160]
Hi, newbie T-rex miner here. Was fiddling around and set up a VM running Windows 10 to see if I could run Trex (this also didn't work with Lolminer). Running the script (that works on my local machine) I get the following error:

C:\Miner\t-rex-0.19.9-win-cuda11.1>t-rex.exe -a ethash -o stratum+tcp://us2.ethermine.org:4444 -u (mywallet) -p x -w rig0
20210126 18:39:21 ERROR: Can't start miner, CUDA initialize error, memory dump: eyJhIjoiU1RaSGtTb3NpeDNwU2JKS1pqOGRvN1AwS1VmQytJNmM5NEhpMzk3RVRHVSs3cHpwMlFrQWgyY2tHTGZJVmFvTlVjVUJUbEdkL3NRbWhOcjdZZGIvTVJtRFBsMUJQRkYzVWdyZll3Q0I0UHc9IiwiYiI6ImkyaXVZM1d6UEFybjMvU0JTaTdWbVE9PSJ9Cg==
20210126 18:39:22 T-Rex finished.

I am wondering if this has something to do with how the GPUs are set up on the VM (actually I have no idea) but under the display adapters, two are listed:
- Microsoft Basic Display Adapter (the icon for this one has a yellow triangle error that I cant sort out)
- Microsoft Hyper-V Video

I imagine I want the miner to point to the second virtual display adapter but really am not sure. 

Any help is appreciated!

**Comment by trexminer** [comment]
Hi. Looks like there is no nvcuda.dll in your system. Try to reinstall Nvidia Driver.

**Comment by bjcsoln** [comment]
Yea you are correct. I realized (as I am learning this) that the VM doesn't actually have a recognized "GPU". Something more for me try and sort out.

**Comment by taraschuiko** [comment]
Having the same issue. Installing CUDA didn't help.

**Comment by Dcrain5454** [comment]
Did you ever resolve this issue? I am having the same problem

**Comment by GraverErmitage** [comment]
+1 me too. I am using (try to use) WSL (Windows Subsystem for Linux).

**Comment by TronTian** [comment]
I am using Virtualbox ubuntu with encountering same issue
