### ISSUE TITLE
does not reach the hashrate RTX 3090

### ISSUE THREAD

**Issue by plx2000** [trexminer/T-Rex#164]
Hello, 
I have an RTX 3090. The graphics card reaches 85 to a maximum of 90 hashes at a maximum of 250 watts. I already have the high performance mode in Windows and in Nvidia Control Panel. The card achieved its 350 watts and comparable values in benchmarks. I haven't found any setting options in the bios. However, I don't know how to activate the expert mode in the BIOS. Bios version: AMI F.14, December 8th, 2020

Afterburner and OC do not increase the hashes either.

PC: OMEN 30L Desktop GT13-0022ng

Do you have any tips for me to get 110 to 120 hashes?

**Comment by trexminer** [comment]
You may want to ask mining community for advice, for example in our Discord server https://discord.gg/gj7jcYf
Closing this issue now as we can't fix it in the miner.
