### ISSUE TITLE
Intensity?

### ISSUE THREAD

**Issue by Jonathan4275** [trexminer/T-Rex#165]
How do I change the intensity of of GPU when it pops up that it was auto set to a number?

**Comment by trexminer** [comment]
Use `-i` parameter

**Comment by Jonathan4275** [comment]
im sorry im new where do you do that at?

**Comment by trexminer** [comment]
In your bat file (assuming you're running Windows):
`t-rex.exe -a ethash <...blah-blah-blah...> -i 21`

**Comment by rtm125** [comment]
Hey trex. Would I benefit running max intensity vs letting it auto set? I believe my 80 is running at 20 automatically.

**Comment by ZenFree01** [comment]
I was curious about the intensity setting as well as I up'ed mine from 20 to 25 to see if it would improve the hashrate.  The hashrate remained pretty constant at between 33MH/s and 39MH/s.   My GPU is only sitting at 17% to 40% through so I feel it is slacking off and could be working harder.  Temp is also only between 50 and 60 degrees.  I have a 3080 as well.  

My cmd string is t-rex.exe -a kawpow --coin rvn -o stratum+tcp://stratum.ravenminer.com:3838 -u abc1234 --extra-dag-epoch 0 -i 25

I tried running it with 2 works (.worker1 and .worker2) but it looked like the combined hashrate was less then half the single miner.   

Are there any other settings I can change or things I can do to get more out of my GPU?

**Comment by trexminer** [comment]
You may benefit from higher intensity on some algorithms but not on `ethash`, `kawpow` or `octopus`. I recommend using default values.

@ZenFree01 No need to specify `--extra-dag-epoch 0` when mining `kawpow`, it's only useful for ETH+ZIL. Also ignore GPU load numbers Task Manager reports :)

**Comment by ZenFree01** [comment]
Thanks for the response.  Task managers not the best for sure.  I did just play minecraft and then CyberPunk without much impact though so plenty of grunt left in the GPU.  Hashrate didn't change much and temp is still a cool 56 degrees (not that I want it to be 98 degrees like my old 1080 ran).

I guess my question is, is 39MH/s what I should expect mining Raven on a 3080?

**Comment by rtm125** [comment]
Hey Zen. I can tell you with stock settings my 3080 ran ~80/mhs with +1100 on the memory I'm running ~95/mhs on eth. If you want to fire up eth to compare those are a good bench mark range to gauge from. 

Also go into Nvidia control panel, changing the power mode from adaptive to maximum performance mode will iron out allot of lower peaks while mining.

**Comment by pattrann** [comment]
hi, my miner is taking almost an hour to connect to the pool. Any idea on how i can speed up the connection?

**Comment by Lumatozer** [comment]
> hi, my miner is taking almost an hour to connect to the pool. Any idea on how i can speed up the connection?

Yeah it happens sometime,
If u use 2miner to mine raven or eth it takes a lot of time for it to start sending you shares.
I guess its a loyalty thingy.

**Comment by Lumatozer** [comment]
But using minerpool.org my connection time is now barely 10-15 seconds after the DAG is generated.
