### ISSUE TITLE
T-rex miner crashes after generating DAG file

### ISSUE THREAD

**Issue by Asus3070** [trexminer/T-Rex#166]
After I added 1 more video card, the problem returned again and again everything is the same.
Here is a screen after which there is a reboot immediately https://prnt.sc/xe3kph

_Originally posted by @Asus3070 in https://github.com/trexminer/T-Rex/issues/147#issuecomment-769941193_

**Comment by Frontgecko** [comment]
I have a similar issue, I recently fixed it by updating the BIOS and motherboard.  It was working with 6 cards for a week, but again today I encountered the error when generating the DAG.

It's similar to what this poster is reporting with his RTX 3070s: https://github.com/trexminer/T-Rex/issues/150

My virtual memory size is set to 48 GB so I don't think that's the problem.  Not sure why it works only with 5 cards but not with the 6th one.  
![error](https://user-images.githubusercontent.com/36797168/106394114-ea460b00-63c8-11eb-9772-810d5e62a8fd.PNG)

**Comment by Asus3070** [comment]
I tried to do this 
--gpu-init-mode 1
And it worked fine

**Comment by Frontgecko** [comment]
thank you for replying, but I already have the gpu-init command in my code
it could be a power supply issue, going to ensure that there's no hardware
problems and will update the thread

**Comment by Frontgecko** [comment]
turned out to be a power and hardware issue, and not an issue with the software, thanks again.
