### ISSUE TITLE
Missing the share difficulty info

### ISSUE THREAD

**Issue by McCalm** [trexminer/T-Rex#169]
Which parameters can be used to display the share difficulty in the overview for the shares found? I miss this important information in the overview. For example: "[OK] 3/3 **[Diff. 223.1 G]** - x MH / s, 12ms ...". It would be really very helpful and would avoid cumbersome searching in the pool. Thanks and Greetings...

**Comment by infidus46** [comment]
@trexminer , hello, when will you add the ability to see the difficulty of the shares ?

**Comment by trexminer** [comment]
Fixed via `--validate-shares` option
