### ISSUE TITLE
Etchash error 840m

### ISSUE THREAD

**Issue by narkolepsizm** [trexminer/T-Rex#170]
i get this error on t-rex
20210130 22:19:47 T-Rex NVIDIA GPU miner v0.19.9  -  [CUDA v11.10 | Windows]
20210130 22:19:47 r.4fb1aa6877f6
20210130 22:19:47
20210130 22:19:47 NVIDIA Driver v461.40
20210130 22:19:47 CUDA devices available: 1
20210130 22:19:47
20210130 22:19:47 WARN: DevFee 1% (etchash)
20210130 22:19:47
20210130 22:19:47 URL : etchash.unmineable.com:3333
20210130 22:19:47 USER: DOGE:D9mpLyMCzUGay4s5s38wAUN3K7Dbun4527.DENEME#nvsq-6o2e
20210130 22:19:47 PASS: x
20210130 22:19:47
20210130 22:19:47 Starting on: etchash.unmineable.com:3333
20210130 22:19:47 WARN: unknown vendor id 0x103c of GPU nvml_id=#0
20210130 22:19:47 ApiServer: HTTP server started on 0.0.0.0:4067
20210130 22:19:47 -------------------------------------------------------
20210130 22:19:47 For control navigate to: http://192.168.1.105:4067/trex
20210130 22:19:47 -------------------------------------------------------
20210130 22:19:47 ApiServer: Telnet server started on 0.0.0.0:4068
20210130 22:19:47 WARN: GPU #0(000a00): GeForce 840M, intensity set to 22
20210130 22:19:47 Using protocol: stratum1.
20210130 22:19:47 Authorizing...
20210130 22:19:47 Authorized successfully.
20210130 22:19:47 etchash epoch: 201, block: 12089139, diff: 8.73 G
20210130 22:19:47 etchash epoch: 201, block: 12089139, diff: 8.73 G
20210130 22:19:48 WARN: NVML: can't get fan speed for GPU #0, not supported
20210130 22:19:48 WARN: NVML: can't get power for GPU #0, not supported
20210130 22:19:49 GPU #0: generating DAG 2.57 GB for epoch 201(402) ...
20210130 22:20:30 etchash epoch: 201, block: 12089140, diff: 8.73 G
20210130 22:20:33 etchash epoch: 201, block: 12089141, diff: 8.73 G
20210130 22:20:42 etchash epoch: 201, block: 12089142, diff: 8.73 G
20210130 22:20:48
20210130 22:20:48 Mining at etchash.unmineable.com:3333, diff: 8.73 G
20210130 22:20:48 GPU #0: 840M - 0.00 H/s, [T:90C]
20210130 22:20:48 Shares/min: 0
20210130 22:20:48 Uptime: 1 min 1 sec | Algo: etchash | T-Rex v0.19.9
20210130 22:20:48
20210130 22:20:52 GPU #0: DAG generated [crc: a97eeae8, time: 62954 ms], memory left: 795.70 MB
20210130 22:20:56 TREX: Can't find nonce with device [ID=0, GPU #0], cuda exception in [Ethash::benchmark_kernel, 58], the launch timed out and was terminated, try to reduce OC to stabilize GPU state
20210130 22:20:56 WARN: Miner is going to shutdown...
20210130 22:20:56 Main loop finished. Cleaning up resources...
20210130 22:20:56 ApiServer: stopped listening on 0.0.0.0:4067
20210130 22:20:56 ApiServer: stopped listening on 0.0.0.0:4068
20210130 22:20:57 T-Rex finished.
20210130 22:20:57 WARN: WATCHDOG: T-Rex does not exist anymore, restarting...

**Comment by trexminer** [comment]
Hi. Your GPU is apparently quite slow. Try launching the miner with `-i 16 --kernel 4` extra parameters.

**Comment by narkolepsizm** [comment]
It works. Thanks
