### ISSUE TITLE
T-Rex will not stay running and watchdog kicks in

### ISSUE THREAD

**Issue by maverickbna** [trexminer/T-Rex#171]
I am running miner 0.19.9, on NVIDIA driver 461.40 running on Windows 10 with a GTX 1080 Ti. T-Rex detects the card but does not engage it. Windows Defender catches the executable as potential malware, but I made an exception for it. It always seems to time out the watchdog timer, and never engages the GPU to run any mining software. I'm really perplexed, because my boss gave me the code from his machine, and his worked perfectly, while mine got stopped from running.

Here is the content of my batch file to call T-Rex:

```
t-rex.exe -a ethash -o stratum+ssl://us2.ethermine.org:5555 -u 0xTHISISNOTAREALKEY -p x -w rig0 -d 0
pause
```

And here is the output:

```
20210131 05:54:31 T-Rex NVIDIA GPU miner v0.19.9  -  [CUDA v10.0 | Windows]
20210131 05:54:31 r.4fb1aa6877f6
20210131 05:54:31
20210131 05:54:31 NVIDIA Driver v461.40
20210131 05:54:31 CUDA devices available: 1
20210131 05:54:31
20210131 05:54:31 WARN: DevFee 1% (ethash)
20210131 05:54:31

20210131 05:54:31
20210131 05:54:31 Starting on: us2.ethermine.org:5555
20210131 05:54:31 Using protocol: stratum1.
20210131 05:54:31 Authorizing...
20210131 05:54:31 Authorized successfully.
20210131 05:54:31 ApiServer: HTTP server started on 0.0.0.0:4067
20210131 05:54:31 ethash epoch: 392, block: 11764178, diff: 4.00 G
20210131 05:54:31 ethash epoch: 392, block: 11764178, diff: 4.00 G
20210131 05:54:32 WARN: WATCHDOG: T-Rex does not exist anymore, restarting...
20210131 05:54:35 T-Rex NVIDIA GPU miner v0.19.9  -  [CUDA v10.0 | Windows]
20210131 05:54:35 r.4fb1aa6877f6
20210131 05:54:35
20210131 05:54:35 NVIDIA Driver v461.40
20210131 05:54:35 CUDA devices available: 1
20210131 05:54:35
20210131 05:54:35 WARN: DevFee 1% (ethash)
20210131 05:54:35
20210131 05:54:35 URL : stratum+ssl://us2.ethermine.org:5555
20210131 05:54:35 USER: 0x
20210131 05:54:35 PASS: x
20210131 05:54:35 WRK : rig0
20210131 05:54:35
20210131 05:54:35 Starting on: us2.ethermine.org:5555
20210131 05:54:36 Using protocol: stratum1.
20210131 05:54:36 Authorizing...
20210131 05:54:36 ApiServer: HTTP server started on 0.0.0.0:4067
20210131 05:54:36 WARN: WATCHDOG: T-Rex does not exist anymore, restarting...
```

Any help would be much appreciated. I'm new to mining Ethereum, and would like to get started as soon as possible.

Thanks in advance!

**Comment by trexminer** [comment]
Please check Event Viewer and see if there are any relevant error messages recorded at the time of miner restart.

**Comment by maverickbna** [comment]
Please disregard. I reinstalled Windows and it worked.

" 'With the first link, the chain is forged. The first speech censured, the
first thought forbidden, the first freedom denied, chains us all
irrevocably.' Those words were uttered by Judge Aaron Satie as wisdom and
warning... The first time any man's freedom is trodden on, we’re all
damaged." - Jean-Luc Picard, quoting Judge Aaron Satie, Star Trek: TNG
episode "The Drumhead"
- Alex Smith
- Lacey, Washington (Olympia, WA metropolitan area)
