### ISSUE TITLE
Trex Can't find nonce with device, maximum number of memory allocation attempts exceeded

### ISSUE THREAD

**Issue by grollcha000** [trexminer/T-Rex#174]
Getting this error when I connect a 3070 with 2 3060s, but no errors when I run it with just one 3060.
<img width="1440" alt="Screen_Shot_2021-01-29_at_7 27 24_PM" src="https://user-images.githubusercontent.com/42676514/106396411-be7d5200-63d5-11eb-9cad-39811873d6a0.png">

**Comment by trexminer** [comment]
Try increasing virtual memory size like the error message says

**Comment by mlawson456** [comment]
I have the same issue, 20GB virtual memory size (should be plenty??).  Any solutions?

**Comment by trexminer** [comment]
@mlawson456 The virtual memory size should be >= a sum of VRAM sizes of all GPUs you have in the system

**Comment by mlawson456** [comment]
Thanks, I have resolved the issue.  The max size of the virtual memory was correct, but it seems Windows was not taking what it needed by default.  I forced it in system settings and it is now working splendidly.
