### ISSUE TITLE
Memory leak 5 day uptime

### ISSUE THREAD

**Issue by Starec666** [trexminer/T-Rex#180]
При непрерывной работе trex 0.19.9 свыше 5 дней ( конкретно на 7-8 дне) заметил что всю оперативку занял процесс майнера. Может либ такое быть связано с активным ключем для лог файла? После перезапуска майнера память освбодилась до нормальных значений.

**Comment by trexminer** [comment]
На системах HiveOS логи включены постоянно. Репортов об утечках памяти не было.
Какие настройки вы передаёте майнеру?

**Comment by Starec666** [comment]
Забыл сказать, у меня все это на вин10

t-rex.exe -a ethash -o stratum+tcp://eth-eu.sparkpool.com:3333 -u XXX-p x -w 1 -d 2,3,5 --kernel 5,5,4 -i 21 -l 0.txt --gpu-init-mode 1 --exit-on-cuda-error --exit-on-connection-lost --reconnect-on-fail-shares 5

Сейчас аптайм 30 часов, и в памяти 1 гиг занимает процесс.

**Comment by trexminer** [comment]
Тогда, если не затруднит, попробуйте отключить логирование, посмотрим, исчезнет ли утечка.

**Comment by Starec666** [comment]
Запустил тест, у меня на одной ферме запущено 2 майнера трекс, половина карт на одном, половина на другом. И у одного убрал логирование. Завтра отпишусь.

**Comment by Starec666** [comment]
8 часов аптайм, процессы "пухнут" одинаково с логером и без.
У меня 3 рига под вин10, и на всех трех при майнинге эфира такой процесс распухания. 
P.S. если что для меня это не проблема раз в пару дней ребутнуть майнер.
![2021-02-05_225018](https://user-images.githubusercontent.com/36118638/107082021-a0b05280-6804-11eb-8875-6f12fc554dd3.gif)

**Comment by Starec666** [comment]
Вот прошло еще 17-18 часов. Общий аптайм 26 часов
![2021-02-06_155811](https://user-images.githubusercontent.com/36118638/107118800-229b8c80-6894-11eb-9408-e6dd04dc92d9.gif)

**Comment by trexminer** [comment]
Есть ли у вас возможность попробовать погонять ещё 2 версии майнера. 0.19.5 и 0.19.7? Если да, попробуйте пожалуйста. Мы в поисках проблемы.

**Comment by Starec666** [comment]
запусти 19.5 и 19.7 в параллель, отпишусь.

**Comment by Starec666** [comment]
К сожалению ниодна из версий утечку не решила :( 5 7 и 10 перепробовал.

**Comment by trexminer** [comment]
Уточните пожалуйста, какой драйвер установлен.
У нас есть ещё один репорт с утечкой памяти. Всего 2 (включая ваш). Хотим понять, что общего у вас.

Можете ли вы попробовать погонять один риг на другом алгоритме в течении нужного времени, чтобы понять есть ли утечка? Мы можем материально компенсировать потери за время теста. Если готовы помочь, то напишите мне в telegram (@ikseg)

**Comment by trexminer** [comment]
Memory leak is caused by a bug in NVML in the recent NVIDIA drivers. Disabling NVML fixes it.

**Comment by HappyRogue658** [comment]
Does the hotfix driver (version 461.81) fix this? I'm also having memory leak and I've disabled NVML for now.

**Comment by trexminer** [comment]
As far as I'm aware the memory leak has been patched in NVIDIA drivers 470+, so going to close this issue.
