### ISSUE TITLE
Separate bad shares counters: incorrect and stale

### ISSUE THREAD

**Issue by megalolka** [trexminer/T-Rex#184]
Hello!
Is it possible to make T-Rex count and show incorrect and stale shares for each GPU *separately*?
Like the PhoenixMiner does this (accepted X shares / incorrect Y shares / stales Z shares).
Because incorrect shares are mostly caused by overclocking and miners should see that the overclocking should be adjusted.
And the stale shared doesn't require to make overlocking changes.

**Comment by trexminer** [comment]
This feature can potentially affect on your effective hashrate. I think we may add it but activate only in case of user selects it  explicitly.

**Comment by megalolka** [comment]
I think, the found share first is checked on CPU and T-rex miner shows if it's OK or FAIL.
And then this found share is sent to the pool which answers that it's ACCEPTED or REJECTED (STALE).
Is this correct? 
Why then the separate counters for FAIL and STALE shares will affect the hashrate?

**Comment by trexminer** [comment]
T-rex miner shows 'OK' only in case of a pool accepted a share. We don't validate shares on CPU at the moment.
"share first is checked on CPU" -> "And then this found share is sent to the pool"
which means that you have a delay between sending to a pool and this delay can make your share a stale one.

**Comment by megalolka** [comment]
OK. 
And what do you think about this algorithm?:
Send the found share to the pool without validating on CPU.
And if the pool rejected the share - only then validate it on CPU. 
If validation is OK - then we know that there is no problem with our hardware overclocking. 
And if CPU validation is failed we should adjust the overclocking.

**Comment by AuthenticAMD** [comment]
If the pool rejected the share, then it is bad. Why would you then re-evaluate it on the CPU? That doesn't make any sense.

**Comment by megalolka** [comment]
I think that the pool can reject the share for 2 main reasons:
1. It's late share (STALE)
2. It's incorrectly computed (because of too much overclocking).
Am I correct?
If it's correct, we need to know how many shares are rejected due to overclocking and how many shares are stale.
That's why it will be VERY VERY VERY useful to check the rejected share on CPU.
If we will see 2 different counters for stale and for overclocked shares - we will know what should we fix: internet channel latency or memory overclocking.
This different counters for incorrect and stale shares is one of the main reasons why some miners use PhoenixMiner - because it shows how to improve the mining...

**Comment by AuthenticAMD** [comment]
My pool tells me whether a share is accepted, stale or invalid.

Let me be clear, I am not against an implementation where the trex validates a share before sending it to the pool. But as @trexminer said, it can cause more stale shares. I've used phoenix miner, and while it worked well for me, it also had a higher number of stale shares (0.5% vs 0.2%), likely due to validation before sending to pool.

I am against an implementation that caches a share while it waits for the pool to accept or reject the share only to validate it at that time it is already rejected.

**Comment by megalolka** [comment]
"My pool tells me whether a share is accepted, stale or invalid."
But your pool can not tell which GPU is overclocked.
For example, you have some rigs with 12 GPUs with different models (3060Ti, 3080, 1080Ti) in one rig.
Your pool just tells that you need to reduce memory overclocking. But the Phoenix tells that the incorrect shares are only on 1080Ti (for example). So you need only to adjust several GPUs and the other GPUs will continue to work with maximum efficiency.

"I am against an implementation that caches a share while it waits for the pool to accept or reject the share only to validate it at that time it is already rejected."
Why? What side effects of that validation do you see?

**Comment by megalolka** [comment]
Dear @trexminer ,
What do you think about checking the rejected share after sending it to pool?

**Comment by trexminer** [comment]
Invalid shares are now detected and separated from stales for ethash, octopus and autolykos2 if `--validate-shares` parameter is set
