### ISSUE TITLE
Wrong protocol detected

### ISSUE THREAD

**Issue by Unlifate** [trexminer/T-Rex#188]
I was starting t-rex-0.19.7-win-cuda11.1, when I experienced an issue, connecting to hiveon.

I was using this url scheme: stratum+ssl://eu-eth.hiveon.net:24443
Which works, if put into launch startup arguments. But the same url doesn't work, when put into config file.
The entry looks like that:
```
  "pools": [
    {
      "user": "0xabdmywalletadress", // wallet address (change it)
      "url": "stratum+ssl://eu-eth.hiveon.net:24443", // pool url
      "worker": "worker" // worker name
    }
```

This is the output of t-rex:

```
20210206 07:55:25
20210206 07:55:25 URL : stratum+ssl://eu-eth.hiveon.net:24443
20210206 07:55:25 USER: 0xabdmywalletadress
20210206 07:55:25 PASS:
20210206 07:55:25 WRK : worker
20210206 07:55:25
20210206 07:55:25 Starting on: eu-eth.hiveon.net:24443
20210206 07:55:25 Using protocol: stratum3.
20210206 07:55:26 WARN: failed to stratum2-subscribe on eu-eth.hiveon.net:24443: can't parse json:
* Line 1, Column 1
  Syntax error: value, object or array expected.
```

As you can clearly see, it thinks it should use stratum3. And then fails to connect using stratum2? I don't know, but when starting the program, using the parameter method (=not using the config), it uses stratum1.

I guess that's a bug or I am missing something.

**Comment by trexminer** [comment]
Could you provide a bit more info on the log? Which algorithm was selected by the miner?  Startum3 is default protocol for 'kawpow' algorithm. Are you sure that your config file has no "algo" field set with "kawpow"?

**Comment by Unlifate** [comment]
That's the reason. I've had "algo": "kawpow". It should have been: "algo": "ethash".
