### ISSUE TITLE
Error at hooking API "LoadStringA"

### ISSUE THREAD

**Issue by nullptrerror** [trexminer/T-Rex#195]
Running an RTX 2080 TI with CUDA 11

t-rex.exe -a ethash -o stratum+tcp://us1.ethermine.org:4444 -u 0xf336E4ee963f1F398D4a1E51c7059bEd1bE6976f -p x -w rig0

![image](https://user-images.githubusercontent.com/59756494/107478486-88fc0580-6b47-11eb-8884-abbab9f7be3c.png)

**Comment by trexminer** [comment]
Reboot your PC, and if that doesn't help, try reinstalling Microsoft Visual C++ Redistributable for Visual Studio 2015 https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0. Make sure to select x64 version.

**Comment by nullptrerror** [comment]
I downloaded the latest release and that seems to have fixed the problem. I was unable to determine the exact cause of the error.
