### ISSUE TITLE
Energy usage units are wrong

### ISSUE THREAD

**Issue by mattkellymt** [trexminer/T-Rex#198]
In the console, energy is reported as kH/W. It's kWh. Lowercase k, uppercase W, lowercase h. There is no division, it's all multiplication. That means if you double the hours, you double the total energy. If you double the wattage, you double the energy.

**Comment by DeBelsch** [comment]
Hello, not a developer, but if I'm not mistaken, the E is not for energy, but for efficiency. So the kH/W is kiloHasch per Watt.

**Comment by mattkellymt** [comment]
Makes sense. I will close this.
