### ISSUE TITLE
HTTP-API - control?pause

### ISSUE THREAD

**Issue by Unlifate** [trexminer/T-Rex#199]
`control?pause=true` not working, nothing happens. It is only working if you specify the GPU. Would be great if we didn't need to specify the exact gpus. According to the readme, it should work without specifying the GPUs.

(used version: v0.19.10  -  [CUDA v11.10 | Windows] r.fcc3b6574e6b )

**Comment by trexminer** [comment]
It's a regression introduced in 0.19.10, will be fixed in the next version.
You can use 0.19.9 in the meantime, the pause functionality works correctly there.

**Comment by trexminer** [comment]
Should be fixed in https://github.com/trexminer/T-Rex/releases/tag/0.19.11

**Comment by trexminer** [comment]
Fixed in 0.19.11
