### ISSUE TITLE
Can you help me with a version?

### ISSUE THREAD

**Issue by lqwyz** [trexminer/T-Rex#2]
No need for telnet, web.
No calculations other than bcd are required.
No version information is required.
![image](https://user-images.githubusercontent.com/45497578/49310768-2dbb3b00-f51a-11e8-8ed3-fd4a300cd33f.png)

I hope he is an extremely streamlined version.
Thank you。

After comparison, trexminer is the best

**Comment by trexminer** [comment]
Sorry we are not going to change the binary attributes.
