### ISSUE TITLE
Using SSL reduces hashrates

### ISSUE THREAD

**Issue by dompazz** [trexminer/T-Rex#202]
I'm finding lower reported hash rates when connecting to a pool over SSL vs TCP.  

version 0.19.10 CUDA 10.0

Tested over a 2.5 hour block on both protocols

Two TCP connections with identical hash rates:
![sparkpool_hash](https://user-images.githubusercontent.com/5799952/107700597-b18a1980-6c85-11eb-8106-8f4ce386001d.png)
![flexpool_tcp_hash](https://user-images.githubusercontent.com/5799952/107700602-b51da080-6c85-11eb-8a6d-25adaed98712.png)

Connection with SSL.  Hash rate drops from 29.5 to 29.  
![flexpool_hash](https://user-images.githubusercontent.com/5799952/107700685-dbdbd700-6c85-11eb-9df4-52252a68bc62.png)

**Comment by Unlifate** [comment]
Have you tried using another pool? Might be an issue of your pool.

**Comment by dompazz** [comment]
Tried again this morning.  Issue seems to have resolved.  Might have been something with the pool.  I could make the above happen at will yesterday.

Will close and let you know if I see it again.
