### ISSUE TITLE
[Major issue] T-Rex 0.19.11 not working at all (Windows 10 / Cuda 11.10)

### ISSUE THREAD

**Issue by Unlifate** [trexminer/T-Rex#203]
I've replaced the old t-rex.exe file ( v0.19.10 - [CUDA v11.10 | Windows] r.fcc3b6574e6b )) with the new one (v0.19.11  -  [CUDA v11.10 | Windows] r.9c70a63f2290).

T-Rex is starting and the t-rex internal WATCHDOG keeps restarting T-Rex.
```
20210212 13:16:12 Starting on: eu-eth.hiveon.net:24443
20210212 13:16:12 WARN: WATCHDOG: T-Rex does not exist anymore, restarting...
```
It does not start any more! So you might actually crash even auto-updates with your new release @trexminer .

This is either a major bug or I am doing something very wrong.

I am running t-rex on windows 10. I've tried using my old config file, I've tried launching it without -c parameter and as an admin and without being admin. Nothing works anymore. t-rex is a dead dinosaur now. (lol)

**Comment by RainbowMiner** [comment]
Confirmed. Trex v0.19.11 is broken. With watchdog disabled, it starts and tries to connect to the pool - but then just stops to the command line.

**Comment by Unlifate** [comment]
If anybody is wondering where I got that version from - it was visible for a few minutes. I guess @trexminer just removed it due to this bug, to avoid auto-update crashes.

**Comment by trexminer** [comment]
Unfortunately packing software broke release binary. Release was re published. Try again please.

**Comment by RainbowMiner** [comment]
I can confirm, v0.19.11 is now fully functional.

**Comment by AChangXD** [comment]
Issue still here with the newest version v0.19.11

**Comment by Unlifate** [comment]
@AChangXD 
No this issue got fixed. Your issue is something new. And if you have any problem you should open a new ticket.

**Comment by AChangXD** [comment]
@Unlifate Gotcha, it seems like it's a problem with the new driver. The good old nvlddmkm.sys back at it again after adding a 3060

**Comment by aoinoikaz** [comment]
i have this issue at the moment using newest version of trex. says the same thing on windows with rtx3060s... basically it stopped after 21 hours, and i looked in log and the watch dog timer was different then uptime. and i found in the logs it said this: "warn watchdog t-rex does not exist anymore restarting "
