### ISSUE TITLE
Can't find nonce with device [ID=1, GPU #1], cuda exception in [generate_dag_normal, 123], unspecified launch failure

### ISSUE THREAD

**Issue by Freekers** [trexminer/T-Rex#205]
T-Rex crashes instantly if Memory tweak mode is activated with the following error: "Can't find nonce with device [ID=1, GPU #1], cuda exception in [generate_dag_normal, 123], unspecified launch failure)". I have tried different memory tweak modes (from 1 to 6).

I suspect it's BIOS related, but I do not know which setting to change. 4G Decoding is enabled, PCI-e Gen is set to '2'.

Motherboard: X11SAT-F Supermicro (1.0a 04/29/2016)
CPU: 8 × Intel(R) Xeon(R) CPU E3-1240L v5 @ 2.10GHz AES
GPU: 2x Asus GeForce GTX 1080 8119 MB - Micron GDDR5X - vBIOS 86.04.17.00.11
nVidia Driver version: 460.39
OS: hiveos-0.6-190-stable (Ubuntu 18.04)
T-Rex: 0.19.10-cuda111

**Comment by Unlifate** [comment]
Did you check permissions? At least in Windows systems you need admin permissions. Sudo/root for you then.
You should also check this issue: #78

**Comment by Freekers** [comment]
Thanks for your reply. I was able to solve the problem. It was not permissions related. Apparently I need to reboot my rig after every change in OC. Doesn't matter if I OC if the miner iis not running, after every OC change a reboot is needed, else it will error out.

**Comment by highflow85** [comment]
today i found my own solution.....i tryd sooo much and many times and find a command who works with it!
in the first command line....at last....set: -B
and now it works....hope with you too!:)
