### ISSUE TITLE
Clock screwed up!  Что это значит?

### ISSUE THREAD

**Issue by Starec666** [trexminer/T-Rex#206]
Добрый день, подскажите что значит эта ошибка "Clock screwed up! ", изза которой перезапускается майнер

При этом в логе не написано по какой видео карте проблема, хотя при переразгоне обычно писалось какая карта вылетела.

Ха, правда в логе вижу, как будто время в компьюетере обновилось, и майнеру это не понравилось?

20210212 13:17:55 Uptime: 6 hours 59 mins 37 secs | Algo: ethash | T-Rex v0.19.9
20210212 13:17:55 WD: 2 days 13 hours 10 mins 51 secs, shares 7868/7870, restarts 1
20210212 13:17:55 
20210212 13:17:55 [ OK ] 931/931 - 146.36 MH/s, 63ms ... GPU #3
20210212 **13:18:06** [ OK ] 932/932 - 146.46 MH/s, 63ms ... GPU #2
20210212 **13:16:14** Clock screwed up!
20210212 13:16:14 WARN: Miner is going to shutdown...
20210212 13:16:15 Main loop finished. Cleaning up resources...
20210212 13:16:15 ApiServer: stopped listening on 0.0.0.0:4067
20210212 13:16:15 ApiServer: stopped listening on 0.0.0.0:4068 

Странно, отключу синхронизацию времени.

**Comment by Starec666** [comment]
это началось сегодня одновременно на 2х ригах. Они стоят на улице, достаточно холодно, возможно материнка сходит с ума, и время "скачет"

**Comment by trexminer** [comment]
Это защита от перевода времени, чтобы различные счётчики внутри майнера работали кооректно, иначе возможны непредсказуемые эффекты. Если время в системе было скорректированно, то майнер перезагрузится.
