### ISSUE TITLE
Cannot Start T-Rex Miner

### ISSUE THREAD

**Issue by Strawberly** [trexminer/T-Rex#208]
Currently getting this issue every time I try to run the bat file

20210212 23:00:27 T-Rex finished.
20210212 23:00:32 ERROR: Can't start miner, CUDA initialize error, memory dump: eyJhIjoiNUtCcjYxUDVya2krbkN3aXBIQlFEOEo0MnV0cDZVNFYxeU5hWEVtelNGSnFhSTBuRG50aUp1QVVQTlhJdFM3alM5Y2NTWlNsV0c5Wm1MZWZvMTlwT2c9PSIsImIiOiIydE1mOXp2U2FvWStZSHY3VHdLMGlnPT0ifQo=

**Comment by trexminer** [comment]
Hi. What's your NVIDIA driver version?

**Comment by Strawberly** [comment]
391.35

**Comment by trexminer** [comment]
Thanks. v397.x is the oldest T-Rex supports.

**Comment by matchday-th** [comment]
i same problem  but i use rx570 8gb  how can i fix
