### ISSUE TITLE
TREX: Can't find nonce with device [ID=0, GPU #0], cuda exception in [Ethash::benchmark_kernel, 61] ....

### ISSUE THREAD

**Issue by ShowiZzQC** [trexminer/T-Rex#210]
Hi,

I wanna start mining Ethereum since I saw that was possible with gaming rig.

My GPU drivers is updated to the lastest version and I have never overclocked it.

What could possibly be the problem ?

![image](https://user-images.githubusercontent.com/79023903/107860837-c2ff2d00-6e0f-11eb-893a-f93f1479ada9.png)

**Comment by sjby365** [comment]
--kernel 4  ，试着调整kernel的值
