### ISSUE TITLE
Feature-request: A) set a max. pool difficulty on autoports + B) Parallel using a GPU on one MB

### ISSUE THREAD

**Issue by PetrStanislav** [trexminer/T-Rex#211]
It will be fine set a max difficulty on auto port...
Many pools have a autoport, where difficulty is changed overtime, but if it will be possible set a more GPUs work like one bigger (for example 4x nVidia GTX 1050ti 4GB DDR5 (7-8GBps), 5000Mhz/798cuda cores working on PCIe x16  ---> will be aprox. like one card 16GB DDR5 (7-8GBps), 5000MHz with 4x798cuda cores), the problem with capacity of memory will be downsized... isnt?

Motivation:
- set a max. diff on autoport for a stabilization a mining results in current round/epoch
- using more GPUs like one bigger by setting in parallel mode

Is it possible or is it a bad idea?

thx 
PS

**Comment by trexminer** [comment]
When you're running a multi-GPU setup on the same PC, your cards are already treated like a single "worker" with hashrate higher than that of each individual GPU. If you're looking at combining multiple computers into a single worker, then you need to use something like https://pypi.org/project/ethproxy/
