### ISSUE TITLE
How exactly do I work --nonce-start --nonce-range-size?

### ISSUE THREAD

**Issue by hivemindinc** [trexminer/T-Rex#212]
I put in 1649481687 for the start. And then I put in 3000000 for the range and nothing.

**Comment by trexminer** [comment]
Could you tell what you're trying to achieve?

**Comment by hivemindinc** [comment]
Well, I'd like to start out at a different nonce than other miners. I suspect since the calculations are so quick that most people wind up on the same nonce, and therefore those who have even slightly slower machines are just literally rehashing the same formula.

**Comment by trexminer** [comment]
I see. The truth is there's no need to worry about that, because mining pools give each miner a unique "job" to avoid the situation you're describing. So, there is no point in restricting the nonce range.
`--nonce-start` and `--nonce-range-size` parameters were added to circumvent a bug in one of the mining algorithms in the past.

**Comment by hivemindinc** [comment]
Ah, I see. What are the parameters of the two though? I'm just curious because I do web development, so my line of work is far different than yours. You have to have numbers and letters in that array, so say h2198d2n0d2 is where you start out from. How does it increment? Letter then number by letter and number? And as for the range, would the miner stay within that range? But how would you calculate that without slowing down your rig significantly? I mean to have the value of a number is one thing, it's linear, it's easy. Unless. You made the letters into integers and solved it as a block, so "a =1, b =2, 13 =M" and so when it was time for the M block to change to a N block, the integer changed to 14? I would love to hear how you programmed it.

**Comment by trexminer** [comment]
`--nonce-start` and `--nonce-range-size` take integers and then the resulting range gets divided into roughly equal chunks between the GPUs. These chunks must be big enough for the GPUs not to process them fully until the miner receives the next job from the pool. Each GPU will process its own sub-range.
Hope that helps.
