### ISSUE TITLE
Support for Tensor Cores + Options

### ISSUE THREAD

**Issue by hivemindinc** [trexminer/T-Rex#213]
Also, can we have an option that lets you go above or below the difficulty by increments of 0.1 up/down to 5?

--diff-clock
--cuda-scheduler help remove the bottlenecks in some rigs
--process-rate (how much to hash one spot / 50% 25% 90%)
--expiry
--scantime
--maxmemory (the A100s only use up about 6GB of their memory out of their HUGE 40GB limit)
--dontpause (stops the miner from taking millisecond/second breaks between functions)
--dag-cache

**Comment by trexminer** [comment]
> Do you plan on supporting the A100, V100, P100 series?

They are already supported.

> Also, can we have an option that lets you go above or below the difficulty by increments of 0.1 up/down to 5?

Not sure what you mean. Could you clarify?

> Also
...

--dag-cache is already implemented, see the readme. I don't understand the meaning of other parameters you mentioned, unfortunately.
