### ISSUE TITLE
How can i control trex another device 

### ISSUE THREAD

**Issue by alperen2311** [trexminer/T-Rex#216]
Can u guys pls help me how can i control trex from my phone?

**Comment by trexminer** [comment]
Bind the HTTP API to `0.0.0.0:4067`, and then go to `http://<your_ip>:4067/trex` in the browser

**Comment by alperen2311** [comment]
> Bind the HTTP API to `0.0.0.0:4067`, and then go to `http://<your_ip>:4067/trex` in the browser

you mean dns i don't know how to do that :(

**Comment by trexminer** [comment]
T-Rex cmd line params you're looking for are `--api-bind-http 0.0.0.0:4067 --api-read-only`

**Comment by alperen2311** [comment]
> T-Rex cmd line params you're looking for are `--api-bind-http 0.0.0.0:4067 --api-read-only`
aaand where should i looking for that

**Comment by trexminer** [comment]
https://github.com/trexminer/T-Rex#usage, and also release notes under https://github.com/trexminer/T-Rex/releases/tag/0.19.11

**Comment by alperen2311** [comment]
> https://github.com/trexminer/T-Rex#usage, and also release notes under https://github.com/trexminer/T-Rex/releases/tag/0.19.11

bro thx lot but i really don't understand would u pls tell it to me slowly and calmly what should i do i'm using ethermine should i change something here 
![Screenshot_1](https://user-images.githubusercontent.com/17513296/107916681-bb5a9800-6f77-11eb-9564-b6d6348ab915.png)

**Comment by trexminer** [comment]
Append ` --api-bind-http 0.0.0.0:4067 --api-read-only` to the first line in your bat file, that'll make T-Rex web UI accessible through a browser from another device in your local network.

**Comment by alperen2311** [comment]
> Append ` --api-bind-http 0.0.0.0:4067 --api-read-only` to the first line in your bat file, that'll make T-Rex web UI accessible through a browser from another device in your local network.

thanks so much dude sorry for my eng and sorry for being dump thx lot
