### ISSUE TITLE
Provided Pow invalid

### ISSUE THREAD

**Issue by Sam3style** [trexminer/T-Rex#217]
i'm been using 0.19.7 cuda 11.1, most stable of all. once i update 0.19.9/10/11, 1 of the GPU started to failed. Provided PoW solution is invalid. 25% - 100%.

So i have no choice and using back the 0.19.7

**Comment by trexminer** [comment]
What GPU is that?

**Comment by Sam3style** [comment]
1st rig - 3060ti & 1070 - 1070 failed
2nd rig - 3x 1070 - 1070 failed

**Comment by trexminer** [comment]
Please try running the miner with `--dag-build-mode 2` and let me know if that fixes the issue

**Comment by Sam3style** [comment]
Tested for 2 hours, so far so good. Thanks Admin for fast response!

**Comment by LukasPutala** [comment]
Hi, I have rtx 3070 and gtx 1660, and this solution not worked for me. I use t-rex ver 0.19.11-win-cuda11.1

**Comment by Flinkas** [comment]
Same issue here:

0.19.11 Cuda 10
GTX 1070ti (No problems)
GTX 1080 (Rejected shares issues) (clock +0, memory +500, pl 67%)
Latest Drivers

$running with --mt 6

**Comment by yorkjr2** [comment]
I am having the same issue.  I installed a new RTX 3070, last night, to my mining rig.  This new card is getting the same "Provided PoW solution is invalid".  I use HiveOS for my OS platform and it is paired with TRex miner.  I see that it was recommended to run 0.19.00 with --dag-build-mode 2 but I am not sure how to do this.  Can someone provide some instruction on how to implement this?  Thanks.

**Comment by hcancelik** [comment]
> I am having the same issue. I installed a new RTX 3070, last night, to my mining rig. This new card is getting the same "Provided PoW solution is invalid". I use HiveOS for my OS platform and it is paired with TRex miner. I see that it was recommended to run 0.19.00 with --dag-build-mode 2 but I am not sure how to do this. Can someone provide some instruction on how to implement this? Thanks.

In your flight sheet, click "Setup Miner Config" and add the following line under "Extra config arguments:"

```
"dag-build-mode": "2"
```

Though I'm not sure if just one "2" is enough or you would need to type as many as gpus you have. For example if you have 6 rtx 3070s then it is `"dag-build-mode": "2,2,2,2,2,2"`
