### ISSUE TITLE
GPU Intensity or Limits of GPU RAM

### ISSUE THREAD

**Issue by William8Work** [trexminer/T-Rex#221]
I have a 3070 which has 8GB vram. Is there a way to limit the GPU memory requirement per T-Rex so that I can run two of the processes, or run one with max 4096 MiB and keep the other 50% for other GPU workloads?

I tried to set the intensity but it doesn't change the memory usage on the GPU.

version 
T-Rex NVIDIA GPU miner v0.19.11 rev.9c70a63f2290

os
ubuntu 20.04

**Comment by trexminer** [comment]
Each algorithm has its own memory requirements. If you mine ETH, it needs more than 4GB at the moment, so there is no way you can squeeze two ETH miners into your 3070. Technically it is possible, but at a cost of a severe performance degradation.
On the other hand, if you mine RVN then what you've described is achievable.

**Comment by William8Work** [comment]
thanks for the response @trexminer. If mining RVN, how do I set the max memory for GPU usage? Or I just simply run two separate RVN processes with one 3070 and the two t-rex processes will share the GPU?

**Comment by trexminer** [comment]
No worries.
> Or I just simply run two separate RVN processes with one 3070 and the two t-rex processes will share the GPU?

this

**Comment by William8Work** [comment]
thanks!
