### ISSUE TITLE
Unable to connect to Api from LAN

### ISSUE THREAD

**Issue by MRishiK99** [trexminer/T-Rex#224]
I'm trying to connect to the miner api. I am actually using trex through nicehash. 
I have set the bind address as 0.0.0.0:4067 as instructed through the initial api page at 127.0.0.1:4000. Accessing from the same system works very well. 
But I am not able to access from a device on the same network, ie a phone. I tried allowing the port on windows firewall. But that too didn't work.

**Comment by trexminer** [comment]
Sorry, can't really help here. There's nothing we can do on the miner side to fix this. There must be something blocking incoming connections, or the phone is not in the same local network as your rig.

**Comment by marmeladirekka** [comment]
I have exactly same problem. Occured after the update. Nothing seems to fix it. Verified all the devices are connected to same network. Weird.

**Comment by MRishiK99** [comment]
> Sorry, can't really help here. There's nothing we can do on the miner side to fix this. There must be something blocking incoming connections, or the phone is not in the same local network as your rig.
Checked both. Ig it has to do something with nh

**Comment by marmeladirekka** [comment]
With Nicehash? I don't use it so I don't think that's the reason.. still no way to fix this :/

**Comment by trexminer** [comment]
> I have exactly same problem. Occured after the update. Nothing seems to fix it. Verified all the devices are connected to same network. Weird.

Have you specified the binding address manually though?

**Comment by marmeladirekka** [comment]
> > I have exactly same problem. Occured after the update. Nothing seems to fix it. Verified all the devices are connected to same network. Weird.
> 
> Have you specified the binding address manually though?

I think so yes? I changed it at the api from 127.0.0.1:4067 to 0.0.0.0:4067 ? Is that what you mean?

**Comment by trexminer** [comment]
Yes, `--api-bind-http 0.0.0.0:4067` makes it identical to 0.19.10 in terms of API setup

**Comment by marmeladirekka** [comment]
Weird but won't work :/

**Comment by MRishiK99** [comment]
Found the issue. Nicehash seems to interfere with the api bind. Ig nicehash allows only certain arguments to be passed. Ran trex directly connected to a pool and was able to access the api from Lan
