### ISSUE TITLE
WARN: cannot get fan speed, error 999

### ISSUE THREAD

**Issue by Aidan27** [trexminer/T-Rex#226]
WARN: cannot get fan speed, error 999 popped up. How could I fix this I've uninstalled drivers and that didn't help

**Comment by trexminer** [comment]
It's essentially the same problem as https://github.com/trexminer/T-Rex/issues/226

**Comment by Aidan27** [comment]
It worked by changing the oc settings thanks

**Comment by QuiqueVargas** [comment]
what exactly you did?

**Comment by trexminer** [comment]
Leaving a very relevant article here for future readers: https://translate.google.com/translate?hl=en&sl=auto&tl=en&u=https://cryptoprofi-info.turbopages.org/cryptoprofi.info/s/?pcgi=p%253D5519
