### ISSUE TITLE
Not connect to p2pool without extranonce

### ISSUE THREAD

**Issue by kr1z1s** [trexminer/T-Rex#23]
Hi
I p2pool developer.
Please, add --no-extranonce option to you miner

http://p2p-spb.xyz:6102/static/ - Raven node for check

**Comment by trexminer** [comment]
Thanks for reporting, will be fixed in the next release. No extra option will be required.

**Comment by trexminer** [comment]
Fixed in 0.11.0
Feel free to reopen the issue if the problem remains
