### ISSUE TITLE
WARN: NVML: can't get GPU #0, error code 15

### ISSUE THREAD

**Issue by jvoda1** [trexminer/T-Rex#230]
I am running T-Rex 0.19.11, and got the following error which so far is solved by recurrently restarting the rig:

WARN: NVML: can't get GPU #0, error code 15
...
WARN: GPU #0: EVGA Geforce GTX 1060 6GB is idle, last activity was 51 secs ago
WARN: WATCHDOG: T-Rex has a problem with GPU, terminating...
WARN: WATCHDOG: recovering T-Rex

Any hint to fix it is appreciated

**Comment by progamerOG** [comment]
i got same error, never had it before.

**Comment by progamerOG** [comment]
follow-up, i toreff the pc rack down and found a burnt cable to pci riser, replaced cable mine is now working 100%.

good luck

**Comment by jvoda1** [comment]
> follow-up, i tore the pc rack down and found a burnt cable to pci riser, replaced cable mine is now working 100%.
> 
> good luck

Thanks for your reply. Unfortunately I just can perform remote configuration adjustments since I am not close to the Rig. Then if there is not any other option I will deactivate GPU 0 and have a visual inspection to the cables in few weeks once I am able to make a site visit.

**Comment by gtdiehl** [comment]
I ran into this problem today. Checked the cables everything looks good. Restarted the machine and it's back to 100%.

Wondering if it's a software problem, as I have been also having watchdog errors where I get an error and the `miner` process consumes 100% of the CPU. Or I'll see a GPU crash and the miner will continue along.

I'm running with 1x1070 and 2x3070 under Debian Buster with NVIDIA `460.39` drivers
OC settings:
```
nvidia-settings -c :0 -a [gpu:0]/GPUMemoryTransferRateOffsetAllPerformanceLevels=800 -a [gpu:0]/GPUGraphicsClockOffsetAllPerformanceLevels=130
nvidia-settings -c :0 -a [gpu:1]/GPUMemoryTransferRateOffsetAllPerformanceLevels=2000 -a [gpu:1]/GPUGraphicsClockOffsetAllPerformanceLevels=130
nvidia-settings -c :0 -a [gpu:2]/GPUMemoryTransferRateOffsetAllPerformanceLevels=2000 -a [gpu:2]/GPUGraphicsClockOffsetAllPerformanceLevels=130
```

**Comment by jvoda1** [comment]
> I ran into this problem today. Checked the cables everything looks good. Restarted the machine and it's back to 100%.
> 
> Wondering if it's a software problem, as I have been also having watchdog errors where I get an error and the `miner` process consumes 100% of the CPU. Or I'll see a GPU crash and the miner will continue along.
> 
> I'm running with 1x1070 and 2x3070 under Debian Buster with NVIDIA `460.39` drivers
> OC settings:
> 
> ```
> nvidia-settings -c :0 -a [gpu:0]/GPUMemoryTransferRateOffsetAllPerformanceLevels=800 -a [gpu:0]/GPUGraphicsClockOffsetAllPerformanceLevels=130
> nvidia-settings -c :0 -a [gpu:1]/GPUMemoryTransferRateOffsetAllPerformanceLevels=2000 -a [gpu:1]/GPUGraphicsClockOffsetAllPerformanceLevels=130
> nvidia-settings -c :0 -a [gpu:2]/GPUMemoryTransferRateOffsetAllPerformanceLevels=2000 -a [gpu:2]/GPUGraphicsClockOffsetAllPerformanceLevels=130
> ```

Thanks for sharing your view.

It happens to me on at least on releases  0.19.10 and  0.19.11. Tried to increase the virtual memory and issue still there.
When I reboot the rig, it is solved but after a while (from 10min up to 2 hours) the issue comes back.
So far I am just mining with one GPU less (5 instead of 6). All my GPUs on this rig are EVGA 1060 GTX SSC 6GB.

Did not find the problem yet and I cannot visit the rig on site for several weeks to check cables.

**Comment by Ramsin** [comment]
I'm having the same issue here, I've tried different risers, cables...in my case it certainly doesn't seem like it's riser related. I tried an older driver with no luck. Tried T-Rex .10 and .11, no luck.

I use T-Rex to mine Ethereum without issue, but only when I try mining Raven Coin that it gives me this error. Coincidentally, it does happen to be the only card that I have on a riser, but again, it works fine for Ethererum. The only thing I haven't tried is moving around my cards....just to definitively determine that it's riser related.

For reference:

GPU 0: 3060ti Founders Edition
GPU 1: 3060ti MSI Ventus 2x
GPU 2: 3060ti Gigabyte OC Gaming (this is the only one that's external/on a riser)

**Comment by jvoda1** [comment]
> I'm having the same issue here, I've tried different risers, cables...in my case it certainly doesn't seem like it's riser related. I tried an older driver with no luck. Tried T-Rex .10 and .11, no luck.
> 
> I use T-Rex to mine Ethereum without issue, but only when I try mining Raven Coin that it gives me this error. Coincidentally, it does happen to be the only card that I have on a riser, but again, it works fine for Ethererum. The only thing I haven't tried is moving around my cards....just to definitively determine that it's riser related.
> 
> For reference:
> 
> GPU 0: 3060ti Founders Edition
> GPU 1: 3060ti MSI Ventus 2x
> GPU 2: 3060ti Gigabyte OC Gaming (this is the only one that's external/on a riser)

Nice feedback... probably it is not the riser but one of the raiser cables? If you are able to move around the cards and maybe plug the failing one on the motherboard without raiser, it would be nice to help to discard some things...

Another option could be that for any reason a thermal pad is not doing its work and one of the memories is getting hotter than usual... but I in my case I replaced all thermal pads one month ago so they are pretty recent.

thanks for replying

**Comment by Ramsin** [comment]
> Nice feedback... probably it is not the riser but one of the cables feeding it up? If you are able to move around the cards and maybe plug the failing one on the motherboard without riser, it would be nice to find or discard some things... even nicer if you maybe only plug the failing card and see if the issue occurs or not.
>

I should've done this when I had it out, but truthfully, I was just being lazy and decided to try it some other time.
 
> Another option could be that for any reason a thermal pad is not doing its work and one of the memories is getting hotter than usual... but I in my case I replaced all thermal pads one month ago so they are pretty recent.
> 
> I dont think it is related to the coin you are mining. The only thing that stands out in my mind is that maybe depending on the coin you are mining, you are stressing more/less any of the memory chipset which reinforces the theory of a memory component which might be not dissipating the heat properly.
> 
> thanks for replying

In my case, this is most probably not an issue, as a matter of fact, the only time the cards have ever hit anything above 60ºc is when I was getting the OC'ing right. Aside from that, the warmest card I have is running at 52ºc, the others are at 45º under full load.

I live in Chicago and the rig is in my crawlspace. They're basically in a huge refrigerator. I highly doubt thermals are a factor in this issue.

**Comment by Ramsin** [comment]
Ok, here's my update...

My issue was power draw...my power supply is a bit low (waiting for new supply to come in). What I had to do is start Afterburner, load a profile that dropped the power to around 132 watts per card (3060ti's), launch gMiner and after DAG creation was complete, switch profiles.

T-Rex miner stopped giving me the error, but locks up a few minutes after it started mining. I can't figure out why it does that, so I just switched miners...Now I'm just trying to figure out why I'm only getting ~77Mh/s vs the 80 to 90 that some of the calculators are claiming I should be able to achieve. I hope this helps.

**Comment by gtdiehl** [comment]
I stopped having the error (so far) after dropping my Memory offset to 1650 and GPU offset to 0 from 2000 and 135 on only my two 3070s.

Maybe the power setting is too low for the higher offsets? I have the power set to 125w for the 3070s.

**Comment by jvoda1** [comment]
> Ok, here's my update...
> 
> My issue was power draw...my power supply is a bit low (waiting for new supply to come in). What I had to do is start Afterburner, load a profile that dropped the power to around 132 watts per card (3060ti's), launch gMiner and after DAG creation was complete, switch profiles.
> 
> T-Rex miner stopped giving me the error, but locks up a few minutes after it started mining. I can't figure out why it does that, so I just switched miners...Now I'm just trying to figure out why I'm only getting ~77Mh/s vs the 80 to 90 that some of the calculators are claiming I should be able to achieve. I hope this helps.

Good that you at least solved the issue and not any error code 15 message is appearing. Did you confirm this with a long period of test time (at least 24h)?

When it comes to the decrement of MHs, it is surely related to the power low profile you loaded on Afterburner. Is it lowering the mem / GPU clock speeds?

**Comment by jvoda1** [comment]
> I stopped having the error (so far) after dropping my Memory offset to 1650 and GPU offset to 0 from 2000 and 135 on only my two 3070s.
> 
> Maybe the power setting is too low for the higher offsets? I have the power set to 125w for the 3070s.

My cards were running at default GPU/mem clocks (I want them to keep alive for a while) but they are already 4 years old. I just decreased the clock for both gpu and mem as you just did to see if the error is happening again. This has drop the MHs from 20.1 to 17.9 aprox. Lets see if it works, otherwise I will also play with the power limit on the AfterBurner as well.

thanks a lot, will keep you posted

**Comment by ril3y** [comment]
I have the same error on a 13x 3070 rig.  Never had it before but also never had 13x in 1 rig before.  If I reboot it all works again.  However, not sure its related, but sometimes when i reboot one card will "show up" but not mine.  I rebooted again and it seems to work.

**Comment by jvoda1** [comment]
> I have the same error on a 13x 3070 rig. Never had it before but also never had 13x in 1 rig before. If I reboot it all works again. However, not sure its related, but sometimes when i reboot one card will "show up" but not mine. I rebooted again and it seems to work.

try decreasing the clock of the mem or the gpu and/or the gpu that is failing... seems to be working for me

**Comment by ril3y** [comment]
@jvoda1 thanks for the suggestion.  I have a LiteON 1400W PSU I am going to try vs the HP one I have.  This HP one is old and I got it used.  I switched it out and am observing now.  If I get another error 15 I will drop the overclocking and try your idea.  I will report back.

**Comment by jvoda1** [comment]
> @jvoda1 thanks for the suggestion. I have a LiteON 1400W PSU I am going to try vs the HP one I have. This HP one is old and I got it used. I switched it out and am observing now. If I get another error 15 I will drop the overclocking and try your idea. I will report back.

Try and let us know... but I dont think it is a problem from the PSU due to lack or unstable power. To me it is more related to the mem clock which is too high to work properly either because we overclocked it excessively or a chipset that stabilizes a memory is getting too warm and we cannot detect it on the reported temperatures or just because the HW is getting old :)

**Comment by ril3y** [comment]
These are new cards. So not old. Also what is odd is the whole machine
locks up. I would expect it to just drop that card but nope.

**Comment by jvoda1** [comment]
@ril3y I believe none of us had the whole rig locked with the issue. In my case the card goes to idle mode on t-rex and do not mine anymore. Pls try to decrease the mem and/or gpu clock of the faulty card and come back to us with the result.

**Comment by ril3y** [comment]
Jvoda1,

Yah you got it.  I just changed out that PSU and am just going to want and
see how it goes.  If it does fix it great.  If not I am lowering my OC
settings for sure.  I will report back either way.

**Comment by gtdiehl** [comment]
I just changed from Debian Buster with NVIDIA `460.39` drivers to HiveOS with NVIDIA `455.45.01` drivers and am able to push my 3070s a bit further without any crashing using the latest T-Rex. Maybe the latest Nvidia drivers are causing some problems?

![Screen Shot 2021-02-23 at 3 47 32 PM](https://user-images.githubusercontent.com/34967045/108923895-79bc9380-75ee-11eb-96fe-a76a36a1ad7a.png)

**Comment by AChangXD** [comment]
Same issue on my 4x 3090 + 3080 rig, one card just gets the error code 15 and crashes

**Comment by jvoda1** [comment]
@gtdiehl @AChangXD could you please try to decrease the mem clock and see if the issue reappears? In my case I lost 10% of Hash rate but on the other hand I've never seen this error again on the faulty GPU

**Comment by giyama** [comment]
In my case the cable burned close to the power supply
![IMG-20210329-WA0006](https://user-images.githubusercontent.com/13488143/112863146-ec58dd00-908c-11eb-8673-d927411a3292.jpeg)

**Comment by Maxkaizo** [comment]
In summary it seems to be caused by two main issues, 1) Wrong (exceeded) OC Settings or 2) Power issues (insufficient power or damaged cabling). In my case, it seems that its the first one, I'll run some tests and post results later

**Comment by rbfx4x** [comment]
I seem to have fixed it on the 3070 that was giving me this error.  
A little rig maintenance, checking wires, making sure everything was seated properly and I gave the card in question 5W more juice and it is stable so far for the last 30 mins.

**Comment by tileb1** [comment]
@rbfx4x did changing the riser solve the problem?

**Comment by rbfx4x** [comment]
> @rbfx4x did changing the riser solve the problem?

Yes it did. Stable ever since, even while pushing the OC with Kawpow.

**Comment by Headsimon** [comment]
> 
> 
> > @rbfx4x did changing the riser solve the problem?
> 
> Yes it did. Stable ever since, even while pushing the OC with Kawpow.

Guys i am having two GPUs, 3060ti Founder edition and 3060ti Gigabyte edition. Gigabyte one was older on which i have mined for 3 months with no issues. However after mounting it on riser, an error is coming up at random times. Sometimes after 2 hours, sometimes after 2 days. I was using PhoenixMiner. Error goes like this, "hwmc GPU2: unable to get GPU fan speed- GPU is lost (15)" and then it restarts the PC. 
The riser used by me is "https://www.amazon.in/PiPlusTM-VER009S-Powered-Adapter-Extension/dp/B08YXHPZXL/ref=sr_1_4?dchild=1&keywords=piplus+riser&qid=1632508986&sr=8-4". Please check. I am a newbie therefore dont know much technicalities. However i have powered riser and gpu from different PCIe cables from psu. I will try increasing fan speed but the issue is that it will run for a day or two nonstop and then suddenly in every 2 hours i get this error and miner reboots. Today it restarted the pc at 6:57, 8:57, 10:57 and so on. This is one log file for your reference,

2021.09.24:22:57:08.377: eths Eth: New job #efefc125 from ssl://asia1.ethermine.org:5555; diff: 4295MH
2021.09.24:22:57:10.022: hwmc GPU2: unable to get fan speed - GPU is lost (15)
2021.09.24:22:57:10.065: main GPU1: 68C 72% 140W, GPU2: 67C
GPUs power: 139.9 W; 428 kH/J
2021.09.24:22:57:11.320: main Eth speed: 59.923 MH/s, shares: 184/1/0, time: 1:58
2021.09.24:22:57:11.320: main GPUs: 1: 59.923 MH/s (90) 2: 0.000 MH/s (95)

2021.09.24:22:57:15.871: main *** 1:58 *** 9/24 22:57 **************************************
2021.09.24:22:57:15.871: main Eth: Mining ETH on ssl://asia1.ethermine.org:5555 for 1:16
2021.09.24:22:57:15.871: main Eth: Accepted shares 184 (1 stales), rejected shares 1 (0 stales)
2021.09.24:22:57:15.871: main Eth: Incorrect shares 0 (0.00%), est. stales percentage 0.54%
2021.09.24:22:57:15.871: main Eth: Maximum difficulty of found share: 2716.9 GH (!)
2021.09.24:22:57:15.871: main Eth: Average speed (5 min): 112.418 MH/s
2021.09.24:22:57:15.871: main Eth: Effective speed: 111.47 MH/s; at pool: 110.87 MH/s
2021.09.24:22:57:15.871: main  

after this mining is continued for 30 seconds and then it restarts the PC with windows failure of NO CARD DETECTED. Is the problem with riser? I tried changing the position of GPUs i.e. replaced two GPUs with one another and still the problem persists. Now i switched to Trex miner.
My OC settings are Power limit 70, core clock tried a whole range of 0,-200,-300,-502, mem clock 900,950,1000,1100,1150,1200 fan speed such that it stays around 67 C. After rotating GPUs i think problem is isolated with riser and its power cables. I use 850 W Antec HCGGold PSU. The power cables for riser and GPU are both separate. 

I think its defective riser but not able to see how after restart problem vanishes. In fact i ordered this riser yesterday, https://www.amazon.in/Tapia-V009S-Plus-Indicator-Extension/dp/B097R24JFB/ref=sr_1_5?dchild=1&keywords=riser&qid=1632540537&sr=8-5. Should i cancel it and reorder? This is the another 010s riser i could find https://www.vedantcomputers.com/riser-extender-ver0010s-plus-8-capacitor-ultra-stable-extra-led-16-into-to%20-1-into-power-pcie-80cm-usb-3point0-cable?search=riser.
