### ISSUE TITLE
GPU randomly goes idle

### ISSUE THREAD

**Issue by FQLT** [trexminer/T-Rex#232]
Hello ! I have following problem: my Gigabyte GeForce GTX 1080 Ti randomly goes idle, it happens around 16-18 times per 24 hours.
My OC settings:
Power limit: 80%
Core clock: 975 mV 1985 MHz
Memory clock: -200
I don't think it happens due OC settings, moreover idle problem started happening around 3 days ago. Until that GPU worked 2 days without any problems. What can I do to prevent it ?
My logs example: https://pastebin.com/aqnThbyg

**Comment by trexminer** [comment]
Hi. Seems hardware related as the GPU just stops mining (power usage drops significantly)

**Comment by FQLT** [comment]
Yeah, after some experiments I realized that it was OC problem
