### ISSUE TITLE
Error with ETHHash

### ISSUE THREAD

**Issue by LambThe** [trexminer/T-Rex#239]
Hi,

The programs loops and does not connect at all.
Anyone able to help me solve the problem?

GPU: GTX 1050 Ti (8gb)
Processor: i7-6700 CPU @ 3.40GHz   3.41 GHz
Installed RAM: 16.0 GB
All the drivers are up to date.

C:\Users\Isiah\Downloads\t-rex-0.19.11-win-cuda11.1>t-rex.exe -a ethash -o stratum+tcp://asia1.ethermine.org:4444 -u 0xb6328D71DfA35C5e46fc7FbD3610eb5B192aaDCb -p x -i 20 --kernel 2 -w rig0
20210222 23:28:16 T-Rex NVIDIA GPU miner v0.19.11  -  [CUDA v11.10 | Windows]
20210222 23:28:16 r.9c70a63f2290
20210222 23:28:16
20210222 23:28:16 NVIDIA Driver v461.40
20210222 23:28:16 CUDA devices available: 1
20210222 23:28:16
20210222 23:28:16 WARN: DevFee 1% (ethash)
20210222 23:28:16
20210222 23:28:16 URL : stratum+tcp://asia1.ethermine.org:4444
20210222 23:28:16 USER: 0xb6328D71DfA35C5e46fc7FbD3610eb5B192aaDCb
20210222 23:28:16 PASS: x
20210222 23:28:16 WRK : rig0
20210222 23:28:16
20210222 23:28:16 Starting on: asia1.ethermine.org:4444
20210222 23:28:16 ApiServer: HTTP server started on 127.0.0.1:4067
20210222 23:28:16 ---------------------------------------------------
20210222 23:28:16 For control navigate to: http://127.0.0.1:4067/trex
20210222 23:28:16 ---------------------------------------------------
20210222 23:28:16 ApiServer: Telnet server started on 127.0.0.1:4068
20210222 23:28:17 WARN: GPU #0(000100): GeForce GTX 1050 Ti, intensity set to 20, kernel 2
20210222 23:28:17 WARN: NVML: can't get power for GPU #0, not supported
20210222 23:28:37 ERROR: No connection, retry after 10 seconds
20210222 23:29:08 ERROR: No connection, retry after 10 seconds
20210222 23:29:17
20210222 23:29:17 Mining at asia1.ethermine.org:4444
20210222 23:29:17 GPU #0: GTX 1050 Ti - 0.00 H/s, [T:35C, F:40%]
20210222 23:29:17 Shares/min: 0
20210222 23:29:17 Uptime: 1 min | Algo: ethash | T-Rex v0.19.11
20210222 23:29:17
20210222 23:29:40 ERROR: No connection, retry after 10 seconds
20210222 23:29:47
20210222 23:29:47 Mining at asia1.ethermine.org:4444
20210222 23:29:47 GPU #0: GTX 1050 Ti - 0.00 H/s, [T:34C, F:40%]
20210222 23:29:47 Shares/min: 0
20210222 23:29:47 Uptime: 1 min 30 secs | Algo: ethash | T-Rex v0.19.11
20210222 23:29:47
20210222 23:30:11 ERROR: No connection, retry after 10 seconds
20210222 23:30:17
20210222 23:30:17 Mining at asia1.ethermine.org:4444
20210222 23:30:17 GPU #0: GTX 1050 Ti - 0.00 H/s, [T:34C, F:40%]
20210222 23:30:17 Shares/min: 0
20210222 23:30:17 Uptime: 2 mins | Algo: ethash | T-Rex v0.19.11
20210222 23:30:17
20210222 23:30:42 ERROR: No connection, retry after 10 seconds
20210222 23:30:47
20210222 23:30:47 Mining at asia1.ethermine.org:4444
20210222 23:30:47 GPU #0: GTX 1050 Ti - 0.00 H/s, [T:34C, F:40%]
20210222 23:30:47 Shares/min: 0
20210222 23:30:47 Uptime: 2 mins 30 secs | Algo: ethash | T-Rex v0.19.11
20210222 23:30:47
20210222 23:31:13 ERROR: No connection, retry after 10 seconds
20210222 23:31:17
20210222 23:31:17 Mining at asia1.ethermine.org:4444
20210222 23:31:17 GPU #0: GTX 1050 Ti - 0.00 H/s, [T:34C, F:40%]
20210222 23:31:17 Shares/min: 0
20210222 23:31:17 Uptime: 3 mins | Algo: ethash | T-Rex v0.19.11
20210222 23:31:17
20210222 23:31:44 ERROR: No connection, retry after 10 seconds
20210222 23:31:47
20210222 23:31:47 Mining at asia1.ethermine.org:4444
20210222 23:31:47 GPU #0: GTX 1050 Ti - 0.00 H/s, [T:34C, F:40%]
20210222 23:31:47 Shares/min: 0
20210222 23:31:47 Uptime: 3 mins 30 secs | Algo: ethash | T-Rex v0.19.11
20210222 23:31:47

**Comment by LambThe** [comment]
Did some tweaking.

Is this mining now at this setup?

Please help.


C:\Users\Oliver\Downloads\t-rex-0.19.11-win-cuda11.1>t-rex.exe -a ethash -o stratum+tcp://asia1.ethermine.org:14444 -u 0xb6328D71DfA35C5e46fc7FbD3610eb5B192aaDCb -p x -w rig0 -i 10 --gpu-init-mode 1
20210223 02:08:24 T-Rex NVIDIA GPU miner v0.19.11  -  [CUDA v11.10 | Windows]
20210223 02:08:24 r.9c70a63f2290
20210223 02:08:24
20210223 02:08:24 NVIDIA Driver v461.40
20210223 02:08:24 CUDA devices available: 1
20210223 02:08:24
20210223 02:08:24 WARN: DevFee 1% (ethash)
20210223 02:08:24
20210223 02:08:24 URL : stratum+tcp://asia1.ethermine.org:14444
20210223 02:08:24 USER: 0xb6328D71DfA35C5e46fc7FbD3610eb5B192aaDCb
20210223 02:08:24 PASS: x
20210223 02:08:24 WRK : rig0
20210223 02:08:24
20210223 02:08:24 Starting on: asia1.ethermine.org:14444
20210223 02:08:24 ApiServer: HTTP server started on 127.0.0.1:4067
20210223 02:08:24 ---------------------------------------------------
20210223 02:08:24 For control navigate to: http://127.0.0.1:4067/trex
20210223 02:08:24 ---------------------------------------------------
20210223 02:08:24 ApiServer: Telnet server started on 127.0.0.1:4068
20210223 02:08:24 Using protocol: stratum1.
20210223 02:08:24 Authorizing...
20210223 02:08:25 Authorized successfully.
20210223 02:08:25 WARN: GPU #0(000100): GeForce GTX 1050 Ti, intensity set to 10
20210223 02:08:25 ethash epoch: 396, block: 11908375, diff: 4.00 G
20210223 02:08:25 ethash epoch: 396, block: 11908375, diff: 4.00 G
20210223 02:08:25 WARN: NVML: can't get power for GPU #0, not supported
20210223 02:08:27 WARN: GPU #0: not enough memory to hold the full DAG for epoch 396.
20210223 02:08:27 WARN: GPU #0: effective hashrate will be ~0.0% of its usual value
20210223 02:08:27 GPU #0: generating DAG 3.29 GB (80.44% of full size) for epoch 396 ...
20210223 02:08:29 ethash epoch: 396, block: 11908376, diff: 4.00 G
20210223 02:08:42 ethash epoch: 396, block: 11908377, diff: 4.00 G
20210223 02:08:43 ethash epoch: 396, block: 11908378, diff: 4.00 G
20210223 02:08:44 GPU #0: DAG generated [crc: 42ece1eb, time: 16886 ms], memory left: 243.20 KB
20210223 02:09:01 ethash epoch: 396, block: 11908379, diff: 4.00 G
20210223 02:09:22 ethash epoch: 396, block: 11908380, diff: 4.00 G
20210223 02:09:25
20210223 02:09:25 Mining at asia1.ethermine.org:14444, diff: 4.00 G
20210223 02:09:25 GPU #0: GTX 1050 Ti - 8.00 H/s, [T:61C, F:45%]
20210223 02:09:25 Shares/min: 0
20210223 02:09:25 Uptime: 1 min | Algo: ethash | T-Rex v0.19.11
20210223 02:09:25
20210223 02:09:25 ethash epoch: 396, block: 11908381, diff: 4.00 G
20210223 02:09:55
20210223 02:09:55 Mining at asia1.ethermine.org:14444, diff: 4.00 G
20210223 02:09:55 GPU #0: GTX 1050 Ti - 8.00 H/s, [T:61C, F:45%]
20210223 02:09:55 Shares/min: 0
20210223 02:09:55 Uptime: 1 min 30 secs | Algo: ethash | T-Rex v0.19.11
20210223 02:09:55
20210223 02:10:15 ethash epoch: 396, block: 11908382, diff: 4.00 G
20210223 02:10:17 ethash epoch: 396, block: 11908383, diff: 4.00 G
20210223 02:10:19 ethash epoch: 396, block: 11908384, diff: 4.00 G
20210223 02:10:25
20210223 02:10:25 Mining at asia1.ethermine.org:14444, diff: 4.00 G
20210223 02:10:25 GPU #0: GTX 1050 Ti - 8.00 H/s, [T:62C, F:45%]
20210223 02:10:25 Shares/min: 0
20210223 02:10:25 Uptime: 2 mins | Algo: ethash | T-Rex v0.19.11
20210223 02:10:25
20210223 02:10:29 ethash epoch: 396, block: 11908385, diff: 4.00 G
20210223 02:10:36 ethash epoch: 396, block: 11908386, diff: 4.00 G
20210223 02:10:38 ethash epoch: 396, block: 11908387, diff: 4.00 G
20210223 02:10:55
20210223 02:10:55 Mining at asia1.ethermine.org:14444, diff: 4.00 G
20210223 02:10:55 GPU #0: GTX 1050 Ti - 8.00 H/s, [T:62C, F:45%]
20210223 02:10:55 Shares/min: 0
20210223 02:10:55 Uptime: 2 mins 30 secs | Algo: ethash | T-Rex v0.19.11
20210223 02:10:55
20210223 02:11:01 ethash epoch: 396, block: 11908388, diff: 4.00 G
20210223 02:11:11 ethash epoch: 396, block: 11908389, diff: 4.00 G
20210223 02:11:25
20210223 02:11:25 Mining at asia1.ethermine.org:14444, diff: 4.00 G
20210223 02:11:25 GPU #0: GTX 1050 Ti - 8.00 H/s, [T:62C, F:45%]
20210223 02:11:25 Shares/min: 0
20210223 02:11:25 Uptime: 3 mins | Algo: ethash | T-Rex v0.19.11
20210223 02:11:25
20210223 02:11:38 ethash epoch: 396, block: 11908390, diff: 4.00 G
20210223 02:11:47 ethash epoch: 396, block: 11908391, diff: 4.00 G

**Comment by trexminer** [comment]
1050ti doesn't have enough memory to mine ETH efficiently. See

```
20210223 02:08:27 WARN: GPU #0: not enough memory to hold the full DAG for epoch 396.
20210223 02:08:27 WARN: GPU #0: effective hashrate will be ~0.0% of its usual value
```

**Comment by LambThe** [comment]
> 1050ti doesn't have enough memory to mine ETH efficiently. See
> 
> ```
> 20210223 02:08:27 WARN: GPU #0: not enough memory to hold the full DAG for epoch 396.
> 20210223 02:08:27 WARN: GPU #0: effective hashrate will be ~0.0% of its usual value
> ```

How about at this now? hash shows value now.


t-rex-0.19.11-win-cuda11.1>t-rex.exe -a ethash -o stratum+tcp://asia1.ethermine.org:14444 -u 0xb6328D71DfA35C5e46fc7FbD3610eb5B192aaDCb -p x -w rig0
20210224 01:00:27 T-Rex NVIDIA GPU miner v0.19.11  -  [CUDA v11.10 | Windows]
20210224 01:00:27 r.9c70a63f2290
20210224 01:00:27
20210224 01:00:27 NVIDIA Driver v461.40
20210224 01:00:27 CUDA devices available: 1
20210224 01:00:27
20210224 01:00:27 WARN: DevFee 1% (ethash)
20210224 01:00:27
20210224 01:00:27 URL : stratum+tcp://asia1.ethermine.org:14444
20210224 01:00:27 USER: 0xb6328D71DfA35C5e46fc7FbD3610eb5B192aaDCb
20210224 01:00:27 PASS: x
20210224 01:00:27 WRK : rig0
20210224 01:00:27
20210224 01:00:27 Starting on: asia1.ethermine.org:14444
20210224 01:00:27 ApiServer: HTTP server started on 127.0.0.1:4067
20210224 01:00:27 ---------------------------------------------------
20210224 01:00:27 For control navigate to: http://127.0.0.1:4067/trex
20210224 01:00:27 ---------------------------------------------------
20210224 01:00:27 ApiServer: Telnet server started on 127.0.0.1:4068
20210224 01:00:27 Using protocol: stratum1.
20210224 01:00:27 Authorizing...
20210224 01:00:27 WARN: GPU #0(000100): GeForce GTX 1050 Ti, intensity set to 22
20210224 01:00:27 Authorized successfully.
20210224 01:00:27 ethash epoch: 397, block: 11914560, diff: 4.00 G
20210224 01:00:27 ethash epoch: 397, block: 11914560, diff: 4.00 G
20210224 01:00:28 WARN: NVML: can't get power for GPU #0, not supported
20210224 01:00:29 WARN: GPU #0: not enough memory to hold the full DAG for epoch 397.
20210224 01:00:29 WARN: GPU #0: effective hashrate will be ~0.0% of its usual value
20210224 01:00:29 GPU #0: generating DAG 3.29 GB (80.29% of full size) for epoch 397 ...
20210224 01:00:32 ethash epoch: 397, block: 11914561, diff: 4.00 G
20210224 01:00:46 GPU #0: DAG generated [crc: 6f6c3f4c, time: 16437 ms], memory left: 243.20 KB
20210224 01:00:46 ethash epoch: 397, block: 11914562, diff: 4.00 G
20210224 01:00:48 ethash epoch: 397, block: 11914563, diff: 4.00 G
20210224 01:00:50 ethash epoch: 397, block: 11914564, diff: 4.00 G
20210224 01:00:51 ethash epoch: 397, block: 11914565, diff: 4.00 G
20210224 01:01:03 ethash epoch: 397, block: 11914566, diff: 4.00 G
20210224 01:01:04 ethash epoch: 397, block: 11914567, diff: 4.00 G
20210224 01:01:12 ethash epoch: 397, block: 11914568, diff: 4.00 G
20210224 01:01:27
20210224 01:01:27 Mining at asia1.ethermine.org:14444, diff: 4.00 G
20210224 01:01:27 GPU #0: GTX 1050 Ti - 11.00 H/s, [T:62C, F:44%]
20210224 01:01:27 Shares/min: 0
20210224 01:01:27 Uptime: 1 min | Algo: ethash | T-Rex v0.19.11
20210224 01:01:27
20210224 01:01:31 ethash epoch: 397, block: 11914569, diff: 4.00 G
20210224 01:01:46 ethash epoch: 397, block: 11914570, diff: 4.00 G
20210224 01:01:46 ethash epoch: 397, block: 11914571, diff: 4.00 G
20210224 01:01:57
20210224 01:01:57 Mining at asia1.ethermine.org:14444, diff: 4.00 G
20210224 01:01:57 GPU #0: GTX 1050 Ti - 10.00 H/s, [T:55C, F:44%]
20210224 01:01:57 Shares/min: 0
20210224 01:01:57 Uptime: 1 min 30 secs | Algo: ethash | T-Rex v0.19.11
20210224 01:01:57
20210224 01:02:01 ethash epoch: 397, block: 11914572, diff: 4.00 G
20210224 01:02:08 ethash epoch: 397, block: 11914573, diff: 4.00 G
20210224 01:02:09 ethash epoch: 397, block: 11914574, diff: 4.00 G
20210224 01:02:15 ethash epoch: 397, block: 11914575, diff: 4.00 G
20210224 01:02:27
20210224 01:02:27 Mining at asia1.ethermine.org:14444, diff: 4.00 G
20210224 01:02:27 GPU #0: GTX 1050 Ti - 8.00 H/s, [T:55C, F:44%]
20210224 01:02:27 Shares/min: 0
20210224 01:02:27 Uptime: 2 mins | Algo: ethash | T-Rex v0.19.11
20210224 01:02:27
20210224 01:02:28 ethash epoch: 397, block: 11914576, diff: 4.00 G
20210224 01:02:54 ethash epoch: 397, block: 11914577, diff: 4.00 G
20210224 01:02:55 ethash epoch: 397, block: 11914578, diff: 4.00 G
20210224 01:02:57
20210224 01:02:57 Mining at asia1.ethermine.org:14444, diff: 4.00 G
20210224 01:02:57 GPU #0: GTX 1050 Ti - 6.00 H/s, [T:55C, F:43%]
20210224 01:02:57 Shares/min: 0
20210224 01:02:57 Uptime: 2 mins 30 secs | Algo: ethash | T-Rex v0.19.11
20210224 01:02:57
20210224 01:03:19 ethash epoch: 397, block: 11914579, diff: 4.00 G
20210224 01:03:27
20210224 01:03:27 Mining at asia1.ethermine.org:14444, diff: 4.00 G
20210224 01:03:27 GPU #0: GTX 1050 Ti - 5.00 H/s, [T:55C, F:43%]
20210224 01:03:27 Shares/min: 0
20210224 01:03:27 Uptime: 3 mins | Algo: ethash | T-Rex v0.19.11
20210224 01:03:27
20210224 01:03:31 ethash epoch: 397, block: 11914580, diff: 4.00 G
20210224 01:03:43 ethash epoch: 397, block: 11914581, diff: 4.00 G
20210224 01:03:46 ethash epoch: 397, block: 11914582, diff: 4.00 G
20210224 01:03:55 ethash epoch: 397, block: 11914583, diff: 4.00 G
20210224 01:03:57
20210224 01:03:57 Mining at asia1.ethermine.org:14444, diff: 4.00 G
20210224 01:03:57 GPU #0: GTX 1050 Ti - 6.00 H/s, [T:60C, F:43%]
20210224 01:03:57 Shares/min: 0
20210224 01:03:57 Uptime: 3 mins 30 secs | Algo: ethash | T-Rex v0.19.11
20210224 01:03:57
20210224 01:03:58 ethash epoch: 397, block: 11914584, diff: 4.00 G
20210224 01:04:10 ethash epoch: 397, block: 11914585, diff: 4.00 G
20210224 01:04:15 ethash epoch: 397, block: 11914586, diff: 4.00 G
20210224 01:04:24 ethash epoch: 397, block: 11914587, diff: 4.00 G
20210224 01:04:27
20210224 01:04:27 Mining at asia1.ethermine.org:14444, diff: 4.00 G
20210224 01:04:27 GPU #0: GTX 1050 Ti - 9.00 H/s, [T:63C, F:45%]
20210224 01:04:27 Shares/min: 0
20210224 01:04:27 Uptime: 4 mins | Algo: ethash | T-Rex v0.19.11
20210224 01:04:27
20210224 01:04:40 ethash epoch: 397, block: 11914588, diff: 4.00 G
20210224 01:04:55 ethash epoch: 397, block: 11914589, diff: 4.00 G
20210224 01:04:57
20210224 01:04:57 Mining at asia1.ethermine.org:14444, diff: 4.00 G
20210224 01:04:57 GPU #0: GTX 1050 Ti - 11.00 H/s, [T:65C, F:46%]
20210224 01:04:57 Shares/min: 0
20210224 01:04:57 Uptime: 4 mins 30 secs | Algo: ethash | T-Rex v0.19.11
20210224 01:04:57
20210224 01:05:24 ethash epoch: 397, block: 11914590, diff: 4.00 G
20210224 01:05:27
20210224 01:05:27 Mining at asia1.ethermine.org:14444, diff: 4.00 G
20210224 01:05:27 GPU #0: GTX 1050 Ti - 11.00 H/s, [T:66C, F:46%]
20210224 01:05:27 Shares/min: 0
20210224 01:05:27 Uptime: 5 mins | Algo: ethash | T-Rex v0.19.11
20210224 01:05:27
20210224 01:05:32 ethash epoch: 397, block: 11914591, diff: 4.00 G
20210224 01:05:51 ethash epoch: 397, block: 11914592, diff: 4.00 G
20210224 01:05:57
20210224 01:05:57 Mining at asia1.ethermine.org:14444, diff: 4.00 G
20210224 01:05:57 GPU #0: GTX 1050 Ti - 11.00 H/s, [T:68C, F:46%]
20210224 01:05:57 Shares/min: 0
20210224 01:05:57 Uptime: 5 mins 30 secs | Algo: ethash | T-Rex v0.19.11
20210224 01:05:57
20210224 01:06:08 ethash epoch: 397, block: 11914593, diff: 4.00 G
20210224 01:06:26 ethash epoch: 397, block: 11914594, diff: 4.00 G
20210224 01:06:27
20210224 01:06:27 Mining at asia1.ethermine.org:14444, diff: 4.00 G
20210224 01:06:27 GPU #0: GTX 1050 Ti - 11.00 H/s, [T:69C, F:47%]
20210224 01:06:27 Shares/min: 0
20210224 01:06:27 Uptime: 6 mins | Algo: ethash | T-Rex v0.19.11
20210224 01:06:27
20210224 01:06:35 ethash epoch: 397, block: 11914595, diff: 4.00 G
20210224 01:06:40 ethash epoch: 397, block: 11914596, diff: 4.00 G
20210224 01:06:57
20210224 01:06:57 Mining at asia1.ethermine.org:14444, diff: 4.00 G
20210224 01:06:57 GPU #0: GTX 1050 Ti - 11.00 H/s, [T:69C, F:48%]
20210224 01:06:57 Shares/min: 0
20210224 01:06:57 Uptime: 6 mins 30 secs | Algo: ethash | T-Rex v0.19.11
20210224 01:06:57
20210224 01:06:58 ethash epoch: 397, block: 11914597, diff: 4.00 G
20210224 01:07:03 ethash epoch: 397, block: 11914598, diff: 4.00 G
20210224 01:07:24 ethash epoch: 397, block: 11914599, diff: 4.00 G
20210224 01:07:27 ethash epoch: 397, block: 11914600, diff: 4.00 G
20210224 01:07:27
20210224 01:07:27 Mining at asia1.ethermine.org:14444, diff: 4.00 G
20210224 01:07:27 GPU #0: GTX 1050 Ti - 11.00 H/s, [T:69C, F:48%]
20210224 01:07:27 Shares/min: 0
20210224 01:07:27 Uptime: 7 mins | Algo: ethash | T-Rex v0.19.11
20210224 01:07:27
20210224 01:07:29 ethash epoch: 397, block: 11914601, diff: 4.00 G
20210224 01:07:52 ethash epoch: 397, block: 11914602, diff: 4.00 G
20210224 01:07:58
20210224 01:07:58 Mining at asia1.ethermine.org:14444, diff: 4.00 G
20210224 01:07:58 GPU #0: GTX 1050 Ti - 11.00 H/s, [T:70C, F:48%]
20210224 01:07:58 Shares/min: 0
20210224 01:07:58 Uptime: 7 mins 31 secs | Algo: ethash | T-Rex v0.19.11
20210224 01:07:58
20210224 01:08:05 WARN: Connection with pool timed out. Trying to reconnect...
20210224 01:08:05 Using protocol: stratum1.
20210224 01:08:05 Authorizing...
20210224 01:08:05 Authorized successfully.
20210224 01:08:05 ethash epoch: 397, block: 11914602, diff: 4.00 G
20210224 01:08:06 ethash epoch: 397, block: 11914603, diff: 4.00 G
20210224 01:08:16 ethash epoch: 397, block: 11914604, diff: 4.00 G
20210224 01:08:28
20210224 01:08:28 Mining at asia1.ethermine.org:14444, diff: 4.00 G
20210224 01:08:28 GPU #0: GTX 1050 Ti - 11.00 H/s, [T:70C, F:48%]
20210224 01:08:28 Shares/min: 0
20210224 01:08:28 Uptime: 8 mins 1 sec | Algo: ethash | T-Rex v0.19.11
20210224 01:08:28
20210224 01:08:39 ethash epoch: 397, block: 11914605, diff: 4.00 G
20210224 01:08:40 ethash epoch: 397, block: 11914606, diff: 4.00 G
20210224 01:08:54 ethash epoch: 397, block: 11914607, diff: 4.00 G
20210224 01:08:55 ethash epoch: 397, block: 11914608, diff: 4.00 G
20210224 01:08:58
20210224 01:08:58 Mining at asia1.ethermine.org:14444, diff: 4.00 G
20210224 01:08:58 GPU #0: GTX 1050 Ti - 11.00 H/s, [T:70C, F:48%]
20210224 01:08:58 Shares/min: 0
20210224 01:08:58 Uptime: 8 mins 31 secs | Algo: ethash | T-Rex v0.19.11
20210224 01:08:58
20210224 01:09:16 ethash epoch: 397, block: 11914609, diff: 4.00 G
20210224 01:09:28
20210224 01:09:28 Mining at asia1.ethermine.org:14444, diff: 4.00 G
20210224 01:09:28 GPU #0: GTX 1050 Ti - 11.00 H/s, [T:70C, F:48%]
20210224 01:09:28 Shares/min: 0
20210224 01:09:28 Uptime: 9 mins 1 sec | Algo: ethash | T-Rex v0.19.11
20210224 01:09:28
20210224 01:09:32 ethash epoch: 397, block: 11914610, diff: 4.00 G
20210224 01:09:41 ethash epoch: 397, block: 11914611, diff: 4.00 G
20210224 01:09:44 ethash epoch: 397, block: 11914612, diff: 4.00 G
20210224 01:09:52 ethash epoch: 397, block: 11914613, diff: 4.00 G
20210224 01:09:56 ethash epoch: 397, block: 11914614, diff: 4.00 G
20210224 01:09:58
20210224 01:09:58 Mining at asia1.ethermine.org:14444, diff: 4.00 G
20210224 01:09:58 GPU #0: GTX 1050 Ti - 11.00 H/s, [T:70C, F:48%]
20210224 01:09:58 Shares/min: 0
20210224 01:09:58 Uptime: 9 mins 31 secs | Algo: ethash | T-Rex v0.19.11
20210224 01:09:58
20210224 01:09:58 ethash epoch: 397, block: 11914615, diff: 4.00 G
20210224 01:10:09 ethash epoch: 397, block: 11914616, diff: 4.00 G
20210224 01:10:12 ethash epoch: 397, block: 11914617, diff: 4.00 G
20210224 01:10:12 ethash epoch: 397, block: 11914618, diff: 4.00 G
20210224 01:10:28
20210224 01:10:28 Mining at asia1.ethermine.org:14444, diff: 4.00 G
20210224 01:10:28 GPU #0: GTX 1050 Ti - 11.00 H/s, [T:70C, F:49%]
20210224 01:10:28 Shares/min: 0
20210224 01:10:28 Uptime: 10 mins 1 sec | Algo: ethash | T-Rex v0.19.11
20210224 01:10:28
20210224 01:10:31 ethash epoch: 397, block: 11914619, diff: 4.00 G
20210224 01:10:35 ethash epoch: 397, block: 11914620, diff: 4.00 G
20210224 01:10:58
20210224 01:10:58 Mining at asia1.ethermine.org:14444, diff: 4.00 G
20210224 01:10:58 GPU #0: GTX 1050 Ti - 11.00 H/s, [T:70C, F:49%]
20210224 01:10:58 Shares/min: 0
20210224 01:10:58 Uptime: 10 mins 31 secs | Algo: ethash | T-Rex v0.19.11
20210224 01:10:58

**Comment by scorpio8783** [comment]
LanbThe: what tweaking did u do to make it work?
i have same gpu gtx 1050ti trying to mine on T-Rex and had same issue as u have before.

**Comment by LambThe** [comment]
> LanbThe: what tweaking did u do to make it work?
> i have same gpu gtx 1050ti trying to mine on T-Rex and had same issue as u have before.

As it seems 4Gbs can no longer mine ETH to grown dag size. Switched mining RVN with the 4gb cards instead.
