### ISSUE TITLE
Benchmark mode closes program

### ISSUE THREAD

**Issue by luc1an24** [trexminer/T-Rex#24]
Hi

If I enable benchmark mode, the program will close itself.
The command I am using is: `.\t-rex.exe --algo x16r --devices 3 --benchmark --time-limit 60`

While mining is working without any issues.
Could you please look into it?

Thank you and have a great day!

**Comment by trexminer** [comment]
Thanks for reporting, it will be fixed in the next version

**Comment by trexminer** [comment]
Fixed in 0.12.1
BTW, x16r benchmark is currently useless, it only benchmarks one hash order, so I suggest benchmarking x17 instead, it'll give you a rough estimate of what your x16r average hashrate would be (x17 is actually a few per cent faster)
