### ISSUE TITLE
Incorrect number of shares posted by T-Rex miner

### ISSUE THREAD

**Issue by guanhuay** [trexminer/T-Rex#245]
Hi @trexminer ,

Thanks for putting up this great tool, and I found this is the best tool for mining Ethereum.

For my setup,

I have one GTX 1070 GPU and T-Rex miner version t-rex-0.19.11-win-cuda11.1.

I have found issues with the miner where the shares number shown in T-Rex miner is different than it in Ethermine, please find the below screenshot for evidences:

My T-Rex miner shows 199 shares mined with status OK:

![Capture](https://user-images.githubusercontent.com/16933391/108873284-d9e01500-75af-11eb-9d96-e5fbff8e1999.JPG)

![Capture](https://user-images.githubusercontent.com/16933391/108874983-95ee0f80-75b1-11eb-8c5f-7b80817c38b9.JPG)

While my Ethermine dashboard shows only 37 shares is valid:

![Capture1](https://user-images.githubusercontent.com/16933391/108873405-f2e8c600-75af-11eb-8d33-c85218fe5ebd.JPG)

I am not sure why there is a huge difference, would you mind provide some helps regarding this matter?

Thank you very much!

**Comment by willis936** [comment]
If you hover over the shares field on ethermine there is a tooltip that says it is the number of shares in the past hour.

The t-rex API shows the number of shares since start: in your case 8.5 hours.  This is verified by looking at the "shares/min" field.
