### ISSUE TITLE
Miner crashed with error: Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by ftl52** [trexminer/T-Rex#252]
Hi, I am solo mining with octopus algorithm, the miner worked fine for the last couple of weeks. Somehow it started to crash with this error recently. I tried starting it several times and I am guessing it may be related to the mining difficulty. It failed immediately when the difficuty is 1T hash and seemed to work when difficult is under 800G.
Is there a parameter I can tune to avoid the miner from crashing?

<pre><code>20210226 17:47:45 WARN: GPU #0(000100): MSI GeForce RTX 2060 SUPER, intensity set to 20
Segmentation fault (core dumped)
</code></pre>

**Comment by ftl52** [comment]
t-rex-0.19.5-linux-cuda11.1 in Ubuntu18.04

**Comment by trexminer** [comment]
Could you try this assembly please? 
https://www.dropbox.com/s/260a63trzk7vxnw/t-rex-0.19.11-newvm-linux-cuda11.1.tar.gz?dl=1

**Comment by ftl52** [comment]
Still got the same error(current mining difficulty above 1T):
<pre><code>20210301 13:31:24 Using protocol: octopus.
20210301 13:31:24 Authorizing...
20210301 13:31:24 Authorized successfully.
20210301 13:31:24 WARN: GPU #0(000100): MSI GeForce RTX 2060 SUPER, intensity set to 20
Segmentation fault (core dumped)</code></pre>

Successful if connecting to a mining pool:
<pre><code>20210301 13:35:12 WARN: GPU #0(000100): MSI GeForce RTX 2060 SUPER, intensity set to 20
20210301 13:35:13 Using protocol: octopus.
20210301 13:35:13 Authorizing...
20210301 13:35:13 Authorized successfully.
20210301 13:35:13 octopus epoch: 17, block: 9225298, diff: 10.00 G
20210301 13:35:13 octopus epoch: 17, block: 9225298, diff: 10.00 G
20210301 13:35:13 octopus epoch: 17, block: 9225299, diff: 10.00 G
20210301 13:35:13 GPU #0: generating DAG 4.27 GB for epoch 17 ...</code></pre>

I am going to clear the state of my local conflux-rust node, start over and see if that helps.

**Comment by ftl52** [comment]
Well, still the same error with the fresh started node...

**Comment by trexminer** [comment]
Should be fixed in the newest version
