### ISSUE TITLE
Degraded desktop usability when running in background in Linux

### ISSUE THREAD

**Issue by ironstarfish** [trexminer/T-Rex#254]
Experiencing degraded usability and stuttering when mining in the background.  Only experiencing this issue in Linux, Windows seems to run fine with expected drop in hashrate when running gpu intensive tasks.
Tried reducing intensity using the flag but issue still persists.

Settings used (Windows and Linux):
-i 20 --mt 5

**Comment by trexminer** [comment]
The miner is trying to squeeze everything it can from the GPU, so I'm not surprised you experience stuttering. Just stop mining when you're using the desktop. You can also try smaller intensity values like `-i 14` but the hashrate will degrade.

**Comment by deeperarcher** [comment]
Same issue here. I'm on Manjaro 20.2.1 with KDE 5.79.0 with a RTX 3070. With the miner running in the background, I get a lot of stuttering and it's basically unusable for anything else, even with the intensity set a lot lower.  While I haven't used t-rex on windows, I've used nicehash on windows and do not experience a similar drop in performance.

**Comment by spocthier83** [comment]
You can disable hardware acceleration in your "xorg.conf".
X server will run on CPU instead of GPU.

```
...

Section "Screen"
    Identifier     "Screen1"
    Device         "Device1"
    Monitor        "Monitor1"
    DefaultDepth    24
    Option         "Accel" "False"
    Option         "Coolbits" "28"
    SubSection     "Display"
        Depth       24
    EndSubSection
EndSection

...

```

**Comment by deeperarcher** [comment]
> You can disable hardware acceleration in your "xorg.conf".
> X server will run on CPU instead of GPU.
> 
> ```
> ...
> 
> Section "Screen"
>     Identifier     "Screen1"
>     Device         "Device1"
>     Monitor        "Monitor1"
>     DefaultDepth    24
>     Option         "Accel" "False"
>     Option         "Coolbits" "28"
>     SubSection     "Display"
>         Depth       24
>     EndSubSection
> EndSection
> 
> ...
> ```

This worked for me, thanks!

**Comment by ironstarfish** [comment]
Disabling hardware accel worked for me as well.
Had to change default browser from Firefox to Chromium as Firefox is still very laggy.
