### ISSUE TITLE
RTX 3070 [FAIL] - Provided Pow solution is invalid, set dag-build-mode not working

### ISSUE THREAD

**Issue by LukasPutala** [trexminer/T-Rex#256]
Hi,
I have rtx 3070 and gtx 1660 and I use t-rex-0.19.11-win-cuda11.1.
I have several of these failures a day. I try to use parameter `--dag-build-mode 2`, but it didn't help.
I have rtx as gpu #0 and gtx as gpu#1 and I also tried to set a parameter ` --dag-build-mode 2,0` but my driver has restarted.
Please can you help me?

**Comment by MOVZX** [comment]
OC too high.

**Comment by LukasPutala** [comment]
I don't think it's high. I have ASUS tuf 3070, power limit - 60%, core: +0, memory: +1380, fan: 85%, measurement with a thermal imager showed a maximum of 68°C

**Comment by trexminer** [comment]
If the `DAG generated` message has `(!)` symbol at the end of the CRC, then the DAG is corrupted. `--dag-build-mode` is already 2 by default for 1660 and 3070, so no point in setting it explicitly. You can try `--dag-build-mode 1` though.
Generally I'd recommend resetting memory OC to stock settings to rule out the excessive overclock.

**Comment by LukasPutala** [comment]
Thanks.
