### ISSUE TITLE
GLIBC problem

### ISSUE THREAD

**Issue by issues8** [trexminer/T-Rex#257]
Hello,
I have installed CentOS 7, I got error about GLIBC.2_18.
In CentOS I got GLIBC.2_17.
Is there any way to turn on t-rex on glibc.2_17 ?

**Comment by trexminer** [comment]
Sorry, this would require recompiling under an older OS, so we probably won't do it.

**Comment by hintro32** [comment]
> Hello,
> I have installed CentOS 7, I got error about GLIBC.2_18.
> In CentOS I got GLIBC.2_17.
> Is there any way to turn on t-rex on glibc.2_17 ?

https://trex-miner.com/download/test/t-rex-0.21.6-centos7-linux.tar.gz

**Comment by trexminer** [comment]
Fixed in 0.22.1

**Comment by sammcj** [comment]
Seems to still be broken in 0.24.8
