### ISSUE TITLE
T-Rex failed to run

### ISSUE THREAD

**Issue by giting-666** [trexminer/T-Rex#259]
My running environment is Windows 10, version 11.1 T-Rex, the processor is I7-10750H, the graphics card is 1650TI, but when running T-Rex prompt: Can't start miner, video driver is too old Please update the video driver or use T-Rex Competted with Cuda V11.0 or older.

How to deal with it?

**Comment by trexminer** [comment]
Run CUDA 10.0 version of the miner instead of 11.1
