### ISSUE TITLE
NVML : Can't get fan speed error

### ISSUE THREAD

**Issue by gwongis88** [trexminer/T-Rex#260]
Can someone please help how to fix this problem?  It hang and crash.

Thanks
![TRexNVMLError](https://user-images.githubusercontent.com/56802628/109692582-b3dde600-7b56-11eb-8fa3-ce22a6809a85.PNG)

**Comment by gwongis88** [comment]
I will slow it down a bit  Please suggest otherwise.  Thanks

**Comment by AChangXD** [comment]
@gwongis88 On some laptops, fan speed is not supported. This kinda applies to pre-builds (seems like what you have going on rn)

**Comment by gwongis88** [comment]
What I have is a desktop, not laptop.

**Comment by trexminer** [comment]
Usually this is hardware related error. Look this for possible solution (site was translated to english):
https://translate.yandex.fr/translate?lang=ru-en&url=https%3A%2F%2Fcryptoprofi-info.turbopages.org%2Fcryptoprofi.info%2Fs%2F%3Fpcgi%3Dp%3D5519
