### ISSUE TITLE
not enough memory to hold the full DAG for epoch ..., effective hashrate will be ~0.0% of its usual value

### ISSUE THREAD

**Issue by jieweix** [trexminer/T-Rex#266]
20210304 11:44:56 T-Rex NVIDIA GPU miner v0.19.11  -  [CUDA v11.10 | Windows]
20210304 11:44:56 r.9c70a63f2290
20210304 11:44:56
20210304 11:44:56 NVIDIA Driver v461.72
20210304 11:44:56 CUDA devices available: 1
20210304 11:44:56
20210304 11:44:56 WARN: DevFee 1% (ethash)
20210304 11:44:56
20210304 11:44:56 URL : stratum+ssl://asia1.ethermine.org:5555
20210304 11:44:56 USER: 0xc973627275468475d87a20C18EBF20dAB687c7aB
20210304 11:44:56 PASS: x
20210304 11:44:56 WRK : jiewei
20210304 11:44:56
20210304 11:44:56 Starting on: asia1.ethermine.org:5555
20210304 11:44:56 WARN: unknown vendor id 0x103c of GPU nvml_id=#0
20210304 11:44:56 ApiServer: HTTP server started on 127.0.0.1:4067
20210304 11:44:56 ---------------------------------------------------
20210304 11:44:56 For control navigate to: http://127.0.0.1:4067/trex
20210304 11:44:56 ---------------------------------------------------
20210304 11:44:56 ApiServer: Telnet server started on 127.0.0.1:4068
20210304 11:44:56 WARN: GPU #0(000100): GeForce GTX 1050, intensity set to 22
20210304 11:44:56 Using protocol: stratum1.
20210304 11:44:56 Authorizing...
20210304 11:44:57 Authorized successfully.
20210304 11:44:57 ethash epoch: 398, block: 11969402, diff: 4.00 G
20210304 11:44:57 ethash epoch: 398, block: 11969402, diff: 4.00 G
20210304 11:44:57 WARN: NVML: can't get fan speed for GPU #0, not supported
20210304 11:44:57 WARN: NVML: can't get power for GPU #0, not supported
20210304 11:45:00 WARN: GPU #0: not enough memory to hold the full DAG for epoch 398.
20210304 11:45:00 WARN: GPU #0: effective hashrate will be ~0.0% of its usual value
20210304 11:45:00 GPU #0: generating DAG 1.60 GB (39.02% of full size) for epoch 398 ...
20210304 11:45:08 GPU #0: DAG generated [crc: d634be61, time: 8209 ms], memory left: 204.40 KB
20210304 11:45:10 ethash epoch: 398, block: 11969403, diff: 4.00 G
20210304 11:45:25 ethash epoch: 398, block: 11969404, diff: 4.00 G
20210304 11:45:29 ethash epoch: 398, block: 11969405, diff: 4.00 G
20210304 11:45:47 ethash epoch: 398, block: 11969406, diff: 4.00 G
20210304 11:45:54 ethash epoch: 398, block: 11969407, diff: 4.00 G
20210304 11:45:57
20210304 11:45:57 Mining at asia1.ethermine.org:5555, diff: 4.00 G
20210304 11:45:57 GPU #0: GTX 1050 - 0.00 H/s, [T:77C]
20210304 11:45:57 Shares/min: 0
20210304 11:45:57 Uptime: 1 min 1 sec | Algo: ethash | T-Rex v0.19.11
20210304 11:45:57
20210304 11:46:17 WARN: shutdown t-rex, got Ctrl+C from console
20210304 11:46:17 Main loop finished. Cleaning up resources...
20210304 11:46:17 ApiServer: stopped listening on 127.0.0.1:4067
20210304 11:46:17 ApiServer: stopped listening on 127.0.0.1:4068
20210304 11:46:17 ethash epoch: 398, block: 11969408, diff: 4.00 G
20210304 11:46:18 T-Rex finished.

**Comment by trexminer** [comment]
You can't mine ETH with 1050, it doesn't have enough VRAM
