### ISSUE TITLE
t-rex miner on WSL 2.0 with CUDA - WATCHDOG: initialize error, memory dump at startup

### ISSUE THREAD

**Issue by ProfessorMadman** [trexminer/T-Rex#269]
I am on Windows 10 dev build 21H1 21327.1000 and trying to mine on Ethermine using t-rex in a docker image using WSL 2.0 on Docker Desktop 3.10.

I used the tutorial available here to get this all working

[https://docs.nvidia.com/cuda/wsl-user-guide/index.html](https://docs.nvidia.com/cuda/wsl-user-guide/index.html)

I'm using this docker image:

[https://github.com/PTRFRLL/nv-docker-trex](https://github.com/PTRFRLL/nv-docker-trex)

My host has latest NVIDIA CUDA drivers installed (v465.42) and the GPU is visible within my WSL 2.0 kernel (Ubuntu running on WSL2 kernel 5.4.91-microsoft-standard-WSL2)

When the docker image spins up it refused initially to start up due to CUDA version discrepancies but passing the -env NVIDIA_DISABLE_REQUIRE=1 flag bypasses CUDA version check and the miner starts up ok but then crashes with a memory dump on initialisation.  The version of t-rex I'm using is **T-Rex NVIDIA GPU miner v0.19.11 - [CUDA v11.10 | Linux]**

`20210305 22:41:09 WATCHDOG: initialize error, memory dump: eyJhIjoiWWFRTlpnQW5HcnBYaW4yUDlETENReDdHT1hrZ1dKNm40TkhqR3NWUzloN0RWMFUxdW45R3M2UFdhcmF5Y2RFeVllVzZQWU1VUjZ3SGREbnFWdFRwdm5rYU9YZElLWEhPY1dMalZpam1QVmMzU2s1dmpFbTF5MjNOd1VwL05nY3Q4Z0dJZ3owaU81ZW82ZG0xWjkwYTZBPT0iLCJiIjoiVS9meWRFNEU4OCtqQUNzOXUzRVhhUT09In0K`

**nv-docker-trex log:**

`Starting T-rex miner...

============================================================

Server: stratum+ssl://eu1.ethermine.org:5555

Algorithm: ethash

Wallet: (my eth address)

Worker: rig0

============================================================

20210305 22:41:09 WATCHDOG: initialize error, memory dump: eyJhIjoiWWFRTlpnQW5HcnBYaW4yUDlETENReDdHT1hrZ1dKNm40TkhqR3NWUzloN0RWMFUxdW45R3M2UFdhcmF5Y2RFeVllVzZQWU1VUjZ3SGREbnFWdFRwdm5rYU9YZElLWEhPY1dMalZpam1QVmMzU2s1dmpFbTF5MjNOd1VwL05nY3Q4Z0dJZ3owaU81ZW82ZG0xWjkwYTZBPT0iLCJiIjoiVS9meWRFNEU4OCtqQUNzOXUzRVhhUT09In0K

20210305 22:41:11 T-Rex NVIDIA GPU miner v0.19.11 - [CUDA v11.10 | Linux]

20210305 22:41:11 r.9c70a63f2290

20210305 22:41:11

20210305 22:41:11 NVIDIA Driver v465.42

20210305 22:41:11 CUDA devices available: 1

20210305 22:41:11

20210305 22:41:11 WARN: DevFee 1% (ethash)

20210305 22:41:11

20210305 22:41:11 URL : stratum+ssl://eu1.ethermine.org:5555

20210305 22:41:11 USER: (my eth address)

20210305 22:41:11 PASS: x

20210305 22:41:11 WRK : rig0

20210305 22:41:11

20210305 22:41:11 Starting on: eu1.ethermine.org:5555

20210305 22:41:11 Using protocol: stratum1.

20210305 22:41:11 Authorizing...

20210305 22:41:11 Authorized successfully.

20210305 22:41:11 ethash epoch: 399, block: 11981092, diff: 4.00 G

20210305 22:41:11 ethash epoch: 399, block: 11981092, diff: 4.00 G

20210305 22:41:11 ApiServer: HTTP server started on 0.0.0.0:4067

20210305 22:41:11 ----------------------------------------------------

20210305 22:41:11 For control navigate to: http://172.17.0.2:4067/trex

20210305 22:41:11 ----------------------------------------------------

20210305 22:41:11 ApiServer: Telnet server started on 127.0.0.1:4068

20210305 22:41:11 Main loop finished. Cleaning up resources...

20210305 22:41:11 ApiServer: stopped listening on 0.0.0.0:4067

20210305 22:41:11 ApiServer: stopped listening on 127.0.0.1:4068

20210305 22:41:11 WARN: GPU #0(000b00): GeForce RTX 3090, intensity set to 22

20210305 22:41:13 GPU #0: generating DAG 4.12 GB for epoch 399 ...

20210305 22:41:13 T-Rex finished.`

**I'm starting the docker image with these run parameters:**

`docker run -d --gpus all --env NVIDIA_DISABLE_REQUIRE=1 --name='trex-miner' -e WALLET=(myethaddress) -e SERVER=stratum+ssl://eu1.ethermine.org:5555 -e WORKER=rig0 -e ALGO=ethash -p '4067:4067/tcp' ptrfrll/nv-docker-trex:cuda11`

**nvidia-smi output on my Windows host:**

`Fri Mar  5 22:44:51 2021
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 465.42       Driver Version: 465.42       CUDA Version: 11.3     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce RTX 3090   WDDM  | 00000000:0B:00.0  On |                  N/A |
| 30%   29C    P5    41W / 255W |   2588MiB / 24576MiB |      1%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
REDACTED
+-----------------------------------------------------------------------------+`

**nvidia-smi output on my WSL 2.0 host:**

`Fri Mar  5 23:18:04 2021
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 465.00       Driver Version: 465.42       CUDA Version: 11.3     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce RTX 3090    Off  | 00000000:0B:00.0  On |                  N/A |
| 30%   29C    P8    37W / 255W |   3271MiB / 24576MiB |    ERR!      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+`

**uname -r output on my WSL 2.0 host:**

`5.4.91-microsoft-standard-WSL2`

**ls /dev/ on my WSL 2.0 host: (you can see dev/dxg is visible to the host and available to docker containers)**

`~$ ls /dev/
autofs           kmsg          mapper  ram11  ram8    sg3     tty13  tty23  tty33  tty43  tty53  tty63    vcsa
block            kvm           mem     ram12  ram9    shm     tty14  tty24  tty34  tty44  tty54  tty7     vcsa1
bsg              loop-control  net     ram13  random  stderr  tty15  tty25  tty35  tty45  tty55  tty8     vcsu
btrfs-control    loop0         null    ram14  rtc0    stdin   tty16  tty26  tty36  tty46  tty56  tty9     vcsu1
console          loop1         nvram   ram15  sda     stdout  tty17  tty27  tty37  tty47  tty57  ttyS0    vfio
cpu_dma_latency  loop2         ppp     ram2   sdb     tty     tty18  tty28  tty38  tty48  tty58  ttyS1    vhost-net
cuse             loop3         ptmx    ram3   sdc     tty0    tty19  tty29  tty39  tty49  tty59  ttyS2    vsock
dxg              loop4         pts     ram4   sdd     tty1    tty2   tty3   tty4   tty5   tty6   ttyS3    zero
fd               loop5         ram0    ram5   sg0     tty10   tty20  tty30  tty40  tty50  tty60  urandom
full             loop6         ram1    ram6   sg1     tty11   tty21  tty31  tty41  tty51  tty61  vcs
fuse             loop7         ram10   ram7   sg2     tty12   tty22  tty32  tty42  tty52  tty62  vcs1`

**Run commandof docker CUDA sample docker image:**

`docker run --gpus all -env NVIDIA_DISABLE_REQUIRE=1 nvcr.io/nvidia/k8s/cuda-sample:nbody nbody -gpu -benchmark`

**Output of running CUDA test docker image above showing that the GPU is visible on the docker container and working:**

`Run "nbody -benchmark [-numbodies=<numBodies>]" to measure performance.

-fullscreen (run n-body simulation in fullscreen mode)

-fp64 (use double precision floating point values for simulation)

-hostmem (stores simulation data in host memory)

-benchmark (run benchmark to measure performance)

-numbodies=<N> (number of bodies (>= 1) to run in simulation)

-device=<d> (where d=0,1,2.... for the CUDA device to use)

-numdevices=<i> (where i=(number of CUDA devices > 0) to use for simulation)

-compare (compares simulation results running once on the default GPU and once on the CPU)

-cpu (run n-body simulation on the CPU)

-tipsy=<file.bin> (load a tipsy model file for simulation)

NOTE: The CUDA Samples are not meant for performance measurements. Results may vary when GPU Boost is enabled.

> Windowed mode

> Simulation data stored in video memory

> Single precision floating point simulation

> 1 Devices used for simulation

GPU Device 0: "Ampere" with compute capability 8.6

> Compute 8.6 CUDA device: [GeForce RTX 3090]

83968 bodies, total time for 10 iterations: 102.474 ms

= 688.042 billion interactions per second

= 13760.845 single-precision GFLOP/s at 20 flops per interaction`

Any help appreciated!

**Comment by trexminer** [comment]
Could you please provide a console output for the following command: ls -lah /usr/lib/x86_64-linux-gnu/ | grep cuda

**Comment by ProfessorMadman** [comment]
Hi, I've reverted back to mining on my host OS for now whilst MS refines WSL 2.0.  There was a known bug where GPU was not passed properly to containers - [https://github.com/microsoft/WSL/issues/6617](https://github.com/microsoft/WSL/issues/6617).  This is resolved in [build 21332](https://blogs.windows.com/windows-insider/2021/03/10/announcing-windows-10-insider-preview-build-21332/) but I've not updated yet and will wait longer until the dev channel Insider build is more mature.

**Comment by stevekstevek** [comment]
I have the same problem (see issue #663).  I'd be happy to try to figure out what the problem is, but quite annoyingly the program has some anti-debugging stuff in it, so we can't easily do simple things like strace to see what files it's looking at.  

I suspect the issue is pretty simple -- using some non-standard technique to determine if the GPU is there that fails, using a different version of CUDA libraries than I have installed, or something like this.  WSL now works pretty well for GPU usage, and I can get other miners to work.

**Comment by joymon** [comment]
thanks @stevekstevek for the response. Fortunately, the lolMiner worked and went there. Following this thread so that I can use T-Rex later.

**Comment by stevekstevek** [comment]
how has lolMiner worked for you?  I can get it to work with eth (though very slow -- ~1.5Mh/s on my 3060 Ti LHR), but it doesn't work for ERGO.

**Comment by joymon** [comment]
@stevekstevek , nothing special. I tried one after another, T-rex then Pheonix, NBminer then lolMiner. Somehow lolMiner worked. But as you are experiencing the h/s is very low at 1.1Mh/s only

**Comment by byramses** [comment]
rtx 3060 lhr v2 lhr tune %73.5 ( 35 - 36 ) lerde idi normalde, bu sürücü ile trex 510.06 inanılmaz şekilde %75 te sabitlendi ( 37 -38 mh ) alıyorum artık ve bu değer stabil
