### ISSUE TITLE
t-rex 0.12.2

### ISSUE THREAD

**Issue by laudicina1011** [trexminer/T-Rex#27]
hi where can dowload the new version?

**Comment by Urgo** [comment]
I wasn't even aware there was a new version. But it looks like on July 7th this was posted on the T-Rex discord:

T-Rex 0.12.2 (BETA)

Add SSL support (e.g. look for SSL stratums at coinblockers pool
    https://veil.coinblockers.com/getting_started - stratum+ssl://veil-eu.coinblockers.com:4244
    https://rvn.coinblockers.com/getting_started - stratum+ssl://rvn-eu.coinblockers.com:4543)

Cosmetic changes and bug fixes:
* Miner restart automatically performed by the watchdog after an update no longer increases the WD restart counter
* Fix miner shutdown API command when invoked with watchdog enabled

Download
Windows:
CUDA 9.1: https://mega.nz/#!nBFnTQqA!vP-2AtOKETj9jOiyMwdvAgAMpn9DJ_KbYqYxdoRaS3g
CUDA 9.2: https://mega.nz/#!yEc3WS4T!mruqMQl1QgklSnrg3gH_C1DWFuIkOSG9B37IQXA7quE
CUDA 10.0: https://mega.nz/#!fYFlQarC!MVwo-W1kTBu9EWSTrPvUGqLHAGgGuZrCjs4JGhY3_RE

Linux:
CUDA 9.1: https://mega.nz/#!CUMTkYZB!56AmZTezr5GM27T9acszIyuw7ob8fwbA7Pknj7NN6Yg
CUDA 9.2: https://mega.nz/#!jZUBxa6R!NMnWVo6dLjw1FM4Yb4uwmqNcUNNI-aoj8y0CFgdvRco
CUDA 10.0: https://mega.nz/#!6FcR2CCY!uOz6AYtQs0925dH0-6i3lLsNUivvCN5Zzw0rPruL6Nw

**Comment by laudicina1011** [comment]
ok but is t aviable on github??
thanks for your answare!

**Comment by trexminer** [comment]
Updated github with 0.13.0

**Comment by laudicina1011** [comment]
ok thanks!!!
