### ISSUE TITLE
Display Hashrate drop half when monitor is power on

### ISSUE THREAD

**Issue by Gamelroid** [trexminer/T-Rex#274]
the miner shows my hashrate for 3060ti is 59.37MH/s when monitor is off
while ethermine shows range from 58 to 72MH/s

but when I turn on my monitor(which is running 3440x1440 60Hz. 
the miner shows hashrate drop to around 33 to 34MH/s
meanwhile sometimes ethermine shows keeping around 45 to 55MH/s, sometimes even drops to 30-40MH/s

> 20210308 21:26:27 GPU #0: Gigabyte RTX 3060 Ti - 58.25 MH/s, [T:54C, P:145W, F:64%, E:402kH/W], 1827/1827 R:0%
20210308 21:26:27 Shares/min: 1.324 (Avr. 0.756)
20210308 21:26:27 Uptime: 20 hours 58 mins 40 secs | Algo: ethash | T-Rex v0.19.11
20210308 21:26:27 WD: 1 day 16 hours 20 mins 39 secs, shares 1827/1827, restarts 1
20210308 21:26:27
20210308 21:26:33 ethash epoch: 399, block: 11998134, diff: 4.00 G
20210308 21:26:39 ethash epoch: 399, block: 11998135, diff: 4.00 G
20210308 21:26:41 [ OK ] 952/952 - 58.22 MH/s, 40ms ... GPU #0
20210308 21:26:53 ethash epoch: 399, block: 11998136, diff: 4.00 G
20210308 21:26:58
20210308 21:26:58 Mining at asia1.ethermine.org:4444, diff: 4.00 G
20210308 21:26:58 GPU #0: Gigabyte RTX 3060 Ti - 58.16 MH/s, [T:54C, P:145W, F:64%, E:401kH/W], 1828/1828 R:0%
20210308 21:26:58 Shares/min: 1.297 (Avr. 0.756)
20210308 21:26:58 Uptime: 20 hours 59 mins 10 secs | Algo: ethash | T-Rex v0.19.11
20210308 21:26:58 WD: 1 day 16 hours 21 mins 9 secs, shares 1828/1828, restarts 1
20210308 21:26:58
20210308 21:27:08 ethash epoch: 399, block: 11998137, diff: 4.00 G
20210308 21:27:14 [ OK ] 953/953 - 57.86 MH/s, 39ms ... GPU #0
20210308 21:27:19 ethash epoch: 399, block: 11998138, diff: 4.00 G
20210308 21:27:26 ethash epoch: 399, block: 11998139, diff: 4.00 G
20210308 21:27:28
20210308 21:27:28 Mining at asia1.ethermine.org:4444, diff: 4.00 G
20210308 21:27:28 GPU #0: Gigabyte RTX 3060 Ti - 58.02 MH/s, [T:54C, P:147W, F:64%, E:400kH/W], 1829/1829 R:0%
20210308 21:27:28 Shares/min: 1.329 (Avr. 0.757)
20210308 21:27:28 Uptime: 20 hours 59 mins 40 secs | Algo: ethash | T-Rex v0.19.11
20210308 21:27:28 WD: 1 day 16 hours 21 mins 39 secs, shares 1829/1829, restarts 1
20210308 21:27:28
20210308 21:27:29 ethash epoch: 399, block: 11998140, diff: 4.00 G
20210308 21:27:58
20210308 21:27:58 Mining at asia1.ethermine.org:4444, diff: 4.00 G
20210308 21:27:58 GPU #0: Gigabyte RTX 3060 Ti - 58.02 MH/s, [T:54C, P:145W, F:64%, E:400kH/W], 1829/1829 R:0%
20210308 21:27:58 Shares/min: 1.329 (Avr. 0.757)
20210308 21:27:58 Uptime: 21 hours 10 secs | Algo: ethash | T-Rex v0.19.11
20210308 21:27:58 WD: 1 day 16 hours 22 mins 9 secs, shares 1829/1829, restarts 1
20210308 21:27:58
20210308 21:28:04 [ OK ] 954/954 - 57.96 MH/s, 41ms ... GPU #0
20210308 21:28:09 ethash epoch: 399, block: 11998141, diff: 4.00 G
20210308 21:28:24 ethash epoch: 399, block: 11998142, diff: 4.00 G
20210308 21:28:28
20210308 21:28:28 Mining at asia1.ethermine.org:4444, diff: 4.00 G
20210308 21:28:28 GPU #0: Gigabyte RTX 3060 Ti - 57.96 MH/s, [T:54C, P:145W, F:64%, E:402kH/W], 1830/1830 R:0%
20210308 21:28:28 Shares/min: 1.318 (Avr. 0.757)
20210308 21:28:28 Uptime: 21 hours 40 secs | Algo: ethash | T-Rex v0.19.11
20210308 21:28:28 WD: 1 day 16 hours 22 mins 40 secs, shares 1830/1830, restarts 1
20210308 21:28:28
20210308 21:28:58
20210308 21:28:58 Mining at asia1.ethermine.org:4444, diff: 4.00 G
20210308 21:28:58 GPU #0: Gigabyte RTX 3060 Ti - 57.84 MH/s, [T:54C, P:147W, F:64%, E:399kH/W], 1830/1830 R:0%
20210308 21:28:58 Shares/min: 1.318 (Avr. 0.757)
20210308 21:28:58 Uptime: 21 hours 1 min 10 secs | Algo: ethash | T-Rex v0.19.11
20210308 21:28:58 WD: 1 day 16 hours 23 mins 10 secs, shares 1830/1830, restarts 1
20210308 21:28:58
20210308 21:29:06 ethash epoch: 399, block: 11998143, diff: 4.00 G
20210308 21:29:24 ethash epoch: 399, block: 11998144, diff: 4.00 G
20210308 21:29:28
20210308 21:29:28 Mining at asia1.ethermine.org:4444, diff: 4.00 G
20210308 21:29:28 GPU #0: Gigabyte RTX 3060 Ti - 49.14 MH/s, [T:54C, P:141W, F:64%, E:344kH/W], 1830/1830 R:0%
20210308 21:29:28 Shares/min: 1.318 (Avr. 0.757)
20210308 21:29:28 Uptime: 21 hours 1 min 40 secs | Algo: ethash | T-Rex v0.19.11
20210308 21:29:28 WD: 1 day 16 hours 23 mins 40 secs, shares 1830/1830, restarts 1
20210308 21:29:28
20210308 21:29:55 ethash epoch: 399, block: 11998145, diff: 4.00 G
20210308 21:29:58
20210308 21:29:58 Mining at asia1.ethermine.org:4444, diff: 4.00 G
20210308 21:29:58 GPU #0: Gigabyte RTX 3060 Ti - 38.37 MH/s, [T:55C, P:142W, F:64%, E:272kH/W], 1830/1830 R:0%
20210308 21:29:58 Shares/min: 1.318 (Avr. 0.757)
20210308 21:29:58 Uptime: 21 hours 2 mins 10 secs | Algo: ethash | T-Rex v0.19.11
20210308 21:29:58 WD: 1 day 16 hours 24 mins 10 secs, shares 1830/1830, restarts 1
20210308 21:29:58
20210308 21:30:08 ethash epoch: 399, block: 11998146, diff: 4.00 G
20210308 21:30:28
20210308 21:30:28 Mining at asia1.ethermine.org:4444, diff: 4.00 G
20210308 21:30:28 GPU #0: Gigabyte RTX 3060 Ti - 33.02 MH/s, [T:55C, P:142W, F:64%, E:234kH/W], 1830/1830 R:0%
20210308 21:30:28 Shares/min: 1.318 (Avr. 0.757)
20210308 21:30:28 Uptime: 21 hours 2 mins 41 secs | Algo: ethash | T-Rex v0.19.11
20210308 21:30:28 WD: 1 day 16 hours 24 mins 40 secs, shares 1830/1830, restarts 1
20210308 21:30:28
20210308 21:30:39 ethash epoch: 399, block: 11998147, diff: 4.00 G
20210308 21:30:43 ethash epoch: 399, block: 11998148, diff: 4.00 G
20210308 21:30:52 ethash epoch: 399, block: 11998149, diff: 4.00 G
20210308 21:30:55 ethash epoch: 399, block: 11998150, diff: 4.00 G
20210308 21:30:58
20210308 21:30:58 Mining at asia1.ethermine.org:4444, diff: 4.00 G
20210308 21:30:58 GPU #0: Gigabyte RTX 3060 Ti - 32.89 MH/s, [T:54C, P:141W, F:64%, E:233kH/W], 1830/1830 R:0%
20210308 21:30:58 Shares/min: 1.318 (Avr. 0.757)
20210308 21:30:58 Uptime: 21 hours 3 mins 11 secs | Algo: ethash | T-Rex v0.19.11
20210308 21:30:58 WD: 1 day 16 hours 25 mins 10 secs, shares 1830/1830, restarts 1
20210308 21:30:58
20210308 21:31:22 ethash epoch: 399, block: 11998151, diff: 4.00 G
20210308 21:31:28
20210308 21:31:28 Mining at asia1.ethermine.org:4444, diff: 4.00 G
20210308 21:31:28 GPU #0: Gigabyte RTX 3060 Ti - 33.01 MH/s, [T:54C, P:141W, F:64%, E:234kH/W], 1830/1830 R:0%
20210308 21:31:28 Shares/min: 1.318 (Avr. 0.757)
20210308 21:31:28 Uptime: 21 hours 3 mins 41 secs | Algo: ethash | T-Rex v0.19.11
20210308 21:31:28 WD: 1 day 16 hours 25 mins 40 secs, shares 1830/1830, restarts 1
20210308 21:31:28
20210308 21:31:29 ethash epoch: 399, block: 11998152, diff: 4.00 G
20210308 21:31:42 ethash epoch: 399, block: 11998153, diff: 4.00 G
20210308 21:31:47 ethash epoch: 399, block: 11998154, diff: 4.00 G
20210308 21:31:58
20210308 21:31:58 Mining at asia1.ethermine.org:4444, diff: 4.00 G
20210308 21:31:58 GPU #0: Gigabyte RTX 3060 Ti - 32.96 MH/s, [T:54C, P:141W, F:64%, E:234kH/W], 1830/1830 R:0%

**Comment by aet08** [comment]
Might be related to NVIDIA Crippling 3060/ti cards, not your monitor
[](https://www.pcworld.com/article/3608370/nvidia-nerfs-rtx-3060-mining-ahead-of-launch-but-dont-expect-miracles.html)

**Comment by Gamelroid** [comment]
> This is related to NVIDIA Crippling 3060/ti cards, not your monitor status.
> https://www.pcworld.com/article/3608370/nvidia-nerfs-rtx-3060-mining-ahead-of-launch-but-dont-expect-miracles.html
> 
> “RTX 3060 software drivers are designed to detect specific attributes of the Ethereum cryptocurrency mining algorithm, and limit the hash rate, or cryptocurrency mining efficiency, by around 50 percent,”

3060 and 3060ti are two different cards

**Comment by Gamelroid** [comment]
I think I found the issue, if I shut down wallpaper engine, hashrate will go back up again
