### ISSUE TITLE
GTX 1080 with Cuda 11 version consistently ending after 2 minutes. ==> Bad Power Supply PSU

### ISSUE THREAD

**Issue by tseanard** [trexminer/T-Rex#281]
I started using T-Rex (CUDA 11 version) Dr ownloaded yesterday for Eth on ethermine with a GTX 1080.  I get about two minutes of mining, and T-Rex closes without any visible error or issue.  I added a loop to the batch file to keep restarting it, but with the time it takes to start mining again, I am losing 20-30% of my mining potential.  I suggest tried the --keep-gpu-busy and --no-watchdog command line options.  What do I need to do/tune to keep this running consistently?  Once I can do that I am considering installing a water cooling block (that I already have) and overclocking, but need to make sure the apps are stable before I sink a bunch of time into it...

**Comment by trexminer** [comment]
Could you please run the miner with `--log-path trex.log` parameter and upload the log file so that we can troubleshoot the issue? Thanks.

**Comment by tseanard** [comment]
[trex-[1615468692].log](https://github.com/trexminer/T-Rex/files/6123234/trex-.1615468692.log)
[trex-[1615468843].log](https://github.com/trexminer/T-Rex/files/6123235/trex-.1615468843.log)
[trex-[1615468995].log](https://github.com/trexminer/T-Rex/files/6123236/trex-.1615468995.log)

**Comment by tseanard** [comment]
Logs in previous comment, script here (wallet ID obscured here, but it is mining into the wallet)

C:
cd C:\_Mining\t-rex-0.19.11-win-cuda11.1\
:START
t-rex.exe -a ethash -o stratum+tcp://us1.ethermine.org:4444 -u **** -w rig0 -i 25 --keep-gpu-busy --no-watchdog --log-path trex.log
goto START
pause

**Comment by tseanard** [comment]
![image](https://user-images.githubusercontent.com/3173923/110840389-a9b49980-8272-11eb-9744-7645c55e5edf.png)

**Comment by DejanRibnikar** [comment]
I believe it's overheating.

**Comment by tseanard** [comment]
I bumped up the fan profile to test that (which brought it down to an operating temp low 60s), and the issue persisted

**Comment by tseanard** [comment]
I have sorted this one out - it seems that my PSU (1000W, 6yrs old) is on it's last legs.  Assuming ~10% degradation per year, I am effectively at a 590W PSU, which doesn't even cover the baseline power needs of the system (let along everything being overclocked).  It has been doing other weird things lately as well, which in hindsight are fully in line with an aging power supply. 
 New PSU is on the way.
