### ISSUE TITLE
Inavalid Proof of work, RTX 2080

### ISSUE THREAD

**Issue by LachlanMcWilliam** [trexminer/T-Rex#285]
Similar issues: #282 #217 

Build is: 0.19.11 Cuda 10.0
Output is as follows:
[FAIL] 0/15 - Provided PoW solution is invalid!, 28ms ... GPU #0
GPU #0: Gigabyte RTX 2080 - 36.37 MH/s, [T:64C, P:159W, F:52%, E:229kH/W], 0/13 R:100%

Tried specifying `--dag-build-mode 1` but it seems to have done nothing. I am really new to this so I have likely done something tremendously stupid lol.

**Comment by trexminer** [comment]
Could you post the entire log please? You may be mining the wrong algorithm.

**Comment by LachlanMcWilliam** [comment]
I was running the ETC .bat file rather than the ETH so I was correct about the stupid part
