### ISSUE TITLE
admin pls delete: ethminer: 0.0H/s no memory, removing files, then T-Rex works

### ISSUE THREAD

**Issue by lassanmondom** [trexminer/T-Rex#286]
Hello Guys! New here, new to Linux.

I have: Ubuntu 20.04, nVidia driver 460, cuda 11
My card:
![2021-03-12_17-19](https://user-images.githubusercontent.com/79266942/110974722-1efd9880-835f-11eb-9af9-633816511e7f.png)

Can you tell me whether I did it right? Tried to install ethminer many times but unsuccessfully, said memory was unsufficient, my pc was extremely slow and 0.0H/s. It said:

"WARN: GPU #0: not enough memory to hold the full DAG for epoch 400.20210312 WARN: GPU #0: effective hashrate will be ~0.0% of its usual value"

![2021-03-12_17-20](https://user-images.githubusercontent.com/79266942/110974625-02616080-835f-11eb-8958-07488acdf5df.png)
As you can see on the pic, the memory is busy. Not this time but before I realized nvidia-smi showed ethminer job too.

I did nautilus command and manually deleted all "ethminer" files and "geth" too, cause I tried that before as well.

Reinstalled nvidia (460 and cuda 11 again), downloaded t-rex from Github and now it works:
![Screenshot from 2021-03-12 18-20-40](https://user-images.githubusercontent.com/79266942/110975212-bd89f980-835f-11eb-9722-4891aa6ab2fd.png)

**Comment by trexminer** [comment]
I don't quite understand what the issue is in relation to T-Rex. Could you clarify?

**Comment by lassanmondom** [comment]
> I don't quite understand what the issue is in relation to T-Rex. Could you clarify?

You're right it's a dumb post
