### ISSUE TITLE
[Feature Request] Report hashrate separatly for each CUDA devices

### ISSUE THREAD

**Issue by Novivy** [trexminer/T-Rex#291]
If you use the option -d 0,1,2,3,4,5 it will use all theses GPU to mine but will only report the gobal hashrate.

It would be great to report the hasrate individually for each gpu (with a name for each of them that we would define).

So we don't have to run a TREX separate instance for each gpu to get details on the pool.

**Comment by trexminer** [comment]
Unless you've messed up with the settings, the miner prints out the hashrate summary including per-GPU stats every 30s or so

**Comment by Novivy** [comment]
@trexminer Yeah but the reported hashrate to the POOL will only be the global one. I would like that each GPU report it's hashrate independantly to the POOL, so i can see my worker. And this without having to run separate instance of T-REX

For example look at the bottom of this page: https://ethermine.org/miners/26fb06C0e53c46Aa8b72219a60f52408e52B3F5F/dashboard

**Comment by trexminer** [comment]
I see what you mean.
That's how it's done by any mining software out there and how pools handle it. Reporting each GPU's hashrate to the pool individually would require establishing as many connections to the pool as there are GPUs in a rig, which is pretty much equivalent to running multiple instances.

**Comment by Novivy** [comment]
Ok it makes sense, thanks
