### ISSUE TITLE
can't initialize T-rex error

### ISSUE THREAD

**Issue by dracosc22679** [trexminer/T-Rex#299]
Hi. I have 2 rigs using same totally same configurations. PSU,CPU,Motherboard,miner etc (simplemining OS)
My second rig is working perfectly. On first rig, when miner is starting, takes too much time (over 2 minutes), and most of the time i get the following error and then restarts miner 2-3 times until it works. Error is : WARNING: WATCHDOG: can't initialize T-Rex, assign: Bad file descriptor.
/root/xminer.sh: line 183: 22327 Killed

Have tried to reflash OS and changed hard disk too. Tried to remove overclocking, tried simple miner settings, but still problem is only on the first rig.
Miner used is 19.11Cuda11.1. Also tried 19.9Cuda11.1 and 19.10Cuda11.1
If i use Cuda10 versions, i don't get the above error, but still takes too much time to start the miner!
Any help please?

**Comment by trexminer** [comment]
Hi. Please, try to use 0.19.12 and post your results.

**Comment by dracosc22679** [comment]
Just updated to 19.12 and problem is resolved! Thanks.

**Comment by zhanko73** [comment]
20220317 09:02:01 ERROR: WATCHDOG: can't initialize T-Rex, assign: Bad file descriptor
Killed

**Comment by zhanko73** [comment]
0.25.8 still do this now:
20220317 11:26:05 ERROR: WATCHDOG: can't initialize T-Rex, assign: Bad file descriptor
Killed
