### ISSUE TITLE
how to start?

### ISSUE THREAD

**Issue by ichiungchang** [trexminer/T-Rex#3]
how do i run it, is there a start.bat file?

**Comment by thaistar** [comment]
Linux command line: ~/t-rex/t-rex -a x16r -o stratum+tcp://mine.nlpool.nl:9916 -u 14Bt2RmmSm9WaYm2WDg87gojdyQv5hycgD -p Rig-03

**Comment by trexminer** [comment]
Thanks thaistar. There are also a few bat files in the miner archive, along with the help txt file.
