### ISSUE TITLE
T-Rex not working with mining CFX on HiveOS

### ISSUE THREAD

**Issue by ILOVEYOUNA** [trexminer/T-Rex#301]
T-Rex not working with mining CFX on HiveOS

Hashrate = 0

**Comment by trexminer** [comment]
Please, provide more info. Attach logs from the very beginning of the mining process.

**Comment by ILOVEYOUNA** [comment]
https://ibb.co/S6r8FY5
https://ibb.co/7kC6YD3

these photos.

**Comment by ILOVEYOUNA** [comment]
Fixed by change port to Stratum port

@trexminer may I know how to add config for the SSL port?

**Comment by trexminer** [comment]
You'd need to change `stratum+tcp` to `stratum+ssl`, and you are also going to have to add `--no-strict-ssl` if it still fails.
