### ISSUE TITLE
ID=0, GPU=0, Cuda exception in [mtpcommon::allocate_extra_memory,45], out of memory

### ISSUE THREAD

**Issue by k0ak0a** [trexminer/T-Rex#304]
Hey Legends, would someone please advise on the error below, thanks 
I'm running GTX 1650 ti - 16gb ram - windows10 64bit - 100g virtual memory

![image](https://user-images.githubusercontent.com/80809458/111424283-a70be580-8745-11eb-94ce-2e46f17fe1dd.png)

**Comment by trexminer** [comment]
Hi. You need more than 4Gb of VRAM to mine MTP. In other words, 1650ti cannot mine MTP.
