### ISSUE TITLE
Per-GPU accepted/rejected shares

### ISSUE THREAD

**Issue by o2genum** [trexminer/T-Rex#31]
Could you add reporting per-device accepted and rejected shares in the `/summary` API?

This is useful for diagnosing which GPU is responsible for the rejected shares.

**Comment by trexminer** [comment]
We could implement it.
What kind of share rejects are you looking to track? If it's "invalid job id" or other "stale share" type of rejects, I don't see any use for it as those rejects are caused by network latency.

**Comment by o2genum** [comment]
I'm looking forward to integrating T-Rex into automated mining software.

What I want to do:
1. I want to detect large percentage of rejected shares to warn the user. I can do this already with the current API.
2. People typically overclock too much. I want to point out the exact GPUs which have too many rejected shares.

So this data would be enough: _аccepted shares, rejected shares_ - per GPU. I think any "not accepted" shares can go under "rejected" in the API. The exact reason for rejection (stale/invalid job id) could be logged to stdout and log.

**Comment by trexminer** [comment]
"Stale/invalid job id" shares are not caused by overclocked cards, they are usually caused by network issues / high latency, so I don't really see a point in collecting "rejects per GPU" stats.

**Comment by o2genum** [comment]
Coarse and not always useful stats, but it's generally convenient to have at least `total_shares` and `accepted_shares` fields per GPU.

For monitoring tools, this is per-gpu "health status" info that is easy to display to the user. The user can then open the log to see what exactly is happening.

I could read the same info from the log (less convenient, as logs are not pre-documented), but it's still doesn't show the responsible GPU, or does it?

**Comment by trexminer** [comment]
Added reporting per-device accepted and rejected shares in the /summary API. For usage look at readme file enclosed into miner archive. Also, in console and trex web page you will find rejected shares statistics output.

**Comment by McCalm** [comment]
That is not correct. I have tested it with a "normal" and "overclocked" GPU.

--> GTX 1060 GPU --> ...8ms --> share OK; never have had a fatal share.
--> GTX 1070 EX GPU --> ...8ms --> FATAL SHARE; not OK and this with ALL shares.

So, here is definitely a problem in T-REX in use with factory overclocked cards. So I can agree with this repord and info from "o2gemum".

P.S: Also this problem in T-Tex-0.19.10-win-cuda 11.1

Greetings.

**Comment by trexminer** [comment]
Hi @McCalm What exactly "is not correct"? Accepted/Rejected shares stats per-GPU report is already implemented.

**Comment by McCalm** [comment]
Hello,

I think you misunderstood my message. I meant that apparently shares that are overclocked via graphics cards by the manufacturer are not being correctly transmitted. After my tests, I found that all my GPUs work properly with your program and have no problems finding shares and transmitting them promptly. Only a single GPU, which I use and overclocked by the manufacturer, transmits all shares with your program in the same pool with the server response: "Not accepted, faulty". I don't think it's a hardware problem, the same GPU works flawlessly via other programs in different pools. The problem only exists with T-REX.

Greetings...

________________________________
Von: trexminer <notifications@github.com>
Gesendet: Montag, 8. Februar 2021 01:34
An: trexminer/T-Rex <T-Rex@noreply.github.com>
Cc: McCalm <mccalm@outlook.de>; Mention <mention@noreply.github.com>
Betreff: Re: [trexminer/T-Rex] Per-GPU accepted/rejected shares (#31)


Hi @McCalm<https://github.com/McCalm> What exactly "is not correct"? Accepted/Rejected shares stats per-GPU report is already implemented.

**Comment by oo777** [comment]
Cheers! I had one GPU responsible for all the rejected shares. I could identify and fix it now!
