### ISSUE TITLE
t-rex unable to start mining

### ISSUE THREAD

**Issue by Ryxwaer** [trexminer/T-Rex#316]
Today I woke up and started t-rex. After a few minutes it stopped working. I tought that it was caused by me updating the manjaro. I tryed downgrading packages and later reinstaling my manjaro kde to manjaro xfce. Nothing changed. I have nvidia 1070 with proprietary drivers. I tryed other miners and PhoenixMiner is working pretty good.
I was trying to mine on niceHash with command:
`./t-rex -a ethash -o stratum+tcp://daggerhashimoto.eu-west.nicehash.com:3353 -u 3KpMphop6m1NxhXC1PCdWNftmosXnH5KAy`
and also on ethermine at the screenshot:
![image](https://user-images.githubusercontent.com/58151625/111787662-7e0f6000-88bf-11eb-8cdb-afa6d6f5eb8e.png)

I am looking forward to hearing from you.
and sorry for my bad english ;)

**Comment by Ryxwaer** [comment]
error message: 
TREX: eyJhIjoiY0s2Vy9tM2d1OTgvbVBtVmc4enBZRiswUHpxREVqV1FTRFdOVUVDaUgxSVpJa0xVaTBiN3IwRHQxZENkakpybnM3aXcxMU81RkorS0IrUDdFaFlhdFhXNFVsRXdoMTJnbjl5dmxFYWR5ZmM9IiwiYiI6Ilh3WkxMNHNmdU8xVngxeHNBOFBmQUE9PSJ9Cg==

**Comment by BeMacized** [comment]
Running into the same issue here, same error message.

**Comment by pc-2198x** [comment]
See #296 , has working test builds for this issue CUDA 10 and 11.

**Comment by Ryxwaer** [comment]
t-rex-0.19.12-linux-cuda10.0 fixed the issue for me.
Thanks
