### ISSUE TITLE
Strange high Hash rates numbers.

### ISSUE THREAD

**Issue by MuhammedAbdelftah** [trexminer/T-Rex#318]
I have been getting higher hash rates from my two GPUs, previously I can get 60 Mh from my RTX 3070 after applying +1200 to the memory clock but now when I start without applying any OC to the memory I get 60 Mh and if I apply OC to the memory +1000 I get 70Mh the same applies to my GTX 1060, it seems like I got a wired boost in performance from each of my cards is there is something am missing.
![1](https://user-images.githubusercontent.com/46532944/111802208-68596500-88d6-11eb-8723-bf882e43ee4e.PNG)

also, I can't OC the memory of the RTX 3070 like before without the miner restarting every 10 to 15 mins and recovering again giving errors like Clock screw up!
![9](https://user-images.githubusercontent.com/46532944/111808209-74e0bc00-88dc-11eb-9591-8e75506da362.PNG)

**Comment by pdieppa** [comment]
What does the pool say about the actual hash rate? I also encountered a higher stale and invalid shares using the latest version. I picked 0.19.10.Cuda111 and seems to have fixed the issue. I have only (3) 3060Ti, the rest are AMD 5700XT which run a different miner. It's been 5 1/2 hours since the switch and I see 0 stale or invalid shares.

**Comment by MuhammedAbdelftah** [comment]
the pool reports the same numbers as the miner and the stall shares are the same as before
![fhg](https://user-images.githubusercontent.com/46532944/111815348-39e28680-88e4-11eb-9e93-f5e6811a89c9.PNG)
but i keep getting this error and the miner restarts "Clock screwed up!"

**Comment by pdieppa** [comment]
I would leave it alone. You gained 10mh/s without overclocking. Ha ha ha.
The true test is to let it run for 24 hours to see what the average rate is.  I may have to start buying 3070s instead of 3060Tis!

**Comment by MuhammedAbdelftah** [comment]
ya, I do not know what is happening really but I think it is not stable it keeps crashing the miner and it restarts randomly with the error "Clock screwed up!'' every approximately one hour or so

**Comment by pdieppa** [comment]
Is it crashing with no OC? I would limit the power only and leave the core and memory alone to see how the miner runs!

**Comment by trexminer** [comment]
Apparently you've got a really unstable system clock - that's what "Clock screw up" error tells us, the clock jumps forwards by too much or goes backwards occasionally as a result of time synchronisation, and that may be a cause of the incorrect hashrate measurements. The miner also relies on the system clock when calculating time slots for the dev fee, so clock shifts can be dangerous, and to avoid unexpectedly long dev fee sessions the miner restarts itself.

**Comment by chengziorg** [comment]
> I have been getting higher hash rates from my two GPUs, previously I can get 60 Mh from my RTX 3070 after applying +1200 to the memory clock but now when I start without applying any OC to the memory I get 60 Mh and if I apply OC to the memory +1000 I get 70Mh the same applies to my GTX 1060, it seems like I got a wired boost in performance from each of my cards is there is something am missing.
> ![1](https://user-images.githubusercontent.com/46532944/111802208-68596500-88d6-11eb-8723-bf882e43ee4e.PNG)
> 
> also, I can't OC the memory of the RTX 3070 like before without the miner restarting every 10 to 15 mins and recovering again giving errors like Clock screw up!
> ![9](https://user-images.githubusercontent.com/46532944/111808209-74e0bc00-88dc-11eb-9591-8e75506da362.PNG)

So, is your problem solved?    I also encountered this error "Clock screwed up!'' recently.  I thought my graphics card was screwed up, that's terrible.
![Uploading 微信图片_20210404202554.jpg…]()

**Comment by trexminer** [comment]
This should be fixed in 0.20.4+
