### ISSUE TITLE
Unable to get CUDA count.

### ISSUE THREAD

**Issue by PrinceOfParallax** [trexminer/T-Rex#32]
Keep getting this error on my card. what can I do to fix it? card is a little older (2012) but strong Quadro

**Comment by trexminer** [comment]
What's the model of your card? I guess it's simply too old. T-Rex supports CC 5.0 and above https://developer.nvidia.com/cuda-gpus

**Comment by PrinceOfParallax** [comment]
Quadro 7000 I think its stuck with CC 3.0, so no dice. Its a Fermi card, but is still is a beast for its day.

**Comment by cannonballdex** [comment]
Any time I have encountered this error, updating the Nvidia driver software has fixed this.
