### ISSUE TITLE
Miner shuts down immediately after opening

### ISSUE THREAD

**Issue by KawaKode** [trexminer/T-Rex#326]
Hello,

I recently updated my arch install and cuda too. The version of Cuda that's running is 11.2.2-1. Since that, trex doesn't run correctly anymore. (I have a GTX 1070 that is in very good shape BTW)
Here's what's happening, and I cant figure out what's wrong with TRex here : 
![Capture d'écran Deepin_zone de sélection _20210320135005](https://user-images.githubusercontent.com/75862028/111870155-4f5abd80-8983-11eb-9657-30cadd8ef20e.png)

I have the same issue with the TRex 0.19.11 release (which was working great before the update to cuda)

**Comment by KawaKode** [comment]
I ran both version one after the other to see if there was any changes, but the same behavior crops up.

**Comment by pc-2198x** [comment]
See #296 , has working test builds for this issue CUDA 10 and 11.

**Comment by KawaKode** [comment]
Thanks ! It works perfectly now !

**Comment by KawaKode** [comment]
Issue resolved
