### ISSUE TITLE
How to use different GPU devices for different mining

### ISSUE THREAD

**Issue by William8Work** [trexminer/T-Rex#328]
Could you please help me to understand how to use the --devices flag to specify which GPU to use when mining eth?

1). Should it be `--devices=0 `if want to use the first GPU device, and `devices=1` to use second one, etc?
2). If there are multiple GPUs in a machine, could it run multiple concurrent t-rex processes to assign one gpu per t-rex process?

Thank you!!

**Comment by trexminer** [comment]
1. `--devices 0` and `--devices 1`, yes.
2. Yes, run as many t-rex instances as you need, specifying `--devices` accordingly

**Comment by William8Work** [comment]
Thanks @trexminer. Super helpful.

I have a 3090 GPU which has 24GB ram. Running an t-rex consumes only 4GB with about 100-110MH/s hashrate for eth. Is it possible to run another instance of t-rex?

If not, could I run a concurrent t-rex on the same machine for RVN or another coin since the machine has good CPU and RAM?

**Comment by trexminer** [comment]
Whilst it only consumes 4GB of VRAM, T-Rex uses almost 100% of the memory bandwidth your GPU provides, so you won't be able to run another instance in parallel without significantly reducing your hashrate. In theory it is possible to mine something that doesn't use memory much but I can't think of any coin with core-intensive algorithm whose network isn't flooded by FPGAs and ASICs.

**Comment by William8Work** [comment]
Got it. thanks again!
