### ISSUE TITLE
Support for –cuda-streams	–cuda-block-size	–cuda-grid-size

### ISSUE THREAD

**Issue by pschroedl** [trexminer/T-Rex#334]
Has anyone looked into, or planning to support settings the number of cuda-streams, cuda-block-size, and cuda-grid-size like ethereum-mining/ethminer does?  Being able to tune these would allow for better parallelization of t-rex with other tasks, such as video transcoding.

**Comment by trexminer** [comment]
You can use `--intensity`, it control the grid size. There's no way change the block size as usually it's implementation dependent.
