### ISSUE TITLE
1 GPU showing 100% Provided PoW Solution is Invalid

### ISSUE THREAD

**Issue by sturbodoir** [trexminer/T-Rex#337]
HI Dev, would need your help to solve the issue, where my rig has been running for 5 Days, and suddenly 1 GPU of ASUS 1660 Super started having rejected share. I've rebooted and it stills at 100% rejected share 0/11 for 30 minutes of uptime.

TrexMiner version v.0.19.12 on HiveOS

**Comment by yorkjr2** [comment]
Have you resolved this yet?  I am having a similar issue with one of my GPUs (EVGA RTX 3070) now getting the PoW Solution Invalid error.  I've been looking for some help to get this resolved.

**Comment by sturbodoir** [comment]
> Have you resolved this yet? I am having a similar issue with one of my GPUs (EVGA RTX 3070) now getting the PoW Solution Invalid error. I've been looking for some help to get this resolved.

I’ve found that, turns out the card with 100% rejected share was broken. When i plugged it in to my main PC, It shows artifacts, probably because of bad memory OC. 
But my case was 100% rejected shares literally, 0 out of 50 shares accepted.

**Comment by sturbodoir** [comment]
> Have you resolved this yet? I am having a similar issue with one of my GPUs (EVGA RTX 3070) now getting the PoW Solution Invalid error. I've been looking for some help to get this resolved.

Are yours also fully rejected?? Or only some??
I suggest lowering the OC, or try other version of the miner.

**Comment by yorkjr2** [comment]
I am only getting some rejects for PoW Solution Invalid.  At this moment I have 578 shares found and 4 rejected with that error.  This one RTX 3070 is new so I just added it to my rig last night.  None of my other cards have this issue.

**Comment by yorkjr2** [comment]
I am not sure how to run a different version of the miner.  I am on HiveOS and the TRex miner version is 0.19.12.  Honestly I have no idea how to upgrade it or downgrade it.

**Comment by sturbodoir** [comment]
> I am only getting some rejects for PoW Solution Invalid. At this moment I have 578 shares found and 4 rejected with that error. This one RTX 3070 is new so I just added it to my rig last night. None of my other cards have this issue.

ahh, perhaps for that, you can try lowering your OC setting bit by bit, to see which is most stable settings. because if you got high hashrate with quite a lot of rejected, the hashrate doesn't really matter anyway. 

My current 3070 is running with 62.33 MH/s, got 2 rejected out of 1420 shares, which I still deemed okay. Zotac RTX 3070 Holo Amp, Samsung memory Core Clock 0, Memory Clock +2600, PL 125 Watts.

**Comment by sturbodoir** [comment]
> I am not sure how to run a different version of the miner. I am on HiveOS and the TRex miner version is 0.19.12. Honestly I have no idea how to upgrade it or downgrade it.

you can tweak and change for the different miner from the flight sheet. there's option when you click to edit your current online flight sheet, "setup miner config", it will show the miner settings and version. but I suggest try lowering the OC first before changing the miner haha, I don't want to mess with the whole rig just because of 1 card.

**Comment by yorkjr2** [comment]
This ring has 4 cards in it.  2- 3060 ti and 2- 3070.  I have all of the cards set to 2650 memory, 0 core and 125W (1 3060 ti is at 130W).  The 3060 ti cards are getting 62.17 and 62.63 mh/s and the 3070s are getting 62.50 and 62.53 mh/s.  I can lower the memory clock on the one 3070 with the rejects I suppose.  It just seemed strange that only the one card was having the issue while using the same settings as the other cards. Dang Silicon Lottery, smh!

**Comment by yorkjr2** [comment]
Of course I meant rig and not ring lol
That being said I have found where others have had similar issues with just one card on a rig and ultimately ran trex version 0.19.11.  This ended up clearing up their issues so I decided to down grade my version to this one to see how it runs.  I will update after some time goes by as to if this works for me or not.

**Comment by sturbodoir** [comment]
> Of course I meant rig and not ring lol
> That being said I have found where others have had similar issues with just one card on a rig and ultimately ran trex version 0.19.11. This ended up clearing up their issues so I decided to down grade my version to this one to see how it runs. I will update after some time goes by as to if this works for me or not.

hahaa dang nice rig lineup, mine got 6x 1660Super, 1x 3070 and 1x 2070 Super. can't get hold of 3070, too expensive and not worth it already. scalper's price everywhere.

Well good to hear you've found the issue! update on how its doing haha just don't meddle with the settings that affect the whole rig if you're not sure.

All the best bro!

**Comment by yorkjr2** [comment]
After 2 hrs of uptime now, this 3070 has found 113 shares.  The 114th share was rejected with the PoW invalid error again.  I will now adjust the memory clock down a little bit to see if that makes a difference.

**Comment by yorkjr2** [comment]
Ok, so fast forward a few hours... I decreased my memory clock from 2650 to 2625. I now have 1098 found shares and still only the one rejected shares.  I have run the card for about 3 hours since changing the memory clock setting so I feel pretty comfortable saying that decreasing the memory clock has corrected my issue.  Thanks for the advice and happy mining!
***issue resolved***

**Comment by sturbodoir** [comment]
> Ok, so fast forward a few hours... I decreased my memory clock from 2650 to 2625. I now have 1098 found shares and still only the one rejected shares. I have run the card for about 3 hours since changing the memory clock setting so I feel pretty comfortable saying that decreasing the memory clock has corrected my issue. Thanks for the advice and happy mining!
> _**issue resolved**_

Nicee! Keep it that way, well i’m aiming for no rejected for my 3070, but the threshold is always 0.2% rejected for my 3070 card. 
I’m gonna close this thread as its already resolved! Good to have you share your update here. Thank you and happy mining!
