### ISSUE TITLE
RavenCoin hardfork

### ISSUE THREAD

**Issue by o2genum** [trexminer/T-Rex#34]
RVN is switching to the new x16rV2 algo on October, 1.

https://coindar.org/en/event/ravencoin-rvn-hard-fork-23616

Do you plan on supporting it?

**Comment by trexminer** [comment]
Yes, a beta version with x16rv2 support is available in our Discord server (#download-links channel)

**Comment by sihuoyu** [comment]
> 是的 ， 一个 beta 版本提供支持与 x16rv2 挑拨我们服务器下载链接信道 (#)

Where can I download it?

**Comment by sihuoyu** [comment]
> Yes, a beta version with x16rv2 support is available in our Discord server (#download-links channel)

Where can I download it?

**Comment by o2genum** [comment]
@trexminer Is there an ETA for the new miner release? I'm integrating the miner into automated software, so the earlier, the more users will be able to update in time.

**Comment by leshacat** [comment]
DOWNLOAD ON T-REX DISCORD SERVER - #download-links

**Comment by sihuoyu** [comment]
> > > Yes, a beta version with x16rv2 support is available in our Discord server (#download-links channel)
> > 
> > 
> > Where can I download it?
> 
> **DOWNLOAD BETA ON T-REX DISCORD SERVER** - #download-links channel
> 
I am Chinese, do not know download-links channe is where! Can you send me the website address? Thank you very much!

**Comment by trexminer** [comment]
Released https://github.com/trexminer/T-Rex/releases/tag/0.14.4
