### ISSUE TITLE
Problen with T-Rex 

### ISSUE THREAD

**Issue by AdaHorus** [trexminer/T-Rex#340]
I recently downloaded T-Rex to start mining and I have this problem that you see in the image:
![Archivo_000](https://user-images.githubusercontent.com/80793461/112545877-7ce6a300-8d97-11eb-9b11-d3c4d802ba04.jpeg)

I hope you can help me because I have not found a solution on the web

bests regards

**Comment by jomual0** [comment]
Hola,
You must execute .bat file instead of t-rex.exe directly. Inside file .bat you must put all data related to your pool, coin, wallet, rig name ... etc.
Regards,

**Comment by jomual0** [comment]
Hi,
Check "antivirus" as well, you must permit t-rex program as an exception.
Regards,

**Comment by pdieppa** [comment]
jomual0 is correct. Looks like your antivirus blocked the file as most miners are flagged as malware and blocked by default.
