### ISSUE TITLE
RTX 3070 - Started to show LOW Hashrate 1 day ago. (36MH/s) / Detail info provided.

### ISSUE THREAD

**Issue by jeankcr** [trexminer/T-Rex#342]
Hi, I've been mining with a 3070 for a couple of weeks now, and I was getting around 57MH/s but from yesterday it started to show a low number (45's), I restarted the t-rex when that happen and it went back to normal, **but** it now started to go lower as **36-34 and it just doesn't want to go up**.

Nvidia driver version:
![image](https://user-images.githubusercontent.com/25378874/112630539-55c1bd00-8dfb-11eb-8954-61a540af45a1.png)

Bat file:
`t-rex.exe -d 0 -a ethash -o stratum+tcp://us1.ethermine.org:4444 -u 0x0A55Cfe34d045e8ceE7F2133a614104917E794d9 -p x -w Vision
pause`

Console hashrate:
![image](https://user-images.githubusercontent.com/25378874/112630725-9de0df80-8dfb-11eb-9e83-b5af2ccd3732.png)

Starting of the script:
![image](https://user-images.githubusercontent.com/25378874/112630836-c7017000-8dfb-11eb-88ca-ac58c290253e.png)

MSI Afterburner settings (these provided me 57MH/s a few days ago)
![image](https://user-images.githubusercontent.com/25378874/112631162-26f81680-8dfc-11eb-89e6-9c033dfd1197.png)

I could give you more information just let me know,
Please help.

**Comment by jeankcr** [comment]
I made a test as well using nanopool and same low hashrate is shown:
![image](https://user-images.githubusercontent.com/25378874/112631855-08dee600-8dfd-11eb-90b6-695ba25a31d6.png)

**Comment by dedizones** [comment]
Try PL 62% ? (powerlimit => 62 for 124/125w

**Comment by jeankcr** [comment]
The problem was, that I was watching a broadcast on chrome. Disable the Hardware Acceleration on Chrome fix the issue.
