### ISSUE TITLE
Incorrect GPU power usage reported

### ISSUE THREAD

**Issue by rawbar** [trexminer/T-Rex#343]
I added a 3080 to an existing HiveOS rig.  Tweaking OC settings, T-REX reports my 3080 is hashing at ~98MH using only 180W which is way too good to be true.    My Kasa power meter the PSU is plugged into reports that adding the 3080 is consuming an additional 280W.

I've tried restarting the miner and rebooting and T-REX consistently is reporting 180W usage.  

This is for a MSI 3080 Ventus 3x.  Other 2 cards on the machine seem to be reporting a reasonable wattage.

![image](https://user-images.githubusercontent.com/3464225/112636080-fa032e00-8e12-11eb-8060-49536b357438.png)

**Comment by trexminer** [comment]
The miner displays NVML readings, there's no guesswork or additional calculations involved where we could've made a mistake. You should be able to verify T-Rex is not making the numbers up by running `nvidia-smi` command, it reports power usage too. If these numbers don't accurately represent the actual power usage, feel free to file a bug to NVIDIA

**Comment by rawbar** [comment]
ah ha, thank you.  it didn't even occur to me it might be at the driver level. 

![image](https://user-images.githubusercontent.com/3464225/112742100-65efae80-8f59-11eb-9f53-1b7b785b7045.png)

**Comment by rawbar** [comment]
updating the drivers didn't help, i'll open the ticket with nvidia, thanks for the help.

![image](https://user-images.githubusercontent.com/3464225/112742304-7bfe6e80-8f5b-11eb-8bf5-705fbcbe8e2a.png)
![image](https://user-images.githubusercontent.com/3464225/112742316-91739880-8f5b-11eb-99ab-55c64a26bc9f.png)

**Comment by trexminer** [comment]
No problem
