### ISSUE TITLE
Launch error on Ubuntu 18.04.5 LTS

### ISSUE THREAD

**Issue by toasteure** [trexminer/T-Rex#347]
On Ubuntu 18.04.5 LTS machine with cuda_11 installed, I get the following red message error when I try to launc t-rex. I downloaded the release version for cuda 11 but tried cuda 9 and 10 as well. Can you help me fix this problem?

20210327 17:27:33 TREX: eyJhIjoicmNuN0U4NlByZkNaditwOFBncUYxNEFkNkQvMEprRlcwL3hNNnA2djRIbz0iLCJiIjoiVnRORHY0aVBpY29FekhieTdocnFZdz09In0K

Tried #296 link for cuda 11 and it doesn't work as well.

**Comment by trexminer** [comment]
It appears you've got `LD_PRELOAD` env variable set, try running the miner with `LD_PRELOAD="" ./t-rex ... `

**Comment by toasteure** [comment]
Thank you so much, this solved the problem
