### ISSUE TITLE
How to increase my hastrate of my GTX1080

### ISSUE THREAD

**Issue by GeorgeQ-Q** [trexminer/T-Rex#350]
Hi,

I am mining on a RTX3060 and a GTX1080 on one mother board.
currently I have ~45MH/s on 3060 which is normal. But I get only ~21MH/s on 1080.
I googled a bit find that different mining setting could increase the hashrate of 1080 what command should I use to start
and will that hurts my hashrate on 3060?

Thanks

**Comment by adamgyongyosi** [comment]
hy

try --mt 4 for gtx 1080

i have one gtx 1080 with --mt 4 and 35-32MH/s

![image](https://user-images.githubusercontent.com/5511526/112801492-4055c880-9071-11eb-8d36-fdd55c6d9a75.png)

but i test nicehash

**Comment by GeorgeQ-Q** [comment]
That works thanks.
