### ISSUE TITLE
What's the meaning of 'R' in the running log?

### ISSUE THREAD

**Issue by UNAecho** [trexminer/T-Rex#357]
![image](https://user-images.githubusercontent.com/38469320/112967768-2d7cea00-917e-11eb-81e4-1382ecb13b48.png)
I noticed that the log of t-rex shows **[R] is 2.7%** , and **change its colour from white to yellow**

These parameters or logs are not described in the Readme.md

Could someone else help me ? Many thanks

**Comment by trexminer** [comment]
It's the percentage of rejected shares (1/37 in your case)

**Comment by UNAecho** [comment]
Thank you for your reply !

I want to know the other meaning of para like E:225kH/W or something like that .

How can I do it ?Is there any doc for it ?

**Comment by trexminer** [comment]
Not at the moment.
T is the GPU temperature, P is power consumption, F is fan speed, E is efficiency

**Comment by UNAecho** [comment]
okay, many thanks!

**Comment by DreamFun2014** [comment]
you can type "help" into the mineApp

在 2021年3月30日星期二，yad ***@***.***> 写道：
