### ISSUE TITLE
T-Rex initialize error

### ISSUE THREAD

**Issue by Alexander0921** [trexminer/T-Rex#36]
Since T-Rex 0.10.2 runs an error, the previous version is OK.

20190906 15:48:26 WATCHDOG: initialize error, memory dump: eyJhIjoiUVMrS1hta2I0b0NiSyttblJ5VEdMa3BHNmJrYWZXNUJFb2dsdHZ3MmVLd2xBTlVIeVNuYS9PSU5nWmdncGgyOXpnekIzZm9tVkluVzIrMXFyZHFvc0YwRE44a0hTWlMvQXAzQ1F3S2ozNmQxNmpvL3U4RXBlNVJ3OWlXcElSSmtIdHRxUlNmczh6M1ZpNlNmckM5ZlV3PT0iLCJiIjoib1RZSHBiL1RpRVZDSzBJSW1PeXBTQT09In0K
20190906 15:48:26 WARN: Messy shutdown...

**Comment by trexminer** [comment]
Thanks for reporting, the issue will be fixed in the next release

**Comment by trexminer** [comment]
Should be fixed in https://github.com/trexminer/T-Rex/releases/tag/0.14.4
