### ISSUE TITLE
not enough memory to hold the full DAG for epoch 404 on a 5GB VRAM GPU

### ISSUE THREAD

**Issue by mlamlam** [trexminer/T-Rex#360]
My graphic card is GTX 1060 and has 5GB VRAM, OS is Windows Server 2019 and Driver version is 470.05.

it seems that now ETH DAG size is ~4.2GB and my graphic card has 5GB VRAM, but it still say not enough memory?
I have only this graphic card on this computer, Page file set to 200GB already.

20210331 18:32:41 T-Rex NVIDIA GPU miner v0.19.14  -  [CUDA v11.10 | Windows]
20210331 18:32:41 r.39dd950be1c7
20210331 18:32:41 
20210331 18:32:41 NVIDIA Driver v470.05
20210331 18:32:41 CUDA devices available: 1
20210331 18:32:41 
20210331 18:32:41 WARN: DevFee 1% (ethash)
20210331 18:32:41 
20210331 18:32:41 URL : stratum+ssl://asia1.ethermine.org:5555
20210331 18:32:41 USER: XXXXXXXXXXXXXXXXXXXXXXXX
20210331 18:32:41 PASS: x
20210331 18:32:41 WRK : my
20210331 18:32:41 
20210331 18:32:41 Starting on: asia1.ethermine.org:5555
20210331 18:32:41 Using protocol: stratum1.
20210331 18:32:41 Authorizing...
20210331 18:32:41 Authorized successfully.
20210331 18:32:41 ethash epoch: 404, block: 12146577, diff: 4.00 G
20210331 18:32:41 ethash epoch: 404, block: 12146577, diff: 4.00 G
20210331 18:32:41 ApiServer: HTTP server started on 127.0.0.1:4067
20210331 18:32:41 ---------------------------------------------------
20210331 18:32:41 For control navigate to: http://127.0.0.1:4067/trex
20210331 18:32:41 ---------------------------------------------------
20210331 18:32:41 ApiServer: Telnet server started on 127.0.0.1:4068
20210331 18:32:41 WARN: GPU #0(000200): NVIDIA GeForce GTX 1060 5GB, intensity set to 22
20210331 18:32:46 ethash epoch: 404, block: 12146578, diff: 4.00 G
20210331 18:32:47 WARN: GPU #0: not enough memory to hold the full DAG for epoch 404.
20210331 18:32:47 WARN: GPU #0: effective hashrate will be ~54.5% of its usual value
20210331 18:32:47 GPU #0: generating DAG 4.12 GB (99.06% of full size) for epoch 404 ...
20210331 18:32:48 ethash epoch: 404, block: 12146579, diff: 4.00 G
20210331 18:32:57 ethash epoch: 404, block: 12146580, diff: 4.00 G
20210331 18:33:00 ethash epoch: 404, block: 12146581, diff: 4.00 G
20210331 18:33:02 GPU #0: DAG generated [crc: ed73dc0f, time: 14795 ms], memory left: 0.00 B
20210331 18:33:33 ethash epoch: 404, block: 12146582, diff: 4.00 G
20210331 18:33:34 ethash epoch: 404, block: 12146583, diff: 4.00 G

-------------- 20210331 18:33:41 ---------------
Mining at asia1.ethermine.org:5555, diff: 4.00 G
GPU #0: NVIDIA GTX 1060 5GB - 10.32 MH/s, [T:68C, P:88W, F:63%, E:136kH/W]
Shares/min: 0
Uptime: 1 min | Algo: ethash | T-Rex v0.19.14

-------------- 20210331 18:34:11 ---------------
Mining at asia1.ethermine.org:5555, diff: 4.00 G
GPU #0: NVIDIA GTX 1060 5GB - 10.31 MH/s, [T:70C, P:90W, F:62%, E:117kH/W]
Shares/min: 0
Uptime: 1 min 30 secs | Algo: ethash | T-Rex v0.19.14

20210331 18:34:20 ethash epoch: 404, block: 12146584, diff: 4.00 G
20210331 18:34:22 ethash epoch: 404, block: 12146585, diff: 4.00 G
20210331 18:34:41 ethash epoch: 404, block: 12146586, diff: 4.00 G

-------------- 20210331 18:34:41 ---------------
Mining at asia1.ethermine.org:5555, diff: 4.00 G
GPU #0: NVIDIA GTX 1060 5GB - 10.28 MH/s, [T:71C, P:91W, F:62%, E:114kH/W]
Shares/min: 0
Uptime: 2 mins | Algo: ethash | T-Rex v0.19.14

20210331 18:34:44 ethash epoch: 404, block: 12146587, diff: 4.00 G
20210331 18:34:45 WARN: shutdown t-rex, got Ctrl+C from console
20210331 18:34:46 Main loop finished. Cleaning up resources...
20210331 18:34:46 ApiServer: stopped listening on 127.0.0.1:4067
20210331 18:34:46 ApiServer: stopped listening on 127.0.0.1:4068
20210331 18:34:46 T-Rex finished.
![1](https://user-images.githubusercontent.com/81685485/113132114-9c2a7800-9250-11eb-975d-947b311e5c19.png)

**Comment by trexminer** [comment]
WDDM is not letting t-rex allocate enough memory, not our fault :) I'd recommend using Linux, there's a good chance you'll be able to mine at full speed.

**Comment by mlamlam** [comment]
Is it possible to use GPU pass thru on Hyper V and mining in Guest OS (ie Ubuntu) ?

**Comment by pdieppa** [comment]
PowerShell commands for you to investigate:

`Dismount-VMHostAssignableDevice -LocationPath gpu-device-location -force

Add-VMAssignableDevice -LocationPath gpu-device-location -VMName`
