### ISSUE TITLE
T-Rex says: fan control is not supported on Linux

### ISSUE THREAD

**Issue by horphi0815** [trexminer/T-Rex#366]
Hello,

Can't save config to HDD!
T-Rex says: fan control is not supported on Linux

How can i skip this?

BR

Phil

**Comment by lotar1954** [comment]
Same problem here with t-rex 0.19.14

Mr. Phil, if you are using Nvidia GPUs, use the following to set the GPU's speed

```
nvidia-settings -a '[gpu:0]/GPUFanControlState=1'
nvidia-settings -a '[fan:0]/GPUTargetFanSpeed=50'   ---> 50%
nvidia-settings -a '[fan:0]/GPUTargetFanSpeed=0'     ---> DO NOT DO THIS! 
```
Change [gpu:0] and [fan:0] accordingly to your GPU's ID.


If you are running a Graphic Desktop Environment (Mate, Gnome, KDE, etc) and you want to be able to Change the Fan Speed via the Nvidia-settings type

`sudo nvidia-xconfig --cool-bits=28`

Reboot 

nvidia-settings --> Thermal Settings --> Enable GPU Fan Setting 
nvidia-settings --> Power Mizer to overclock/under-clock your GPU's Core and VRAM

I hope this helped.

**Comment by horphi0815** [comment]
20210408 13:14:00 ERROR: Can't start miner, fan control is not supported on Linux
20210408 13:14:00 T-Rex finished.

**Comment by horphi0815** [comment]
Nobody has this error?

BR

Phil

**Comment by brettsconfused** [comment]
Yep, I have this issue also.  

I have been using T-Rex for about 2 months, running inside a docker container on my unraid server.

It was working fine until i upgraded, but im a bit of a noob, i cant figure out how to roll it back.

**Comment by trexminer** [comment]
It's a bug, the miner saves fan control settings (dummy ones on Linux) to the config file, and then fails to start because fan control isn't supported on Linux. The workaround would be to manually remove `"fan"` section from the config file. Possibly it'll also complain about `"mclock"`, `"cclock"`, and `"pl"`. We'll try to figure out how to fix it.

**Comment by trexminer** [comment]
The issue should be fixed by https://github.com/trexminer/T-Rex/releases/tag/0.20.3

**Comment by trexminer** [comment]
@robinostlund `--pl` is now supported (version 0.21.5 and above), `--mclock` and `--cclock` are not (maybe will be in future)

**Comment by tmartinx** [comment]
Sorry to post in a closed issue, but I just want to say that I'm looking forward to the `--mclock` and `--cclock` support on Linux!
Is there an open issue for that? Maybe on bountysource so people can donate for that feature?
