### ISSUE TITLE
Lots of high ping accepted shares

### ISSUE THREAD

**Issue by eliasasl** [trexminer/T-Rex#369]
Hello, I've using T-Rex miner until a couple of weeks ago when I started to encounter high latency problem, and I opened this issue: https://github.com/trexminer/T-Rex/issues/297
In the meantime I continued mining using another software and it never caused this type of problems, so I checked multiple times my internet connection, replaced router and switch, all run good and smooth.
A couple of days ago, with the newly release, I switched back to T-Rex miner hoping that this problem somehow got fixed, but guess what? Nothing changed. I'm not blaming anyone, I simply can't understand why only this software is causing this problems on my mining rig.
I love T-Rex and I think it s the best Nvidia oriented mining software, but for me, as it is it's unusable.

For reference, on ethermine.org, I saw at least 20%-30% stale shares for the time T-Rex was being used with the latest version.
So I checked the log file and I searched for the latency info. It came out that T-Rex was sending shares with over a 1000 ms, 2000 ms even 3000 ms latency, like the first issue (there is a log file so you can check).
I don't know what to do, but I really want to use T-Rex as my main mining software. 
Any suggestion is much appreciated and sorry for the length of this issue,
Best regards.

**Comment by dedizones** [comment]
i have same problem with Vers: 0.19.14-cuda111

i rollback t-rex-ver. 0.19.12-cuda111  and try this for nvidia 3xxx only

"gpu-init-mode": 1
"dag-build-mode": 2

![image](https://user-images.githubusercontent.com/58809062/113469239-6a7e0080-944c-11eb-9186-4656d4b07eda.png)

**Comment by eliasasl** [comment]
Thank you for your answer.
Just for curiosity, what kind of software is that? It seems nice e useful :D
Tomorrow morning, when I will be able to access my rigs for maintenance, I will try to heavily downgrade T-Rex as of tests and i will also change the cuda version, from 11 to 10. 
By the way I'm using 3x3070 and an old 1060, do you think could be anything related to these cards? I also, from the beginning, always used both parameters you mentioned, and it was able to run super smoothly. One day suddenly, don't know how or why, it started to give me this high ping problems. 
My problem seems to be like the actual comunication between T-Rex and the mining pool.
Best regards

**Comment by dedizones** [comment]
i use mobaxterm for SSH.

I sometimes have this ping problem, I let the dag be generated, then I restart the miner two or three times and after more problems.
Looks like a dag or syncronization problem somewhere. because after more worries, so if it was the pool, I would win all the time.

Try with hiveOS pool? outside nanopool

**Comment by eliasasl** [comment]
For devs.
After the lastest version I've no longer this high stales shares and it's working like a charm.
Don't know exactly what was wrong, but latest T Rex fixed it.
Thank you anyways.
