### ISSUE TITLE
OSX pre-compiled binary?

### ISSUE THREAD

**Issue by juanpc2018** [trexminer/T-Rex#37]
OSX HighSierra is faster than Windows8.1 for CPU Only algorithms like Argon2D-256.
same machine MacPro5,1, intel 2nd gen i7.

since Nvidia has CUDA drivers for OSX, im curious to know:
OSX vs. Win8.1 with X13-BCD.

**Comment by trexminer** [comment]
Sorry, MacOS isn't supported.

**Comment by Messa1** [comment]
To bad i was looking for the same :)
