### ISSUE TITLE
T-rex miner isn't validated

### ISSUE THREAD

**Issue by ethermin** [trexminer/T-Rex#380]
![Screenshot_2021-04-05-02-16-31-928_com teamviewer teamviewer market mobile](https://user-images.githubusercontent.com/82041867/113724699-e5684500-96f2-11eb-9d5a-9c87cb8a1dcc.jpg)

The miner constantly shows this message every now and then, i close it and start it again it works just fine then do it again ? 

I have msi rtx 3090 suprim

GC : 750mv @ 1200 Mhz
OC : +1100

**Comment by ethermin** [comment]
It worked just fine in the previous version but after the update this started to happen

**Comment by pdieppa** [comment]
300+ watts? Wow.. Have you tried to lower the power limits. Your power bill will use all your earnings. Your efficiency is 399, I would try to get that number as close to 500 as possible. Even if your hash rate drops, you'll end up making more money.

**Comment by ethermin** [comment]
I've done my math, it's around 2.3 dollars per day for electricity and I
gain about 11 dollars so my profit is around 9 dollars per day .
The second thing is that rtx 3090 will not mine under 300 watts , it's like
the bare minimum any less than that will cause problems.
So if you have any recommended settings better than mine please send them
otherwise tell me about the error message and why its coming up very often

‫في الثلاثاء، 6 أبريل 2021 في 7:30 م تمت كتابة ما يلي بواسطة ‪AMD+NVIDIA
Rigs‬‏ ***@***.***‬‏>:‬

**Comment by ethermin** [comment]
Its resolved on its own thnx
