### ISSUE TITLE
T-Rex.exe is not recognized as an internal or external command,

### ISSUE THREAD

**Issue by therealloscake** [trexminer/T-Rex#382]
I tried redownloading and it still doesn't work

**Comment by trexminer** [comment]
Antivirus deleting the executable is the most likely reason

**Comment by Nobtostart** [comment]
Some one have settings how to fix it

**Comment by trexminer** [comment]
@Nobtostart Please post a screenshot with the error

**Comment by ImTheKanman** [comment]
im having the same issue it reads as follows. 

C:\Users\Tyler\Downloads\t-rex-0.24.0-win>t-rex.exe -a ethash -o stratum+tcp://us1.ethermine.org:4444 -u 0x031802fb411b44fc78f57Beb798eB702716A9Da9 -p x -w N1050
't-rex.exe' is not recognized as an internal or external command,
operable program or batch file.

I have already uninstalled factory AVP and still have this issue.

**Comment by WunnaThantZin007** [comment]
I cannot find the compatibility in properties.

**Comment by SacredMuscle** [comment]
> 

Same here...

**Comment by alepodj** [comment]
For whomever this will help or apply to, make sure either t-rex.exe is added to environment variable PATH, or much easier, edit ETH-ethermine.bat to include a full path to t-rex.exe.

Using the example from "ImTheKanman" there is issue in the path to the file there (mind the > should be \\ ):

```
C:\Users\Tyler\Downloads\t-rex-0.24.0-win>t-rex.exe .....
```

Should be:

```
C:\Users\Tyler\Downloads\t-rex-0.24.0-win\t-rex.exe ......
```

Hope that helps
