### ISSUE TITLE
Not enough VRAM to mine ETH, 4GB GPU

### ISSUE THREAD

**Issue by 2pehr** [trexminer/T-Rex#383]
hey there 
i have gtx 1650  , i7 9750 (laptop) , win 10 x64 , lenovo legion y540
as i know , lenovo prevented me to access all fan speeds (CPU & GPU) . i've tried to change fan speed several times using different methods but i couldn't.(as a newbie not pro)
anyway, i have same problem here and the miner cant access to my fan speed and gives me this error:

>warn: GPU #0(000100): Geforce GTX 1650 , intensity set to 22
>ethash epoch: 406, block: 12193085, diff: 4.00 G
>ethash epoch: 406, block: 12193085, diff: 4.00 G
> warn: nvml: can't get fan speed for GPU #0, not supported
> Trex: cant find noonce with device[ID=0 , GPU #0] , GPU #0: not enough free memory
> warn: miner is goin to shutdown...
![sad](https://user-images.githubusercontent.com/56658970/113879344-a956e200-97cf-11eb-8d2a-28ba0981ebcf.PNG)

aslo i should mention that i have a hybrid GPU which i disabled the integrated Intel graphic .
thanks for all the good works here.

**Comment by AmityTek** [comment]
Hi,

I've got the same error with gtx 1650 ti

**Comment by trexminer** [comment]
Failure to get the fan speed is a warning, it wouldn't have prevented you from mining, but having only 4GB of VRAM is a deal breaker, you won't be able to mine ETH.

**Comment by deslumoprime** [comment]
ETH requires at least 4GB VRAM to mine now, the DAG size is larger than 4GB, which is why you hear miners talk about 8GB and 4GB cards. Your card is not e-waste though, you can still mine things like Ravencoin and Ethereum Classic with decent profits. Cheers!
