### ISSUE TITLE
Validate shares difficulty measurement - "B" ??

### ISSUE THREAD

**Issue by Kzeery** [trexminer/T-Rex#386]
When using the validate-shares method, the difficulty of each submitted share is shown. Usually this is something like 5.65 G for example. This makes perfect sense to me, it was a 5.65 gigahash difficult share. However, sometimes I get submitted shares like 1.34 B for example. Just wanted to confirm that this "B" measurement refers to terahash somehow? It cant be giga or anything less, otherwise it would not be accepted because my pool's difficulty for accepted shares is 12.00 G. 

Also, is there a separate letter for petahash? Is it P? or would it just show up as 1000 B?

**Comment by trexminer** [comment]
Could you post a log file / screenshot please? I checked the source code but I couldn't find a reference to the `B` suffix.

**Comment by Kzeery** [comment]
[log.txt](https://github.com/trexminer/T-Rex/files/6279901/log.txt)

Sure,  I have uploaded a log  file. Deleted most of it (it was multiple thousand lines long) but if you look at share 41 and share 61 they both have the "B" suffix, and are less than 12 in value.

**Comment by lewiserz3** [comment]
I'm also noticing this. Currently my max diff share is  "4.61 B" and previously it was "636 G" - implying B > G as a suffix.

**Comment by trexminer** [comment]
@Kzeery @lewiserz3  Please try version 0.20.0, and let me know if you're still seeing "B"

**Comment by trexminer** [comment]
This issue should be fixed in 0.20.1, please give it a try and let me know how it goes.

**Comment by ismet** [comment]
Hi @trexminer 

I just started to use `validate-shares` parameter. It is nice to see which GPU produces how many accepted/rejected/invalid shares.

However, what is the importance of knowing the difficulty of each share and the max difficulty of all shares? Why does it matter?

**Comment by Kzeery** [comment]
@trexminer Works good now! correctly shows "T" for Terahash.

@ismet there really isnt a point. Its just a cool feature to see if maybe you mined a block for your pool.
