### ISSUE TITLE
Conflux Error Then Mines KawPow

### ISSUE THREAD

**Issue by sdbarrish** [trexminer/T-Rex#388]
Only on my desktop computer, I will be mining CFX to Nanopool and all of a sudden, there's an error and then it starts mining KawPow.

I'll try and post a screenshot in a reply to this message.

**Comment by trexminer** [comment]
Make sure you're using the latest version, and your HTTP API is NOT bound to `0.0.0.0`.

**Comment by sdbarrish** [comment]
It was the latest version back then and I had my exact IP address for the web API.  I haven't mined CFX in a while now, so I don't know if this issue still exists in v21.6.
