### ISSUE TITLE
Fail to receive data from pool

### ISSUE THREAD

**Issue by lemonci** [trexminer/T-Rex#392]
Input: `./t-rex -a ethash -o stratum+tcp://us1.ethermine.org:5555 -u 0xa6C55BDA74274Aa29Ff08D6FBE6FA94eBcB8ff5e -p x -w rig0`

Output: `20210411 22:13:21 T-Rex NVIDIA GPU miner v0.20.0  -  [Linux]
20210411 22:13:21 r.5dadbedc9bd6
20210411 22:13:21 
20210411 22:13:21 NVIDIA Driver v460.67
20210411 22:13:21 CUDA devices available: 1
20210411 22:13:21 
20210411 22:13:21 WARN: DevFee 1% (ethash)
20210411 22:13:21 
20210411 22:13:21 URL : stratum+tcp://us1.ethermine.org:5555
20210411 22:13:21 USER: 0xa6C55BDA74274Aa29Ff08D6FBE6FA94eBcB8ff5e
20210411 22:13:21 PASS: x
20210411 22:13:21 WRK : rig0
20210411 22:13:21 
20210411 22:13:21 Starting on: us1.ethermine.org:5555
20210411 22:13:21 Using protocol: stratum1.
20210411 22:13:21 Authorizing...
20210411 22:13:21 ApiServer: HTTP server started on 127.0.0.1:4067
20210411 22:13:21 ---------------------------------------------------
20210411 22:13:21 For control navigate to: http://127.0.0.1:4067/trex
20210411 22:13:21 ---------------------------------------------------
20210411 22:13:21 ApiServer: Telnet server started on 127.0.0.1:4068
20210411 22:13:21 WARN: GPU #0(000100): Dell GeForce RTX 3070, intensity 22
20210411 22:13:31 Wait on data is timed out, 10 seconds have passed, 0 bytes in socket remained
20210411 22:13:31 WARN: failed to ethproxy-subscribe on us1.ethermine.org:5555: can't parse json: 
* Line 1, Column 1
  Syntax error: value, object or array expected.

20210411 22:13:31 ERROR: No connection, retry after 10 seconds
20210411 22:13:41 Using protocol: stratum1.
20210411 22:13:41 Authorizing...
20210411 22:13:51 Wait on data is timed out, 10 seconds have passed, 0 bytes in socket remained
20210411 22:13:51 WARN: failed to ethproxy-subscribe on us1.ethermine.org:5555: can't parse json: 
* Line 1, Column 1
  Syntax error: value, object or array expected.

20210411 22:13:51 ERROR: No connection, retry after 10 seconds
20210411 22:14:01 Using protocol: stratum1.
20210411 22:14:01 Authorizing...
20210411 22:14:11 Wait on data is timed out, 10 seconds have passed, 0 bytes in socket remained
20210411 22:14:11 WARN: failed to ethproxy-subscribe on us1.ethermine.org:5555: can't parse json: 
* Line 1, Column 1
  Syntax error: value, object or array expected.

20210411 22:14:11 ERROR: No connection, retry after 10 seconds
20210411 22:14:21 Using protocol: stratum1.
20210411 22:14:21 Authorizing...
20210411 22:14:31 Wait on data is timed out, 10 seconds have passed, 0 bytes in socket remained
20210411 22:14:31 WARN: failed to ethproxy-subscribe on us1.ethermine.org:5555: can't parse json: 
* Line 1, Column 1
  Syntax error: value, object or array expected.

20210411 22:14:31 ERROR: No connection, retry after 10 seconds
20210411 22:14:41 Using protocol: stratum1.
20210411 22:14:41 Authorizing...

------ 20210411 22:14:47 -------
Mining at us1.ethermine.org:5555
GPU #0: Dell RTX 3070 - 0.00 H/s, [T:27C, P:14W, F:30%, E:0.00H/W]
Shares/min: 0
Uptime: 1 min 25 secs | Algo: ethash | T-Rex v0.20.0

20210411 22:14:51 Wait on data is timed out, 10 seconds have passed, 0 bytes in socket remained
20210411 22:14:51 WARN: failed to ethproxy-subscribe on us1.ethermine.org:5555: can't parse json: 
* Line 1, Column 1
  Syntax error: value, object or array expected.

20210411 22:14:51 ERROR: No connection, retry after 10 seconds
20210411 22:15:01 Using protocol: stratum1.
20210411 22:15:01 Authorizing...
20210411 22:15:11 Wait on data is timed out, 10 seconds have passed, 0 bytes in socket remained
20210411 22:15:11 WARN: failed to ethproxy-subscribe on us1.ethermine.org:5555: can't parse json: 
* Line 1, Column 1
  Syntax error: value, object or array expected.

20210411 22:15:11 ERROR: No connection, retry after 10 seconds

------ 20210411 22:15:17 -------
Mining at us1.ethermine.org:5555
GPU #0: Dell RTX 3070 - 0.00 H/s, [T:27C, P:14W, F:30%, E:0.00H/W]
Shares/min: 0
Uptime: 1 min 55 secs | Algo: ethash | T-Rex v0.20.0

20210411 22:15:21 Using protocol: stratum1.
20210411 22:15:21 Authorizing...
20210411 22:15:31 Wait on data is timed out, 10 seconds have passed, 0 bytes in socket remained
20210411 22:15:31 WARN: failed to ethproxy-subscribe on us1.ethermine.org:5555: can't parse json: 
* Line 1, Column 1
  Syntax error: value, object or array expected`

Tried `ping us1.ethermine.org` and the connection is fine. May I ask how to solve the problem? I wonder if it is the network firewall so I tried to connect via my phone's hotspot but it also fails.

**Comment by trexminer** [comment]
`5555` is an SSL port, so you need to change your connection string to `stratum+ssl://us1.ethermine.org:5555` (note the `ssl`)

**Comment by lemonci** [comment]
Hi @trexminer thanks for the help.
After I changed it to `./t-rex -a ethash -o stratum+ssh://us1.ethermine.org:5555 -u 0xa6C55BDA74274Aa29Ff08D6FBE6FA94eBcB8ff5e -p x -w rig0` , it has the same error. It is the same with `stratum+tcp://us1.ethermine.org:4444` or `stratum+tcp://us1.ethermine.org:14444`.

**Comment by trexminer** [comment]
@lemonci It should be `ssl`, not `ssh`
