### ISSUE TITLE
hi how i should use --pl --mclock and --cclock

### ISSUE THREAD

**Issue by alperen2311** [trexminer/T-Rex#395]
hi how i should use --pl --mclock and --cclock (i mean where should i write it or write next that parameters)

**Comment by MonsieurKas** [comment]
here an example:

t-rex -a ethash -o stratum+tcp://eu.ezil.me:5555 -u [ethadress].zil[ziladress] -p x --worker RTX3070 -d 0 --extra-dag-epoch 0 **--pl 50 --mclock 1400 --cclock 0**

as you can you can simply add them after your launch line in the right .bat file

**Comment by alperen2311** [comment]
Thank you so much dude

**Comment by MonsieurKas** [comment]
please don't forget to close ticket, it's below next to comment. Thanks!
