### ISSUE TITLE
Display crashing after shutting down miner

### ISSUE THREAD

**Issue by pyr0hu** [trexminer/T-Rex#396]
Hey all,

I'm mining with a GTX1660Super, all was good until one day I wanted to exit the miner to do other stuff on the computer. When I restarted the miner I noticed something strange. I was running with the card on 7500 Mhz memory clock speed but after the miner started it was scaled back by 200 Mhz for no reason (running on 7300). Also after stopping the miner with Ctrl+C, after priging Shutting down, the whole screen became a single color display, and windows seems to freeze.

Tried running older version of the miner, downgrading nvidia drivers, nothing helped

**Comment by MonsieurKas** [comment]
If you are overclocking tried dial it back a little. What are your current OC setting?

**Comment by pyr0hu** [comment]
Power Limit: 68%, Memory: +700Mhz, Core: -502Mhz, stable at 62C, no crashing so far, only when I close the miner

**Comment by pyr0hu** [comment]
@MonsieurKas if I first reset the OC before shutting down the miner, all seems to be working. I think that was the issue, not sure why this happened in the first time, a week ago it was not happening though.
