### ISSUE TITLE
Any way to use --pl, --mclock and --cclock with more than 1 card

### ISSUE THREAD

**Issue by MonsieurKas** [trexminer/T-Rex#397]
Hi, I was wondering if I can have the new oc settings in one bat command for both my rtx3070 and my 1080ti?

They have different config, now I'm using them with two separate bat files.

**Comment by winiel559** [comment]
Use comma as for --devices, --mt, --fan, --kernel, etc.

**Comment by MonsieurKas** [comment]
Can you give an example? here you can see both bat config for 1080ti and 3070. The idea is to have the overclocking config on same bat.

t-rex -a ethash -o stratum+tcp://eu.ezil.me:5555 -u ethadress.ziladress -p x --worker homePC1080ti -d 1 --mt 2 --extra-dag-epoch 0 --pl 60 --mclock 500 --cclock 135 --fan 65

t-rex -a ethash -o stratum+tcp://eu.ezil.me:5555 -u ethadress.ziladress -p x --worker homePC3070 -d 0 --extra-dag-epoch 0 --pl 50 --mclock 1400 --cclock 0 --fan 65

**Comment by MonsieurKas** [comment]
never mind, found it. Thanks!

t-rex -a ethash -o stratum+tcp://eu.ezil.me:5555 -u ethadress.ziladress -p x --worker BisounoursPcDual --extra-dag-epoch 0 --mt 2 --pl 50,60 --mclock 1400,500 --cclock 0,135 --fan 65

**Comment by NewbieH4x** [comment]
Is there a way I can specify negative delta for core clock? I want core clock to be -495

**Comment by winiel559** [comment]
> Is there a way I can specify negative delta for core clock? I want core clock to be -495

Just enter -495
--cclock -495
