### ISSUE TITLE
feature request: proxy support (or at least donate over proxy)

### ISSUE THREAD

**Issue by CodeRoboto** [trexminer/T-Rex#399]
Well, sometimes the fireware block normal connection and the pool can only be connect with port forward. It will be easier if SOCKET5 proxy is support for the TCP connection, or at lease, may donate over proxy be supported? The devfee mining is always blocked by my firewall now.

**Comment by chadpetersen1337** [comment]
Can you please implement this function?

**Comment by trexminer** [comment]
Added SOCKS5 support in 0.24.6
