### ISSUE TITLE
CURL_OPENSSL_3

### ISSUE THREAD

**Issue by thaistar** [trexminer/T-Rex#4]
/usr/lib/x86_64-linux-gnu/libcurl.so.4: version `CURL_OPENSSL_3' not found.
You're using an obsolete version of OPENSSL_3. If your program is repaired with sudo apt-get install libcurl3 then it breaks BOINC 7.9.3. BOINC is more important so I'm done deploying your program to my fleet until it's updated. TIA

**Comment by thaistar** [comment]
Five releases and this is still a fatal flaw. T-rex 0.8.9 will not work if one uses an updated Ubuntu 18.04.

**Comment by trexminer** [comment]
We're aware of this problem and will try to fix it in future releases. We'll put this item into release notes when it's fixed. No need to try new versions until it's mentioned. Sorry for the inconvenience.

**Comment by trexminer** [comment]
This should be fixed in 0.9.1. Please check.

**Comment by thaistar** [comment]
Hi, I've tried it on 4 cards (970, 1070, 1080 & 1080 Ti) with CUDA 10 and Linux Mint 19. I've also tried a couple of algos. It works good. Thanks for the heads up. Ron
    On Monday, January 7, 2019, 2:02:42 AM PST, trexminer <notifications@github.com> wrote:  
 
 
This should be fixed in 0.9.1. Please check.
