### ISSUE TITLE
0.14.4 failed to bind socket 4067

### ISSUE THREAD

**Issue by thaistar** [trexminer/T-Rex#40]
I'm trying to sell Linux T-Rex x16rv2 to nicehash and all I get are warnings:
WARN: API Server: Failed to bind socket 0.0.0.0:4067. (Address already in use.)

I looked at process list in the system monitor and using netstat -l and find nothing else using 4067 or 4068.
![image](https://user-images.githubusercontent.com/7033982/66150239-93a8a100-e5c9-11e9-8b88-98699b74e93d.png)

**Comment by trexminer** [comment]
If you want to use http-api and bind webserver to non standard port use --api-bind-http option. e.g. --api-bind-http 12345.

ps.
To make sure that port is free use netstat -lp | grep t-rex. (you forgot 'p')

**Comment by thaistar** [comment]
No I don't want to have to use --api-bind http. 
I want your default 4067 & 4068 to work.

**Comment by trexminer** [comment]
Well, you can try to disable webserver. Write --api-bind-telnet 0 --api-bind-http 0
Miner should start without port bind error.
Anyway, there is no magic. Something in your system prevents miner to bind to default ports.

**Comment by thaistar** [comment]
I tried --api-bind-telnet 0 --api-bind-http 0 and that does not work either. It's not just one computer its all my Linux computers. 
I just noticed that running NHM 1.9.2.15 that T-Rex uses 4001:
![image](https://user-images.githubusercontent.com/7033982/66158924-c9ef1c00-e5db-11e9-85fd-72950fd8dcbd.png)
