### ISSUE TITLE
Why my gpu idle? Please help

### ISSUE THREAD

**Issue by StreamDark-01** [trexminer/T-Rex#401]
![P_20210413_125430.jpg](https://user-images.githubusercontent.com/82432197/114500426-907c7f80-9c5a-11eb-96ed-e7be087c6f4f.jpg)

**Comment by trexminer** [comment]
It's mining at the time you took the screenshot but went idle 16 mins before that, and the watchdog restarted the miner. The issue is most likely caused by overclock or some hardware problem, like bad riser connections etc.

**Comment by StreamDark-01** [comment]
> It's mining at the time you took the screenshot but went idle 16 mins before that, and the watchdog restarted the miner. The issue is most likely caused by overclock or some hardware problem, like bad riser connections etc.
