### ISSUE TITLE
[check_if_cuda_really_exists, 223] CUDA_ERROR_INVALID_VALUE

### ISSUE THREAD

**Issue by Sandyran** [trexminer/T-Rex#411]
When I am trying to run T-Rex, it stops right after it begins. I get the same error message [check_if_cuda_really_exists, 223] CUDA_ERROR_INVALID_VALUE. The T-Rex version I am using, is 20.0.

I am using a GTX 1060 3 GB, and the driver version is 460.32 for servers.

**Comment by joickle** [comment]
I just started having the same issue as well. It happed right after I restarted the miner after a nvidia driver 460 update. I'm guessing it's related. Running on headless ubuntu server.

**Comment by pdieppa** [comment]
Try 460.67 to see if that fixes the issue.

**Comment by joickle** [comment]
460.32.03 is the latest nvidia-headless-460-server driver available in the ubuntu repos

**Comment by joickle** [comment]
switching from nvidia-headless-460-server to nvidia-headless-460 updated my driver to 460.56 and seems to have resolved the issue :)

**Comment by deslumoprime** [comment]
What are you mining? ETH needs VRAM > 4GB. Also try installing the latest Game Ready Driver.

**Comment by Sandyran** [comment]
> What are you mining? ETH needs VRAM > 4GB. Also try installing the latest Game Ready Driver.

Yeah, I thought this was the issue. Thanks for telling me.
