### ISSUE TITLE
Asus 1080 Memory tweak breaks on 20.1

### ISSUE THREAD

**Issue by ctrang032** [trexminer/T-Rex#419]
Hey guys, I was using 20.1 and notice that my Asus 1080 Strix hashrates are down to 21-22. I reverted back to 19.14 and it's back up to 32-33. I think this is related to the memory tweaks. My 20xx and 30xx cards are fine though.

I also notice quite a bit instability with 20.1 with msi afterburner. I'm not sure if it's directly related to MSI afterburner but I would get CPU spikes and my computer would pretty much slow down to a crawl. Reverted back to 19.14 and this issue isn't present.

**Comment by trexminer** [comment]
Hi. What CUDA version of 0.19.14 are you using?

**Comment by runarriot** [comment]
I've got the same on 1080ti - 25 on 20.1,  45 - on 19.14-win-cuda11.1

**Comment by gary6587** [comment]
I have the same issue --mt only works on the first of my 1080ti cards.. doesn't matter if I put --mt 3 or --mt 3,3,3,3 last 3 cards don't get the tweak but in startup it shows mtweak 3 on all cards

**Comment by ctrang032** [comment]
> Hi. What CUDA version of 0.19.14 are you using?

Cuda 11

**Comment by trexminer** [comment]
@ctrang032 @runarriot When you have a moment, could you please give this new test build a try and let me know if it fixes the issue?
https://www.dropbox.com/s/j4c02wtv9aacoid/t-rex-0.20.1-linux.tar.gz?dl=1
https://www.dropbox.com/s/9lb0zaubniy9qru/t-rex-0.20.1-win.zip?dl=1

**Comment by runarriot** [comment]
sorry, no change on test build.. still lower hashrate (25MH/s) on 1080ti.. compared to previous versions (45MH/s)

**Comment by trexminer** [comment]
Could you please start miner with logging and send me the log. Add -l trex.log to args.

**Comment by gary6587** [comment]
[trex20-11_logs.txt](https://github.com/trexminer/T-Rex/files/6331694/trex20-11_logs.txt)

Here is my log with it showing first card good last 3 no  --mt effect

![Hashrates-trex_19-14](https://user-images.githubusercontent.com/82735095/115152742-505a3a00-a06a-11eb-915e-140deaebadcd.jpg)
 
And the rates in 19.14 cuda 10

**Comment by runarriot** [comment]
here are mine logs 
[trex19.log](https://github.com/trexminer/T-Rex/files/6331846/trex19.log)
[trex20.log](https://github.com/trexminer/T-Rex/files/6331847/trex20.log)

@gary6587 you can lower some settings to get gpu cooler and more power efficient

**Comment by gary6587** [comment]
@runarriot I don't pay for power ;)

**Comment by ctrang032** [comment]
I'll try the test build when I'm home.

@gary6587 you actually improve hashrate by lowering the power limit and then increasing your memory clock. What doesnt really show is your memory's temperature which is usually quite a bit higher than the gpu temperature during mining and when that hits a certain temperature it'll drop your hashrates. It's really easy to undervolt you should try it. My temps are usually mid to high 50s with the fans off and high 40s with it on

**Comment by gary6587** [comment]
@ctrang032 Thanks for the information I have been only mining for a few weeks now so still learning... I have the Micron memory and find so far the OC works best at core +127 and Memory +560 if I go any higher rates don't go much higher and it crashes, would be interested in all your OC settings to try..!

**Comment by runarriot** [comment]
no.. it's not in freezer.. just play a little with curve editor in afterburner, my 1080ti is running at 850mV
![Untitled](https://user-images.githubusercontent.com/32324078/115162223-9c28d580-a0a2-11eb-8f54-43884fd756fe.png)

**Comment by trexminer** [comment]
Thanks @gary6587 and @runarriot . I apologise for not mentioning this earlier, but unfortunately the default log level won't give me enough details to troubleshoot. There's a way to enable a more detailed log by specifying `--protocol-dump` in addition to the arguments you already have. If it won't trouble you, would you be so kind to re-run 0.20.1 again with this flag ON and send me the log file? Thanks in advance.

**Comment by runarriot** [comment]
logs with dump
[trex19d.log](https://github.com/trexminer/T-Rex/files/6339546/trex19d.log)
[trex20d.log](https://github.com/trexminer/T-Rex/files/6339547/trex20d.log)

**Comment by trexminer** [comment]
@runarriot could you please try this assembly with possible fix:
https://www.dropbox.com/s/5a6zbp48xafvo51/t-rex-0.20.1-tweaks-win.zip?dl=1

**Comment by runarriot** [comment]
nothing has changed... still 23 :(
[trex-fix.log](https://github.com/trexminer/T-Rex/files/6345162/trex-fix.log)

**Comment by trexminer** [comment]
@runarriot Thanks for trying it! Hope this is the last attempt: https://www.dropbox.com/s/smy7y772bxq8sqf/t-rex-0.20.1-tweaks2-win.zip?dl=1 . Essentially reverted the way tweaks are applied to 0.19.14-like state. Please let me know if this build fixes the issue.

**Comment by runarriot** [comment]
yes, now with tweak2 it looks ok :) thanks
[trex-tweak2.log](https://github.com/trexminer/T-Rex/files/6351311/trex-tweak2.log)

**Comment by MaximeFrancoeur** [comment]
same problem on GTX 1080 FE impossible to run -mt 1 to 6.
But with t-rex version 0.19.14 it's works well.

**Comment by MaximeFrancoeur** [comment]
I forget to mentioned but the problem happen only when I put my GTX 1080 on the second PCI-E slot (x8)
But when I run on my first slot PCI-E 16x I can use last version (0.20.1) with -mt 5

I run one RTX 2070 & one GTX 1080

**Comment by trexminer** [comment]
The new release https://github.com/trexminer/T-Rex/releases/tag/0.20.3 is supposed to fix the issue discussed here
