### ISSUE TITLE
ERROR: NO CONNECTION, RETRY AFTER 10 SECONDS

### ISSUE THREAD

**Issue by tzewern97** [trexminer/T-Rex#425]
![7a8995670aef0429907333e95802386](https://user-images.githubusercontent.com/82664459/115044955-9bf4d280-9f08-11eb-93a7-7fe8d60a5c83.png)

**Comment by pdieppa** [comment]
I always try another pool from the miner to see if I can still connect. Internet is not perfect :)

**Comment by pdieppa** [comment]
Port 4444 is incorrect for SSL. It needs to be 5555

**Comment by tzewern97** [comment]
> Port 4444 is incorrect for SSL. It needs to be 5555

thanks it works 
![WeChat Image_20210417204102](https://user-images.githubusercontent.com/82664459/115113495-44646e80-9fbd-11eb-81d3-31b9e463f3b9.jpg)

**Comment by tzewern97** [comment]
> Port 4444 is incorrect for SSL. It needs to be 5555
