### ISSUE TITLE
Research command

### ISSUE THREAD

**Issue by choppysterio** [trexminer/T-Rex#427]
Hello I would like to know if there is a command to block a GPU among my available? thank you in advance

**Comment by trexminer** [comment]
Hi, look up `--devices` parameter in readme

**Comment by choppysterio** [comment]
Thanks, but i can use 1 gpu but 1 want to use 4 on 5 gpu and i don't know How to do this

**Comment by trexminer** [comment]
`--devices 4,5` will use GPU#4 and GPU#5
