### ISSUE TITLE
My display stops working on Ubuntu

### ISSUE THREAD

**Issue by RedFour** [trexminer/T-Rex#430]
After running t-rex miner, my Ubuntu's monitor display stops working. It only starts working again if I restart the computer with my ethernet unplugged. Even without the trex script running, if I plug in my ethernet cable my display goes out.

Not sure what's going on.

System:
Ubuntu 20.04.2.0
CPU: Intel i5
GPUs: radeon r390x, nvidia 1060

**Comment by trexminer** [comment]
> Even without the trex script running, if I plug in my ethernet cable my display goes out.

That's sounds like an issue unrelated to T-Rex, to be honest.

**Comment by RedFour** [comment]
I think you are right.
