### ISSUE TITLE
GPU find less shares than expectation when mining octopus with high memory oc without any warning

### ISSUE THREAD

**Issue by jcstudio-jeff-chen** [trexminer/T-Rex#431]
I have 4 GPUs mining octopus. The hashrates are 49, 54, 55, 39. The 55 one has +1500 memory oc, all others are below +1100. After 6 hours of mining, all GPUs share count are almost proportional to their hashrates, but the 55 one is way below, even less than the 39 one.

This isn't just one time, it happens every time I look into the numbers. Not only happen to one GPU, I used to mine octopus with rtx3060 before the 470.05 driver came out. Same thing happened when the 3060 has +1400 memory OC, just straight up 30% less shares than expectation. It happened to my rtx2070 too when I has its memory OC +1400, it went to normal after I lower it to +1100.

I'm sure this is happening, I tested for 24 hours, and every time I look into the numbers, this is always the case, so I have at least 100 hours of samples to support it.

There is not a single warning whatsoever. You will never notice this if you don't look into the numbers. 0 rejected shares, the total shares found by that card just magically decreased.

Don't try to hide any problem from users, if something went wrong inside the software, let us know so we can avoid it.

**Comment by trexminer** [comment]
I'm 99% sure it's normal and due to variance. Run the miner until each card finds ~20-30k of shares and compare the numbers, they'll be more or less proportional to the reported hashrate.

**Comment by jcstudio-jeff-chen** [comment]
The 55 MH/s one should get 27.92% of the total shares. Let's see it as a binomial distribution. The total shares found in 6 hours is roughly 468 (I forgot the number, I just use 1.3*6*60), so we have p=0.2792, n=468.

The mean is 130.67, the standard deviation is 9.705. I remember the other cards shares are proportional to their hashrate, and the 55 one is same as the 39 one. This means it only get around 100.84 shares (468*39/(49+54+39+39))

The difference is 3.07 times standard deviation, the chance of this happening is below 0.3%.

This 6 hours is just yesterday morning, I noticed this problem 2 months ago and observed it for more than 100 hours when my 3060 wasn't able to mine ethereum. Use 100 hours 7800 shares as the sample size, the mean is 2181.66, standard deviation is 39.64. The chance of it deviate below the 39 MH/s card is 1-erf(8.9369). Every online calculator say this value is 0, i.e. practically impossible.

**Comment by trexminer** [comment]
Comparing the shares found by a single card to the total share count of the rig makes the calculations harder. I would instead suggest you calculate how many shares your GPU is supposed to find according to its reported hashrate (it's easily doable if you know the diff your pool sets to you). And then compare the amount of shares GPU actually found with that number.
Mining is better modelled by a Poisson process, TRM devs made a good write up on the topic here: https://github.com/Kerney666/trm-ethash-miner-tester/blob/master/README.md#mining-as-a-poisson-process
You can do the calculations yourself, but if you see at the table there, if your GPU has only found 100 shares, it is off from what it is supposed to find in ideal world by more than 30% with 5% probability which explains what you see.
Again, I suggest you run the miner longer, until each GPU finds at least 10k shares and then compare. If you can't be bothered to wait weeks or how many hours it takes to find that amount, you can run the miner against a fake pool with low difficulty.
