### ISSUE TITLE
Desktop Performance Linux

### ISSUE THREAD

**Issue by ebivan** [trexminer/T-Rex#433]
Hey there, 
I have been using T-Rex to mine on my desktop machine (with a single 3080) on windows for almost two months now. 
I recently installed Debian Bullseye on that machine, when running T-Rex (and using nvidia-settings and nvidia-smi to set up the card to -400 GPU Clock, +1200 Memory Clock and 220W Power Limit, just like I did with Afterburner in Win) I get comparable hasrates as I had in Win, but the systems responsiveness is unbearable. Switching a tab in Firefox takes TWO, sometimes even FOUR seconds after a mouseclick. Scrolling on a webpage is similarly slow. I cannot work like this.

On Win I used :
`t-rex.exe -a ethash -o stratum+ssl://eu1.ethermine.org:5555 -u <eth_address> -p x -w rig0 --coin eth`
and working on that machine was a breeze, while mining 24/7.

I tried the same line in Debian and had the above mentioned issues with responsiveness. So I tried adding 
`--low-load 1 `
and
`-i 15`
in the hope that this would allocate a little more of the GPUs resources to the linux desktop but all it did was dminishing my hashrate while not providing any improvements in responsiveness.

I am running Debian Bullseye, nVidia Driver 465.19.01 and CUDA 11.3
The system is a Ryzen 3900x with 32GB memory, no other programs exept Firefox, T-Rex and Signal for Desktop were running when I tested this. 

Am I doing anything wrong here, or is performance allocation just bad in linux? Or is it a bug in T-Rex? On Windows I had almost no noticeable performance decrease in responsiveness. I could even play 2D graphic adventure games with fluent animations and only the hashrate dropped from 93 to about 87 MH/s while doing so.

**Comment by trexminer** [comment]
There's an extra layer between the miner and the hardware on Windows - WDDM, which I suspect handles both visual rendering and CUDA workloads making sure rendering is smooth, whereas on Linux the miner uses GPU resources in a more direct way. My only recommendation would be not to mine while you're using the desktop.

**Comment by Chapax** [comment]
I've got similar performance behavior with arch linux and firefox, what worked for me is switching to another web browser.
With Brave Vivaldi even Librewolf which is base on firefox i have no performance issue even watching youtube.
Haven't try to game while mining.
Similary my files manager dolphin is extremly laggy while PCmanFM run smoothly.

**Comment by ebivan** [comment]
Hey there, thank you for your replies! 
It was not only Firefox, but everything else like switching between filemanager windows had these 2-4 sec lags. 
I found a solution that works for me. I simply disabled Hardware Accelation in xorg.conf, this way everything is quite usable. Of course its not as smooth, as is was with HWACCEL on and t-rex off, but its absolutely usable, there is some tearing when scrolling through text but I can live with that.

@trexminer
In Windows I used GPUz to monitor GDDR6x temperatures in order not to fall into throtteling, so far i have not found a tool that displays that information in Linux. Afaik only GPUz and HWinfo can read that sensor in 3080 and 3090 cards. Could you maybe have a look at that and add that sensor to T-Rex' output?

**Comment by trexminer** [comment]
We'd gladly make T-Rex display memory junction temps but unfortunately NVIDIA doesn't publish any details about how to read it. If we ever come by any sort of docs / specs on the subject, we'll add it.

**Comment by ebivan** [comment]
Oh, thats too bad. GPUz and HWinfo are closed source, so no peek into their code on how they did it, anyways could be completely different on Linux anyways. I guess the temperature reading is somehow provided by the driver and may not even be available in the Linux driver.
Do HWinfo and TPU (the devs of GPUz) have some kind of cooperation with Nvidia? Or how did they come up with that sensor value? Resp. the necessary documentation to implement it..!?
What about that other indicator I believe it was called PerfCapReason, just seeing that there is no other reason for throttling different than powerlimit would reassure me that memory is below the specified 110C. Do you have access to that sensor?

**Comment by crocokyle** [comment]
Just leaving this here for your reference. NVIDIA planned to expose the memory junction temp and said that it was given priority only to come back and say they no longer plan to implement it. 

https://forums.developer.nvidia.com/t/request-gpu-memory-junction-temperature-via-nvidia-smi-or-nvml-api/168346/160?u=dixonkyleard
