### ISSUE TITLE
Log file create a new file

### ISSUE THREAD

**Issue by gabanzin** [trexminer/T-Rex#437]
Good morning folks, I want to crate a new .txt log file every time I run the bat file and not to save everytime at the same txt file (default). Anyone can give me a light to do that? Sorry if that is basic of basic, appreciate.

**Comment by trexminer** [comment]
The miner doesn't overwrite the existing log file, it renames it adding a timestamp and creates a new one.

**Comment by gabanzin** [comment]
Got it. It worked as expected. Thank you sir.
