### ISSUE TITLE
crash when --validate-shares is used

### ISSUE THREAD

**Issue by Gunnl** [trexminer/T-Rex#438]
Command with --validate-shares causes "20210419 16:20:59 ERROR: WATCHDOG: can't initialize T-Rex, assign: Bad file descriptor":
`/usr/local/bin/t-rex/t-rex --pci-indexing -a ethash -o stratum+tcp://eu1.ethermine.org:4444 -u 0xXXXXXXXX -p X -w $HOSTNAME --validate-shares --log-path "/var/log/t-rex/t-rex.log" --exit-on-cuda-error --exit-on-connection-lost --api-bind-telnet 0 --api-bind-http 0.0.0.0:4067 --api-read-only --script-epoch-change /usr/local/bin/t-rex-epoch-change.sh --script-crash /usr/local/bin/t-rex-crash.sh --script-low-hash /usr/local/bin/t-rex-low-hash.sh:460`

Command without --validate-shares, executes with no issues:
`/usr/local/bin/t-rex/t-rex --pci-indexing -a ethash -o stratum+tcp://eu1.ethermine.org:4444 -u 0xXXXXXXXX -p X -w $HOSTNAME --log-path "/var/log/t-rex/t-rex.log" --exit-on-cuda-error --exit-on-connection-lost --api-bind-telnet 0 --api-bind-http 0.0.0.0:4067 --api-read-only --script-epoch-change /usr/local/bin/t-rex-epoch-change.sh --script-crash /usr/local/bin/t-rex-crash.sh --script-low-hash /usr/local/bin/t-rex-low-hash.sh:460`

![image](https://user-images.githubusercontent.com/352718/115243340-1e58de80-a123-11eb-9022-1f8ac750cce6.png)

**Comment by trexminer** [comment]
@Gunnl both of your commands appear to be identical

**Comment by Gunnl** [comment]
> @Gunnl both of your commands appear to be identical

Sorry, you are correct ... my mistake when pasting... they are effectively identical except when I remove the --validate-shares it works and when I dont, I get that message in red on console / log...

**Comment by trexminer** [comment]
@Gunnl No problem, thanks for reporting the issue. Could you please add `--protocol-dump` argument and post the miner's log file?

**Comment by Gunnl** [comment]
Sure, glad to help man ... minimum I can do for using your software for free ;)

![image](https://user-images.githubusercontent.com/352718/115252337-ad69f480-a12b-11eb-9e3d-cefdf45bea9f.png)

And the file contents:
20210419 17:23:14:741782 WATCHDOG: can't start T-Rex, code 16
20210419 17:23:14:741833 WATCHDOG: connecting pipes...
20210419 17:23:44:747200 WATCHDOG: paired successfully
20210419 17:23:44:747307
20210419 17:23:44:747351
20210419 17:23:44:747741 ERROR: WATCHDOG: can't initialize T-Rex, assign: Bad file descriptor

**Comment by trexminer** [comment]
@Gunnl Many thanks for taking time to help us troubleshoot this. Could you try this build with `--protocol-dump` again https://www.dropbox.com/s/0qkkzclqt1oglk4/t-rex-0.20.1-tweaks2-linux.tar.gz?dl=1 ?

**Comment by Gunnl** [comment]
Seems to be working now ... 
![image](https://user-images.githubusercontent.com/352718/115563412-cdc6ba00-a2b7-11eb-8f3e-2fd127a4a6f9.png)
How do you prefer for me to send you the full log file ? pastebin ? other ?

**Comment by trexminer** [comment]
@Gunnl No need to send the log as long as it's working :) Thanks again for testing. The next version will include this fix.

**Comment by Gunnl** [comment]
Great!! ... is it safe to mine with this version until next release ?

**Comment by trexminer** [comment]
Yep. There are no known major issues with it (yet :smile: )
