### ISSUE TITLE
Request for SNI compliance.

### ISSUE THREAD

**Issue by Stackout** [trexminer/T-Rex#44]
I am requesting the `server_name` extension be added to the T-Rex miner to be SNI compliant. 

Using wire shark to determine the current TCP extensions, under SSL, the miner should have the `server_name` extension added in order to properly determine the ownership service of a domain name under a single load balancer IP address.

Without the `server_name` extension, it is impossible for the load balancer to know which service to direct the traffic. 

<img width="1618" alt="Screen Shot 2019-10-30 at 5 52 07 PM" src="https://user-images.githubusercontent.com/4387849/67946014-f465d200-fba5-11e9-8cb3-22d591d821d7.png">

As you can see above, wireshark only sees the following extensions: ec_points_formats, supported_groups, session-ticket, signature_algorithms, extended_master_secret.

The packets sniffed by wireshark above on the successful handshake with the loadbalancer presented with a default certificate as it didn't know which certificate to present to the miner without the `server_name` extension.

Anyone else reading this can see the wiki page on SNI compliance https://en.wikipedia.org/wiki/Server_Name_Indication.

**Comment by Stackout** [comment]
I have a fixed version of this thanks for @trexminer. This can be closed once there is a new release. So far the version I got is working like a charm!

**Comment by trexminer** [comment]
Added in 0.15.3
