### ISSUE TITLE
support socks5 proxy

### ISSUE THREAD

**Issue by clever-cerf** [trexminer/T-Rex#440]
My rig cannot directly connect to the Internet due to restrictions. I want to use the socks5 proxy to access the Internet. I used `proxychain4`, and run with `proxychain4 ./t-rex ...`, but t-rex doesn't work anymore.

Hope to add an option to communicate with the mining pool through the socks5 proxy.

**Comment by trexminer** [comment]
Duplicate of https://github.com/trexminer/T-Rex/issues/399
