### ISSUE TITLE
High RAM usage

### ISSUE THREAD

**Issue by eliasasl** [trexminer/T-Rex#451]
Hello,
Not a proper and actually issue, but I've noticed that day by day the RAM usage of T Rex process keeps rising.
It went from ~600MB to ~1.3Gb in less than a week.
Is this behavior normal? Will the RAM usage keep rising day after day?
Thank you.

**Comment by trexminer** [comment]
Hi, that sounds like a NVML leak, see more details at https://github.com/trexminer/T-Rex/issues/262
