### ISSUE TITLE
This is linux 101 sorry

### ISSUE THREAD

**Issue by mah3re** [trexminer/T-Rex#458]
Hey, I'm just installing and running ubuntu for the first time so bear with me.

I've edited my t-tex ethermine file to include all of the right information

#!/bin/sh
t-rex.exe -a ethash -o stratum+tcp://us1.ethermine.org:4444 -u (my wallet) -p x -w (worker) --coin eth

but the problem arises when I try to run the file from terminal

I get the following error

sudo ./ETH.sh

- It gives me
./ETH.sh: 2: t-rex.exe: not found

I've been trying different tweaks within the sh file, such as dropping the .exe but I get the same exact output, with only the .exe also missing. But that hasn't helped.

**Comment by Gunnl** [comment]
Dude ... if you are trying to run windows binaries on linux... you gotta continue reading, you're not there yet...

**Comment by pdieppa** [comment]
Make sure you remove the .exe from the command line. t-rex.exe is only for windows where you just use t-rex under linux.

**Comment by pdieppa** [comment]
Your eth.sh needs the full path of t-rex. It's telling you it can't find it.
Example:
/path-of-t-rex/t-rex -a ethash -o stratum+tcp://us1.ethermine.org:4444 -u (my wallet) -p x -w (worker) --coin eth
