### ISSUE TITLE
cant initialize device

### ISSUE THREAD

**Issue by avron87** [trexminer/T-Rex#46]
ERROR: Can't initialize device [ID=0, GPU #0], cuda exception in [Mtp::allocate_extra_memory, 59], out of memory

**Comment by avron87** [comment]
T-Rex NVIDIA GPU miner v0.14.6  -  [CUDA v10.0]
20200115 12:09:33 r.ad1aa7ca3433
20200115 12:09:33
20200115 12:09:33 NVIDIA Driver v441.66
20200115 12:09:33 CUDA devices available: 1
20200115 12:09:33
20200115 12:09:33 WARN: DevFee 1% (mtp)
20200115 12:09:33
20200115 12:09:33 URL : stratum+tcp://zcoin.mintpond.com:3000
20200115 12:09:33 USER: a3L5WyJ5gSeEigwUtFBGDRKS1oFVxNHUFX
20200115 12:09:34 PASS: x
20200115 12:09:34
20200115 12:09:34 Starting on: zcoin.mintpond.com:3000
20200115 12:09:34 ApiServer: HTTP server started on 127.0.0.1:4068
20200115 12:09:34 WARN: ApiServer: 127.0.0.1:51749 requested 'summary' which is not found
20200115 12:09:34 Authorizing...
20200115 12:09:34 ERROR: Can't initialize device [ID=0, GPU #0], cuda exception in [Mtp::allocate_extra_memory, 59], out of memory
20200115 12:09:34 WARN: Messy shutdown...

**Comment by ArturChek** [comment]
I have the same issue trying to start mining on more than 2 devices.
OS: Win10.

```
20200121 21:26:43 T-Rex NVIDIA GPU miner v0.14.6  -  [CUDA v10.0]
20200121 21:26:43 r.ad1aa7ca3433
20200121 21:26:43 
20200121 21:26:44 NVIDIA Driver v441.87
20200121 21:26:44 CUDA devices available: 5
20200121 21:26:44 
20200121 21:26:44 WARN: DevFee 1% (mtp)
20200121 21:26:44 
20200121 21:26:44 URL : stratum+tcp://xzc.2miners.com:8080
20200121 21:26:44 USER: ***************************************
20200121 21:26:44 PASS: ***************************************
20200121 21:26:44 
20200121 21:26:44 Starting on: xzc.2miners.com:8080
20200121 21:26:44 ApiServer: HTTP server started on 0.0.0.0:4067
20200121 21:26:44 ------------------------------------------------------
20200121 21:26:44 For control navigate to: http://192.168.1.82:4067/trex
20200121 21:26:44 ------------------------------------------------------
20200121 21:26:44 ApiServer: Telnet server started on 0.0.0.0:4068
20200121 21:26:44 Authorizing...
20200121 21:26:44 Authorized successfully.
20200121 21:26:44 WARN: GPU #0: MSI GeForce GTX 1080 Ti, intensity set to 19.6
20200121 21:26:44 WARN: New difficulty: 0.125
20200121 21:26:44 mtp block 234572, diff 7241.519
20200121 21:26:44 WARN: GPU #2: MSI GeForce GTX 1080 Ti, intensity set to 19.6
20200121 21:26:45 ERROR: Can't initialize device [ID=1, GPU #1], cuda exception in [Mtp::allocate_extra_memory, 59], out of memory
20200121 21:26:45 WARN: Messy shutdown...
20200121 21:26:45 Main loop finished.
20200121 21:26:45 ApiServer: stopped listening on 0.0.0.0:4067
20200121 21:26:45 ApiServer: stopped listening on 0.0.0.0:4068
20200121 21:26:45 ERROR: Can't initialize device [ID=3, GPU #3], cuda exception in [Mtp::allocate_extra_memory, 59], out of memory
20200121 21:26:45 ERROR: Can't initialize device [ID=4, GPU #4], cuda exception in [Mtp::allocate_extra_memory, 59], out of memory
20200121 21:26:46 WARN: WATCHDOG: T-Rex does not exist anymore, restarting...
```
If I run the miner with -d 0,1 parametr than it works.
Another instance of a miner with -d 2,3 running in parallel gives the same error.

**Comment by trexminer** [comment]
If running Windows, make sure you have enough virtual memory. Roughly 5GB * number of GPUs

**Comment by avron87** [comment]
I have 18000 Mb in virtual memory

**Comment by ArturChek** [comment]
@trexminer  It works!
