### ISSUE TITLE
Latest T-Rex miner contains malware.

### ISSUE THREAD

**Issue by storm5510** [trexminer/T-Rex#463]
T-Rex v0.20.3 contains malware identified by Windows 10 Security as **Win32/Contebrew.A!m1**.

**Comment by eldr4** [comment]
You're going to have to provide more information. It's a miner, so lots of security programs detect it as malware. Here's the latest windows version in virustotal

https://www.virustotal.com/gui/file/fe6b59e531ad6f04499fade069dc3551fb13cf58334682ecdcbdc64f1b14c592/detection

**Comment by trexminer** [comment]
@storm5510 see https://github.com/trexminer/T-Rex#antivirus-alerts
