### ISSUE TITLE
(ethash) Performance degradation on Pascal and Turing GPUs

### ISSUE THREAD

**Issue by goyetus** [trexminer/T-Rex#469]
I downloaded the new version from Trex.

1080ti degradation seems the same as before.   46,5 mh/s  with --mt2

Im missing something ?

**Comment by trexminer** [comment]
There was a minor performance degradation introduced in 0.20.1 and it's now fixed. In other words, it's not THAT degradation :) THAT degradation is only affecting Pascal GPUs as far as I know.
