### ISSUE TITLE
GTX Titan 6GB Compute Capability

### ISSUE THREAD

**Issue by juanpc2018** [trexminer/T-Rex#47]
#1. i have a GTX Titan 6GB, i want to test with x13bcd or argon2d-256...
#2. latest Nvidia driver that fully works for W8.1 or W7 is v388.71, all modern drivers have CUDA 64-Bit broken,
tested with CUDA-Z, GPU-Z, GPU-Capsviewer, etc...
"i dont have W10, i havent tested, but probably is the same."
#3. GTX Titan 6GB is a GTX 700 series, GK110 GPU has Compute Capability v3.5
https://en.wikipedia.org/wiki/CUDA
CUDA SDK 9.0 – 9.2 support for compute capability 3.0 – 7.2 (Kepler, Maxwell, Pascal, Volta)
CUDA SDK 10.0 – 10.2 support for compute capability 3.0 – 7.5 (Kepler, Maxwell, Pascal, Volta, Turing). Last version with support for compute capability 3.x (Kepler). 10.2 is the last official release for macOS, as support will not be available for macOS in newer releases.

#4. No GPU miner tested so far, None works, all say: Compute Capability Not Supported.

i know GTX1060 is the same and eats less power, but... still i want to test Nvidia drivers with & without Double Precision, just for curiosity.

**Comment by trexminer** [comment]
Sorry, there's a lot of source code in our code base that's using newer GPU instructions not available on CC 3.5 and below, so I'm afraid Compute Capability v3.5 cards won't be supported
