### ISSUE TITLE
T-Rex Miner 0.20.3 - Error: Can't start miner, CUDA initalize error, memory dump: followed by lots of numbers and letters.

### ISSUE THREAD

**Issue by dannylegge** [trexminer/T-Rex#470]
I am getting the above error when I try and run the .bat file for T-Rex miner. I have this working fine on another computer but on this laptop its not working.

The GPU is below, maybe its rubbish and is not worthwhile but that's not the point for me now. Windows is up to date and so are the GPU drivers so I'm just trying to get it working to learn. Any help would be appreciated. Thanks in advance.

![Error Message](https://user-images.githubusercontent.com/81643511/116241025-62b83000-a75c-11eb-858e-d0ccf7670b17.JPG)
![GPU](https://user-images.githubusercontent.com/81643511/116241030-62b83000-a75c-11eb-9830-1ee0b7139cfd.JPG)

**Comment by trexminer** [comment]
Seems like you're trying to run T-Rex on a AMD GPU

**Comment by dannylegge** [comment]
Thanks sorry for the stupid question.
