### ISSUE TITLE
issue passing --cclock and --mclock parameters

### ISSUE THREAD

**Issue by keithit110** [trexminer/T-Rex#475]
Im getting this warning when trying to define --cclock and --mclock parameters. Was looking to see if I can set my clock settings this way. i did run my bat file as Administrator. Below are the parameters I've used as well. What am i missing so it could take these parameters?
![image](https://user-images.githubusercontent.com/31339871/116331008-c95d3e00-a79c-11eb-989f-81ea23f8b4d8.png)

```D:\Crypto\T-rex\t-rex.exe -a ethash -o stratum+tcp://us1.ethermine.org:4444 -u 0x808Ac14B2a9c5f7124266c9e9b1DaF4720a64938 -w 0_gigabyte3070 -p x --dag-build-mode 2 --gpu-report-interval 5 --devices 1 --intensity 25 --fan t:57 --cclock 1110 --mclock 8171```

**Comment by trexminer** [comment]
You need to pass in the clock offsets, i.e. `--clock 100 --mclock 1000`, the same way you do in MSI Afterburner

**Comment by keithit110** [comment]
I did pass those parameter --cclock and --mclock as noted on my initial post. I get those warning when i pass those parameters. I do have the latest version of t-rex installed (0.20.3). Is there anything else i should be doing?

**Comment by trexminer** [comment]
You passed absolute values as opposed to offsets from stock.

**Comment by keithit110** [comment]
I see. Is there any way in T-rex where we can pass absolute values instead of offsets?

**Comment by trexminer** [comment]
Not at the moment
