### ISSUE TITLE
Can't get fan speed issue for Nvidia GeForce GTX 1650 

### ISSUE THREAD

**Issue by jaywanthgowda11** [trexminer/T-Rex#477]
Running on Integrated Graphics.

Error Log:
<em>20210428 11:46:51</em> WARN: GPU #0(000100): NVIDIA GeForce GTX 1650, intensity 22
<em>20210428 11:46:51</em> ethash epoch: 410, block: 12327250, diff: 4.00 G
<em>20210428 11:46:51</em> ethash epoch: 410, block: 12327250, diff: 4.00 G
<em>20210428 11:46:52</em> WARN: NVML: can't get fan speed for GPU #0, not supported
<em>20210428 11:46:53</em> ethash epoch: 410, block: 12327251, diff: 4.00 G
<em>20210428 11:46:54</em> TREX: Can't find nonce with device [ID=0, GPU #0], GPU #0: not enough free memory to mine ethash at epoch 410
<em>20210428 11:46:54</em> WARN: Miner is going to shutdown...
<em>20210428 11:46:54</em> Main loop finished. Cleaning up resources...
<em>20210428 11:46:54</em> ApiServer: stopped listening on 127.0.0.1:4067
<em>20210428 11:46:54</em> ApiServer: stopped listening on 127.0.0.1:4068
<em>20210428 11:46:54</em> T-Rex finished.
<em>20210428 11:46:55</em> WARN: WATCHDOG: T-Rex does not exist anymore, restarting...

**Comment by trexminer** [comment]
"Can't get fan speed" is a warning and not an error.
"not enough free memory to mine ethash at epoch 410" is the actual error and is self explanatory, you need to mine some other coin
