### ISSUE TITLE
Fan settings not restored when miner shut down

### ISSUE THREAD

**Issue by gronnmann** [trexminer/T-Rex#478]
When using T-rex with --fan setting sat on static fan speed (ex --fan 100), the fan won't go back to normal setting after T-rex is shut down.

**Comment by trexminer** [comment]
The miner resets the fan settings when it's shut down correctly (pressing Ctrl+C in the miner console). Closing the console using X button kills the miner and doesn't let it reset the settings.

**Comment by gronnmann** [comment]
Thank you, makes sense. Issue fixed :)
