### ISSUE TITLE
T-Rex Problem With GPU Connection

### ISSUE THREAD

**Issue by jgonzis** [trexminer/T-Rex#48]
Hi, 
Using T-Rex with MTP, I found that I lose the connection to have the information about my GPU Stats.

I show some pictures… GPU 3 goes down in MSI Afterburner… but the Hash stills the same. 
My command line is:

t-rex.exe --no-watchdog --no-nvml -b 127.0.0.1:4068  -a mtp --quiet -r 10 --cpu-priority 4 ….

The problema is that I made an autorestart if the GPU Temp goes down to 0... so it is autorestarting all the time. That problem I don't have it with other miners.

![TRex](https://user-images.githubusercontent.com/38668405/76140868-fe6d7500-605e-11ea-9c4b-996e5e511e7d.jpg)
![TRex2](https://user-images.githubusercontent.com/38668405/76140869-ff9ea200-605e-11ea-80b0-54dd74f23c35.jpg)

Many thanks

**Comment by jgonzis** [comment]
I have try without any overclock too and I only have these Problem with T-rex… where is the problema?

**Comment by mo35** [comment]
nothing to do with overclock , my underclocked evga 2060 supers does exactly the same, so does 1070 and 1070Ti asus rigs , and only with trex , observed with mtp and kawpow (prolly happening with all of algos)

**Comment by trexminer** [comment]
So, what problem are you reporting? The one where the GPU stops hashing but the miner keeps reporting the same hashrate? Or something to do with the temperatures and restarts - that one I didn't quiet understand.
Also please check 0.17.3 and let me known if the issue is still there.
