### ISSUE TITLE
Miner crashes every some hours | WARN: unknown vendor id 0x103c of GPU nvml_id=#3

### ISSUE THREAD

**Issue by pberetta** [trexminer/T-Rex#482]
Hello,

I'm running a rig with some 3080s, as soon as I open T-Rex 0.20.1 on Windows, I got the following message:

WARN: unknown vendor id 0x103c of GPU nvml_id=#3

The miner will work for a while and then the whole system will reboot.

Is this kind of issues related to the miner? From an application stand point.

**Comment by trexminer** [comment]
> WARN: unknown vendor id 0x103c of GPU nvml_id=#3

This is a warning and not an error, it doesn't affect mining in any way
