### ISSUE TITLE
issues running on centos7

### ISSUE THREAD

**Issue by stranger29** [trexminer/T-Rex#5]
hi tried a few latest releases, looks like has to be recompiled:

 ./t-rex: /lib64/libcurl.so.4: no version information available (required by ./t-rex)
./t-rex: /lib64/libssl.so.1.0.0: version `OPENSSL_1.0.0' not found (required by ./t-rex)
./t-rex: /lib64/libcrypto.so.1.0.0: version `OPENSSL_1.0.0' not found (required by ./t-rex)
./t-rex: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ./t-rex)
./t-rex: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./t-rex)

**Comment by trexminer** [comment]
Thanks. Will be fixed in the next release.

**Comment by trexminer** [comment]
Should be fixed in 0.9.2
@stranger29 Please let me know if it works with your setup.
