### ISSUE TITLE
ERROR: Can't find nonce with device [ID=0, GPU #0], kernel doesn't match progpow algo type

### ISSUE THREAD

**Issue by WhiteRedWolf** [trexminer/T-Rex#50]
So i tried benchmarking my GTX 1060 6gb with Kawpow for the upcoming Ravencoin fork, and im getting this error,

C:\Users\arkad>t-rex.exe` -a kawpow --benchmark
20200506 11:09:25 T-Rex NVIDIA GPU miner v0.15.4  -  [CUDA v10.0]
20200506 11:09:25 r.d54ad77b45a7
20200506 11:09:25
20200506 11:09:25 NVIDIA Driver v442.59
20200506 11:09:25 CUDA devices available: 1
20200506 11:09:25
20200506 11:09:25 WARN: DevFee 1% (kawpow)
20200506 11:09:25
20200506 11:09:25 WARN: GPU #0: Gigabyte GeForce GTX 1060 6GB
20200506 11:09:25 ERROR: Can't find nonce with device [ID=0, GPU #0], kernel doesn't match progpow algo type
20200506 11:09:25 WARN: Messy shutdown...
20200506 11:09:25 Main loop finished

**Comment by trexminer** [comment]
Fixed in 0.15.6
