### ISSUE TITLE
fan speed for linux

### ISSUE THREAD

**Issue by hermesonfg** [trexminer/T-Rex#501]
has someone knows how to set fan speed on the .bat on linux? thanks

**Comment by meow6969** [comment]
1. linux does not use batch
2. if you are using a Nvidia card you will probably need to have coolbits set

**Comment by ganzocrypt** [comment]
I have a script that enables Fan and overclocking for specific [nVidia cards](https://github.com/ganzocrypt/nVidia-gpu-overclocking) but you can adapt to yours.
