### ISSUE TITLE
Can't reset core clock lock

### ISSUE THREAD

**Issue by mrencep** [trexminer/T-Rex#503]
Lock cclock function can't reset, even restart the OS on windows 10, and set --lock-cclock to 0, core clock still remain. Use with rtx 3060.

**Comment by trexminer** [comment]
Make sure you exit the miner by pressing Ctrl+C in the terminal rather than clicking X button to close it. This way T-Rex will have an opportunity to perform a clean up which includes resetting overclock parameters. For now just reboot the system, it'll reset every setting to its default.

**Comment by lauretiu** [comment]
it would be nice if we would get a command to be able to reset it just like we get --lock-cclock. i am using Awesome miner(profit switching software)  and every time it switches algorithms it's a hassle and i have to reset my rig for it to reset the clocks
