### ISSUE TITLE
Can't get power for GPU #0, not supported

### ISSUE THREAD

**Issue by jammiie** [trexminer/T-Rex#506]
ryzen 5 2400g
GTX 1050ti
8gb ram

![mining](https://user-images.githubusercontent.com/85977657/122154331-58cac780-ce97-11eb-822f-d375c0131d86.jpg)

I am new to mining and I don't know what the problem is pls help

**Comment by trexminer** [comment]
Probably power consumption information is not provided by NVML library for your card. It shouldn't affect the mining though.

**Comment by jammiie** [comment]
So it works just fine? Thank you

**Comment by trexminer** [comment]
If there are no error messages and it prints out green `[ OK ]` from time to time, then yes.

**Comment by jammiie** [comment]
Alright, thank you
