### ISSUE TITLE
Not working on hiveos with sero on woolypool

### ISSUE THREAD

**Issue by b8engl** [trexminer/T-Rex#507]
flat, no overclock and no extra parameters
miner very slow, no information on stats (nvml)
tested from 0.20.1 up to latest
not working with extra parameters, all at once or one at a time

exemple
"dag-build-mode": "2"
"api-bind-http": "0"
"api-bind-telnet": "0"
"hide-date": true
"quiet" true

3060 - 460.84 stable
3060 - 460.39

**Comment by trexminer** [comment]
Please post the log file

**Comment by anakein** [comment]
i have error too.

![error](https://user-images.githubusercontent.com/1563663/122252188-73b72f00-cecb-11eb-8763-331efcb6beac.PNG)

**Comment by b8engl** [comment]
`root@SETUP_01:/var/log/miner/t-rex# tail -n 100 t-rex.log

20210616 18:34:15 T-Rex NVIDIA GPU miner v0.20.4  -  [Linux]
20210616 18:34:15 r.acd264734a65
20210616 18:34:15
20210616 18:34:15 NVIDIA Driver v460.84
20210616 18:34:15 CUDA devices available: 5
20210616 18:34:15
20210616 18:34:15 WARN: DevFee 1% (progpow)
20210616 18:34:15
20210616 18:34:15 URL : stratum1+tcp://pool.eu.woolypooly.com:8009
20210616 18:34:15 USER: WPMYjhlbmdsQGdtYWlsLmNvbQ
20210616 18:34:15 PASS: x
20210616 18:34:15
20210616 18:34:15 WARN: Built-in watchdog has been disabled!
20210616 18:34:15 Starting on: pool.eu.woolypooly.com:8009
20210616 18:34:15 Using protocol: stratum1.
20210616 18:34:15 Authorizing...
20210616 18:34:15 Authorized successfully.
20210616 18:34:15 ApiServer: HTTP server started on 127.0.0.1:4059
20210616 18:34:15 ---------------------------------------------------
20210616 18:34:15 For control navigate to: http://127.0.0.1:4059/trex
20210616 18:34:15 ---------------------------------------------------
20210616 18:34:15 ApiServer: Telnet server started on 127.0.0.1:4058
20210616 18:34:15 GPU #0(000100): EVGA GeForce RTX 3060, intensity 20
20210616 18:34:15 GPU #1(000400): EVGA GeForce RTX 3060, intensity 20
20210616 18:34:16 GPU #2(000500): EVGA GeForce RTX 3060, intensity 20
20210616 18:34:16 GPU #3(000600): EVGA GeForce RTX 3060, intensity 20
20210616 18:34:16 GPU #4(000900): EVGA GeForce RTX 3060, intensity 20

---------20210616 18:35:44 ----------
Mining at pool.eu.woolypooly.com:8009
GPU #0: EVGA RTX 3060 - 0.00 H/s, [T:31C, P:33W, F:80%, E:0.00H/W]
GPU #1: EVGA RTX 3060 - 0.00 H/s, [T:31C, P:30W, F:80%, E:0.00H/W]
GPU #2: EVGA RTX 3060 - 0.00 H/s, [T:33C, P:31W, F:80%, E:0.00H/W]
GPU #3: EVGA RTX 3060 - 0.00 H/s, [T:32C, P:33W, F:80%, E:0.00H/W]
GPU #4: EVGA RTX 3060 - 0.00 H/s, [T:32C, P:28W, F:80%, E:0.00H/W]
Hashrate: 0.00 H/s, Shares/min: 0, Avr.P: 155W, Avr.E: 0.00H/W
Uptime: 1 min 30 secs | Algo: progpow | T-Rex v0.20.4


---------20210616 18:36:14 ----------
Mining at pool.eu.woolypooly.com:8009
GPU #0: EVGA RTX 3060 - 0.00 H/s, [T:31C, P:33W, F:80%, E:0.00H/W]
GPU #1: EVGA RTX 3060 - 0.00 H/s, [T:31C, P:30W, F:80%, E:0.00H/W]
GPU #2: EVGA RTX 3060 - 0.00 H/s, [T:33C, P:31W, F:80%, E:0.00H/W]
GPU #3: EVGA RTX 3060 - 0.00 H/s, [T:32C, P:33W, F:80%, E:0.00H/W]
GPU #4: EVGA RTX 3060 - 0.00 H/s, [T:32C, P:28W, F:80%, E:0.00H/W]
Hashrate: 0.00 H/s, Shares/min: 0, Avr.P: 155W, Avr.E: 0.00H/W
Uptime: 2 mins | Algo: progpow | T-Rex v0.20.4`

**Comment by trexminer** [comment]
@b8engl Thanks. You need to add `"coin": "sero"` parameter for it to work.

**Comment by b8engl** [comment]
"coin": "sero"
"intensity": "22"
"gpu-init-mode": "0"
"dag-build-mode": "2"
"api-bind-http": "0"
"api-bind-telnet": "0"
"hide-date": true
"quiet" true

**Comment by b8engl** [comment]
I must have forgot to put it back the argument. 

Although I have ask there, because that's correct place to do in this kind of questions. It seems that they don't care enouhg, always placing links to youtube. That or they really don't want to help. 

This situation has started because the api and the rest of the arguments are not accepeted. I have open the config.json with nano and the values are still there and mine at the bottom.

I have try to add today and they are not accepted. The miner print the error on line 2 form config. It's like deja vu, starting to do the same things that lead me here. 

I'm going to leave the hive, and back to windows.

**Comment by b8engl** [comment]
Anyway, thanks buddy!
