### ISSUE TITLE
Trex miner memory leak

### ISSUE THREAD

**Issue by Jsaini23** [trexminer/T-Rex#508]
Trex miner memory usage keep increasing till the ram is completely full causing a system crash. Virtual page size allocation has been jncrrase which is a temp fix but can this be resolved please

**Comment by trexminer** [comment]
Duplicate of https://github.com/trexminer/T-Rex/issues/262

**Comment by Jsaini23** [comment]
Even if we were to use nonvml that means we cant use absolute core clock

**Comment by trexminer** [comment]
That's right.
Alternatively, you can use the drivers mentioned here that don't leak: https://github.com/nicehash/NiceHashQuickMiner/issues/292

**Comment by Jsaini23** [comment]
Cheers mate appreciate the response
