### ISSUE TITLE
ethermine.org - No connection error

### ISSUE THREAD

**Issue by wgalera** [trexminer/T-Rex#509]
I'm trying to connect to flexpool.io thorugh t-rex, but I'm always getting the same problem, ERROR: No connection, retry after 10 seconds.

When I use the ethermine.org, I don't have this issue.

Below you can see the logs of ethermine and flexpool, please, I didn´t find too much on Google, any help would be most appreciate.

Thanks!
  
###FLEXPOOL:

20210621 10:06:30 T-Rex NVIDIA GPU miner v0.20.4  -  [Windows]
20210621 10:06:30 r.acd264734a65
20210621 10:06:30 
20210621 10:06:30 NVIDIA Driver v465.89
20210621 10:06:30 CUDA devices available: 3
20210621 10:06:30 
20210621 10:06:30 WARN: DevFee 1% (ethash)
20210621 10:06:30 
20210621 10:06:30 URL : stratum+ssl://eth-br.flexpool.io:5555
20210621 10:06:30 USER: 0x4db99537f0e3b8e77239b963570451911a6235fa
20210621 10:06:30 PASS: x
20210621 10:06:30 WRK : RigWin001
20210621 10:06:30 
20210621 10:06:30 Starting on: eth-br.flexpool.io:5555
20210621 10:06:30 ApiServer: HTTP server started on 127.0.0.1:4067
20210621 10:06:30 ---------------------------------------------------
20210621 10:06:30 For control navigate to: http://127.0.0.1:4067/trex
20210621 10:06:30 ---------------------------------------------------
20210621 10:06:30 ApiServer: Telnet server started on 127.0.0.1:4068
20210621 10:06:31 GPU #1(000100): ASUS NVIDIA GeForce RTX 2060, intensity 22, auto-fan 47C, mclock 1040MHz, pl 73%, core clock locked 1050MHz
20210621 10:06:31 GPU #2(000300): ASUS NVIDIA GeForce RTX 2060, intensity 22, auto-fan 47C, mclock 1040MHz, pl 73%, core clock locked 1050MHz
20210621 10:06:31 GPU #0(000400): MSI NVIDIA GeForce RTX 3070, intensity 22, auto-fan 47C, mclock 1200MHz, pl 56%, core clock locked 1075MHz
20210621 10:06:52 ERROR: No connection, retry after 10 seconds
20210621 10:07:23 ERROR: No connection, retry after 10 seconds

###ETHERMINE:
20210621 10:08:30 T-Rex NVIDIA GPU miner v0.20.4  -  [Windows]
20210621 10:08:30 r.acd264734a65
20210621 10:08:30 
20210621 10:08:30 NVIDIA Driver v465.89
20210621 10:08:30 CUDA devices available: 3
20210621 10:08:30 
20210621 10:08:30 WARN: DevFee 1% (ethash)
20210621 10:08:30 
20210621 10:08:30 URL : ssl://us1.ethermine.org:5555
20210621 10:08:30 USER: 0x4db99537f0e3b8e77239b963570451911a6235fa.RigWin001
20210621 10:08:30 PASS: x
20210621 10:08:30 WRK : RigWin001
20210621 10:08:30 
20210621 10:08:30 Starting on: us1.ethermine.org:5555
20210621 10:08:30 ApiServer: HTTP server started on 127.0.0.1:4067
20210621 10:08:30 ---------------------------------------------------
20210621 10:08:30 For control navigate to: http://127.0.0.1:4067/trex
20210621 10:08:30 ---------------------------------------------------
20210621 10:08:30 ApiServer: Telnet server started on 127.0.0.1:4068
20210621 10:08:31 GPU #0(000400): MSI NVIDIA GeForce RTX 3070, intensity 22, auto-fan 52C, mclock 1270MHz, pl 57%, core clock locked 1120MHz
20210621 10:08:31 GPU #2(000300): ASUS NVIDIA GeForce RTX 2060, intensity 22, auto-fan 52C, mclock 1100MHz, pl 73%, core clock locked 1100MHz
20210621 10:08:31 GPU #1(000100): ASUS NVIDIA GeForce RTX 2060, intensity 22, auto-fan 52C, mclock 1100MHz, pl 73%, core clock locked 1100MHz
20210621 10:08:52 Using protocol: stratum1.
20210621 10:08:52 Authorizing...
20210621 10:08:53 Authorized successfully.
20210621 10:08:53 ethash epoch: 422, block: 12677802, diff: 4.29 G

**Comment by trexminer** [comment]
It works fine for me. Most likely it's a networking / firewall / antivirus issue on your side.

**Comment by moms-spaghetti** [comment]
why is your mining pool url ssl://us1.ethermine.org:5555 for ethermine and not stratum+ssl://us1.ethermine.org:5555

**Comment by wgalera** [comment]
> It works fine for me. Most likely it's a networking / firewall / antivirus issue on your side.

I tried all that and nothing...

**Comment by wgalera** [comment]
> why is your mining pool url ssl://us1.ethermine.org:5555 for ethermine and not stratum+ssl://us1.ethermine.org:5555

Both work well... no a specific reason..
