### ISSUE TITLE
CentOS 7

### ISSUE THREAD

**Issue by troyxx** [trexminer/T-Rex#51]
Regarding this output:
/t-rex: /lib64/libc.so.6: version `GLIBC_2.18' not found 
it will only work on CentOS 8
Any chance to build it with GLIBC_2.17?

**Comment by trexminer** [comment]
I'm afraid CentOS 7 and GLIBC_2.17 won't be supported as there are too many compatibility issues between various components we'd need to solve to build against it.

**Comment by trexminer** [comment]
Fixed in 0.22.1

**Comment by sammcj** [comment]
Seems to still be broken in 0.24.8

**Comment by trexminer** [comment]
@sammcj we reverted to building T-Rex on Ubuntu due to some complications with CentOS 7 and low demand
