### ISSUE TITLE
Flexpool worker name as "default"

### ISSUE THREAD

**Issue by jadsonlourenco** [trexminer/T-Rex#511]
Works fine on Ethermine, but on Flexpool show always as "default", I'm running the latest version of T-rex.

**Comment by trexminer** [comment]
Please post your `t-rex` startup cmd line including all parameters

**Comment by jadsonlourenco** [comment]
```t-rex -a $ALGO --devices $DEVICES -o $SERVER1 -o $SERVER2 -w $WORKER -u $WALLET -p $PASS --api-bind-http 0.0.0.0:$PORT```

**Comment by trexminer** [comment]
That looks correct. I couldn't reproduce the issue unfortunately, the flexpool dashboard correctly shows the worker name (I tried with `-o stratum+ssl://eth-br.flexpool.io:5555 -o stratum+ssl://eth-au.flexpool.io:5555` servers. Maybe try their support?

**Comment by jadsonlourenco** [comment]
I'm using `stratum2+ssl`, I will change the protocol to see. TY!
