### ISSUE TITLE
Please fix json in linux - hiveos can't parse commands

### ISSUE THREAD

**Issue by b8engl** [trexminer/T-Rex#512]
"dag-build-mode": "2"
"gpu-init-mode": "0"

**Comment by trexminer** [comment]
JSON config is definitely working on both Windows and Linux.
Please post the config file the miner is started with so that we could help you. Not the screenshot of "extra parameters" or whatever it's called in HiveOS, but the actual config file.
Thanks.

**Comment by b8engl** [comment]
I have a blank config.json

**Comment by b8engl** [comment]
20210625 10:53:47 T-Rex NVIDIA GPU miner v0.20.4  -  [Linux]
20210625 10:53:47 r.acd264734a65
20210625 10:53:47
20210625 10:53:47 NVIDIA Driver v460.39
20210625 10:53:47 CUDA devices available: 5
20210625 10:53:47
20210625 10:53:47 WARN: DevFee 1% (progpow-veil)
20210625 10:53:47
20210625 10:53:47 URL : stratum1+tcp://pool.eu.woolypooly.com:3099
20210625 10:53:47 USER: 
20210625 10:53:47 PASS: x
20210625 10:53:47
20210625 10:53:47 WARN: Built-in watchdog has been disabled!
20210625 10:53:47 Starting on: pool.eu.woolypooly.com:3099
20210625 10:53:47 Using protocol: stratum1.
20210625 10:53:47 Authorizing...
20210625 10:53:48 Authorized successfully.
20210625 10:53:48 progpow-veil epoch: 231, block: 1278188, period: -1, diff: 861.17 M
20210625 10:53:48 progpow-veil epoch: 231, block: 1278188, period: 127818, diff: 861.17 M
20210625 10:53:48 ApiServer: HTTP server started on 127.0.0.1:4059
20210625 10:53:48 ---------------------------------------------------
20210625 10:53:48 For control navigate to: http://127.0.0.1:4059/trex
20210625 10:53:48 ---------------------------------------------------
20210625 10:53:48 ApiServer: Telnet server started on 127.0.0.1:4058
20210625 10:53:48 GPU #0(000100): EVGA Graphics Device, intensity 20
20210625 10:53:48 GPU #1(000400): EVGA Graphics Device, intensity 20
20210625 10:53:48 GPU #2(000500): EVGA Graphics Device, intensity 20
20210625 10:53:48 GPU #3(000600): EVGA Graphics Device, intensity 20
20210625 10:53:48 GPU #4(000900): EVGA Graphics Device, intensity 20
20210625 10:53:50 GPU #2: generating DAG 4.71 GB for epoch 231 ...
20210625 10:53:50 GPU #1: generating DAG 4.71 GB for epoch 231 ...
20210625 10:53:50 GPU #3: generating DAG 4.71 GB for epoch 231 ...
20210625 10:53:50 GPU #4: generating DAG 4.71 GB for epoch 231 ...
20210625 10:54:22 GPU #1: DAG generated [crc: 0630add9, time: 31484 ms], memory left: 6.95 GB
20210625 10:54:22 GPU #3: DAG generated [crc: 0630add9, time: 31518 ms], memory left: 6.95 GB
20210625 10:54:22 GPU #2: DAG generated [crc: 0630add9, time: 31860 ms], memory left: 6.95 GB
20210625 10:54:22 [ OK ] 1/1 - 0.00 H/s, 77ms ... GPU #2
20210625 10:54:22 GPU #4: DAG generated [crc: 0630add9, time: 32094 ms], memory left: 6.95 GB
20210625 10:54:23 GPU #0: DAG generated [crc: 0630add9, time: 32473 ms], memory left: 6.94 GB
20210625 10:54:27 [ OK ] 2/2 - 120.58 MH/s, 74ms ... GPU #0
20210625 10:54:33 progpow-veil epoch: 231, block: 1278189, period: 127818, diff: 861.17 M
20210625 10:54:39 [ OK ] 3/3 - 120.68 MH/s, 70ms ... GPU #3
20210625 10:54:41 [ OK ] 4/4 - 120.69 MH/s, 69ms ... GPU #0
20210625 10:54:45 [ OK ] 5/5 - 120.69 MH/s, 72ms ... GPU #3
20210625 10:54:45 [ OK ] 6/6 - 120.69 MH/s, 71ms ... GPU #2
20210625 10:54:49 [ OK ] 7/7 - 120.70 MH/s, 72ms ... GPU #1
20210625 10:54:53 [ OK ] 8/8 - 120.70 MH/s, 74ms ... GPU #1

-----------------20210625 10:54:58 ------------------
Mining at pool.eu.woolypooly.com:3099, diff: 861.17 M
GPU #0: EVGA Graphics Device - 24.12 MH/s, [T:64C, P:138W, F:80%, E:176kH/W], 2/2 R:0%
GPU #1: EVGA Graphics Device - 24.13 MH/s, [T:62C, P:136W, F:80%, E:179kH/W], 2/2 R:0%
GPU #2: EVGA Graphics Device - 24.14 MH/s, [T:63C, P:137W, F:80%, E:177kH/W], 2/2 R:0%
GPU #3: EVGA Graphics Device - 24.15 MH/s, [T:64C, P:141W, F:80%, E:173kH/W], 2/2 R:0%
GPU #4: EVGA Graphics Device - 24.17 MH/s, [T:64C, P:140W, F:80%, E:174kH/W]
Hashrate: 120.70 MH/s, Shares/min: 13.705 (Avr. 7.385), Avr.P: 687W, Avr.E: 176kH/W
Uptime: 1 min 10 secs | Algo: progpow-veil | T-Rex v0.20.4

**Comment by b8engl** [comment]
drwxr-xr-x 2 user user     4096 Jun 25 10:47 .
drwxr-xr-x 3 user user     4096 Jun 22 15:44 ..
-rw-rw-rw- 1 user user      444 May 27 10:15 config_global.json
lrwxrwxrwx 1 user user       34 May 27 10:15 config.json -> /run/hive/miners/t-rex/config.json
-rw-r--r-- 1 root root     1024 Jun 25 10:42 .config.json.swp
-rw-r--r-- 1 root root     1024 Jun 25 10:47 ..config.json.swp.swp
-rw-rw-rw- 1 user user    29295 May 27 10:15 README.md
-rwxrwxrwx 1 user user 35171002 May 27 10:15 t-rex

**Comment by b8engl** [comment]
config_global.json

{
  "pools": [
    {
      "user": "wallet.worker",
      "url": "stratum+tcp://url:port",
      "pass": "x"
    }
  ],

  "api-bind-telnet": "127.0.0.1:4058",
  "api-bind-http": 0,
  "json-response": true,

  "retries": 3,
  "retry-pause": 10,
  "timeout": 180,
  "no-watchdog": true,

  "algo": "x16r",
  "hashrate-avr": 30,

  "log-path": "/var/log/miner/t-rex/t-rex.log",

  "exit-on-cuda-error": true,
  "exit-on-connection-lost": false

**Comment by b8engl** [comment]
I apply,
"api-bind-telnet": "0"
"api-bind-http": "0"

Still print,
20210625 11:01:10 ---------------------------------------------------
20210625 11:01:10 For control navigate to: http://127.0.0.1:4059/trex
20210625 11:01:10 ---------------------------------------------------

**Comment by b8engl** [comment]
{
  "pools": [
    {
      "user": "",
      "url": "stratum1+tcp://pool.eu.woolypooly.com:3099",
      "pass": "x",
      "worker": ""
    }
  ],
  "api-bind-telnet": "0",
  "api-bind-http": "127.0.0.1:4059",
  "json-response": true,
  "retries": 3,
  "retry-pause": 10,
  "timeout": 180,
  "no-watchdog": true,
  "algo": "progpow-veil",
  "hashrate-avr": 30,
  "log-path": "/var/log/miner/t-rex/t-rex.log",
  "exit-on-cuda-error": true,
  "exit-on-connection-lost": false,
  "quiet": true,
  "_notes": "Generated at Fri Jun 25 11:10:39 BST 2021"
}

**Comment by b8engl** [comment]
I apply,
"api-bind-telnet": "0"
"api-bind-http": "0"
"quiet": true

Still print,
20210625 11:10:41 ApiServer: HTTP server started on 127.0.0.1:4059
20210625 11:10:41 ---------------------------------------------------
20210625 11:10:41 For control navigate to: http://127.0.0.1:4059/trex
20210625 11:10:41 ---------------------------------------------------
...
20210625 11:12:15 progpow-veil epoch: 231, block: 1278211, period: 127821, diff: 861.17 M
20210625 11:12:17 [ OK ] 10/10 - 120.59 MH/s, 72ms ... GPU #1
20210625 11:12:22 [ OK ] 11/11 - 120.60 MH/s, 70ms ... GPU #0
20210625 11:12:49 [ OK ] 12/12 - 120.66 MH/s, 74ms ... GPU #4
20210625 11:12:52 [ OK ] 13/13 - 120.66 MH/s, 75ms ... GPU #1
20210625 11:12:53 [ OK ] 14/14 - 120.67 MH/s, 72ms ... GPU #3
20210625 11:13:12 [ OK ] 15/15 - 120.65 MH/s, 73ms ... GPU #4
20210625 11:13:20 [ OK ] 16/16 - 120.65 MH/s, 72ms ... GPU #2
20210625 11:13:49 [ OK ] 17/17 - 120.65 MH/s, 68ms ... GPU #3
20210625 11:13:49 [ OK ] 18/18 - 120.65 MH/s, 73ms ... GPU #0
20210625 11:14:02 [ OK ] 19/19 - 120.65 MH/s, 71ms ... GPU #2
20210625 11:14:14 [ OK ] 20/20 - 120.65 MH/s, 68ms ... GPU #2
20210625 11:14:14 [ OK ] 21/21 - 120.65 MH/s, 71ms ... GPU #4
20210625 11:14:20 progpow-veil epoch: 231, block: 1278212, period: 127821, diff: 1.36 G
20210625 11:14:20 progpow-veil epoch: 231, block: 1278212, period: 127821, diff: 1.36 G
20210625 11:14:33 [ OK ] 22/22 - 120.66 MH/s, 71ms ... GPU #0
20210625 11:14:33 [ OK ] 23/23 - 120.67 MH/s, 71ms ... GPU #0
20210625 11:15:16 [ OK ] 24/24 - 120.65 MH/s, 72ms ... GPU #3
20210625 11:15:21 [ OK ] 25/25 - 120.65 MH/s, 74ms ... GPU #0
20210625 11:15:31 [ OK ] 26/26 - 120.65 MH/s, 73ms ... GPU #3
20210625 11:15:34 [ OK ] 27/27 - 120.65 MH/s, 74ms ... GPU #0

**Comment by b8engl** [comment]
{
  "pools": [
    {
      "user": "",
      "url": "stratum1+tcp://pool.eu.woolypooly.com:3099",
      "pass": "x",
      "worker": ""
    }
  ],
  "api-bind-telnet": "0",
  "api-bind-http": "127.0.0.1:4059",
  "json-response": true,
  "retries": 3,
  "retry-pause": 10,
  "timeout": 180,
  "no-watchdog": true,
  "algo": "progpow-veil",
  "hashrate-avr": 30,
  "log-path": "/var/log/miner/t-rex/t-rex.log",
  "exit-on-cuda-error": true,
  "exit-on-connection-lost": false,
  "api-read-only": true,
  "quiet": true,
  "_notes": "Generated at Fri Jun 25 11:22:49 BST 2021"
}

**Comment by trexminer** [comment]
I see. Try contacting HiveOS support to see if there are any guides on how to propagate extra t-rex params to the config file. They don't get applied in your case for some reason.

**Comment by b8engl** [comment]
But I have

**lrwxrwxrwx** 1 user user 34 May 27 10:15 config.json -> /run/hive/miners/t-rex/config.json

**Comment by b8engl** [comment]
And in some cases I have

**"api-bind-telnet": "127.0.0.1:4059",
"api-bind-http": "127.0.0.1:4059",**
"json-response": true,
"retries": 3,
"retry-pause": 10,
"timeout": 180,
"no-watchdog": true,
"algo": "progpow-veil",
"hashrate-avr": 30,
"log-path": "/var/log/miner/t-rex/t-rex.log",
"exit-on-cuda-error": true,
"exit-on-connection-lost": false,
**"api-bind-telnet": "0",
"api-bind-http": "0",
"quiet": true,**

**Comment by b8engl** [comment]
Ah ok I see your point... I apply on hive system.

**Comment by b8engl** [comment]
Thanks buddy!
