### ISSUE TITLE
Total Power not showing with 1050 Ti and other cards

### ISSUE THREAD

**Issue by ganzocrypt** [trexminer/T-Rex#516]
I found an issue (not a big deal) on t-rex on ubuntu 18.
I have a 1050 Ti  (and other 10 nVidia cards) which does not report power and efficiency (and that's ok). 
But the total power for the rig, which contains other cards too, is not reported.

The total power should be reported ignoring the 1050 Ti.

**Comment by trexminer** [comment]
Thanks. Should be fixed in https://github.com/trexminer/T-Rex/releases/tag/0.21.0
