### ISSUE TITLE
Is it possible to set different powerlimit / clock settings for each gpu in the config.json?

### ISSUE THREAD

**Issue by moms-spaghetti** [trexminer/T-Rex#519]
Multi gpu setup, all the same card but varying performance between each one.

Is possible to set different clocks / power limits etc for each card in the config json rather than running multiple instances? 
Thanks

**Comment by pdieppa** [comment]
Example for clock; power limit should follow the same format.

--lock-cclock              Specifies desired locked GPU core clock speed in MHz. (default: 0 - disabled).
                                   Requires running the miner with administrative privileges.
                                   Example: --lock-cclock 1000 (applies clock 1000Mhz to all cards that support this functionality)
                                            --lock-cclock 1000,1300,0 (applies clock 1000Mhz to GPU #0, 1300MHz to GPU #1, ignore GPU #2)

**Comment by moms-spaghetti** [comment]
very helpful thank you

**Comment by moms-spaghetti** [comment]
> Example for clock; power limit should follow the same format.
> 
> --lock-cclock Specifies desired locked GPU core clock speed in MHz. (default: 0 - disabled).
> Requires running the miner with administrative privileges.
> Example: --lock-cclock 1000 (applies clock 1000Mhz to all cards that support this functionality)
> --lock-cclock 1000,1300,0 (applies clock 1000Mhz to GPU #0, 1300MHz to GPU #1, ignore GPU #2)

just to update, worked perfectly for power limits. Many thanks
