### ISSUE TITLE
how to use a network proxy with T-rex

### ISSUE THREAD

**Issue by xiaod-dev** [trexminer/T-Rex#520]
My network is not stable to connecting with some pools, so I am considering use a VPN to accelerate the speed. Now I have a Http Proxy and Sock5 proxy endpoint, How can I connecting pools with these network proxy tools with T-rex?

**Comment by trexminer** [comment]
Duplicate of https://github.com/trexminer/T-Rex/issues/399

**Comment by xiaod-dev** [comment]
Thanks for reply. I 've looked at #139 , It seems still open. So the socks5 proxy is still WIP?

**Comment by trexminer** [comment]
> So the socks5 proxy is still WIP?

It's not. We haven't started implementing it.

**Comment by XFNeo** [comment]
Hi @trexminer any updates?
