### ISSUE TITLE
Powerconsumption setting at linux

### ISSUE THREAD

**Issue by horphi0815** [trexminer/T-Rex#522]
Hi, 
is it possible to change the power limits on linux?

Best regards,
Phil

**Comment by trexminer** [comment]
Hi, yes, `--pl` is available on Linux as of version 0.21.5

**Comment by horphi0815** [comment]
> Hi, yes, `--pl` is available on Linux as of version 0.21.5

Hi,
can it be also embedded in the config file?

**Comment by trexminer** [comment]
Yes, see `config_example`
