### ISSUE TITLE
21 on Windows 2 GPU ERG = high CPU usage

### ISSUE THREAD

**Issue by GinterVonHelsig** [trexminer/T-Rex#523]
When running version 21, 2 GPUs, ERG / autolykos2 algo, cpu constant @25%.  ETH 0%.

![image](https://user-images.githubusercontent.com/86945526/124423714-baae7c80-dd33-11eb-8556-46da36e8936c.png)

**Comment by trexminer** [comment]
@GinterVonHelsig What's your NVIDIA driver version?

**Comment by GinterVonHelsig** [comment]
466.77

Also, as of note, upgraded my hiveOS instance, same issue, my load average went from 0.02 to:

![image](https://user-images.githubusercontent.com/86945526/124510802-9e95f400-dda2-11eb-9a80-87780f30815e.png)

So, essentially the identical manifestation of the Windows problem.

**Comment by megalolka** [comment]
The same situation is on Windows 10 with 470.05 (developer) driver - CPU load is 100% with 3 RTX 3060 cards on ERG.

**Comment by trexminer** [comment]
Thanks. The issue will be fixed in the next version.

**Comment by trexminer** [comment]
This should be fixed in https://github.com/trexminer/T-Rex/releases/tag/0.21.1
