### ISSUE TITLE
Watchdog killing T-Rex before DAG generated on KAWPOW algo

### ISSUE THREAD

**Issue by adamnoffie** [trexminer/T-Rex#53]
I have a system with two Quadro M2000 video cards.  If I attempt to mine Ravencoin on Ravenminer with the new kawpow algo, T-Rex will start up and say that it is generating a 2.30 GB DAG for each of the GPU.  Then the watchdog will start spitting out messages about how the GPUs are both idle.  Even if one of the DAG is eventually generated, the Watchdog will kill and restart T-Rex before the second one is generated and the whole thing starts over again.

It seems to me that perhaps the watchdog should not start checking the GPUs for activity until after the DAG is generated?

**Comment by adamnoffie** [comment]
I meant to add that if I start T-Rex with the no-watchdog option, it will generate both DAG and start mining successfully.

**Comment by trexminer** [comment]
Thank you for the report. Will look into it.

**Comment by trexminer** [comment]
Fixed in 0.17.2
