### ISSUE TITLE
ERROR: Can't start miner, GPU fan control is not supported on Linux

### ISSUE THREAD

**Issue by b8engl** [trexminer/T-Rex#537]
using config.json with `"fan": "80",`

`nvidia-smi`
![smi](https://user-images.githubusercontent.com/29173784/126064499-75ec86c0-94f3-46b0-ad16-c65a7e9c7a46.PNG)

`ls -lah /usr/lib/x86_64-linux-gnu/ | grep cuda`
lrwxrwxrwx  1 root root   12 Jun 16 03:21 libcuda.so -> libcuda.so.1
lrwxrwxrwx  1 root root   20 Jun 16 03:21 libcuda.so.1 -> libcuda.so.470.42.01
-rw-r--r--  1 root root  22M Jun 15 22:49 libcuda.so.470.42.01
lrwxrwxrwx  1 root root   18 Mar 16  2020 libicudata.so.60 -> libicudata.so.60.2
-rw-r--r--  1 root root  26M Mar 16  2020 libicudata.so.60.2

wsl2 kernel 5.10.43
docker version 20.10.7, build f0df350

**Comment by trexminer** [comment]
Fan control is a Windows only feature for now, it is under `GPU fine tuning (Windows only)` section in the readme.

**Comment by b8engl** [comment]
ups, sorry!
