### ISSUE TITLE
Rejected shares with new version 0.21.4

### ISSUE THREAD

**Issue by bunkaq** [trexminer/T-Rex#539]
Hello,

I had to revert to 0.20.4 because I had on ETH (ethminer.org) about 0.5% rejected or even few invalid shares with new 0.21.4. Again 0 with 0.20.4

All at linux HiveOS or Ubuntu 20.04 with many different Nvidia cards (3080,3070,1060,2060s,1660,T4,P2000) .... but all had same issue with new version and ETH....

My hash rate on one rig dropped due to this from 300 to 250 only within 1 day of use

**Comment by adiel91** [comment]
I have the same problem with latest 0.25.2 TRex miner.
dag build mode set to 2 (written as recommended for 30xxx cards).
using ethermine pools, with 2 GPUs - 3090, 3070. 
3070 shows 0.5% invalid shares within 12 hours, the 3090 shows none (0%)

@trexminer is that a known issue? something we're doing wrong?
Thank you!

**Comment by trexminer** [comment]
@adiel91 dial down the memory OC on that 3070

**Comment by adiel91** [comment]
Its on +1350, what lower value you recommend?

**Comment by adiel91** [comment]
@trexminer i lowered to 1100 and still same results.
If i run the miner, wait a minute, and only then apply OC settings to 3070, everything working ok

**Comment by adiel91** [comment]
@trexminer this seems to be a wide issue related to DAG generation while OC already applied, see https://www.reddit.com/r/EtherMining/comments/kokgh9/3060ti_rejected_shares_if_i_oc_before_generating/
Even when applying oc after DAG Generated, if during mining DAG will be re generated, the issue will occur again.

Do you assume it somehow can be fixed from miner side?

**Comment by trexminer** [comment]
@adiel91 assuming you're running Windows, you can set overclock settings through T-Rex rather than MSI AB or other third party tools, and in that case it'll be applied after DAG has been generated.

@bunkaq To answer the OP, try 0.25.2 and open a create a new ticket if the issue still persists.
