### ISSUE TITLE
Computer very slow

### ISSUE THREAD

**Issue by owen7guo** [trexminer/T-Rex#54]
After switching to 0.15.3 with new algo, computer get really slow when mining. I was running intensity of 18 with x16rv2 and computer remains ability for normal usage. But now even I set intensity to 8, computer still gets unusable lag, any new setting for this? Thanks guys

**Comment by adamnoffie** [comment]
Same here - I think I have seen others say that the intensity settings seem to be ignored for kawpow algo.

**Comment by trexminer** [comment]
@owen7guo adamnoffie is correct, the intensity setting was ignored for kawpow, however that's fixed in 0.15.5 and above. Please try the latest version and let me know how it goes with different intensity settings
