### ISSUE TITLE
Can't choose stratum+tcp - miner always setting stratum1+tcp

### ISSUE THREAD

**Issue by b8engl** [trexminer/T-Rex#542]
![stratum](https://user-images.githubusercontent.com/29173784/126314660-76e08e5d-72a6-4c6d-bdcc-b67de8d21f8f.PNG)

**Comment by pdieppa** [comment]
Please post the complete command line

**Comment by b8engl** [comment]
basic command connection, but the important is that the stratum+tcp is not apply!

**Comment by pdieppa** [comment]
I asked for the command line to see what pool you are using and how you are trying to connect to it. There are not many but some pools require stratum+ssl and will reject connections with tcp.

**Comment by b8engl** [comment]
I didn't say that the connection required ssl!

**Comment by b8engl** [comment]
I'm just saying that I applied stratum+tcp and get stratum1+tcp

**Comment by b8engl** [comment]
why release parameter ` -o, --url ` if miner in the end choose the the method... pointless!

**Comment by pdieppa** [comment]
I was not aware that stratum was not the same as stratum1. I learned something today.

**Comment by trexminer** [comment]
@b8engl  `stratum` is like an "auto" mode and it defaults to either `stratum1` or `stratum2` depending on the algorithm / pool
