### ISSUE TITLE
Error setting gpu-init-mode

### ISSUE THREAD

**Issue by pdieppa** [trexminer/T-Rex#544]
I just downloaded 0.21.4 and tried to set the gpu-init-mode to 1 and t-rex is giving me an error. Am I missing something?

![image](https://user-images.githubusercontent.com/74556152/126647387-949e1bd5-a545-4228-8e94-96be307c3de4.png)

![image](https://user-images.githubusercontent.com/74556152/126647414-beceaec4-4d79-40de-b025-86af8a4c2969.png)

**Comment by trexminer** [comment]
Should be `"gpu-init-mode": 1` without the double quotes
