### ISSUE TITLE
Inno3D GPUs sensors support

### ISSUE THREAD

**Issue by sur1v** [trexminer/T-Rex#545]
Latest available miner version wont detect properly this GPU brand/cards. Tested with Inno3D RTX 3060 TWIN X2 OC and Inno3D RTX 3090 ICHILL X4.  Most importantly, is not possible to check memory temps on the 3090. Thanks!

**Comment by trexminer** [comment]
Could you clarify what you mean by 
> wont detect properly this GPU brand/cards

?

**Comment by sur1v** [comment]
It's basically detected has a generic "NVIDIA RTX 3090" only with core temp available

**Comment by trexminer** [comment]
Does HWiNFO report the memory junction temperature for it?

**Comment by sur1v** [comment]
Not sure, this GPU is running with HiveOS. Any equivalent?

**Comment by trexminer** [comment]
Oh, okay. Memory temperature is a Windows only feature for now.

**Comment by sur1v** [comment]
Ok, thanks anyways!
