### ISSUE TITLE
Please help: I'm having this error: TREX: Can't find nince with device [ID=4, GPU: #4], cuda exception: CUDA_ERROR_LAUNCH_FAILED, try to reduce overclock to stabilize GPU state

### ISSUE THREAD

**Issue by CristhianJP** [trexminer/T-Rex#546]
Please help: I'm having this error: TREX: Can't find nince with device [ID=4, GPU: #4], cuda exception: CUDA_ERROR_LAUNCH_FAILED, try to reduce overclock to stabilize GPU state.

That GPU is a RTX 3080 EVGA FTW3 with PL: 230, Core Clock: -200, Mem Clock: 2000 , the error appears every 2 hours, 1 hour. Please, any help with this problem would be very appreciate 

@trexminer please!

Thanks in advance.

**Comment by trexminer** [comment]
Reduce you mem clock like the error message suggests

**Comment by CristhianJP** [comment]
> Reduce you mem clock like the error message suggests

Hi @trexminer, now I’m having this problem:

kernel: NVRM: Xid (PCI:0000:08:00): 69, pid=2448, Class Error: ChId 0015, Class 0000c7c0, Offset 00000160, Data ffffffff, ErrorCode 00000004
Jul 25 06:41:44 CristhianJP_RTX kernel: NVRM: Xid (PCI:0000:08:00): 69, pid=26803, Class Error: ChId 0014, Class 0000c7c0, Offset 00001b0c, Data ffffffff, ErrorCode 0000000c
Jul 25 15:34:34 CristhianJP_RTX kernel: NVRM: Xid (PCI:0000:01:00): 62, pid=24349, 0000(0000) 00000000 00000000
Jul 25 15:34:34 CristhianJP_RTX kernel: NVRM: Xid (PCI:0000:01:00): 45, pid=24349, Ch 00000010

could you help me, please? 🙏🏻

**Comment by Zefirott** [comment]
If you add a card gpu in windows, add virtual memory

**Comment by CristhianJP** [comment]
I've resolved the problem changing the slot of riser and lowered the memory clock to 1900 and core clock 1100, PL 230. 3 days working without restarts. I'll check how to add virtual memory in windows. Thanks!
