### ISSUE TITLE
No way to set pstate for selected devices only

### ISSUE THREAD

**Issue by nadlabak** [trexminer/T-Rex#547]
E.g. "pstate": "p0,0,0,0,0,0" is rejected as an invalid option in config file.

> ERROR: Can't start miner, invalid pstate value 'p0,0,0,0,0,0', only pstate 'p0' is supported

**Comment by trexminer** [comment]
This is a known limitation. P-State lock can only be applied at the driver level and affects all GPUs.

**Comment by nadlabak** [comment]
I see, thanks.
