### ISSUE TITLE
How to configure Ergo Mining on nanopool via T Rex Miner

### ISSUE THREAD

**Issue by Naveen51615161** [trexminer/T-Rex#548]
Kindly suggest how to configure email address & other such settings in T Rex miner Ergo mining nano pool because the help file doesn't show this. Email address change is required to change payout in nanopool. So kindly suggest ASAP

**Comment by trexminer** [comment]
Try setting `-u` to `<your_wallet_address>.<worker_name>/some@email.org`, this was working for ETH, probably it's the same for ERG.
