### ISSUE TITLE
Problem with T Rex nvidia

### ISSUE THREAD

**Issue by cryptopeach** [trexminer/T-Rex#55]
T Rex miner on KAWPOW algo always says that the GPU (my GPU as 4 GB VRAM) is idle and doesn't mine, i disable the watchdog but the problem persists. Any idea on why this is happening?

**Comment by trexminer** [comment]
Could you confirm if the issue persists in 0.17.2?

**Comment by cryptopeach** [comment]
Hi,

Now this error shows up
[image: image.png]

trexminer <notifications@github.com> escreveu no dia sexta, 18/09/2020 à(s)
12:00:

**Comment by trexminer** [comment]
@cryptopeach the image didn't come through

**Comment by cryptopeach** [comment]
No dia sexta-feira, 9 de outubro de 2020, trexminer <
notifications@github.com> escreveu:
