### ISSUE TITLE
ayuda tengo este error: no se puede iniciar el minero, no se pudo inicializar el mapa del dispositivo: no se puede obtener busid, código -6

### ISSUE THREAD

**Issue by OscarBusy** [trexminer/T-Rex#551]
descargue la nueva actualizacion y no me deja iniciar por ese error, tambien me dice C:\Users\User \Desktop\t-rex-0.21.5-win>pause
Presione una tecla para continuar

**Comment by trexminer** [comment]
Duplicate of https://github.com/trexminer/T-Rex/issues/529
