### ISSUE TITLE
Hashing power lowered in 0.21.5

### ISSUE THREAD

**Issue by Tanujshriyan** [trexminer/T-Rex#552]
Same OC settings would give 50MH/s on 0.21.4 but after the update, it barely crosses 48.5. Gonna try downgrading the miner check if that's the issue, will update soon.

**Comment by Tanujshriyan** [comment]
Definitely something changed in the newer version. Getting 50MH/s over here

**Comment by trexminer** [comment]
Please provide more details: GPU model, algorithm, OS, OC settings.

**Comment by Tanujshriyan** [comment]
[OC Settings](https://paste.pics/DCUGS) RTX 3060 NON-LHR, Running on 470.5 drivers. I'm using Windows 11 though.

**Comment by trexminer** [comment]
Thanks. Are you mining ETH?

**Comment by Tanujshriyan** [comment]
Yes!

**Comment by trexminer** [comment]
So, when you run 0.21.4 with the OC settings that give you 50MH/s, what kernel does the miner select after benchmarking? It's printed out in the console after DAG creation.
You can check the same for 0.21.5, and if the kernels are different between the two versions, then just select it manually on 0.21.5 through `--kernel` parameter. Let me know if that helps.

**Comment by Tanujshriyan** [comment]
Using kernel #4

**Comment by Tanujshriyan** [comment]
I guess it's working now! weird it wasn't for couple of days
