### ISSUE TITLE
T-Rex + HiveOs Extra config arguments type?

### ISSUE THREAD

**Issue by Tor283** [trexminer/T-Rex#554]
Dear friends, how i can use  extra config arguments for T-Rex in HiveOS?

I need this one: 
--gpu-init-mode 1 
--keep-gpu-busy 
--no-nvml

But in HiveOs it is dont work, for example i used "no-nvml" - but miner didnt start with this arguments

**Comment by trexminer** [comment]
HiveOS sets up T-Rex using json config, so the parameters must be specified the way `config_example` in miner archive lists it, e.g. `"no-nvml": true`.

**Comment by Tor283** [comment]
> HiveOS sets up T-Rex using json config, so the parameters must be specified the way `config_example` in miner archive lists it, e.g. `"no-nvml": t
