### ISSUE TITLE
Cannot override worker name

### ISSUE THREAD

**Issue by lordlightman** [trexminer/T-Rex#556]
Hello,

I encountered an issue which prevents me from overriding a worker name specified in config file. I tried placing a '--worker' command line arg before '--config' and after it to no avail.

I attached my batch, config file and a part of my log.

I use T-Rex v0.21.5 on my Windows 10.

[trex-files.zip](https://github.com/trexminer/T-Rex/files/6913165/trex-files.zip)

**Comment by trexminer** [comment]
Thanks. We'll fix it in the next version.

**Comment by trexminer** [comment]
Should be fixed in 0.21.6
