### ISSUE TITLE
T-Rex 0.21.5 (windows) - Virus detection positive/false 

### ISSUE THREAD

**Issue by JosefBocan** [trexminer/T-Rex#559]
**Hi Guys,** 

First of all thank you very much for your software. 
I would like to have a question for an community and also for you. Due the download of new version of your T-Rex application my comuter find an **vigorf.a** malware(trojan) in you application I would like to be sure that your application is correctly signed and there is nothing like these stuff brought to zip file. If it's just a problem of your windows zip file I am able to builld it by my own linux machine and use without using the zip file. Can you write me here your opinium or if someone can gimme a hint about false-positive/positive virus detection? 

_FYI: I will only accept this hint about false-positive/positive from @trexminer._

Thank you for your work and also for an answer. Have a Great day miners 💯

**Comment by trexminer** [comment]
It is a false positive. We get asked this question every release.
See https://github.com/trexminer/T-Rex#antivirus-alerts

**Comment by JosefBocan** [comment]
Thank you for an answer. I normally expect the Classic virus but there was one more and wanted to know Why. Anyway Thank you.
