### ISSUE TITLE
System crash because of a lost connection.  v0.21.4  gtx1080 

### ISSUE THREAD

**Issue by kukucqc** [trexminer/T-Rex#560]
Hey guys,

A dumb and strange question here, my t-rex will crash my computer when there is no internet connection, i don't know why and not sure if this question has been asked before.   

T-rex works perfectly when the internet is ON.

Trex：0.21.4
GPU：Gtx1080
Driver: 466.47
MT -3

Workaround is adding --keep-gpu-busy, thanks to Backslash!

Thanks!
Joseph

**Comment by trexminer** [comment]
Yes, `--keep-gpu-busy` was added exactly for that reason :smile:
