### ISSUE TITLE
Is it possible to launch a .bat executing each "x" hours a different algorithm?

### ISSUE THREAD

**Issue by oskuroCrypto** [trexminer/T-Rex#561]
Hi!,

would it be possible to create a .bat file that launches 2 different Algorithms, 1 after the other, with a 12h duration time for each one for instance?.

What I mean, a .bat with something like for each line:

Commands for mining Ethereum
timeout for 12hours
Commands for mining "Ravencoin/whatever"
timeout for 12hours

and then it would start over again with Ethereum.

Do you know if that´s possible?.

I'm trying to find the way to do it, but so far no luck.

Or another .bat file that calls 2.bat files, something like:

Call "Eth.bat"
Call "Rvn.bat"

with a delay in between of "12hours".

Thanks!

EDIT: Ok problem solved, I found the way :)

**Comment by trexminer** [comment]
Glad you solved it, but please post your solution for the benefit of future readers.
My suggestion would be using `--time-limit` T-Rex option which would tell the miner to terminate after mining for N seconds, and then the execution would move on to the next line in your .bat
