### ISSUE TITLE
ERG 2miners: Wait on data is timed out

### ISSUE THREAD

**Issue by lordlightman** [trexminer/T-Rex#568]
Hello,

Recently I started mining ERG on 2miners pool. Everything is working fine except I get an occasional time-out every 15-20 minutes. After it the miner connects and authorizes successfully.

Can you help me understand what's causing this issue?

Here is an example from the logs:

```
-------------20210812 11:22:53 --------------
Mining at erg.2miners.com:18888, diff: 8.73 G
GPU #1: EVGA RTX 3060 Ti - 170.98 MH/s, [T:55C, P:143W, F:83%, E:1.20MH/W], 64/64 R:0% I:0%
Shares/min: 1.328 (Avr. 1.171)
Uptime: 47 mins 52 secs | Algo: autolykos2 | T-Rex v0.21.6
WD: 58 mins 50 secs, shares: 64/64 , restarts 1

20210812 11:23:07 Wait on data is timed out, 120 seconds have passed, 0 bytes in socket remained
20210812 11:23:07 WARN: Connection with pool timed out. Trying to reconnect...
20210812 11:23:07 Extranonce is set to: c209
20210812 11:23:07 Authorizing...
20210812 11:23:07 Authorized successfully.
20210812 11:23:07 autolykos2 block: 552915, diff: 8.73 G

-------------20210812 11:23:23 --------------
Mining at erg.2miners.com:18888, diff: 8.73 G
GPU #1: EVGA RTX 3060 Ti - 170.98 MH/s, [T:55C, P:143W, F:83%, E:1.20MH/W], 64/64 R:0% I:0%
Shares/min: 1.328 (Avr. 1.171)
Uptime: 48 mins 22 secs | Algo: autolykos2 | T-Rex v0.21.6
WD: 59 mins 20 secs, shares: 64/64 , restarts 1
```

I've attached my config and the log.

[trex-erg-2miners-timeout.zip](https://github.com/trexminer/T-Rex/files/6977489/trex-erg-2miners-timeout.zip)

**Comment by trexminer** [comment]
Hi. There hadn't been any network activity for 2 minutes, so the connection timed out. You can increase the timeout by changing `"timeout" : 120` setting in your config file. It's 300 seconds by default.

**Comment by lordlightman** [comment]
Thanks, that seems to have helper. Although, I am concerned now that there is no network activity from the pool for such periods of time. Can I be missing out some profitability because of this?

**Comment by trexminer** [comment]
Not likely. I think you were just unlucky not to find a share within that 2min window and also no one found a block, so the pool didn't send anything over the network either.

**Comment by lordlightman** [comment]
Okay, thanks for the info.

**Comment by darck92** [comment]
and when you are mining alone and you get that which is what happens
