### ISSUE TITLE
Rejected shares display issue on monitoring page

### ISSUE THREAD

**Issue by lordlightman** [trexminer/T-Rex#569]
Hello,

Since 0.21.6 I started experiencing a weird display issue with rejected shared on my 2nd GPU in my PC.

Here is what it looks like:

![image](https://user-images.githubusercontent.com/88287379/129245499-fd6f2a32-a6c0-4cef-8807-4bcbe44b2311.png)

I've attached a config file that I use.

[trex-rej-web-ui-issue.zip](https://github.com/trexminer/T-Rex/files/6977547/trex-rej-web-ui-issue.zip)

**Comment by trexminer** [comment]
Hi. So, what's weird about it?

**Comment by lordlightman** [comment]
Hello,

Well, the rejects data is only displayed on the right of the pipe symbol. Left always displays 0%.

Actually, I just ran T-Rex miner on my first GPU and everything looks fine there - only one reject entry.

Here is a screenshot with comparison:

![image](https://user-images.githubusercontent.com/88287379/129359216-265bec22-64d1-4fd9-8184-0442a37b8268.png)

Is it supposed to be displayed this way or is it an issue?

**Comment by trexminer** [comment]
Oh, I see. It's not a pipe symbol, it's `I` as in "**I**nvalid shares". And `R` is for the ones rejected by the pool.

**Comment by lordlightman** [comment]
Oh, sorry, my bad. I thought it was a pipe and got confused.
