### ISSUE TITLE
Infinite loop after CUDA crash

### ISSUE THREAD

**Issue by ivnish** [trexminer/T-Rex#574]
After

20210815 04:26:40 TREX: Can't stop device [ID=2, GPU #2], cuda exception: CUDA_ERROR_ILLEGAL_ADDRESS, try to reduce overclock to stabilize GPU state

I have infinite miner's restart

Like this

20210815 04:26:40 TREX: Can't stop device [ID=2, GPU #2], cuda exception: CUDA_ERROR_ILLEGAL_ADDRESS, try to reduce overclock to stabilize GPU state
20210815 04:26:40 WARN: Miner is going to shutdown...
20210815 04:26:40 Main loop finished. Cleaning up resources...
20210815 04:26:40 ApiServer: stopped listening on 0.0.0.0:4067
20210815 04:26:40 ApiServer: stopped listening on 127.0.0.1:4068
20210815 04:26:43 T-Rex finished.
20210815 04:26:43 WARN: WATCHDOG: T-Rex does not exist anymore, restarting...
20210815 04:27:00 T-Rex NVIDIA GPU miner v0.21.5  -  [Windows]
20210815 04:27:00 r.738648414f44
20210815 04:27:00 
20210815 04:27:05 NVIDIA Driver v470.05
20210815 04:27:05 CUDA devices available: 5
20210815 04:27:05 
20210815 04:27:05 WARN: DevFee 1% (ethash)
20210815 04:27:05 
20210815 04:27:05 URL : stratum+tcp://eu-eth.hiveon.net:4444
20210815 04:27:05 USER: 0x5d9002608856e3eb4e383ad3879c0c987d8907e5
20210815 04:27:05 PASS: x
20210815 04:27:05 WRK : rig1
20210815 04:27:05 
20210815 04:27:11 Starting on: eu-eth.hiveon.net:4444
20210815 04:27:13 Using protocol: stratum1.
20210815 04:27:13 Authorizing...
20210815 04:27:13 Authorized successfully.
20210815 04:27:13 ethash epoch: 434, diff: 5.00 G
20210815 04:27:16 WARN: WATCHDOG: T-Rex has a problem with GPU, terminating...
20210815 04:27:16 WARN: WATCHDOG: recovering T-Rex
20210815 04:27:30 T-Rex NVIDIA GPU miner v0.21.5  -  [Windows]
20210815 04:27:30 r.738648414f44
20210815 04:27:30 
20210815 04:27:34 NVIDIA Driver v470.05
20210815 04:27:34 CUDA devices available: 5
20210815 04:27:34 
20210815 04:27:34 WARN: DevFee 1% (ethash)
20210815 04:27:34 
20210815 04:27:34 URL : stratum+tcp://eu-eth.hiveon.net:4444
20210815 04:27:34 USER: 0x5d9002608856e3eb4e383ad3879c0c987d8907e5
20210815 04:27:34 PASS: x
20210815 04:27:34 WRK : rig1
20210815 04:27:34 
20210815 04:27:38 Starting on: eu-eth.hiveon.net:4444
20210815 04:27:38 Using protocol: stratum1.
20210815 04:27:38 Authorizing...
20210815 04:27:38 Authorized successfully.
20210815 04:27:38 ethash epoch: 434, diff: 5.00 G
20210815 04:27:43 ApiServer: HTTP server started on 0.0.0.0:4067
20210815 04:27:43 -----------------------------------------------------
20210815 04:27:43 For control navigate to: http://192.168.0.4:4067/trex
20210815 04:27:43 -----------------------------------------------------
20210815 04:27:43 ApiServer: Telnet server started on 127.0.0.1:4068
20210815 04:27:44 GPU #1(002800): NVIDIA GeForce RTX 3060, intensity 22
20210815 04:27:44 WARN: ApiServer: 216.245.221.93:50558 requested '', caused internal server error Not implemented
20210815 04:27:49 WARN: WATCHDOG: T-Rex has a problem with GPU, terminating...
20210815 04:27:54 WARN: WATCHDOG: recovering T-Rex

How to reboot windows on CUDA errors? Or if restarts > 5 or some value?

**Comment by trexminer** [comment]
You can use `--watchdog-exit-mode` parameter to set a reboot condition

**Comment by ivnish** [comment]
Thanks! I will try

**Comment by sushilkumarsahani41** [comment]
Which card you are using

**Comment by ivnish** [comment]
@sushilkumarsahani41 RTX 3060, RTX 2070, RTX 2060
