### ISSUE TITLE
Circumventing LHR

### ISSUE THREAD

**Issue by sushilkumarsahani41** [trexminer/T-Rex#575]
Sir new lhr cards having the bios settings for getting a lower hasrate so what aur computer reports to the gpu's bios 

What if we make changes toh the miner and make  like faking the task that we are minig but computer reports we are no mining we are gaming?? Is it not possible

**Comment by jelegend** [comment]
Won't worker. It's not about process and fooling gpu driver but about memory usage. That is the reason not all mining algorithms are not affected proportionately. ETH uses lot of memory so driver notices it easily so slows the GPU down, while RVN is core heavy so not much affect there.

**Comment by Abreshive** [comment]
Could you "wrap" t-rex activity in vDGA? Or to try use like a TurboCache with lhr devices to fool nvidia driver? 
--> https://en.wikipedia.org/wiki/TurboCache  To map gpu memory (let say 6gb) and ram as extension of gpu mem( let say 1-2 gb?) and designated mapped gpu mem for trex and mapped  ram for checking shares before sending to pool server? To use cudaMemcpyAsync ? Or go through Resizable BAR?
