### ISSUE TITLE
failed to subscribe errors

### ISSUE THREAD

**Issue by SOrtonn** [trexminer/T-Rex#58]
"failed to subscribe, failed to get extranonce2_size"
"failed to subscribe, JSON-RPC call failed: type is not convertible to string"

any help???

**Comment by trexminer** [comment]
Please run the miner with `--protocol-dump --log-path trex.log` parameters and attach the log file, it will help us troubleshoot the issue. Thanks.

**Comment by Shekelme** [comment]
[trex.log](https://github.com/trexminer/T-Rex/files/4994304/trex.log)

**Comment by trexminer** [comment]
@Shekelme wrong algorithm, RVN has forked from `x16rv2` to `kawpow`
