### ISSUE TITLE
0.21.6 (Windows): Mining EthashLowMem@prohashing.com not working

### ISSUE THREAD

**Issue by UselessGuru** [trexminer/T-Rex#582]
Command line used:

`t-rex.exe --algo ethash --url stratum2+tcp://eu.prohashing.com:3358 --user #################### --pass a=Ethash-LowMemory,n=########,o=############,l=1 --no-strict-ssl --no-watchdog --api-bind-http 127.0.0.1:4003 --api-bind-telnet 0 --api-read-only --gpu-report-interval 5 --quiet --retry-pause 1 --timeout 50000 --devices 0`

20210819 14:15:02 Using protocol: stratum2.
20210819 14:15:02 Extranonce is set to: 549a
20210819 14:15:02 Authorizing...
20210819 14:15:02 ethash epoch: 270, diff: 2.15 G
20210819 14:15:02 TREX: Can't find nonce with device [ID=0, GPU #0], GPU #0: not enough free memory to mine ethash at epoch 270
20210819 14:15:02 WARN: Miner is going to shutdown...

There seems to be a problem with parsing the password field or the pool does not understand it.

**Comment by trexminer** [comment]
Why do you think there's a problem with password parsing? The error is `GPU #0: not enough free memory to mine ethash at epoch 270`

**Comment by UselessGuru** [comment]
> Why do you think there's a problem with password parsing? 

Because the pool reads the password data to determine the max available VRAM (parameter l=[VRAM GB] and then selects a coin with a DAG that should fit in memory. 
https://prohashing.com/tools/miner-configurator/Ethash-LowMemory

Other miners work fine, e.g. phoenig or gminer

**Comment by trexminer** [comment]
I don't have an account on prohashing so can't really try it myself, but maybe use `stratum` rather than `stratum2`?

**Comment by UselessGuru** [comment]
> maybe use stratum rather than stratum2?

That made a difference - thank you.
ProHashing requires stratum for EthashLowMem, stratum2 however is OK for normal Ethash.
