### ISSUE TITLE
(Hive OS) Hashrate not being detected by OS

### ISSUE THREAD

**Issue by DejanRibnikar** [trexminer/T-Rex#584]
(v0.21.6) I just started using Hive OS and noticed that my OS didn't detect any hashrate while miner was working. Also on Windows, API keeps reporting communication error, but when I refresh the page, it works just fine... GPUs are 6x RTX3080Ti on Hive OS, 1x GTX1080 on Windows, all mining kawpow.
Edit: This only happens with api-bind-http argument set. Without it, hashrate gets reported to OS.

**Comment by trexminer** [comment]
Please report this to HiveOS support, it's not a T-Rex issue. From what you described the miner is working as intended.
As for the windows problem, you may want to create a separate ticket as it's not related to HiveOS and hashrate reporting.
