### ISSUE TITLE
(Windows) API Communication error

### ISSUE THREAD

**Issue by DejanRibnikar** [trexminer/T-Rex#586]
On windows, API is showing communication error all the time. When I refresh the page, the error is gone, but the data is not updating.

![image](https://user-images.githubusercontent.com/25691615/130178008-56074863-3e20-4e2f-882d-0fae87e5df9f.png)

**Comment by trexminer** [comment]
From the description it seems there's a problem with javascript execution in the browser. What browser are you using? Could you try using a different browser? Firefox instead of Microsoft Edge for example.

**Comment by DejanRibnikar** [comment]
I'm using firefox. Tried edge and chrome, but result is the same.
![image](https://user-images.githubusercontent.com/25691615/130182677-7b821f1e-2100-46c4-b9c7-676195d853e7.png)

**Comment by DejanRibnikar** [comment]
I'm closing the thread. Found out the problem is my antivirus. Sorry for any caused trouble.
