### ISSUE TITLE
Can I control which GPU to create DAG file? [Error: Can't find nonce with device]

### ISSUE THREAD

**Issue by pa5tlife** [trexminer/T-Rex#59]
I'm having issues with T-Rex miner 0.15.7 on Ubuntu 20.04 LTS - (kernel 5.4.0-37-generic)
Currently only 2 GPUs because I'm testing. 

GPU#0 is 4GB GTX 1050 Ti and GPU#1 is 2GB 1050
I get this output when running miner with above card configuration:

> 
> 20200610 17:49:36 WARN: GPU #1: Gigabyte GeForce GTX 1050, intensity set to 15 
> 20200610 17:49:36 Extranonce is set to: ee 
> 20200610 17:49:36 Authorizing... 
> 20200610 17:49:36 Authorized successfully. 
> 20200610 17:49:36 WARN: GPU #0: Gigabyte GeForce GTX 1050 Ti, intensity set to 15
> Generating DAG: 2.36 GB
> ERROR: Can't find nonce with device [ID=1, GPU #1], Epoch 169 requires 2.36 GB memory, but device has 1.95 GB...
> **ERROR: Can't find nonce with device [ID=0, GPU #0], cuda exception in [initEpoch, 342], out of memory.** 

Why is the miner trying to generate DAG file on GPU#1 and not #0?

Do all my GPU need 4GB to mine Raven?

I noticed also that when I had the cards switched slots, the miner got the GPU#s incorrect
and listed the 1050Ti as GPU#0 when it's actually in PCIe slot #2.
 (I verified in terminal, I didn't mix up the cards). 
And it still tried to create DAG file with GPU#1 which it thinks is my GPU#0

output with GPUs switched :

> 20200611 15:37:18 ERROR: Can't find nonce with device [ID=1, GPU #1], Epoch 169 requires 2.36 GB memory, but device has 1.95 GB...
> 20200611 15:44:53 Extranonce is set to: 1a
> 20200611 15:44:53 Authorizing...
> 20200611 15:44:53 WARN: GPU #0: Gigabyte GeForce GTX 1050 Ti, intensity set to 15
> 20200611 15:44:53 Authorized successfully.
> 20200611 15:44:53 WARN: GPU #1: Gigabyte GeForce GTX 1050, intensity set to 15
> 20200611 15:44:53 New target is set to: 0x00000009f6000000000000000000000000000000000000000000000000000000
> 20200611 15:44:53 kawpow epoch: 169, block: 1272013, period: 424004, diff: 0.110 = 431.17 Mh
> 20200611 15:44:55 ERROR: Can't find nonce with device [ID=1, GPU #1], Epoch 169 requires 2.36 GB memory, but device has 1.95 GB...

I tried the miner with only the 4GB card in the motherboard and it created DAG and started mining.
Here are some command outputs for additional information on the system:

[sysinfo@paste.ubuntu](https://paste.ubuntu.com/p/x8jF9WKkKp/)

I'm so confused. Can someone help? 

Thanks for your time and hope you have a great day.

**Comment by trexminer** [comment]
> Do all my GPU need 4GB to mine Raven?

Yes, only the GPUs that have enough memory can mine RVN. Even if you only use your 4GB card to generate the DAG, you must have a copy of it on each card that you intend to mine with for performance reasons.


> I noticed also that when I had the cards switched slots, the miner got the GPU#s incorrect
and listed the 1050Ti as GPU#0 when it's actually in PCIe slot #2.

Try running the miner with `--ab-indexing` parameter to match PCI bus order.
