### ISSUE TITLE
Hi. I'm getting this issue : Can't find nonce with device [ID=0, GPU #0],bad allocation

### ISSUE THREAD

**Issue by taomi** [trexminer/T-Rex#599]
![20210828135120](https://user-images.githubusercontent.com/1817451/131207966-5d888916-28b8-4698-89e8-0c9d5c93e68d.png)

0.20.4  Even if you encounter a graphics card error, there will be no endless loop and stop mining

**Comment by innowebka** [comment]
so 2070 super is the issue i think. same is issue here . this error pops at-least 1 to 2 time in 24 hours and no.restarts at-least 2 per day.

**Comment by trexminer** [comment]
Duplicate of https://github.com/trexminer/T-Rex/issues/125
