### ISSUE TITLE
Client.reconnect support

### ISSUE THREAD

**Issue by GrannyCryptomaster** [trexminer/T-Rex#6]
Please add support for client.reconnect. I can't get it connected to port 3333 on MiningRigRentals. I must use an individual port, that expires after 2 days.

**Comment by AndrewTPohlmann** [comment]
Please refresh your port on MRR, and then use the one they give you.

**Comment by trexminer** [comment]
T-Rex does support client.reconnect. What's the error message the miner is displaying? If you could run it with `--protocol-dump` flag and send us the log that would be great. Thanks.

**Comment by GrannyCryptomaster** [comment]
It seems it works on generic port 3333 too. A week ago, when I first started t-rex on MRR, couldn't connect to that port. Sorry for false error report.
