### ISSUE TITLE
ERROR: Can't find nonce with device [ID=1, GPU #1], cuda exception

### ISSUE THREAD

**Issue by CRYPTONIKAV** [trexminer/T-Rex#60]
T-Rex: 0.15.7
GPU: GTX 1070
nVIDIA GPU Driver: 446.14
Pool: nicehash

Core: 120
Memory: 620
Power: 60

Issue:
The rig is hanging randomly and displays this error message:

ERROR: Can't find nonce with device [ID=1, GPU #1], cuda exception in [ProgPOW::ProgPOW::find_nonces, 544], the launch timed out and was terminated

Another rig, exactly the same config works without problems.

Any ideas that may be causing this?

**Comment by trexminer** [comment]
Usually indicates a problem with hardware or overclocking. Try running with stock settings to rule out the overclocking.
