### ISSUE TITLE
GPU goes idle trex

### ISSUE THREAD

**Issue by gizzer1337** [trexminer/T-Rex#600]
Hi. I’ve updated to new trex and my gpu RTX 3060 goes idle every now and then. I’ve total 5 GPUs
With oc -502
1220
And power limit 70 for 4 GPUs. All are EVGA. 
the GPU which keeps crashing has oc -502, 1050 and power limit 69. 
it used to be better with older version of trex. Crashed like every 10 days. Also now when it crashes it restarts itself, sometimes, but changes the OC the gpu which crashing to default. Any idea what could be a problem?

cheers!

**Comment by innowebka** [comment]
> 
> 
> Hi. I’ve updated to new trex and my gpu RTX 3060 goes idle every now and then. I’ve total 5 GPUs
> With oc -502
> 1220
> And power limit 70 for 4 GPUs. All are EVGA.
> the GPU which keeps crashing has oc -502, 1050 and power limit 69.
> it used to be better with older version of trex. Crashed like every 10 days. Also now when it crashes it restarts itself, sometimes, but changes the OC the gpu which crashing to default. Any idea what could be a problem?
> 
> cheers!

4 days 12 restarts 😭  but before (old version trex) no crash. in 10 month cycle 8 months were good 😎  but there 2 months are 💩 worst and too much restarts 😤 . so your gpu has 3 fans right ,
try this for 3060 - pl 70 , temp. limit 71 , core.c -300 , mem.c 1300.

**Comment by gizzer1337** [comment]
It has 2 fans. I tried to change the riser of the gpu which was crashing all the time. It’s 36 hours without crash now. Let’s see if that works. Will keep you posted.

**Comment by gizzer1337** [comment]
It has been 3 days and 19 hours without crash after changing the riser. I even changed the oc from 1050 to 1150 for the gpu which was crashing. So far so good. Will keep you posted another few days and I guess then we can lock the topic.

**Comment by gizzer1337** [comment]
It’s more then a week without crash. I would say problem solved - wrong riser.
