### ISSUE TITLE
TREX error 960m 21.6

### ISSUE THREAD

**Issue by Heidar-An** [trexminer/T-Rex#604]
Hi there,

I'm receiving the error: Can't find nonce with device [ID=0, GPU #0], GPU #0: not enough free memory to mine ethash at epoch 438. Here's a picture:
![image](https://user-images.githubusercontent.com/74025356/131713151-79116665-d787-4365-8b55-c7806ff05459.png)
I have about 3-4 GB free with RAM, the latest version of windows, and it still doesn't work.

I've tried using 
--kernel 4 -i 20 and went down to 10, (--kernel 4 -i 10) and it still doesn't work.

**Comment by trexminer** [comment]
You GPU doesn't have enough VRAM (as opposed to system RAM) to mine ETH
