### ISSUE TITLE
Donation on proxy server

### ISSUE THREAD

**Issue by YimingDong1999** [trexminer/T-Rex#606]
Now I'm using trex ethproxy to connect to the proxy server then to the pool. I wonder if the devfee data packet is proxied. Thanks for your reply in advance.

**Comment by trexminer** [comment]
No, dev fee traffic is not proxied

**Comment by YimingDong1999** [comment]
Is this devfee packet still directly sent to the pool, or to elsewhere? I wanna hide my traffic to the mining pool, how can I do it?

**Comment by trexminer** [comment]
> Is this devfee packet still directly sent to the pool,

Yes

I can't think of a way to hide it, unfortunately.
