### ISSUE TITLE
issues about log

### ISSUE THREAD

**Issue by HOWTYEE** [trexminer/T-Rex#607]
Hi there，
where is the program's logs in linux and windows？
I can't find them.

**Comment by trexminer** [comment]
The full log path is set with `--log-path` parameter

**Comment by HOWTYEE** [comment]
I can't use this command，If you could just tell me Are log files saved in the /VAR folder in Ubuntu？

**Comment by HOWTYEE** [comment]
could u please tell me Is no log generated by default？

**Comment by trexminer** [comment]
The log file is not created unless the miner is run with `--log-path`
