### ISSUE TITLE
Is `--mt` list indexed by only devices in the `--devices` flag or all system GPUs?

### ISSUE THREAD

**Issue by crocokyle** [trexminer/T-Rex#610]
I currently have a HiveOS rig with 3 GPUs. 
```
GPU 0: EVGA RTX 3060 (LHR)
GPU 1: NVIDIA RTX 3070 FE
GPU 2: Asus GTX 1060 6GB
``` 
Since GPU 0 is an LHR card so I am using nbminer for that card only. My other two cards are using T-Rex. 

In my T-Rex config I have the following args:
```json
"devices":"1,2"
"mt":"0,0,4"
```
- I'm trying to determine whether the `--mt` flag should only include two entries since that's all T-Rex is using or if it should include all 3 system GPUs. 

- My second question is which of these `--mt` arguments are appropriate for a Asus GTX 1060 6GB. It seems none of the configurations I have tried have affected the hashrate significantly.

**Comment by trexminer** [comment]
> I'm trying to determine whether the --mt flag should only include two entries since that's all T-Rex is using or if it should include all 3 system GPUs.

It should only include two entries, one for each GPU used, i.e. `"mt":"0,4"` in your case

> My second question is which of these --mt arguments are appropriate for a Asus GTX 1060 6GB. It seems none of the configurations I have tried have affected the hashrate significantly.

Any of 1-6 should work. `4` like you have in your example should work fine too.

**Comment by crocokyle** [comment]
Okay, great thanks for the clarification!
