### ISSUE TITLE
tune GPU with Two fan.

### ISSUE THREAD

**Issue by bassel999** [trexminer/T-Rex#620]
Is it possible to tune GPU with two fan like afterburner ?
If so what I need to change

`t-rex.exe -a ethash -o stratum+tcp://us1.ethermine.org:4444 -u XXXXXXX -p x -w RTX-3090 --temperature-limit 75 --cv 0 --pl 85 --cclock -200 --mclock 1200 --fan 60`

**Comment by trexminer** [comment]
Duplicate of https://github.com/trexminer/T-Rex/issues/581
