### ISSUE TITLE
RTX3060TI LHR - OCTOPUS ERROR (GPU IS IDLE)

### ISSUE THREAD

**Issue by b8engl** [trexminer/T-Rex#631]
Can't put this to work! I don't receive error using kawpow.

- Using trex latest version
- Using basic connection comand (1)
- Driver 472.12
- Windows 10 21H1 (19043.1237)

(1) `t-rex --algo !ALGO! --url !POOL! --user !WALLET! --worker !NAME! `

![error](https://user-images.githubusercontent.com/29173784/134437275-987db9d8-657d-4952-9728-c088760cc58c.PNG)

Please, could you take a look in code?

Thanks in advance!

**Comment by trexminer** [comment]
Could you try running the miner with just one GPU and see if it starts mining?

**Comment by b8engl** [comment]
Same problem!
![no](https://user-images.githubusercontent.com/29173784/134495436-a53c34f8-81b8-4c1b-b186-b93f27e1401c.PNG)

**Comment by trexminer** [comment]
It could be that your mining pool is not sending out mining jobs.
Try using a different pool. If still no luck, run the miner with `-P -l trex.log` parameters and post the log file, I'll have a look.

**Comment by b8engl** [comment]
On the pool, they have 779 users...
I will do the `-P -l` argument and paste the log here

**Comment by b8engl** [comment]
I found the problem! 
The miner sets stratum1 but pool only accept the previous version for this algo. Don't know if your miner detects the connection first, but in the log the connection is established.

`The connection must be stratum+tcp`

**Comment by trexminer** [comment]
There is a default and there are other connection types. The default works for most mining pools.
So, did changing connection type solve the problem?

**Comment by b8engl** [comment]
Yes, the auto connection didn't identify the protocol to use. 
Thanks anyway for the assistance!
