### ISSUE TITLE
LHR Tune Issue

### ISSUE THREAD

**Issue by callidusj** [trexminer/T-Rex#635]
Having issues using the LHR break - even set on 8 I get a max of about ~60MH/s on 3080 Ti's, and leaving the command off entirely I get around ~65MH/s (all other settings the same). It stays on --lhr-tune 8 without dropping, I'm just not seeing the increased hash rate. 

Nvidia Driver: 471.96
MSI Ventus 3x 3080 Ti's
-500 core, +1250 mem, PL 73%
Using t-rex 0.22.1
Algo: ethash (via stratum1)

No --lhr-tune command: ~65 MH/s
--lhr-tune 1: ~54MH/s
--lhr-tune 4: ~59-60MH/s
--lhr-tune 6: ~59-60MH/s
--lhr-tune 8: ~60MH/s

Is there a preferred driver version I should be using to get the best result? Do I need to tweak my settings somehow?

**Comment by trexminer** [comment]
0 core, +1250 mem (if linux, then +2500), PL 80% should give you 82+Mh on --lhr-tune 5 from my testing

**Comment by callidusj** [comment]
Tested those settings on a GPU, let it work for a few minutes - results below:

-------------20210924 07:57:30 -------------
Mining at eth.2miners.com:2020, diff: 8.73 G
GPU #0: MSI RTX 3080 Ti - 58.55 MH/s, [LHR 5] [T:61/90C, P:241W, F:70%, E:229kH/W], 2/2 R:0%
Shares/min: 2 (Avr. 0.502)
Uptime: 4 mins | Algo: ethash | T-Rex v0.22.1
WD: 4 mins 2 secs, shares: 2/2

I think it may be something with newer Nvidia drivers.

**Comment by satsukiyatoshi** [comment]
Maybe your 3080ti are not tweaked / gpu ram enought ?
Got those results (stable) with my 3070ti:
GPU #0: ASUS RTX 3070 Ti - 61.81 MH/s, [LHR 5] [T:59/98C, P:194W, F:100%, E:314kH/W], 3/3 R:0%

afterburner settings (windows):
locked core = 900mhz
memory clock = +2000
locked voltage = 825mz

**Comment by callidusj** [comment]
Just wanted to follow up - solved the issue. After checking out HwInfo a lot more, there were unusually high power fluctuations. After reinstalling the graphics drivers, and changing the GPU riser, everything works. Closing issue. Thanks all!
