### ISSUE TITLE
[0.23.1] "ERROR: Can't start T-Rex, file name contains forbidden characters" caused by "script-low-hash" parameter

### ISSUE THREAD

**Issue by tic-tac-toker** [trexminer/T-Rex#637]
First, congratulations for the new WebUI, it's awesome. However, I have noticed that a command line option that used to work just fine so far, is now broken (or maybe changed?) in 0.23.1.

I am referring to `--script-low-hash`. The following used to work just fine in a command line launch in 0.22.1:

`--script-low-hash /mypath/my_script.sh:60`

But now, with 0.23.1, I get:

`ERROR: Can't start T-Rex, file name contains forbidden characters`

And the miner exits immediately.

Seems that either the format has been changed (but not referenced in the README), or there is something wrong in parsing the filename - it acts like the colon is part of it, instead of a separator for the MH/s value as it was before.

**Comment by trexminer** [comment]
Yes, sorry. For security reasons you can now only execute scripts that are located within the same directory as t-rex executable.

**Comment by tic-tac-toker** [comment]
Ok, thanks for the clarification. I confirm that it works without the "/".

If you deem it appropriate, I would suggest to include that information in the README, just to prevent any future misunderstanding.

**Comment by trexminer** [comment]
Thanks for the suggestion, will update it in the next version.
