### ISSUE TITLE
Can't find nonce with device [ID=0, GPU #2]   GTX 960 Support

### ISSUE THREAD

**Issue by DoesItFit** [trexminer/T-Rex#638]
About a month ago or so I was able to mine RVN on my GTX 960 when it was the only GPU in the PC. Now I consolidated all of my GPUs to a makeshift rig, and when I try to mine RVN on just the 960 I get a variety of errors depending on what version of T-Rex I use.

**T-Rex Miner 0.21.6**

C:\Documents\Mining\Miners\T-Rex\0.20.4>t-rex.exe -a kawpow -o stratum+tcp://stratum-ravencoin.flypool.org:3333 -u RLY7pLLws7G4VeLRcPgPyr5Pj5vDrqs658 -p x -d 2
20210924 09:57:52 T-Rex NVIDIA GPU miner v0.21.6  -  [Windows]
20210924 09:57:52 r.3ea03a096378
20210924 09:57:52
20210924 09:57:52 NVIDIA Driver v471.96
20210924 09:57:52 CUDA devices available: 3
20210924 09:57:52
20210924 09:57:52 WARN: DevFee 1% (kawpow)
20210924 09:57:52
20210924 09:57:52 URL : stratum+tcp://stratum-ravencoin.flypool.org:3333
20210924 09:57:52 USER: RLY7pLLws7G4VeLRcPgPyr5Pj5vDrqs658
20210924 09:57:52 PASS: x
20210924 09:57:52
20210924 09:57:52 Starting on: stratum-ravencoin.flypool.org:3333
20210924 09:57:52 Using protocol: stratum3.
20210924 09:57:52 Extranonce is set to: 0c5fe1
20210924 09:57:52 Authorizing...
20210924 09:57:52 Authorized successfully.
20210924 09:57:52 New target is set to: 431.17 M
20210924 09:57:53 ApiServer: HTTP server started on 127.0.0.1:4067
20210924 09:57:53 ---------------------------------------------------
20210924 09:57:53 For control navigate to: http://127.0.0.1:4067/trex
20210924 09:57:53 ---------------------------------------------------
20210924 09:57:53 ApiServer: Telnet server started on 127.0.0.1:4068
20210924 09:57:53 GPU #2(000900): EVGA NVIDIA GeForce GTX 960, intensity 20
20210924 09:57:53 kawpow epoch: 259, block: 1944012, period: 648004, diff: 431.17 M
20210924 09:57:55 GPU #2: generating DAG 3.02 GB for epoch 259 ...
20210924 09:58:23 GPU #2: DAG generated [crc: 7bd4d035, time: 28661 ms], memory left: 311.35 MB
20210924 09:58:23 TREX: Can't find nonce with device [ID=0, GPU #2], cuda exception: CUDA_ERROR_NOT_SUPPORTED
20210924 09:58:23 WARN: Miner is going to shutdown...
20210924 09:58:24 Main loop finished. Cleaning up resources...
20210924 09:58:24 ApiServer: stopped listening on 127.0.0.1:4067
20210924 09:58:24 ApiServer: stopped listening on 127.0.0.1:4068
20210924 09:58:24 T-Rex finished.
20210924 09:58:25 WARN: WATCHDOG: T-Rex does not exist anymore, restarting...

**T-Rex Miner 0.19.4 Cuda v11.10**

C:\Documents\Mining\Miners\T-Rex\0.19.14-win-cuda11.1>t-rex.exe -a kawpow -o stratum+tcp://stratum-ravencoin.flypool.org:3333 -u RLY7pLLws7G4VeLRcPgPyr5Pj5vDrqs658 -p x -d 2
20210924 10:00:34 T-Rex NVIDIA GPU miner v0.19.14  -  [CUDA v11.10 | Windows]
20210924 10:00:34 r.39dd950be1c7
20210924 10:00:34
20210924 10:00:34 NVIDIA Driver v471.96
20210924 10:00:34 CUDA devices available: 3
20210924 10:00:34
20210924 10:00:34 WARN: DevFee 1% (kawpow)
20210924 10:00:34
20210924 10:00:34 URL : stratum+tcp://stratum-ravencoin.flypool.org:3333
20210924 10:00:34 USER: RLY7pLLws7G4VeLRcPgPyr5Pj5vDrqs658
20210924 10:00:34 PASS: x
20210924 10:00:34
20210924 10:00:34 Starting on: stratum-ravencoin.flypool.org:3333
20210924 10:00:34 Using protocol: stratum3.
20210924 10:00:34 Extranonce is set to: 0c61d5
20210924 10:00:34 Authorizing...
20210924 10:00:34 Authorized successfully.
20210924 10:00:34 New target is set to: 431.17 M
20210924 10:00:34 ApiServer: HTTP server started on 127.0.0.1:4067
20210924 10:00:34 ---------------------------------------------------
20210924 10:00:34 For control navigate to: http://127.0.0.1:4067/trex
20210924 10:00:34 ---------------------------------------------------
20210924 10:00:34 ApiServer: Telnet server started on 127.0.0.1:4068
20210924 10:00:34 WARN: GPU #2(000900): EVGA NVIDIA GeForce GTX 960, intensity set to 20
20210924 10:00:35 kawpow epoch: 259, block: 1944015, period: 648005, diff: 431.17 M
20210924 10:00:36 GPU #2: generating DAG 3.02 GB for epoch 259 ...
20210924 10:00:38 kawpow epoch: 259, block: 1944016, period: 648005, diff: 431.17 M
20210924 10:01:05 GPU #2: DAG generated [crc: 7bd4d035, time: 28625 ms], memory left: 311.35 MB
20210924 10:01:05 TREX: Can't find nonce with device [ID=0, GPU #2], cuda exception in [StreamContext<struct search_results,int>::set_busy, 85], operation not supported
20210924 10:01:05 WARN: Miner is going to shutdown...
20210924 10:01:05 Main loop finished. Cleaning up resources...
20210924 10:01:05 ApiServer: stopped listening on 127.0.0.1:4067
20210924 10:01:06 ApiServer: stopped listening on 127.0.0.1:4068
20210924 10:01:06 T-Rex finished.
20210924 10:01:07 WARN: WATCHDOG: T-Rex does not exist anymore, restarting...

**T-Rex Miner 0.19.11 Cuda v9.20**

C:\Documents\Mining\Miners\T-Rex\0.19.11-win-cuda9.2>t-rex.exe -a kawpow -o stratum+tcp://rvn.2miners.com:6060 -u RBX1G6nYDMHVtyaZiQWySMZw1Bb2DEDpT8.rig -p x -d 2
20210924 10:02:47 T-Rex NVIDIA GPU miner v0.19.11  -  [CUDA v9.20 | Windows]
20210924 10:02:47 r.9c70a63f2290
20210924 10:02:47
20210924 10:02:47 NVIDIA Driver v471.96
20210924 10:02:47 CUDA devices available: 3
20210924 10:02:47
20210924 10:02:47 WARN: DevFee 1% (kawpow)
20210924 10:02:47
20210924 10:02:47 URL : stratum+tcp://rvn.2miners.com:6060
20210924 10:02:47 USER: RBX1G6nYDMHVtyaZiQWySMZw1Bb2DEDpT8.rig
20210924 10:02:47 PASS: x
20210924 10:02:47
20210924 10:02:47 Starting on: rvn.2miners.com:6060
20210924 10:02:47 Using protocol: stratum3.
20210924 10:02:48 Extranonce is set to: 2e
20210924 10:02:48 Authorizing...
20210924 10:02:48 ApiServer: HTTP server started on 127.0.0.1:4067
20210924 10:02:48 ---------------------------------------------------
20210924 10:02:48 For control navigate to: http://127.0.0.1:4067/trex
20210924 10:02:48 ---------------------------------------------------
20210924 10:02:48 ApiServer: Telnet server started on 127.0.0.1:4068
20210924 10:02:48 Authorized successfully.
20210924 10:02:48 New target is set to: 4.29 G
20210924 10:02:48 kawpow epoch: 259, block: 1944019, period: 648006, diff: 4.29 G
20210924 10:02:48 WARN: GPU #2(000900): EVGA NVIDIA GeForce GTX 960, intensity set to 20
20210924 10:02:49 GPU #2: generating DAG 3.02 GB for epoch 259 ...
20210924 10:03:18 GPU #2: DAG generated [crc: 7bd4d035, time: 28612 ms], memory left: 311.35 MB
20210924 10:03:18 TREX: Can't find nonce with device [ID=0, GPU #2], cuda exception in [StreamContext<struct search_results,int>::set_busy, 85], operation not supported
20210924 10:03:18 WARN: Miner is going to shutdown...
20210924 10:03:18 Main loop finished. Cleaning up resources...
20210924 10:03:18 ApiServer: stopped listening on 127.0.0.1:4067
20210924 10:03:18 ApiServer: stopped listening on 127.0.0.1:4068
20210924 10:03:19 T-Rex finished.
20210924 10:03:19 WARN: WATCHDOG: T-Rex does not exist anymore, restarting...

**Comment by DoesItFit** [comment]
Will go ahead and reemphasize how important and helpful the DDU tool is. I'm not sure if the fault was in the driver version or the fact that new GPUs were added, but after running the DDU tool and installing version 456.71 drivers everything appears to work flawlessly, even with the new T-Rex Miner version. 


C:\Documents\Mining\Miners\T-Rex\t-rex-0.23.1-win>t-rex.exe -a kawpow -o stratum+tcp://rvn.2miners.com:6060 -u RBX1G6nYDMHVtyaZiQWySMZw1Bb2DEDpT8.rig -p x -d 2
20210924 13:55:29 T-Rex NVIDIA GPU miner v0.23.1  -  [Windows]
20210924 13:55:29 r.b1aeaf75161f
20210924 13:55:29
20210924 13:55:29
20210924 13:55:29 NVIDIA Driver v456.71
20210924 13:55:29
20210924 13:55:29 - GPU #0: [00:04.0] ASUS GeForce RTX 2060, 6144 MB
20210924 13:55:29 - GPU #1: [00:09.0] Gigabyte GeForce GTX 1660, 6144 MB
20210924 13:55:29 + GPU #2: [00:0a.0] EVGA GeForce GTX 960, 4096 MB
20210924 13:55:29
20210924 13:55:29 WARN: DevFee 1% (kawpow)
20210924 13:55:29
20210924 13:55:29 URL : stratum+tcp://rvn.2miners.com:6060
20210924 13:55:29 USER: RBX1G6nYDMHVtyaZiQWySMZw1Bb2DEDpT8.rig
20210924 13:55:29 PASS: x
20210924 13:55:29
20210924 13:55:29 Starting on: rvn.2miners.com:6060
20210924 13:55:29 Using protocol: stratum3.
20210924 13:55:29 Extranonce is set to: 1a
20210924 13:55:29 Authorizing...
20210924 13:55:29 Authorized successfully.
20210924 13:55:29 New target is set to: 4.29 G
20210924 13:55:29 kawpow epoch: 259, block: 1944239, period: 648079, diff: 4.29 G
20210924 13:55:29 ApiServer: HTTP server started on 127.0.0.1:4067
20210924 13:55:29 ---------------------------------------------------
20210924 13:55:29 For control navigate to: http://127.0.0.1:4067/trex
20210924 13:55:29 ---------------------------------------------------
20210924 13:55:29 GPU #2: intensity 20
20210924 13:55:31 GPU #2: generating DAG 3.02 GB for epoch 259 ...
20210924 13:55:59 GPU #2: DAG generated [crc: 7bd4d035, time: 28587 ms], memory left: 310.05 MB

-------------20210924 13:56:29 -------------
Mining at rvn.2miners.com:6060, diff: 4.29 G
GPU #2: EVGA GTX 960 - 1.48 MH/s, [T:60C, P:67W, F:0%, E:23.8kH/W]
Shares/min: 0
Uptime: 1 min | Algo: kawpow | T-Rex v0.23.1

20210924 13:56:40 kawpow epoch: 259, block: 1944240, period: 648080, diff: 4.29 G
20210924 13:56:44 kawpow epoch: 259, block: 1944241, period: 648080, diff: 4.29 G

-------------20210924 13:56:59 -------------
Mining at rvn.2miners.com:6060, diff: 4.29 G
GPU #2: EVGA GTX 960 - 1.48 MH/s, [T:65C, P:67W, F:7%, E:22.4kH/W]
Shares/min: 0
Uptime: 1 min 30 secs | Algo: kawpow | T-Rex v0.23.1

20210924 13:57:07 kawpow epoch: 259, block: 1944242, period: 648080, diff: 4.29 G

-------------20210924 13:57:29 -------------
Mining at rvn.2miners.com:6060, diff: 4.29 G
GPU #2: EVGA GTX 960 - 1.48 MH/s, [T:67C, P:68W, F:12%, E:22.0kH/W]
Shares/min: 0
Uptime: 2 mins | Algo: kawpow | T-Rex v0.23.1

20210924 13:57:56 kawpow epoch: 259, block: 1944243, period: 648081, diff: 4.29 G

-------------20210924 13:58:00 -------------
Mining at rvn.2miners.com:6060, diff: 4.29 G
GPU #2: EVGA GTX 960 - 1.48 MH/s, [T:68C, P:70W, F:15%, E:21.7kH/W]
Shares/min: 0
Uptime: 2 mins 30 secs | Algo: kawpow | T-Rex v0.23.1

**Comment by trexminer** [comment]
Glad you've sorted it. And thanks for letting everyone know how you did that.
