### ISSUE TITLE
New WebUI is awesome!

### ISSUE THREAD

**Issue by InfiniteImp** [trexminer/T-Rex#640]
Just wanted to let you know the new WebUI looks amazing.  The big problem with it is that if you run multiple mining rigs (4 in this case), you run out screen space really quickly.  I like the new UI so much I was seriously considering buying a widescreen monitor just to view the miner stats on it but I just don't have the desk space for it.

Can you add a way to customize?  Or even just display the graph at the bottom of the screen - that way I could resize the window and not show that part.

**Comment by trexminer** [comment]
Thanks!
Reordering of web page elements isn't possible at the moment, but we'll add a way to collapse the graph. That should solve your problem, right?

**Comment by InfiniteImp** [comment]
Sure, sounds good to me!  Thanks.

**Comment by doramine** [comment]
Yes new WebUI is awesome, but too much empty space make us must do scroll down to view each GPU stats.
Why not split upper info to the top-left and graph to the top-right, so all GPU stats can be seen without having to scroll down?
Or maybe keep it that way but just reduce empty space somehow so we can see all those stats in a window without having to scroll down? Smaller font or smaller boxes can do the trick.
The graph also took to much space, so I think reduce height a little bit wont hurt anything.
Btw why u make it day/night theme when all the ppl using night theme? :D

**Comment by InfiniteImp** [comment]
> Btw why u make it day/night theme when all the ppl using night theme? :D

Probably because people like me only use the day theme :)

**Comment by trexminer** [comment]
Fixed in https://github.com/trexminer/T-Rex/releases/tag/0.23.2
There's a show/hide graph button in the top right corner next to the theme switcher.
