### ISSUE TITLE
API not opening 

### ISSUE THREAD

**Issue by Teddymeyn** [trexminer/T-Rex#644]
Below is my command i used 1234 for API key to diable Readonly mode but not able to open, gett incorrect password..

Please let me know if some command to be added to changed to access API in full control mode

t-rex.exe -a ethash -o stratum+tcp://ethash.poolbinance.com:25 -u johnsmith -p 11111--lhr-tune 6,0 --api-key 1234

**Comment by trexminer** [comment]
see https://github.com/trexminer/T-Rex/wiki/WebUI#security on how to use `--api-key`

**Comment by Teddymeyn** [comment]
thanks for that link! It helped ! working perfect!! appreciate it
