### ISSUE TITLE
Help Thanks 

### ISSUE THREAD

**Issue by szaszaharcos** [trexminer/T-Rex#646]
Thank you very much
You could help which card type matches this
4gb ddr3 is OK NVidia cuda?

**Comment by trexminer** [comment]
Could you clarify the question please?

**Comment by szaszaharcos** [comment]
What type of video card is good for cc5 +

Because cc3 not supported for miner 

Thanks

**Comment by trexminer** [comment]
Any non-LHR 30xx card is good for mining.

**Comment by szaszaharcos** [comment]
Thanks

I was thinking of a cheaper card than the geforce  30xx

because I just want TRX mining


Thanks

your patience
