### ISSUE TITLE
23.1 indexing and order of pl, c/mclock, mt etc..

### ISSUE THREAD

**Issue by jhorath** [trexminer/T-Rex#647]
Man I finally got all of my cards working great and now the order is going to have to be relearned?  Does --ab-indexing not help with this?

**Comment by trexminer** [comment]
The new order is the same as that used in MSI AB, HiveOS and so on. This is actually a good change.
`--ab-indexing` is the same thing except GPU indexing starts from 1 rather than 0.

**Comment by jhorath** [comment]
So if I was previously using --ab-indexing then my order of settings; --pl
, --cclock, etc... should be the same in the new version?

**Comment by trexminer** [comment]
Yes

**Comment by jhorath** [comment]
Awesome.. I finally got my head wrapped around all my clockings within
T-Rex vs. AB and then I saw this note for 23.1 and went into panic mode
lmao. Thanks!!

**Comment by jhorath** [comment]
Final q, since this is updated within the program so I still need that
parameter --ab-indexing?

**Comment by trexminer** [comment]
If you don't use `-d` parameter, then you can take `--ab-indexing` out. Otherwise, leave it.

**Comment by jhorath** [comment]
I'm kinda dumb so I like being able to look at 1-8 vs 0-7 if the need
arises. Thanks again.
