### ISSUE TITLE
WebUI - Power & Hashrate inconsistently rounding up and down 

### ISSUE THREAD

**Issue by derekakelly** [trexminer/T-Rex#655]
Hello,

My issue is minor one with the new WebUI. Overall i think it's great, but I noticed the Power & Hashrate is Rounding up/down in a way that is inconsistent.
![image](https://user-images.githubusercontent.com/5824837/135399950-6b0aa97f-f4b1-4005-bb91-b9b525954f65.png)
Either 2 or 3 decimal places over would be my preference. I wish i could get 2GH/s @ 1kW 😅

The power section at the top is always rounded this way, but the hashrate listed in the chart isn't always.
![image](https://user-images.githubusercontent.com/5824837/135400519-d80cf069-a52e-4295-a583-a27410eeba14.png)

Thanks!

**Comment by trexminer** [comment]
Hi. Could you please try this version of WebUI and confirm whether this issue is fixed?
[webui.zip](https://github.com/trexminer/T-Rex/files/7257842/webui.zip) 
Just put it next to `t-rex.exe` and run the miner as usual. Don't unpack it.
Thanks.

**Comment by derekakelly** [comment]
Hey, thanks for the quick reply.

I'll run it for a bit and see if it glitches again. So far the chart is showing one decimal place over now. If possible, I would prefer two or three, especially with GH & kW. 

And, the power stats at the top is still showing 1kw
![image](https://user-images.githubusercontent.com/5824837/135415734-e0090edf-34b0-496b-8a6c-798fcf5f29db.png)

**Comment by derekakelly** [comment]
I just noticed in the list of GPUs, the efficiency column is also rounding and removing everything after the decimal point
![image](https://user-images.githubusercontent.com/5824837/135422254-7ca50cac-af7d-4a8b-b3be-3d8d894f9166.png)

**Comment by trexminer** [comment]
Could you try this one please [webui.zip](https://github.com/trexminer/T-Rex/files/7258634/webui.zip)

Also, could you please make a request (http://127.0.0.1:4067/summary) from your browser(put it into search line) and attach data you got? Make this request when you see in webui that "the power stats at the top is still showing 1kw".

**Comment by derekakelly** [comment]
This latest webui.zip has resolved the the rounding issue. It looks great! The power section at the top and the efficiency column are now showing the additional digits after the decimal point.
![image](https://user-images.githubusercontent.com/5824837/135439481-745b9d31-6be8-4017-8417-f6b50e92a95c.png)
![image](https://user-images.githubusercontent.com/5824837/135439519-08d17591-a4e1-4f59-ac74-edf54397440a.png)

Seeing as this resolved my issue, I don't think you'll need my summary information anymore. But if you still would like it, please let me know.

Thanks for your VERY PROMPT support, it's very much appreciated 😎
