### ISSUE TITLE
How to mine Bitcoin Interest on ZergPool?

### ISSUE THREAD

**Issue by UselessGuru** [trexminer/T-Rex#67]
I tried:

t-rex.exe --algo progpow --coin bci --intensity 21 --url stratum+tcp://103.249.70.7:3200 --user ********************************* --pass ID=************,c=BTC,mc=BCI --no-watchdog --gpu-report-interval 25 --api-bind-http 127.0.0.1:4003 --api-bind-telnet 0 --devices 0 -P

Result:
> 20200717 11:30:32:584390 T-Rex NVIDIA GPU miner v0.15.8  -  [CUDA v10.0]
> 20200717 11:30:32:584390 r.8dbb1eefa84a
> 20200717 11:30:32:585387
> 20200717 11:30:32:608325 NVIDIA Driver v446.14
> 20200717 11:30:32:608325 CUDA devices available: 1
> 20200717 11:30:32:608325
> 20200717 11:30:32:608325 WARN: DevFee 1% (progpow)
> 20200717 11:30:32:608325
> 20200717 11:30:32:608325 URL : stratum+tcp://103.249.70.7:3200
> 20200717 11:30:32:609321 USER: *********************************
> 20200717 11:30:32:610319 PASS: ID=Blackbox,c=BTC,mc=BCI
> 20200717 11:30:32:610319
> 20200717 11:30:32:610319 WARN: Built-in watchdog has been disabled!
> 20200717 11:30:32:611411 Starting on: 103.249.70.7:3200
> 20200717 11:30:32:612314 asio_thread_func start
> 20200717 11:30:32:612314 get_stratum_work_thread start
> 20200717 11:30:32:612314 submit_work_thread start
> 20200717 11:30:32:613312 Connecting to: 103.249.70.7:3200, ip: 103.249.70.7
> 20200717 11:30:32:618297 ApiServer: HTTP server started on 127.0.0.1:4003
> 20200717 11:30:32:625279 ---------------------------------------------------------
> 20200717 11:30:32:625279 For control navigate to: http://192.168.111.100:4003/trex
> 20200717 11:30:32:627274 ---------------------------------------------------------
> 20200717 11:30:32:672155 Authorizing...
> 20200717 11:30:32:675147 -OUT-> {"id":1,"method":"bci_submitLogin","params":["*********************************"]}
> 20200717 11:30:32:739972 WARN: GPU #0: MSI GeForce GTX 1060 6GB, intensity set to 21
> 20200717 11:30:42:677397 Wait on data is timed out, 10 seconds have passed, 0 bytes in socket remained
> 20200717 11:30:42:678396 WARN: Error during wait on data, The I/O operation has been aborted because of either a thread exit or an application request
> 20200717 11:30:42:679392 WARN: failed to subscribe, JSON-RPC call failed: can't parse json:
> * Line 1, Column 1
>   Syntax error: value, object or array expected.
> 
> 
> 20200717 11:30:42:679392 stratum_disconnect session=
> 20200717 11:30:42:680389 ~AsioWorker
> 20200717 11:30:42:680389 ~AsioWorker DONE
> 20200717 11:30:42:680389 ERROR: No connection, retry after 1 seconds

ProgMiner works well with these parameters:
progpowminer-cuda.exe --pool stratum+tcp://*************************************:ID%3d***************%2cc%3dBTC%2cmc%3dBCI@103.249.70.7:3200 --api-port -4003 --cuda --cuda-devices 0

**Comment by UselessGuru** [comment]
Any update?

**Comment by trexminer** [comment]
Sorry, no update. If you could point us to any open source miner that supports mining BCI, that would help. Thanks.

**Comment by UselessGuru** [comment]
>  If you could point us to any open source miner that supports mining BCI, that would help.

Not that I know of.
