### ISSUE TITLE
[Feature-Idea] mining 2 cryptos with lhr

### ISSUE THREAD

**Issue by forReason** [trexminer/T-Rex#670]
As far as I know, the LHR mode will pause the card sometimes or make it run slower.

Do you think it might be possible to shove another Cryptocurrency in which is not affected by lhr?
EG:
- main mining is ETH in lhr mode
- second cryptocurreny such as raven is mined to utilize the remainder of the card

If that was possible, that would be awesome.

**Comment by megalolka** [comment]
RTX 3060 has 12 Gb of memory, so the ETH DAG file and a RVN or ERGO dataset can be loaded into the video memory at the same time.
Please make the dual-coin mining mode. 
It should increase the LHR-card efficiency.
Thank you!

**Comment by forReason** [comment]
@megalolka please keep in mind, this is just a request. I do not know if it is technically possible.

I have experimented with mining 2 coins in parallel, one which requires more gpu and eth which requires more memory. The result was that both mine at 50%, so no performance uplift.

Adittionally, I tried mining 2 coins parallel in order to circumvent lhr. This was as well not successful. ETH in lhr mode still ate about 50 percent of the hashing power.

So I do not know if the request would be technically possible or would provide much of a benefit. T-Rex is closed source so I cant tell much about the implementation but it might work.

**Comment by trexminer** [comment]
Thanks.
Implemented in https://github.com/trexminer/T-Rex/releases/tag/0.24.0
