### ISSUE TITLE
unable to start miner: api-bind-telnet (Nicehash)

### ISSUE THREAD

**Issue by Miiichal** [trexminer/T-Rex#672]
Hello boyz,
I know, that NicehashMiner officially disabled a chance to download TRex miner inside aka the others excavators.
1) i have NH with new corefiles (still in current version 3.0.6.5)
2) when new version of Trex released, i copy them to the Trex folder

Everything worked fine **till the last version since 23.x**
Every start of any version (23.1 and 23.2) will fail with an error: **api-bind-telnet**
So i have to stand at version 22.6 :(

Is that because of removing api telnet from 23.x?
I am not mining with any special parametrs, nor scripts.
Just overclocked cards with MSI Afterburner and running NH with manual benchmarksof cards).

**Comment by trexminer** [comment]
Hi. Yes, telnet API was removed, `--api-bind-telnet` is no longer a valid parameter.

**Comment by Miiichal** [comment]
OK i see it in your release notes. I dont need it, dont use it :)
Because the NH removed TRex (it was idiotic solution, i know it), am I the only one, who want to use your miner working through the NH app?
As I wrote in my first post - **22.1 and all the previous versions were amazing and good working**.
Now the actual versions since 23.x cannot start.
I dont know, why their app want to find this "telnet" parmeter :(
I really dont want to stay at the old version of excavator only because the Nicehash devs are... "whatever"...

**Comment by Miiichal** [comment]
I know, that i can mine directly with Trex (or any other miner).
But i want to use Nicehash Marketplace because the changing profitability of mined coins and used algos.
**Thats not for me to mine with ONE miner and only ONE coin/algo...**
I only want to add new version of trex directly to his folder (as i did manytimes before) and mine with NEW version of Trex.
But after starting i see an error with "--api-bind-telnet".
So there is something inside NH app, what search telnet (or anything).
Devs of TRex removed telnet from new version and thats the error i get :)

**parse error --api-bind-telnet**

If i am able to avoind this error, it would be great :)

**Comment by VaIerON** [comment]
Miiichal  in which version of NH you can find the folder с TRex ?, I updated NH and it disappeared too
now I use only bat file файл TRex

**Comment by amiazma** [comment]
Still a problem. Cannot we ignore it somehow?
`**parse error: Argument: --api-bind-telnet**`

**Comment by trexminer** [comment]
NH needs to change their plugins not to pass `--api-bind-telnet` as it was removed. The intent to remove it was announced a few releases before the actual removal.

**Comment by amiazma** [comment]
Sounds bad. :D I try to write out it from their code to skipping the `--api-bind-telnet 0` , but I coudnt find this part, just with the cheat engine, and now with hex editors. Im not used to this kind of 'programming'... I hope its in the files, and not an online downloaded temporary variable... :(

**Comment by amiazma** [comment]
It was a hard day...
dnSpy/MP.Trex/MP.Trex.dll/TRex/TRex line 71
