### ISSUE TITLE
-lock-cclock doesn't work with ETH+ERGO dual-mining

### ISSUE THREAD

**Issue by megalolka** [trexminer/T-Rex#684]
Hi!
When running dual-mining ETH+ERGO on the latest 0.24.0 version with 3060Ti LHR cards, the -lock-cclock option does not work. The miner gives an error when starting.
Is it possible to make the core clock lock without hitting the LHR mechanism? 

PS: Is it possible to increase the 30% value of ETH dual-mining on the 3060 \ 3060Ti LHRv2 cards?

**Comment by mexarrinha** [comment]
Try two dashes before the lock.  "--lock-cclock"

**Comment by megalolka** [comment]
Of course I mean two dashes. The miner accepts the key but tells that it's not possible to lock the clock in dual-mode.

**Comment by mexarrinha** [comment]
it is working fine here. maybe some other config is messing that up

**Comment by megalolka** [comment]
You were right, there was no admin rights.
Sorry!
