### ISSUE TITLE
ETH-ERG Hashrate not stable

### ISSUE THREAD

**Issue by AHMAD-30** [trexminer/T-Rex#686]
Why my hash rate is fluctuating on dual mining for two 3080ti ?
GPU 0 PNY 3080ti ETH (20 to 32)MH  ERG (175 to 198)MH
GPU 1 PNY 3080ti ETH (26 to 35)MH  ERG (175 to 193)MH
Clocks Core 0 Memory 2000 Power 287 for both cards
its not stable at all

**Comment by trexminer** [comment]
Reported hashrate is an average over the past minute. Run the miner with `-N 180` (3 minute averaging windows) for a smoother hashrate.
