### ISSUE TITLE
Miner works great, but how do I fix the constant warning spam?

### ISSUE THREAD

**Issue by yoshiko2000** [trexminer/T-Rex#71]
I'm using T-Rex to mine raven. It keeps popping this up. How do I fix this in the configuration?
![warning](https://user-images.githubusercontent.com/67814417/91546850-1bd61a00-e8f1-11ea-9dd5-0cd8926c1a49.png)

**Comment by trexminer** [comment]
You can run t-rex with `--api-bind-telnet 0 --api-bind-http 0` to disable the API since you are not using it, and the miner will stop whinging about the bind errors
