### ISSUE TITLE
Remote update stopped working

### ISSUE THREAD

**Issue by InfiniteImp** [trexminer/T-Rex#721]
Somewhere in the last few release versions the ability to remotely update using the web API (via the green "Do Update" button) stopped working.  Now if you press it, all you see on the target miner's screen is:

20211012 21:48:23 API CALL: change config :
{
        "retrive-all-configs" : true
}

Then it just keeps on mining.  Tested on version 0.23.2, but it did this on the last release or the one before it as well.

**Comment by trexminer** [comment]
Unfortunately old webui can't activate update with new T-Rex versions because of password protection policy. To use all features please try built-in new webui.
