### ISSUE TITLE
ERROR: Can't find nonce with device [ID=0, GPU #0], cuda exception in [ethash_generate_dag, 437], unspecified launch failure

### ISSUE THREAD

**Issue by williamzerner** [trexminer/T-Rex#73]
I dont understand what is this error 
GPU: Nvidia 940MX
GPU Dedicated Ram : 4 GB
Nvidia Driver version: 452.06
Nvidia Cuda version: 11.0.221
OS: Windows 10 Professional
I am trying to mine Ravencoin(RVN) KawPow algorithm dag is 2.49 GB. And also I am not mining anything else especially ethash.
Also i have not overclocked anything and i got the same error when i had cuda version 10 and i tried all sorts of combos(cuda 11 miner with cuda version 10,11 ...cuda 10 miner with cuda version 10,11)

**Comment by trexminer** [comment]
Try to use a new version of the miner 0.17.2. Start with parameter --low-load 1. Let me know if it help.

**Comment by williamzerner** [comment]
same error but instead of ethash_generate_dag, 437 it came ethash_generate_dag, 419. And also before the error came for the first time gpu was inactive for 30 seconds

**Comment by williamzerner** [comment]
any update? I tried different versions of cuda and different versions of miner. Even formatted my machine.

**Comment by trexminer** [comment]
Seems hardware related

**Comment by williamzerner** [comment]
well thanks for trying :(

**Comment by AmityTek** [comment]
Same error on W10 with GTX 1660 TI ...
