### ISSUE TITLE
Request: different algos on differnt cards on rig

### ISSUE THREAD

**Issue by griinis** [trexminer/T-Rex#736]
I have 1060, 1070Ti, 1080Ti in my home PC. It would be great to manage all cards when mining the best performance coin for every card. Now it is eth, but further ....
Best wishes.

**Comment by Crisis83** [comment]
Yup, just run different instances with the -d flag selecting which gpu’s to use. I run 2-3 per rig, mainly since I wanted to split out LHR cards.
