### ISSUE TITLE
--mt parameter

### ISSUE THREAD

**Issue by jarboloide** [trexminer/T-Rex#738]
I suggest that the memory optimization parameter be automatic when identifying 1080 and 1080ti cards.

**Comment by trexminer** [comment]
I can't be automatic because
1. There are 6 values for it, which one would you set?
2. Forcing it enabled by default for everyone will cause GPU crashes and user complaints

**Comment by ezanchi** [comment]
> I can't be automatic because
> 
> 1. There are 6 values for it, which one would you set?
> 2. Forcing it enabled by default for everyone will cause GPU crashes and user complaints

I have got a 1080 and whenever I am using the -mt parameter even on 1 my computer BSOD and restarts after some time. Is that normal/expected behavior?

**Comment by trexminer** [comment]
> I have got a 1080 and whenever I am using the -mt parameter even on 1 my computer BSOD and restarts after some time. Is that normal/expected behavior?

It may have that nasty side effect, yes

**Comment by ezanchi** [comment]
Can anything be done to prevent that? Even lowering OC/UC won't help..

**Comment by trexminer** [comment]
Can't think of anything else other than lowering OC.
Perhaps try asking for help in our Discord server, or any other mining community, I don't own a 1080 personally.
