### ISSUE TITLE
Graph gets spooky starting midnight

### ISSUE THREAD

**Issue by Leozolt** [trexminer/T-Rex#74]
The Graph just looses its "line" from 0 hour (12h midnight) until it recovers starting at 1 am.
I also want to complain that there must be a bigger dev fee than 1% implemented because on my 36 MH/s that the software reports as average, and the pool sees on peaks, there are only 32 Mh/s average left. But that has nothing to do with the chart error.

![Screenshot from 2020-09-17 00-01-25](https://user-images.githubusercontent.com/26518970/93397543-1ded2200-f87a-11ea-91d5-ec003a01f8c9.png)

**Comment by loopy750** [comment]
I came here to report the same graph issue (12am-1am), but searched it first. I guess it's a low priority.

**Comment by DejanRibnikar** [comment]
same thing

**Comment by trexminer** [comment]
Should be fixed in 0.20.1
