### ISSUE TITLE
Not a issue - question

### ISSUE THREAD

**Issue by sam1e-dev** [trexminer/T-Rex#742]
Hi, will this GPU work with the LHR bypass?
From this article: https://www.pcgamer.com/t-rex-mining-gpu-cryptocurrency-hash-rate-unlock/
I've read if you have 10+ gb you can unlock full eth speed on linux but they say since 10+gb vram is needed rtx 3060 wont work, but what about this one 12gb version, will it work? Thanks for any help :D or if you can suggest any other gpu in this price range.
https://www.czc.cz/msi-geforce-rtx-3060-gaming-x-12g-lhr-12gb-gddr6/310900/produkt

**Comment by dimitriovic** [comment]
quote from t-rex specs:

"LHR unlock dual mining mode:
You can now mine ETH (~30% of full speed) and other coins (~70%) simultaneously with LHR cards using their full potential.
Available combinations along with memory requirements:

    ETH+ERGO (8GB+)
    ETH+RVN (8GB+ on linux, 10GB+ on windows)
    ETH+CFX (10GB+)
    See https://github.com/trexminer/T-Rex/wiki/LHR on how to set it up."

3060 have 12gb, it's more than 10gb then it's ok for all the above cases
3060ti have 8gb, it's less than 10gb then:
 it's ok for dual eth+ergo (windows or linux) 
and ok for eth + rvn (on linux, but not on windows cause it requires 10gb+ vram)
and not ok for eth+cfx cause it requires more than 10gb vram be it on windows or linux

**Comment by sam1e-dev** [comment]
Ok sir, thanks :D
