### ISSUE TITLE
TRex miner does not release core clock lock when dual mining (Windows 10)

### ISSUE THREAD

**Issue by absolution1** [trexminer/T-Rex#745]
Hi everyone,

Firstly, TRex is amazing!

My TRex setup does not release the core clock lock when I exit (even using ctrl+C).  This issue only happens when using dual mining AND the miner has been running for a few minutes (long enough to report hash rates).
Weirdly the core clock lock IS released when dual mining if I exit the miner very soon after the command line printout states that the core has now been locked.

I'm using TRex miner 0.24.2 and windows 10 with a 3060 TI, mining eth + ergo.

**Comment by emilytingwang** [comment]
I also reported this about a week ago (issue #723) -  I suspected this had something to do with my using Win11. Glad to see this is not the case!

**Comment by trexminer** [comment]
here is the build with a possible fix for dual mode (windows assembly)
https://www.dropbox.com/s/svmnpjcw3e5syi0/t-rex-0.24.2-win.zip?dl=1

**Comment by absolution1** [comment]
@trexminer that works perfectly.
Thank you Mr or Ms TRex
