### ISSUE TITLE
T-REX Restarting After 5 MINUTES (CUDA_ERROR_ILLEGAL_ADDRESS)

### ISSUE THREAD

**Issue by fabregaspacheco** [trexminer/T-Rex#749]
I'm facing the following trouble when mining is running..

Can’t find nonce with device [ID=0, GPU #0], cuda exception:  CUDA_ERROR_ILLEGAL_ADDRESS, try to reduce overclock to stabilize
GPU state

After it restarts

Does anyone know how to fix it?

**Comment by trexminer** [comment]
> try to reduce overclock

**Comment by fabregaspacheco** [comment]
not working, after changing configs the software is detecting LHR very often

**Comment by trexminer** [comment]
Ok. There are a few open issues where people reported LHR detection issues, you can use those for your report too. Thanks.
