### ISSUE TITLE
Hashrate not showing in API Graph

### ISSUE THREAD

**Issue by Teddymeyn** [trexminer/T-Rex#750]
Hashrate not showing in API Graph , showing as 0 in the API graph, average and current Hash is zero

**Comment by Teddymeyn** [comment]
![Screenshot 2021-10-20 012646](https://user-images.githubusercontent.com/89279442/137981528-d38a2308-b729-44b6-b5df-a039fc8027ec.png)
![Screenshot 2021-10-20 012743](https://user-images.githubusercontent.com/89279442/137981535-086cdc9c-7f46-4f9d-97ea-2eab48a47baf.png)

**Comment by trexminer** [comment]
Thanks.Could you open http://127.0.0.1:4067/summary?last-stat-ts=0 in your web browser when you're experiencing this issue and post the result?

**Comment by Teddymeyn** [comment]
{"accepted_count":0,"active_pool":{"difficulty":"4.00 G","last_submit_ts":0,"ping":0,"retries":0,"url":"stratum+ssl://eth-hk.flexpool.io:5555","user":"0x660A28FF08dcB7574F3b17b60E08eF32c5261Ee1","worker":"Troy"},"algorithm":"ethash","api":"4.1","build_date":"Oct 10 2021 16:42:19","coin":"","description":"T-Rex NVIDIA GPU miner","driver":"471.41","gpu_total":1,"gpus":[{"cclock":1892,"dag_build_mode":0,"device_id":0,"efficiency":"0.00H/W","fan_speed":87,"gpu_id":0,"gpu_user_id":0,"hashrate":0,"hashrate_day":0,"hashrate_hour":0,"hashrate_instant":0,"hashrate_minute":0,"intensity":21.0,"lhr_tune":73.0,"low_load":false,"mclock":8753,"mtweak":0,"name":"RTX 3060","paused":false,"pci_bus":1,"pci_domain":0,"pci_id":0,"potentially_unstable":false,"power":92,"power_avr":90,"shares":{"accepted_count":0,"invalid_count":0,"last_share_diff":0,"last_share_submit_ts":0,"max_share_diff":0,"max_share_submit_ts":0,"rejected_count":0,"solved_count":0},"temperature":62,"uuid":"fa2cc256da074aa82b302e7c8e3ff0a3","vendor":"NVIDIA"}],"hashrate":0,"hashrate_day":0,"hashrate_hour":0,"hashrate_minute":0,"invalid_count":0,"name":"t-rex","os":"win","paused":false,"rejected_count":0,"revision":"66f25c328d28","sharerate":0.0,"sharerate_average":0.0,"solved_count":0,"success":1,"time":1634735431,"uptime":26,"validate_shares":false,"velocities":{"hashrate":[[1634735405,0],[1634735416,0],[1634735426,0]],"power":[[1634735405,115],[1634735416,83],[1634735426,82]]},"version":"0.24.2","watchdog_stat":{"built_in":true,"startup_ts":347260,"total_restarts":0,"uptime":28,"wd_version":"0.24.2"}}

**Comment by Teddymeyn** [comment]
{"accepted_count":3,"active_pool":{"difficulty":"4.00 G","last_submit_ts":1634735619,"ping":113,"retries":0,"url":"stratum+ssl://eth-hk.flexpool.io:5555","user":"0x660A28FF08dcB7574F3b17b60E08eF32c5261Ee1","worker":"Troy"},"algorithm":"ethash","api":"4.1","build_date":"Oct 10 2021 16:42:19","coin":"","description":"T-Rex NVIDIA GPU miner","driver":"471.41","gpu_total":1,"gpus":[{"cclock":1648,"dag_build_mode":0,"device_id":0,"efficiency":"308kH/W","fan_speed":87,"gpu_id":0,"gpu_user_id":0,"hashrate":35167181,"hashrate_day":0,"hashrate_hour":38391437,"hashrate_instant":27737291,"hashrate_minute":35092918,"intensity":21.0,"lhr_tune":73.0,"low_load":false,"mclock":8753,"mtweak":0,"name":"RTX 3060","paused":false,"pci_bus":1,"pci_domain":0,"pci_id":0,"potentially_unstable":false,"power":115,"power_avr":114,"shares":{"accepted_count":3,"invalid_count":0,"last_share_diff":0.0,"last_share_submit_ts":0,"max_share_diff":0.0,"max_share_submit_ts":0,"rejected_count":0,"solved_count":0},"temperature":64,"uuid":"fa2cc256da074aa82b302e7c8e3ff0a3","vendor":"NVIDIA"}],"hashrate":35167181,"hashrate_day":0,"hashrate_hour":38391437,"hashrate_minute":35092918,"invalid_count":0,"name":"t-rex","os":"win","paused":false,"rejected_count":0,"revision":"66f25c328d28","sharerate":0.871,"sharerate_average":0.84099999999999997,"solved_count":0,"success":1,"time":1634735663,"uptime":258,"validate_shares":false,"velocities":{"hashrate":[[1634735405,0],[1634735416,0],[1634735426,0],[1634735436,42170210],[1634735446,34629196],[1634735456,33912864],[1634735466,34314104],[1634735477,34857844],[1634735487,34735482],[1634735497,34476113],[1634735507,33839694],[1634735517,34694433],[1634735527,35154426],[1634735537,34668595],[1634735548,34260762],[1634735558,34460818],[1634735568,35104907],[1634735578,35564660],[1634735588,34736748],[1634735598,34383025],[1634735608,34737098],[1634735619,35151931],[1634735629,34968498],[1634735639,34170967],[1634735649,34015714],[1634735659,34711620]],"power":[[1634735405,115],[1634735416,83],[1634735426,82],[1634735436,115],[1634735446,115],[1634735456,115],[1634735466,115],[1634735477,115],[1634735487,114],[1634735497,114],[1634735507,115],[1634735517,115],[1634735527,115],[1634735537,114],[1634735548,114],[1634735558,115],[1634735568,115],[1634735578,115],[1634735588,114],[1634735598,115],[1634735608,115],[1634735619,115],[1634735629,115],[1634735639,114],[1634735649,115],[1634735659,115]]},"version":"0.24.2","watchdog_stat":{"built_in":true,"startup_ts":347260,"total_restarts":0,"uptime":260,"wd_version":"0.24.2"}}

**Comment by Teddymeyn** [comment]
it is still the same
![5](https://user-images.githubusercontent.com/89279442/138101439-840fc680-05d5-4990-9b7e-6c13ba564684.png)
