### ISSUE TITLE
Gigabyte 3070ti out of memory problem

### ISSUE THREAD

**Issue by hdeveci** [trexminer/T-Rex#766]
I built a rig today with 4 Galax 3070ti, 1 Asus 3070ti, 1 Gigabyte 3070ti and one Gigabyte GTX1070. My problem is with Gigabyte 3070ti. I’m getting “cuda out of memory” error or “cuda unknown error” all the time. With OC and without OC. Tried increasing virtual memory and it didn’t work. I’m sending a photo for reference. Sometimes I get GPU #260 error with galax card but I don’t care about it too much. There happens something interesting I see in the beginning of miner. All of the cards say memory left 3,89 GB but gigabyte says 4,01 GB. Please please help me.
![D31C348F-FBDF-4534-BE57-BA94F9447BAE](https://user-images.githubusercontent.com/93055134/138569668-f96ecfb2-03c4-4a08-bd2f-3ec90dedad2f.png)
![9869302A-AB42-4B90-BBD4-E09247610CE5](https://user-images.githubusercontent.com/93055134/138569670-6077e4fe-1c87-472e-897c-0e1701e5bd91.png)

**Comment by trexminer** [comment]
Out of memory should be solved by increasing virtual memory size which you already did.
As for error code 999, see https://github.com/trexminer/T-Rex/issues/226
