### ISSUE TITLE
3060 LHR GA104 can‘t unlock 70% hashrate

### ISSUE THREAD

**Issue by linlexuan2005** [trexminer/T-Rex#776]
I got a newly released 3060, GA 104, and device ID is 2487, this new core cannot be unclocked 70% hashrate. Hope to solve this problem soon

**Comment by keks2293** [comment]
Logs?

**Comment by mada1666** [comment]
I have the same trouble,no [LHR 71<>] message just vacancy.
Any progress on it?
I follow this thread few day ago,but seem to nothing happen :(
My nvidia driver is 470.80.00 and hiveos is 5.10.0-hiveos #72
card is evga 3060 ga104,ID 2487.

**Comment by trexminer** [comment]
> Any progress on it?

There's a test version that fixes this: https://trex-miner.com/download/test/t-rex-0.24.6-linux.tar.gz

**Comment by mada1666** [comment]
I'm not familar with linux so I might wait for the next version release,
anyway it is glade to hear the news,thank you trexminer.

**Comment by trexminer** [comment]
Fixed 3060 GA104 LHR auto-detection in 0.24.6
