### ISSUE TITLE
using TRex to mine ETH&ERGO, two requests for additional hashrate settings options

### ISSUE THREAD

**Issue by sscfla** [trexminer/T-Rex#778]
I am new to Github, I have benefited from code I've downloaded here for years but this is my first post.  If this should be posted elsewhere or I should be doing something different I'd appreciate knowing where this request should go.

Hi, I'm using T-Rex with a 3060 TI card to mine ETH and ERGO and it seems to be working as it should, yielding about 22 MH/s with ethash and about 77 MH/s with autolykos2.  I have experimented with trying to get finer control of the --lhr-tune option and it does seem to make a difference in the "target hashrate for unlocker" if I put in say 35.5 versus 35 or 36, though I don't know how consistent the change really is or if it is as linear as might be implied.  

I know the change may seem negligible but if I can get even a percent or two improvement it seems worth a few minutes here and there to tweak it and look for changes over a day or so.  Am I correct in assuming the program is really distinguishing between lhr-tune values less than a full percent different?

Secondly, and maybe more important, I'd like the ability to vary the weighting that is given to one algorithm versus the other.   It appears that ethash is running with a reduced "duty cycle," as can be seen in the power consumption varying like a square wave or a pulse, while autolykos is just running with some proportionally reduced hashrate that may not vary once the program is running with some given lhr-tune value.  But I'm wondering if it might be possible to tweak the weighting it's giving to one algorithm vs the other, as again I might be able to get a little more overall return.   I'm not suggesting necessarily I be able to set some absolute value for lhr-tune for each algorithm, though that might work ok, I'm thinking there is some relationship or weighing that's given for a certain lhr-tune to set the "target hashrate for unlocker" for ethash versus the duty cycle or percentage of maximum hashrate allowed for autolykos, and maybe a command line option that allows users to vary that might be useful.

I know that the more options are given end users the more some people may be confused or frustrated as they try to tweak settings when they should be doing something different in the first place, but I'm thinking this may be something some users could benefit from,

**Comment by trexminer** [comment]
Added `--lhr-autotune-step-size` and `--lhr-autotune-interval` in 0.24.6
