### ISSUE TITLE
T-Rex NVIDIA GPU miner v0.17.3  -  [CUDA v11.10]: Can't find nonce with device [ID=0, GPU #0], cuda exception in [trexInitializerM, 241], unspecified launch failure

### ISSUE THREAD

**Issue by UselessGuru** [trexminer/T-Rex#78]
t-rex.exe --algo kawpow --url stratum2+tcp://KAWPOW.eu.nicehash.com:3385 --user **********************.*****--pass x --no-watchdog --gpu-report-interval 1 --api-bind-http 127.0.0.1:4004 --api-bind-telnet 0 --quiet --retry-pause 1 --timeout 50000 --cpu-priority 4 --devices 0
20201001 14:35:59 T-Rex NVIDIA GPU miner v0.17.3  -  [CUDA v11.10]
20201001 14:35:59 r.f5448042d424
20201001 14:35:59
20201001 14:35:59 NVIDIA Driver v452.06
20201001 14:35:59 CUDA devices available: 2
20201001 14:35:59
20201001 14:35:59 WARN: DevFee 1% (kawpow)
20201001 14:35:59
20201001 14:35:59 URL : stratum+tcp://KAWPOW.eu.nicehash.com:3385
20201001 14:35:59 USER: ****************************.*************
20201001 14:35:59 PASS: x
20201001 14:35:59
20201001 14:35:59 WARN: Built-in watchdog has been disabled!
20201001 14:35:59 Starting on: KAWPOW.eu.nicehash.com:3385
20201001 14:35:59 ApiServer: HTTP server started on 127.0.0.1:4004
20201001 14:35:59 ------------------------------------------------------
20201001 14:35:59 For control navigate to: http://172.30.176.1:4004/trex
20201001 14:35:59 ------------------------------------------------------
20201001 14:35:59 Extranonce is set to: 39dab9
20201001 14:35:59 Authorizing...
20201001 14:35:59 Authorized successfully.
20201001 14:35:59 New target is set to: 0x000000094ff8872c000000000000000000000000000000000000000000000000
20201001 14:35:59 kawpow epoch: 190, block: 1431592, period: 477197, diff: 0.110 = 461.20 Mh
20201001 14:35:59 WARN: GPU #0[10000]: MSI GeForce GTX 1060 6GB, intensity set to 20
20201001 14:36:01 GPU #0: generating DAG 2.52 GB ...
20201001 14:36:16 GPU #0: DAG generated [time: 15297 ms], memory left: 3.48 GB
20201001 14:36:16 ERROR: Can't find nonce with device [ID=0, GPU #0], cuda exception in [trexInitializerM, 241], unspecified launch failure
20201001 14:36:16 WARN: Messy shutdown...
20201001 14:36:16 Main loop finished.

**Comment by trexminer** [comment]
Try CUDA v10.0 build or update your video driver. Please let me know how it goes.

**Comment by UselessGuru** [comment]
> Try CUDA v10.0 build or 
CUDAv10.0 build is working
But does CUDA v10.0 build also work with RTX 30x?

> update your video driver. Please let me know how it goes.
Cannot update to newer NVIDIA drivers (their NVML is broken, tried 456.55 before).

**Comment by trexminer** [comment]
No, CUDA v10.0 won't work with RTX 30x. At the moment CUDA v11.1 is the only version that works with RTX 30x.
Here's CUDA Toolkit <-> Driver version compatibility table
![image](https://user-images.githubusercontent.com/44735836/95318026-b149ce00-08e1-11eb-92c7-6421ad2e48fa.png)
So, v456.38 is the minimum in order for the CUDA v11.1 build to work

**Comment by UselessGuru** [comment]
Just installed 456.71 drivers. Problem on CUDA 11.1 seems gone.
And NVML also seems OK.
