### ISSUE TITLE
small fix. LHR mode with decimals in cfg file 

### ISSUE THREAD

**Issue by cubecloud** [trexminer/T-Rex#781]
Hi!
I'm using decimals in LHR mode to fine tune card performance, to create closest and highest to LHR block card performance.
It's helps to get ~0.8-1Mh on Etherium at final config, with tuning with  cclock and memory lock using nvidia-settings
Unfortunately, if i using config mode, i can't tune this parameter with decimals at remote, cos can't **save** this parameter with decimals. 
Can you change this to save lhr-tune to config file with decimals?
![image](https://user-images.githubusercontent.com/6572728/138874712-171d4029-c4cb-4447-9f49-5cd42cb2f949.png)

 
![image](https://user-images.githubusercontent.com/6572728/138875759-dc799bec-f17b-4dec-98a0-2b2b1dbe1981.png)

**Comment by trexminer** [comment]
Fixed in 0.24.7
