### ISSUE TITLE
New Interesting way to get higer hashs

### ISSUE THREAD

**Issue by nudago** [trexminer/T-Rex#784]
## New discovery
I'm a 3060lhr, 2070 miner. I am running t-rex 2.242. on my desktop(3060) used working and game.(normally 30~32hashs)

![image](https://user-images.githubusercontent.com/18652811/138868194-6bb1ad00-089c-4667-8e76-ab4a7f3272cf.png)
(need -42.5 because 2070 runned) after run mining on 3060lhr. I missed exit miner program when I run Starcraft2.

so it's hash dropped dramtically almost 6~8hash. it's normal because i am playing a game happily=). 
![image](https://user-images.githubusercontent.com/18652811/138868353-82bd4daf-3d3d-4883-a672-8089d158a300.png)

but after I playing a game. eth hash goes up to 36hashs.
![image](https://user-images.githubusercontent.com/18652811/138868102-3eef49c9-5f4c-4a08-8bbe-ce9e88a084f5.png)

I am surprised. exit miner and re launch miner program but it cannot reach 36hashs. so something logic worked by playing starcraft2

## Experiments
![image](https://user-images.githubusercontent.com/18652811/138869229-27e27929-aa22-4fa5-b3ff-2b749d63f8ec.png)
It' can easily up to 36hash just running starcraft2 background. actually i can't know why it can be. but it's easy way to up hashs. I'll retry it.
![image](https://user-images.githubusercontent.com/18652811/138869898-bec3e62c-55b9-44ea-a304-a866e5d4d2a5.png)
start starcraft2 play game makes lhr detetection. minimize game and check until lhr tune go to 43
![image](https://user-images.githubusercontent.com/18652811/138897300-cc508a7f-4002-4dae-859c-7bb9c1c48a17.png)
if lhr tune under 44 minimize starcraft2 and check it’s over original hash.
![image](https://user-images.githubusercontent.com/18652811/138897446-de1d02de-367f-4111-879a-ee0eae9fdc1d.png)

if you check hash goes over 40hash you can turn off starcraft2 and do mining
That's it! it' grow up hash!! =) avg36hash reached. even low power consumed.

## hw info
![image](https://user-images.githubusercontent.com/18652811/138897781-5ec7916d-3fc8-437e-88d4-449e6f8f6481.png)
![image](https://user-images.githubusercontent.com/18652811/138897821-c0a7b90d-6909-4e0c-9dca-0fb29b76bee0.png)
![image](https://user-images.githubusercontent.com/18652811/138897111-432e92ff-e8ee-41f1-9881-38e7f8884549.png)

## settings
t-rex.exe -a ethash -o stratum+tcp://asia2.ethermine.org:14444 -u "wallet address" -p x -w 3060lhr --lhr-tune 69 --lhr-low-power --no-new-block-info

## Idea
1. I think using fake game instance it can be deceive lhr detection.
2.  running game makes lhr tune goes 69->43. Interestingly when lhr tune go to 43 good at hashs.(normally  29~ 32hash, avg30hash in 69) changed to 29~ 47hash fluctuate, avg 36 hash(even after turn off sc2) (but must turn on game and miner takes each other GPU resource. (if you only set  lhr tune 43 not worked).
3. Can we implement a situation in which the game is turned on in the miner program?
4. summarize. play game with miner, minimize game and check higher hash rates, turn off game.
![image](https://user-images.githubusercontent.com/18652811/138901641-5912cb7d-a6cd-43e3-9913-80e422976903.png)
![image](https://user-images.githubusercontent.com/18652811/138903674-c9189aeb-790c-490d-87f2-9cdffdaaed1d.png)

**Comment by innowebka** [comment]
for 3060 use 470.05 nvidia ?

**Comment by trexminer** [comment]
> for 3060 use 470.05 nvidia ?

for 3060 rev.1, yes

**Comment by trexminer** [comment]
Confirmed the LHR 43 thing was a bug and fixed in the newer versions, so closing the issue.
