### ISSUE TITLE
Dual mining not working?

### ISSUE THREAD

**Issue by ForbiddenEra** [trexminer/T-Rex#787]
RTX3060 (EVGA 12g-p5-3657-KR GA104 A1 (470.05 won't pick it up) Win10 496.49 (also tried 472.12)

When trying any of the 'unlock' .bats (no settings changed for testing, not even wallet) I get 0 h/s on the 2nd coin and ~20mh/s on eth?

Not sure why it's not working for me.

**Comment by DjHillier55** [comment]
I can confirm what OP has experienced. I just acquired an EVGA 3060 XC, GA104 core, device ID 2487. T-REX does not recognize this as an LHR GPU while it seems to have the same limitations as the latest LHR v2 cards. Attempting to dual mine ETH + RVN with --lhr-tune 30 I get constant LHR detections with hashrates in the 1-5 MH/s range for both algos. Hopefully this can be addressed as it seems alot of the recent 3060s coming out are GA104 based. Fortunately RVN is unrestricted and is most profitable as of now.

**Comment by trexminer** [comment]
Fixed 3060 GA104 LHR auto-detection in 0.24.6
