### ISSUE TITLE
--log-path command is dangerous

### ISSUE THREAD

**Issue by lordsilver** [trexminer/T-Rex#797]
1) The "--log-path" command has some problems, as using it with "C:\Users\User\Desktop" as my absolute path somehow killed my Windows, I was constantly getting "path does not exist" error as I couldn't access my main drive anymore. So I performed a system restore to get it back running.

2) Then I tryed to use again the command, this time "-l" to see if there could be any change, and use a new folder called "log" so that the absolute path would be "C:\Users\User\Desktop\log" This time the "log" folder got automatically renamed to "log-[1635748913]" and a "log.txt" was generated in "C:\Users\User\Desktop".

3) So I tryed one last time specifying "C:\Users\User\Desktop\log\log.txt" as my absolute path, and this time I got a new file called "log-[1635748816].txt" created inside the "log" folder.

Both attempts 2) and 3) luckily didn't break anything aside from not working as intended, and I could actually get the log written to a file, even tho not where I wanted. My assumption at this point is that by specifying the Desktop as my absolute path, T-Rex Miner renamed my Desktop folder or broke something with the C: drive path so that it was no longer accessible. Anyway, there's clearly a serious bug with the program and I won't use the log feature till this issue is fixed.

**Comment by aie0** [comment]
It needs to support a path to a folder and insider make log rolling - otherwise lot.txt will be huge and unmaintainable.

**Comment by trexminer** [comment]
> It needs to support a path to a folder and inside make log rolling - otherwise log.txt will be huge and unmaintainable. Log rolling settings would also be great...

Based on user experience the miner's uptime very rarely becomes long enough to produce a huge log file.
Any logging customisation can be done by redirecting console output to a third-party logging app.

**Comment by trexminer** [comment]
Just to add to the above, the miner automatically rotates log files in 10MB chunks putting them in a separate folder next to `log.txt`

**Comment by trexminer** [comment]
Fixed in 0.24.6
