### ISSUE TITLE
Request: Addition of Equihash 125,4 Algorithm

### ISSUE THREAD

**Issue by gorgarp** [trexminer/T-Rex#798]
Hello! I'd like to request Equihash 125,4 be added. Our project, Flux (Runonflux.io), is a GPU minable coin and is one of the fastest growing projects in the space.

Please reach out to us on dicord.io/runonflux, if you would like to discuss this. Your project looks extremely promising and we'd love to work with you.

Current implementations are gminer, miniz, lolminer.

**Comment by FrameKarl** [comment]
That would be very nice! +1

**Comment by IcannotThinkOfAnymoreNames** [comment]
Current implementations gminer, miniz, lolminer. that do not have practical power limits. Apparently not from this planet.

Help us T-Rex, you are our only hope!

**Comment by FrameKarl** [comment]
ohu yes please integrate FLUX asap

**Comment by gorgarp** [comment]
Hello, any update? Eth is moving towards PoS and Flux is one of the top 4 contenders for the hashrate after.

**Comment by gorgarp** [comment]
Just bumping.
