### ISSUE TITLE
HR drop after update

### ISSUE THREAD

**Issue by GrannyCryptomaster** [trexminer/T-Rex#8]
I updated to 0.9.2, win 10, cuda 10, and for x16rt the hashrate droped from 97 to 92 mh/s on my 7 GPU rig (1060 3GB). This is the average HR on MiningRigRentals during the rental period, after 24 h.

**Comment by trexminer** [comment]
Are you still experiencing this issue? There was no x16rt performance changes in 0.9.2 compared to 0.9.1
