### ISSUE TITLE
Power usage in API no longer available for NVIDIA Driver 456.55 and newer

### ISSUE THREAD

**Issue by UselessGuru** [trexminer/T-Rex#80]
as per title.

Power usage IS exposed in API when NVidia driver is older than version 456.55.
Note: This is not a problem unique to TRex. Same problem with Gminer

**Comment by trexminer** [comment]
Thank you for the report. Will look into it.

**Comment by UselessGuru** [comment]
Seems to work in NVidia driver 457.09

**Comment by trexminer** [comment]
Excellent, thanks for letting me know.
