### ISSUE TITLE
(BUG)script-crash and script-low-hash

### ISSUE THREAD

**Issue by blue-battery** [trexminer/T-Rex#804]
windows10 :21H1
T-Rex :0.24.5
I use trex with a config file.
When I use the latest version of trex,file name contains forbidden characters . I took serval hours to find out where error from and why.
I find script-crash and script-low-hash can't use "../reboot.bat",but 0.22.0 won't show error.
Plz fix it

**Comment by trexminer** [comment]
Not a bug, was done that way purposely for security reasons (to avoid executing arbitrary system scripts). The scripts must be located in the same directory as t-rex executable.
