### ISSUE TITLE
(BUG)script-crash and script-lowhash

### ISSUE THREAD

**Issue by blue-battery** [trexminer/T-Rex#805]
---------old
windows10 :21H1
T-Rex :0.24.5
I use trex with a config file.
When I use the latest version of trex,file name contains forbidden characters . I took serval hours to find out where error from and why.
I find script-crash and script-low-hash can't use "../reboot.bat",but 0.22.0 won't show error.
Plz fix it
-----------
Plz fix your error message!!!

__最初由 @blue-battery 在 https://github.com/trexminer/T-Rex/issues/804 发布__

**Comment by trexminer** [comment]
Fixed in 0.24.6
