### ISSUE TITLE
High CPU usage after Windows 11

### ISSUE THREAD

**Issue by rossetepatrick** [trexminer/T-Rex#807]
Hello guys.
Today I installed Windows 11 and realized that T-Rex Miner is consuming a lot of CPU. 
When I used Windows 10 it was below 2% and now is consuming around 30%..

MB: Asus Z97-M Plus LGA 1150
CPU: Intel i7 4790

![2021-11-04](https://user-images.githubusercontent.com/93733218/140396723-f2f85f72-b5ac-47af-a960-6b34e606b85d.png)

**Comment by trexminer** [comment]
Hi. Is HAGS turned on in your system? https://github.com/trexminer/T-Rex/wiki/FAQ#high-cpu-usage

**Comment by griinis** [comment]
Hi, don't use latest Nvidia drivers on 10X0 cards.

**Comment by rossetepatrick** [comment]
> Hi. Is HAGS turned on in your system? https://github.com/trexminer/T-Rex/wiki/FAQ#high-cpu-usage

Problem solved.
HAGS was turned on in my system.
Thank you very much.
