### ISSUE TITLE
(Question) Dev fee session

### ISSUE THREAD

**Issue by DejanRibnikar** [trexminer/T-Rex#808]
What happens if miner hits a block on solo mining during dev fee session?

**Comment by trexminer** [comment]
Dev fee is mined to mining pools, not nodes.
Could you clarify the question?

**Comment by DejanRibnikar** [comment]
A miner can hit a block at any time. If it hits a block during dev fee session, does that whole block then belong to the pool of that session and get shared with other pool users?

**Comment by trexminer** [comment]
By hitting a block do you mean the miner has found a block, or the mining pool pushed information about a newly found block? If the former, we're not mining solo during dev fee sessions and if the miner finds a block the reward gets distributed according to the dev fee mining pool's reward scheme, be it PPLNS, PPS etc.

**Comment by DejanRibnikar** [comment]
That was my concern yes. If miners finds a block. So in that case all the work is lost for that block...
