### ISSUE TITLE
Question -- support for new ergo epoch on Sunday

### ISSUE THREAD

**Issue by Deadtenor** [trexminer/T-Rex#813]
Does t-rex miner support the new ergo epoch rolling out Sunday November 7?    I saw this video and it made me wonder if it does.  https://www.youtube.com/watch?v=Hfq9HoXYwYc

**Comment by trexminer** [comment]
Yes

**Comment by Marsi4eg** [comment]
After block 614400 hashrate dropped by 30% on maxwell nvidia (970). Was 43.67mh, became 31.3mh. I wonder if some update will be released

**Comment by trexminer** [comment]
@Marsi4eg Must be good old hashrate degradation, similar to when Ethereum's DAG became bigger than 2GB. There's no fix unfortunately, other than buying a newer graphics cards.
