### ISSUE TITLE
Cant find nonce with device 

### ISSUE THREAD

**Issue by Tehqy** [trexminer/T-Rex#815]
Every time i try to mine ethereum with t-rex, ethermine it says that "Cant find nonce with device " 

How to fix the issue? i am running a GTX 1080 Ti and have 8GB of RAM installed. Am i doing something wrong?

![Issue](https://user-images.githubusercontent.com/90979039/140659639-b186bfa0-8f40-474b-9b68-88da0601d0d3.png)

**Comment by dondenata** [comment]
Tu GPU no es una GTX 1080 TI, segun T-REX tienes una GTX1050TI con 4095Mb de RAM.
Necesitas al menos 4.26GB de RAM (4296MB RAM), con lo que te faltan 194 Mb de RAM para poder minar ETH.
Que es lo que te esta indicando TREX
Tambien veo que has mencionado que tu Sistema cuenta con 8GB de RAM. 
Has de entender que una cosa es la RAM del Sistema (en tu caso 8GB) y otra es la RAM de la GPU (en tu caso 4Gb), para la minería de ETH se estan usando gáficas de 6Gb de RAM minimo, por lo que la tuya ya no sirve para esta moneda (otras habra que puedas minar).

Un saludo.

**Comment by Tehqy** [comment]
> Tu GPU no es una GTX 1080 TI, segun T-REX tienes una GTX1050TI con 4095Mb de RAM. Necesitas al menos 4.26GB de RAM (4296MB RAM), con lo que te faltan 194 Mb de RAM para poder minar ETH. Que es lo que te esta indicando TREX Tambien veo que has mencionado que tu Sistema cuenta con 8GB de RAM. Has de entender que una cosa es la RAM del Sistema (en tu caso 8GB) y otra es la RAM de la GPU (en tu caso 4Gb), para la minería de ETH se estan usando gáficas de 6Gb de RAM minimo, por lo que la tuya ya no sirve para esta moneda (otras habra que puedas minar).
> 
> Un saludo.
> 
> .........................................................................in english by Google Translate........................................................
> 
> Your GPU is not a GTX 1080 TI, according to T-REX you have a GTX1050TI with 4095Mb of RAM. You need at least 4.26GB of RAM (4296MB RAM), which means that you need 194 Mb of RAM to be able to mine ETH. What is TREX telling you? I also see that you mentioned that your System has 8GB of RAM. You have to understand that one thing is the System RAM (in your case 8GB) and another is the GPU RAM (in your case 4Gb), for ETH mining, graphics of at least 6Gb of RAM are being used, so that yours no longer works for this currency (there will be others that you can mine).
> 
> All the best.

Sorry, looks like I messed up. yes I have a gtX 1050 Ti. And yeah I know the difference between RAM and VRAM. anyway thx. I guess I have to get a new card lol.
