### ISSUE TITLE
LHR rate fluctuation - hiveos

### ISSUE THREAD

**Issue by Mpuf** [trexminer/T-Rex#824]
I am using 3080 ti cards on hiveos and it appears that my hash rates range from 84 - 92 mh/s without the cards locking or changing lhr mode.

Any suggestions?

Thanks!

**Comment by iartek** [comment]
I have observed similar fluctuations on my end.
3080 ti, 1300 clock, 2800 mem, pl 295 on HiveOS. 
hashrate 88-93 MH/s, with NBminer it was 87.5-89.5.
You can even notice on attached screenshot when I switched from nbminer to trex :)
![7CCB8BCA-0AE4-483A-BBA3-50FF7EE8960D](https://user-images.githubusercontent.com/6204396/141502013-cd485432-257e-42ab-84c8-135e63eb1fbb.jpeg)
![2C0FEE68-AE6D-4438-AFF4-68E310C2B1DB](https://user-images.githubusercontent.com/6204396/141502016-83bcf973-782e-40f2-97a0-1e85f36fc04b.png)

**Comment by trexminer** [comment]
`--hashrate-avr 180` will smooth out hashrate fluctuations (`"hashrate-avr": 180` for HiveOS)
180 is the number of seconds over which the hashrate values are calculated (60 seconds by default). Set even higher number to get pretty much a straight line.

**Comment by Mpuf** [comment]
> `--hashrate-avr 180` will smooth out hashrate fluctuations (`"hashrate-avr": 180` for HiveOS) 180 is the number of seconds over which the hashrate values are calculated (60 seconds by default). Set even higher number to get pretty much a straight line.

Thanks for the response. While this would indeed provide a more "straight" line, i dont believe it actually resolves the issue. In a similar rig in windows this setting is not necessary since with default settings the mh ratings fluctuate by only 1 mh.

This would suggest that on windows the same setup would have a higher mh/s rate since it is more stable even every 60 seconds.

**Comment by trexminer** [comment]
@Mpuf Thanks for letting me know. I just went investigating and found out that HiveOS sets `"hashrate-avr": 30` by default for T-Rex even though internally in the miner it defaults to 60. I'll contact their support and ask them to fix it on their end.

**Comment by Mpuf** [comment]
@trexminer thanks for the quick responses.

To provide some more info for people having the same issue/questions i also did some testing.

By setting "hashrate-avr": 60 in the flight sheet the fluctuation is very similar between hiveos and windows. It can go up to 2.5mh/s per card so if your rig is comprised of many cards you will notice some fluctuation.

I previously used NBminer so the entire rig fluctuation would be 2mh/s. Having said that it appears that on average i have gained 1.5 - 2.5mh/s per card with same consumptions so its worth it.

If we could somehow stabilize the values at their high end the improvement would be even greater and we could probably squeeze another 1 - 2% in overall performance.

Cheers!

**Comment by Teamroc5** [comment]
keep up the amazing work!!! getting better hash. good update!!! will always stay with trex!!! SINCE THE BEGINNING!!!

**Comment by trexminer** [comment]
Thanks.
HiveOS just pushed the fix along with 0.24.7
