### ISSUE TITLE
Dual Mining Ravencoin and ETH on Hiveos

### ISSUE THREAD

**Issue by Bruhter** [trexminer/T-Rex#826]
I have 2x3060ti, 3x3070ti, and 2x3070 on my mining rig running Hives. One of the 3070 wasn't detecting enough memory from day one. Others were running great for a month now. Just yesterday, all the dual mining cards stoped working all showed up with an error message saying there isn't enough free memory. It requires 3.09GB of memory, but it also shows that I have 3.09GB of memory available.  Right now, I had to go back to mining ETH only, as I tried to test all versions of T-Rex miners, but the problem still exists.

**Comment by trexminer** [comment]
Unfortunately, there isn't much we can do about it. DAGs keep growing for both ETH and RVN. 10GB+ cards are now the only ones that can dual mine ETH+RVN.

**Comment by Bruhter** [comment]
> Unfortunately, there isn't much we can do about it. DAGs keep growing for both ETH and RVN. 10GB+ cards are now the only ones that can dual mine ETH+RVN.

It now requires more than 10GB to mine on Hiveos too? But how are some of my friends with the same cards still dual mining?

**Comment by trexminer** [comment]
It still requires just a tad below 8GB, but depending on the GPU model and how much memory Xorg takes for itself, you may be lucky to mine for another week or so.
