### ISSUE TITLE
Something is wrong with automatic updates

### ISSUE THREAD

**Issue by griinis** [trexminer/T-Rex#827]
Program goes in endless cycle "backing v2.46".

**Comment by griinis** [comment]
Solution: delete folders and copy v2.47 manualy.

**Comment by trexminer** [comment]
Yes, sorry about that. We moved `README.md` file to `help` directory inside the miner archive where older versions of t-rex couldn't see it. The solution is to remove the updates folder and restart the miner, it should then update fine.

**Comment by trexminer** [comment]
UPD: auto-update is completely broken on Windows, we've disabled them for now. Sorry for the inconvenience.

**Comment by GreenGinkgo** [comment]
Just for completeness of knowledge for anyone searching, here's the error code that appeared on my end, in Windows...

`20211113 09:12:11 WATCHDOG: software update found
20211113 09:12:11 WATCHDOG: terminating T-Rex
20211113 09:12:12 WATCHDOG: backed up T-Rex v0.24.5 to I:\Crypto\t-rex\backup
20211113 09:12:12 WARN: WATCHDOG: update exception, could not unpack file into I:\Crypto\t-rex\updates\unpacked/help/API.md
20211113 09:12:12 WARN: WATCHDOG: T-Rex does not exist anymore, restarting...`

I have a feeling that the issue has to do with the incorrect forward slashes of "/help/API.md"

You have to download the latest version and just copy your configs/.bats into the new deployment manually

Thanks for your hard work! 👍

**Comment by trexminer** [comment]
Should be fixed now. If there are still any issues, please let me know.
