### ISSUE TITLE
LHR unstable 

### ISSUE THREAD

**Issue by kilass** [trexminer/T-Rex#829]
![hashrate drop](https://user-images.githubusercontent.com/6830498/141648115-ac9c1acd-ebf4-4fa7-9e99-66c91e97428a.png)
Since yesterday I observed an unstable behaviour on LHR unlock. The card (Asus tuf 3080 lhr) was properly working at 72MH/s.

During the night i observed a drastic lock dividing hashrate by 2, now mining at 30 MH/s roughly. I tried differetn settings with lhr-tune and lhr-autotune-mode, but keep getting those hashrates. 

I have the exact same card mining on HiveOS through T-rex miner on the same version and it is pretty stable. I really do not understand the behaviour on my Windows card as no settings were done before the drop. 

Any idea on how to get back my hashrate ? 

PS: BTW, thanks guys for your great job  !

**Comment by kilass** [comment]
Just a quick edit, that might help you guiding me through those troubles, I just found out that the target hashrate seems broken, as it is defined to 32 MH/s when it was 72 MH/s yesterday. Can i fix this to a fix value ?

**Comment by kilass** [comment]
EDIT 2: After 1h hour running without any changes, it came back to 72 Mh/s. I just would like to understand the behaviour, if it is normal and what would cause those behaviour.
![hashrate drop2](https://user-images.githubusercontent.com/6830498/141651403-3661a09a-633c-472f-a175-ae1b80140e04.png)

**Comment by kilass** [comment]
Finally found out that the problem was due to nvidia drivers. I have uninstalled Nvidia Drivers on windows, and let windows downloads it's own drivers. Hashrate is now finally stable.

**Comment by Allvasound** [comment]
Pleas tell me your Nvidia driver version before you clear your problem and after. Thank you
