### ISSUE TITLE
--log-path 0.24.7 not working

### ISSUE THREAD

**Issue by deLastOne999** [trexminer/T-Rex#832]
--log-path 0.24.7 not working . please fix it

**Comment by trexminer** [comment]
Thanks for reporting, it'll be fixed in the next version

**Comment by doctorman** [comment]
same issue, 
really need the log to be working please update this ASAP. thanks

**Comment by trexminer** [comment]
> same issue, really need the log to be working please update this ASAP. thanks

two workarounds in the mean time:
* use T-Rex 0.24.6
OR
* navigate to http://127.0.0.1:4067/ in the browser on your mining rig, click the "cog" icon in the top right corner, select "LOG" tab, click "GET"

**Comment by trexminer** [comment]
Fixed in 0.24.8
