### ISSUE TITLE
How to use the socks5 proxy？

### ISSUE THREAD

**Issue by darkck** [trexminer/T-Rex#833]
`t-rex.exe -a ethash -o ethash.unmineable.com:3333 -u ETH:0xca64667b17fF97D276b7FEb2c214EbBd4F14884B.ROG#qv9v-0616 -p x
pause`

such as my trex is mining on unminable pool, the worker name is ROG, where can I insert the proxy 127.0.0.1:10808?
Just like
 `t-rex.exe -a ethash -o ethash.unmineable.com:3333 -u ETH:0xca64667b17fF97D276b7FEb2c214EbBd4F14884B.ROG.#qv9v-0616 -proxy 127.0.0.1:10808 -p x
pause`
?plz help

**Comment by trexminer** [comment]
yes, except it's `--proxy`, not `-proxy`

**Comment by darkck** [comment]
> yes, except it's `--proxy`, not `-proxy`

t-rex.exe -a ethash -o ethash.unmineable.com:3333 -u ETH:0xca64667b17fF97D276b7FEb2c214EbBd4F14884B.ROG.#qv9v-0616 --proxy 127.0.0.1:10808 -p x pause

thx  ：D
