### ISSUE TITLE
dual on 8GB cards

### ISSUE THREAD

**Issue by basking-in-the-sun2000** [trexminer/T-Rex#838]
I hadn't seen the indication that you needed to mine on larger cards for dual mining before setting the config. However, it has been doing a decent job on a 3060 ti mining eth+rvn. Granted it isn't using 100% of the card capability, but it hasn't crashed. 

I have 2 lhr cards doing this a 3060 and the ti. The plain 3060 is doing 16-20/11-13 while the ti is doing 22-25/13-14 (have the intensity at 40). So I guess the rvn on the ti isn't reaching the speed it should, but not bad.

The ti doesn't have much free memory left (2-24 MB). I left it overnight and the gpu didn't restart.

My overclocks aren't too aggressive but didn't see yours first. The ti has 1400/2300/125 and the 3060 has 1400/1850/110

**Comment by trexminer** [comment]
Sorry, but what's the issue / question?

**Comment by basking-in-the-sun2000** [comment]
Didn't figure where to post, so I added it here. Thought it might be useful for others trying to dual mine, with the caveat that the second coin might not be as efficient.

Thanks for the great miner, and all your hard work :)
