### ISSUE TITLE
proxy server mine

### ISSUE THREAD

**Issue by bjznl** [trexminer/T-Rex#849]
If I mine with a proxy server, will T-REX's dev fee also connect via SOCKS5 proxy server?

**Comment by karlestira** [comment]
I want to ask this question too. I am using bminer and was told that my shares being monitored because of non-encrypted dev fee.

**Comment by trexminer** [comment]
> If I mine with a proxy server, will T-REX's dev fee also connect via SOCKS5 proxy server?

yes

**Comment by bjznl** [comment]
> > If I mine with a proxy server, will T-REX's dev fee also connect via SOCKS5 proxy server?
> 
> yes

Thank you~
