### ISSUE TITLE
TeamBlack Miner Fully Operational with latest Nvidia Drivers - 496.76

### ISSUE THREAD

**Issue by Globespy** [trexminer/T-Rex#856]
For those who mine part time (gaming focused PC's), there's some good news if you don't want to be stuck using months old drivers, or if the new games require updated drivers.
Since T-Rex dev doesn't seem interested in responding about this issue, thought I would post for anyone who wants to use the latest drivers and still have functioning mining when they mine, without the constant LHR locks that will reduce your hash rates to a fraction of what they should be on T-Rex.

Hopefully T-Rex will follow suit, and update to allow new Nvidia drivers to work without the current issues.

**Comment by trexminer** [comment]
Use `--lhr-tune 0` with T-Rex to force it work in a non-LHR mode

**Comment by Globespy** [comment]
Thank you.
I resolved this (for now anyway) by using driver 496.49 which does actually work just fine with the latest version of T-Rex.
So, it's a relatively new gaming driver, and has the same hash rates as 472.12.
Appreciate the follow up.

PS - TeamBlack Miner is trash, and the devs documentation is hopeless - but you probably knew that :)

**Comment by jankestorun** [comment]
@Globespy  Can you post your parameters you’re using?
