### ISSUE TITLE
Limit GPU usage

### ISSUE THREAD

**Issue by hoshmandctf** [trexminer/T-Rex#858]
How do I limit GPU usage while mining ETH with T-Rex miner? 

for example if I want to use 60% of the GPU while mining, is There a way to limit the usage?

**Comment by trexminer** [comment]
There's no direct control, but you can try low intensity values, for example `-i 14`

**Comment by BODYPRINT** [comment]
You can just set a lower power value on the gpu.
I use Afterburner to find where the power limit is for my settings.
Then I know the more  I reduce it from that more it will hit the Power limiter when I want to limit the GPU mining.

**Comment by hoshmandctf** [comment]
Ohh, OK

Thank you guys so much

**Comment by Soggydan** [comment]
there are a few ways you can limit the power usage of your mining rigs.  If you are happy with chaning BIOS settings have a read here, they cover reducing power for CPU and GPU mining

[](https://www.home-mining.com/how-too/reduce-electricity-bill-cost-while-cryptocurrency-mining)

**Comment by Faltskog** [comment]
> How do I limit GPU usage while mining ETH with T-Rex miner?
> 
> for example if I want to use 60% of the GPU while mining, is There a way to limit the usage?

Did you tried --pl?

**Comment by hoshmandctf** [comment]
> you tried --pl?

Yeah I tried power limit but I only works for a while and then It slowed down my PC again.

**Comment by hoshmandctf** [comment]
> there are a few ways you can limit the power usage of your mining rigs. If you are happy with chaning BIOS settings have a read here, they cover reducing power for CPU and GPU mining

Thanks but I want to use the remaining power for something else not just limit the entire usage

**Comment by BODYPRINT** [comment]
I guess the other option is to try set the LHR value to something like 60 even if it's not a LHR card.
That should limit the mining without gimping the card for other uses I think.

**Comment by hoshmandctf** [comment]
> I guess the other option is to try set the LHR value to something like 60 even if it's not a LHR card. That should limit the mining without gimping the card for other uses I think.

I will try that too thanks for the advice!
