### ISSUE TITLE
telnet

### ISSUE THREAD

**Issue by Miiichal** [trexminer/T-Rex#859]
hello there again
can we please reopen an issue for **-api-bind-telnet** ?

Cause i would like to **BEG AND PLEASE** for any chance to avoid this...
thanky you very very very much :)

**https://github.com/trexminer/T-Rex/issues/672**

**Comment by amiazma** [comment]
Hard coded but you can edit it simply. Search the older telnet issue for solution. They dont use that bad dll... You can repair it simply.

**Comment by amiazma** [comment]
OFF: Oh! I has an idea! The power limit settins didnt work for mi via NH! Maybe I'll hardcode them! :D

**Comment by amiazma** [comment]
https://github.com/trexminer/T-Rex/issues/672#issuecomment-948582640

**Comment by trexminer** [comment]
Please, let's not create duplicates

**Comment by trexminer** [comment]
Duplicate of https://github.com/trexminer/T-Rex/issues/672
