### ISSUE TITLE
Devide doesn't have enough free memory

### ISSUE THREAD

**Issue by DaniellBarr** [trexminer/T-Rex#861]
Hello,

so after 2 weeks of farming ETH + RVN on my 3 x 3060ti LHR, my miner suddenly stopped mining and won't start anymore.

i keep getting errors like :

> 20211120 10:10:12 TREX: Can't find nonce with device [ID=0, GPU #0], Device does not have enough free memory to hold the DAG for epoch 270. Required: 3.11 GB, free: 3.10 GB.

Here the error is on GPU #0, but it changes between all of them

I tried upgrading swap file to 64 gbs and also changing overclock but still nothing.

I also run on minerstatOS which is Linux based and shouldn't have a problem with VRAM limits ( and again, been mining non stop for 2 weeks ) .

Any ideas?

**Comment by waltermelow** [comment]
Same problem

**Comment by trexminer** [comment]
8GB cards can no longer mine ETH+RVN due to DAG size growth

**Comment by DaniellBarr** [comment]
Thank you for the help !

**Comment by sihanat** [comment]
How was the problem resolve? I have the same problem
