### ISSUE TITLE
Device not enough memory - Can't find Nounce

### ISSUE THREAD

**Issue by JayTSY** [trexminer/T-Rex#862]
![NiceHash Mining Issue](https://user-images.githubusercontent.com/94759456/142737337-3f527e21-06dd-4566-8ccf-5505b1923962.png)

For some reason I can't seem to start the mining. Any ideas why or how I can fix it?
I've tried to go to settings > performance > advanced settings and changing the VM size but still doesn't work.
My NVIDIA is also the latest version already.

**Comment by waltermelow** [comment]
Same problem

**Comment by trexminer** [comment]
Duplicate of https://github.com/trexminer/T-Rex/issues/861
