### ISSUE TITLE
trex cannot connect to any pool. 

### ISSUE THREAD

**Issue by orangpelupa** [trexminer/T-Rex#863]
trex version 0.24.7

Here's the log:

20211121 14:51:15 WARN: failed to ethproxy-subscribe on asia2.ethermine.org:4444: can't send subscribe request

20211121 14:51:15 --------------------------------------------------------
20211121 14:51:15 ERROR: No connection with asia2.ethermine.org:4444, retry after 10 seconds

i tried nbminer and it can connect to the pool. 
i've also tried disabling windows firewall, and trex still cant connect. 

EDIT:
the workaround i found to be working is by rebooting the computer and praying. as long as it connected once, it will keeps working.

**Comment by trexminer** [comment]
Yes, windows firewall blocking connections is the most likely cause.
For reference: https://github.com/trexminer/T-Rex/wiki/FAQ#im-getting-a-no-connection-error-but-my-network-connection-is-fine

**Comment by orangpelupa** [comment]
unfortunately trex was already added to windows firewall, and i also has tried with windows firewall disabled and it still cant connect. the only workaround that work is by rebooting windows and pray
