### ISSUE TITLE
Keeps mining ergo when card disabled due to high temperature

### ISSUE THREAD

**Issue by puthre** [trexminer/T-Rex#868]
When dual mining, if you set temperature_limit, card shows as disabled but it still uses it for mining:
----------------20211123 00:42:58 -----------------
Mining at fi.ergo.herominers.com:1180, diff: 6.15 G
WARN: [DISABLED] GPU #0: RTX 3080 Ti - 76.86 MH/s, [LHR 29.5<>] [T:77C, P:319W, F:70%, E:333kH/W], 3/3 R:0%
Shares/min: 0.702 (Avg. 0.861)
Uptime: 3 mins 30 secs | Algo: autolykos2 | T-Rex v0.24.7
WD: 3 mins 31 secs, shares: 3/3

**Comment by trexminer** [comment]
Fixed in 0.24.8
