### ISSUE TITLE
"temperature-color-mem": "80,100"

### ISSUE THREAD

**Issue by gmenarvino** [trexminer/T-Rex#870]
Hi I added this into linux and it does not seems to be working, what I should be able to see in the CLI view?

Look the output:
Mining at us-eth.2miners.com:2020, diff: 8.73 G
GPU #0: RTX 3060 Ti - 21.79 MH/s, [LHR 37.5<>] [T:59C, P:139W, F:39%, E:157kH/W]
GPU #1: RTX 3060 Ti - 21.83 MH/s, [LHR 37.5<>] [T:59C, P:139W, F:83%, E:157kH/W], 1/1 R:0% I:0%
GPU #2: RTX 3060 Ti - 22.07 MH/s, [LHR 37.5<>] [T:59C, P:139W, F:85%, E:160kH/W], 1/1 R:0% I:0%
GPU #3: RTX 3060 Ti - 22.02 MH/s, [LHR 37.5<>] [T:62C, P:139W, F:96%, E:160kH/W]
GPU #4: RTX 3060 Ti - 18.52 MH/s, [LHR 37.0<>] [T:61C, P:138W, F:96%, E:134kH/W], 1/1 R:0% I:0%
GPU #5: RTX 3060 Ti - 21.65 MH/s, [LHR 37.5<>] [T:61C, P:138W, F:88%, E:157kH/W]
GPU #6: RTX 3060 Ti - 23.41 MH/s, [LHR 37.5<>] [T:59C, P:139W, F:96%, E:170kH/W]
GPU #7: RTX 3060 Ti - 21.63 MH/s, [LHR 37.5<>] [T:64C, P:139W, F:96%, E:156kH/W]
Hashrate: 172.92 MH/s, Shares/min: 5.075 (Avg. 0.408), Avg.P: 1107W, Avg.E: 156kH/W
Max diff share was found by GPU #1, diff: 22.59 G
Uptime: 9 mins | Algo: ethash | T-Rex v0.24.7

--------------20211123 10:06:45 ---------------
Mining at us-erg.2miners.com:8888, diff: 8.73 G
GPU #0: RTX 3060 Ti - 75.96 MH/s, [LHR 37.5<>] [T:59C, P:139W, F:39%, E:546kH/W], 7/7 R:0% I:0%
GPU #1: RTX 3060 Ti - 75.82 MH/s, [LHR 37.5<>] [T:59C, P:139W, F:83%, E:545kH/W], 3/3 R:0% I:0%
GPU #2: RTX 3060 Ti - 75.52 MH/s, [LHR 37.5<>] [T:59C, P:139W, F:85%, E:547kH/W], 3/3 R:0% I:0%
GPU #3: RTX 3060 Ti - 75.10 MH/s, [LHR 37.5<>] [T:62C, P:139W, F:96%, E:544kH/W], 2/2 R:0% I:0%
GPU #4: RTX 3060 Ti - 76.55 MH/s, [LHR 37.0<>] [T:61C, P:138W, F:96%, E:555kH/W], 6/6 R:0% I:0%
GPU #5: RTX 3060 Ti - 73.37 MH/s, [LHR 37.5<>] [T:61C, P:138W, F:88%, E:532kH/W], 6/6 R:0% I:0%
GPU #6: RTX 3060 Ti - 71.68 MH/s, [LHR 37.5<>] [T:59C, P:139W, F:96%, E:519kH/W], 4/4 R:0% I:0%
GPU #7: RTX 3060 Ti - 75.23 MH/s, [LHR 37.5<>] [T:64C, P:139W, F:96%, E:541kH/W], 5/5 R:0% I:0%
Hashrate: 599.22 MH/s, Shares/min: 4.908 (Avg. 4.091), Avg.P: 1107W, Avg.E: 541kH/W
Max diff share was found by GPU #6, diff: 1.25 T
Uptime: 9 mins | Algo: autolykos2 | T-Rex v0.24.7

**Comment by trexminer** [comment]
Displaying memory temperatures is not supported on Linux

**Comment by gmenarvino** [comment]
ohh... it will be nice to be supported!

**Comment by trexminer** [comment]
I agree it would be great, however: https://github.com/trexminer/T-Rex/issues/433#issuecomment-821990136
