### ISSUE TITLE
can't parse json

### ISSUE THREAD

**Issue by simplexity-kaiou** [trexminer/T-Rex#873]
![7b2c30d2e113e70d7f4304925b774ad](https://user-images.githubusercontent.com/50051786/143171293-2c0c2062-7e79-4b89-a400-deb686232439.png)

I use this command, t-rex -a ethash -o stratum+tcp://us2.ethermine.org:14444 -u **** -p x，It used to be worked, but now it suddenly doesn't work，I don't know why.

**Comment by trexminer** [comment]
Probably it's the firewall blocking the connection, or some other networking issue, not a T-Rex bug.

**Comment by jamesonypy** [comment]
> ![7b2c30d2e113e70d7f4304925b774ad](https://user-images.githubusercontent.com/50051786/143171293-2c0c2062-7e79-4b89-a400-deb686232439.png)
> 
> I use this command, t-rex -a ethash -o stratum+tcp://us2.ethermine.org:14444 -u **** -p x，It used to be worked, but now it suddenly doesn't work，I don't know why.

have u solved?i hava the same problem

**Comment by trexminer** [comment]
@jamesonypy if you're using SSL, try running with `--no-sni --dns-https-server 1.1.1.1`
