### ISSUE TITLE
--no-strict-ssl is ignored

### ISSUE THREAD

**Issue by renaatski** [trexminer/T-Rex#874]
Hello,

Having issues connecting to e.g. nanopool for ergo mining, with 0.24.7     (also tested with 0.24.6)

...
20211124 10:26:09 URL : stratum+ssl://ergo-eu1.nanopool.org:11111
20211124 10:26:09 USER: wallet.worker/email@mail.com
20211124 10:26:09 PASS: x
20211124 10:26:09
20211124 10:26:09 Starting on: ergo-eu1.nanopool.org:11111
20211124 10:26:09 ApiServer: HTTP server started on 127.0.0.1:4067
20211124 10:26:09 ---------------------------------------------------
20211124 10:26:09 For control navigate to: http://127.0.0.1:4067/trex
20211124 10:26:09 ---------------------------------------------------
20211124 10:26:10 GPU #0: intensity 23.9
20211124 10:26:10 WARN: SSL certificate verification failed. To skip verification run with --no-strict-ssl parameter.
20211124 10:26:10 ERROR: No connection with ergo-eu1.nanopool.org:11111, retry after 10 seconds

Problem is, I AM using that parameter... :-/   It just seems to be ignored.

I tried from hiveOS, which uses -c config.json method. which defintely contains a line "no-strict-ssl": true

But also running it manually, from the command-line using e.g.:

root@Rens_rig:/hive/miners/t-rex/0.24.6# ./t-rex -a autolykos2 -o stratum+ssl://ergo-eu1.nanopool.org:11111 -u wallet.worker/email@mail.com -p x --no-strict-ssl 

The results are identical. t-rex seems to be ignoring this parameter? I mined ergo with hive a few months ago and that worked back then...

**Comment by trexminer** [comment]
Hi. The error message is confusing, sorry about that. The real cause is you're using a non-SSL port: the SSL one is 11433 (see https://ergo.nanopool.org)

**Comment by renaatski** [comment]
I stand corrected. I don't know how I missed that :-o    Sorry for having wasted your time.  And keep up the good work!  Love t-rex! ;)
