### ISSUE TITLE
HiveOS - Miner logs keep resetting after every miner restart

### ISSUE THREAD

**Issue by Mpuf** [trexminer/T-Rex#875]
Hey,

i have noticed that my miner restarts at random intervals after adding a new card. I can assume what the issue is ( probably the OC settings ) but my main concern is that when i want to check the miner logs in HiveOS it appears that after every restart of the miner the logs start fresh and i can only view the current session.

There are no new files created so i can't check the old ones so i cannot see what the message was when the miner restarted. Logs are enabled for storage on the HDD from HiveOS but this does not appear to resolve the issue.

I am not sure if this is something you can fix on your end or from HiveOS , so i thought i should let you know.

Thanks.

**Comment by Mpuf** [comment]
Apparently this is the same process as HiveOS describes, but at the same time not what i am getting. I have 1 t-rex.log file and then i have t-rex.0.log.gz up to t-rex.9.log.gz for a total of 10 files (11 including t-rex.log)

Apparently it keeps overwriting over the t-rex.x.log.gz files every time it restarts which evidently keeps a record of 10 miner restarts. It does not offer any other indication such as timestamp or date etc. You have to actually view the files to know which date and time it involves. In addition, since i am no expert in linux, i could use the tail command on the log files to see just the last bit so i only see what interests me - the reason for restart, while now i have to view the .log.gz file and scroll all the way to the end to see what i need.

In any case although it does not appear to behave as intended i did manage to see which card is getting the error and funny story, its not the new one. 

Thanks for the response though :)

**Comment by trexminer** [comment]
No worries. Glad you've sorted it out.
I'm going to close the issue as the log archiving behaviour is controlled by HiveOS in your case.
