### ISSUE TITLE
SOCKS5 proxy not working properly

### ISSUE THREAD

**Issue by plane501** [trexminer/T-Rex#879]
hi,
t-rex can't connect to the pool via the proxy server while Gminer and NBminer working fine. (using the same proxy server which is my router's LAN ip 192.168.2.1:1080 and the same pool.)
t-rex version : 0.24.7

**Comment by trexminer** [comment]
Hi. Could you run the miner with `--protocol-dump` parameter and post the log file? Thanks.

**Comment by ReHekat** [comment]
I have this same issue. Here is the log:

20211126 10:36:54.130[36558.774] [~AsioWorker]
20211126 10:36:54.131[36558.775] [~AsioWorker] done
20211126 10:36:54.131[36558.775] stratum_disconnect session=
20211126 10:36:54.132[36558.776] ERROR: No connection with stratum.ravenminer.com:3838, retry after 10 seconds
20211126 10:37:04.137[36568.781] Connecting to: stratum.ravenminer.com:3838, ip: 108.160.167.158 via proxy: 127.0.0.1:1080
20211126 10:37:04.138[36568.782] Using protocol: stratum3.
20211126 10:37:04.139[36568.783] -OUT-> {"id":1,"method":"mining.subscribe","params":["t-rex/0.24.7"]}
20211126 10:37:14.143[36578.787] Wait on data is timed out, 10 seconds have passed, 0 bytes in socket remained
20211126 10:37:14.144[36578.788] WARN: Error during wait on data, 由于线程退出或应用程序请求，已中止 I/O 操作。
20211126 10:37:14.145[36578.789] WARN: failed to stratum2-subscribe on stratum.ravenminer.com:3838: can't parse json: 
* Line 1, Column 1
  Syntax error: value, object or array expected.

**Comment by tangobravo5656** [comment]
I got the same issue,my socks5 proxy works fine with gminer

**Comment by Nillouise** [comment]
20211127 11:24:42.358[63925.279] WARN: Can't connect to stratum server, resolve: 不知道这样的主机。
20211127 11:24:42.360[63925.281] stratum_disconnect session=
20211127 11:24:42.361[63925.282] ERROR: No connection with asia1.ethermine.org:5555, retry after 10 seconds
20211127 11:24:52.383[63935.304] WARN: Can't connect to stratum server, resolve: 不知道这样的主机。
20211127 11:24:52.384[63935.305] stratum_disconnect session=
20211127 11:24:52.384[63935.305] ERROR: No connection with asia1.ethermine.org:5555, retry after 10 seconds
20211127 11:25:02.415[63945.336] WARN: Can't connect to stratum server, resolve: 不知道这样的主机。
20211127 11:25:02.416[63945.337] stratum_disconnect session=
20211127 11:25:02.418[63945.339] ERROR: No connection with asia1.ethermine.org:5555, retry after 10 seconds


I got the same issue, I think the reason maybe do not proxy the DNS request.

**Comment by Nillouise** [comment]
20211127 11:24:42.358[63925.279] WARN: Can't connect to stratum server, resolve: 不知道这样的主机。
20211127 11:24:42.360[63925.281] stratum_disconnect session=
20211127 11:24:42.361[63925.282] ERROR: No connection with asia1.ethermine.org:5555, retry after 10 seconds
20211127 11:24:52.383[63935.304] WARN: Can't connect to stratum server, resolve: 不知道这样的主机。
20211127 11:24:52.384[63935.305] stratum_disconnect session=
20211127 11:24:52.384[63935.305] ERROR: No connection with asia1.ethermine.org:5555, retry after 10 seconds
20211127 11:25:02.415[63945.336] WARN: Can't connect to stratum server, resolve: 不知道这样的主机。
20211127 11:25:02.416[63945.337] stratum_disconnect session=
20211127 11:25:02.418[63945.339] ERROR: No connection with asia1.ethermine.org:5555, retry after 10 seconds


I got the same issue, I think the reason maybe do not proxy the DNS request.

**Comment by opij22** [comment]
me too,proxy5 can not works with T-Rex,but ok with NBminer and gminer
anyone can help me 
weixin:xccnypf
can afford some money

**Comment by trexminer** [comment]
See https://github.com/trexminer/T-Rex/issues/882 for explanation

**Comment by opij22** [comment]
I’m stupid, don’t understand, is it the next version update?

**Comment by trexminer** [comment]
Yes. In the meantime you can replace the pool's domain name (e.g. eu1.ethermine.org) with its IP address, it should work.

**Comment by trexminer** [comment]
Fixed in 0.24.8
