### ISSUE TITLE
v0.18.6: KawPoW @ MinigPoolHub not working

### ISSUE THREAD

**Issue by UselessGuru** [trexminer/T-Rex#88]
Command line used:
t-rex.exe --algo kawpow --url **stratum2**+tcp://europe.kawpow-hub.miningpoolhub.com:20611 --user ******************.\*\*\*\*\*\*\* --pass x --no-watchdog --gpu-report-interval 1 --api-bind-http 127.0.0.1:4004 --api-bind-telnet 0 --quiet --retry-pause 1 --timeout 50000 --cpu-priority 4 --devices 0

20201107 17:32:55 T-Rex NVIDIA GPU miner v0.18.6  -  [CUDA v11.10]
20201107 17:32:55 r.f6e0818348a3
20201107 17:32:55
20201107 17:32:55 NVIDIA Driver v457.09
20201107 17:32:55 CUDA devices available: 2
20201107 17:32:55
20201107 17:32:55 WARN: DevFee 1% (kawpow)
20201107 17:32:55
20201107 17:32:55 URL : stratum2+tcp://europe.kawpow-hub.miningpoolhub.com:20611
20201107 17:32:55 USER: ******************.\*\*\*\*\*\*\*
20201107 17:32:55 PASS: x
20201107 17:32:55
20201107 17:32:55 WARN: Built-in watchdog has been disabled!
20201107 17:32:55 Starting on: europe.kawpow-hub.miningpoolhub.com:20611
20201107 17:32:55 ApiServer: HTTP server started on 127.0.0.1:4004
20201107 17:32:55 -----------------------------------------------------
20201107 17:32:55 For control navigate to: http://172.23.48.1:4004/trex
20201107 17:32:55 -----------------------------------------------------
20201107 17:32:55 Using protocol: **stratum3**.
20201107 17:32:55 Extranonce is set to: 0041
20201107 17:32:55 Authorizing...
20201107 17:32:55 New target is set to: 0x00000009f6000000000000000000000000000000000000000000000000000000
20201107 17:32:55 WARN: failed to **stratum2**-authorize on europe.kawpow-hub.miningpoolhub.com:20611: pool rejected connection, result {
        "error" : null,
        "id" : 3,
        "result" : false
}

I also tried with 
 --url **ethproxy**+tcp://europe.kawpow-hub.miningpoolhub.com:20611
 --url **nicehash**+tcp://europe.kawpow-hub.miningpoolhub.com:20611
 --url europe.kawpow-hub.miningpoolhub.com:20611

All same error

**Comment by trexminer** [comment]
Update to 0.18.7 please.

**Comment by UselessGuru** [comment]
Same Issue with 0.18.7

**Comment by UselessGuru** [comment]
Same issue with 0.18.7

Command line used:

t-rex.exe --algo kawpow --url stratum2+tcp://europe.kawpow-hub.miningpoolhub.com:20611 --user *************** --worker ********* --pass x --no-watchdog --gpu-report-interval 1 --api-bind-http 127.0.0.1:4004 --api-bind-telnet 0 --quiet --retry-pause 1 --timeout 50000 --cpu-priority 4 --devices 0

**Comment by trexminer** [comment]
I think you have a proble with user name. Try this:
t-rex --algo kawpow --url stratum2+tcp://europe.kawpow-hub.miningpoolhub.com:20611 --user somaton.ryzen --worker wrk --pass x --no-watchdog --gpu-report-interval 1 --api-bind-http 127.0.0.1:4004 --api-bind-telnet 0 --quiet --retry-pause 1 --timeout 50000 --cpu-priority 4 --devices 0

Works for me.

![mph](https://user-images.githubusercontent.com/44735836/98506879-7d115680-226d-11eb-9b2b-f4597976c3b4.jpg)

**Comment by UselessGuru** [comment]
> I think you have a problem with user name.

True. Workername still must have two parts separated by '.'

`t-rex.exe --algo kawpow --url stratum2+tcp://europe.kawpow-hub.miningpoolhub.com:20611 --user USER.WORKER --worker WORKER --pass x --no-watchdog --gpu-report-interval 1 --api-bind-http 127.0.0.1:4004 --api-bind-telnet 0 --quiet --retry-pause 1 --timeout 50000 --cpu-priority 4 --devices 0`

is working fine.
