### ISSUE TITLE
suddenly low hashrate with rtx 3090

### ISSUE THREAD

**Issue by matuopm** [trexminer/T-Rex#880]
Hey I'm a more or less casual miner and have been making a break from mining.

I used t-rex miner a half year ago and was mining around 110-120 MH/s as average. Now I recently updated to Windows 11 and also updated t-rex and NVIDIA drivers etc. and I'm only getting about 60 -70 MH/s right now but stilly my GPU draws about 300 W of power even with the low hashrate.

Here some screenshots that might help:
![image](https://user-images.githubusercontent.com/95039636/143465244-c845bc2a-d8bf-4d3e-883f-e187946e1ccf.png)

Here you can see my temps and usage for from my watercooling monitoring software aquasuite.
![image](https://user-images.githubusercontent.com/95039636/143465386-e26e6754-d13a-4577-8d18-1c457878e249.png)

Even my temperatures are much lower than usually. Normaly I have around 80-85 VRAM temperature by nearly 99% VRAM usage. For some reason my GPU Core usage is also at 100% which was not the case before when I remember right.

I also use the same settings in afterburner as before
Core -300
Memory +1500
Power Limit 78%

I also tested some phoenix miner but have the same problem.

Anyone got a clue where I could search for a solution or what I could try doing ?

EDIT
here is my start.bat
t-rex.exe -a ethash -o stratum+tcp://eu1.ethermine.org:4444 -u 0x2A227eB679D87388439895D3058587XXXXXXXXXX -p x -w matuopm --api-bind-http 0.0.0.0:4067 --api-read-only
pause

**Comment by trexminer** [comment]
Try using 472.12 drivers, we've received a few reports of hashrate degradation on the latest ones.

**Comment by matuopm** [comment]
Unfortunately that did not changen anything.
![image](https://user-images.githubusercontent.com/95039636/143481012-b961b95b-0924-4a2f-a257-8c8b23e164fe.png)

Are there any settings in the driver I could change ? Or any parameters I could use when starting the miner ?

**Comment by matuopm** [comment]
Omg I'm so sorry it was actually my own fault. the aquasuite software slows the miner down. 
I just closed the programm and now its running normally again.
![image](https://user-images.githubusercontent.com/95039636/143483894-fb73333e-aefa-448a-ad24-670d519b0d7a.png)


Sorry my bad.

**Comment by trexminer** [comment]
No worries. Glad you figured it out.

**Comment by matuopm** [comment]
Yea me too. Thanks for the fast support.

**Comment by bolino2k** [comment]
Hello ,

same problem : i want to connect my screen on IGP of my 5700G, and dedicate 3090 for t-rex ( can gain 4 MH/s  i think, i gain this with screen off ), but i can see memory clock of 3090 go to 667Mhz and sometimes 1337Mhz, so my hashrate is 70Mh/s ( 121MH/s when my screen is connected to 3090 ...i try force gpu0 on trex, but same results ...I force maximum power in Nvidia control panel, but it's like 3090 go in idle  when my screen is connected to IGP
