### ISSUE TITLE
Error for RTX 2070 Super - NVAPI NVIDIA Device not found code -6 

### ISSUE THREAD

**Issue by kmacaroni** [trexminer/T-Rex#881]
Need help resolving this error for my RTX 2070 Super when used for mining by itself or with 2 LHR RTX 3060 cards ( 1 is version 1 and the other is version 2). After this the card crashes and becomes unrecognized by Windows Device Manager. This sometimes crashes the PC as well.

These are the batch files I run.

(1) running by itself:
"<mylocal_PCdirectory>\miners\t-rex-0.24.7-win\t-rex.exe" --api-bind-http 0.0.0.0:4067 -d 1 -a ethash -o stratum+tcp://<myserver>:<myport> -u <mywallet> -p <mypassword> -w <myrigname> --fan 80 --pl 58 --lock-cclock 7000 -- mclock 0 --exit-on-high-power 200 
pause

(2) running with 2 LHR cards:
"<mylocal_PCdirectory>\miners\t-rex-0.24.7-win\t-rex.exe" --api-bind-http 0.0.0.0:4067 -d 0,1,2 --lhr-tune 75.7,100,75.7 --lhr-autotune-step-size 0.1 --lhr-autotune-interval 1 -a ethash -o stratum+tcp://<myserver>:<myport> -u <mywallet> -p <mypassword> -w <myrigname> --fan 70,80,70 --pl 68,58,68 --lock-cclock 8750,7000,8750 -- mclock 0,0,0 --exit-on-high-power 700 
pause

When this error occurs, the card crashes and becomes unrecognized by Windows Device Manager.

Prior to this batch file no.(2) runs fine. 

Then the card RTX 2070 super crashed. and I've been having these problems.

I tried to re-apply thermal paste on the gpu thinking it might be a temperature thing but the hotspot temperature does not appear to exceed 80degC, as far as I am aware.

**Comment by trexminer** [comment]
Check this out: https://github.com/trexminer/T-Rex/wiki/FAQ#im-getting-a-code--6

**Comment by kmacaroni** [comment]
thank you. this seemed to be the root cause for this problem.

**Comment by ch3nyy** [comment]
Hello, A 3060Ti graphics card have the same trouble as you. How did you solve it in the end?
Now, this card still doesn't work after replacing the motherboard, which is so annoying.

**Comment by kmacaroni** [comment]
> Hello, A 3060Ti graphics card have the same trouble as you. How did you solve it in the end? Now, this card still doesn't work after replacing the motherboard, which is so annoying.

Based on my last experience, I found that the pcie cable that delivered power to the graphics card has failed (found one of them burnt at a single point along the cable and disconnected). 

I replaced the failed PCIE cable with a new one my card was again recognized by Windows when I my rig.

**Comment by ch3nyy** [comment]
> > Hello, A 3060Ti graphics card have the same trouble as you. How did you solve it in the end? Now, this card still doesn't work after replacing the motherboard, which is so annoying.
> 
> Based on my last experience, I found that the pcie cable that delivered power to the graphics card has failed (found one of them burnt at a single point along the cable and disconnected).
> 
> I replaced the failed PCIE cable with a new one my card was again recognized by Windows when I my rig.

Thanks, it is really helpful!

**Comment by kmacaroni** [comment]
> 

You're welcome.
