### ISSUE TITLE
need socks5h support

### ISSUE THREAD

**Issue by zyfbis** [trexminer/T-Rex#882]
I've noticed that t-rex resolves dns before my proxy server (connection using ip address in my proxy server log), but it was affected by **dns pollution**; And gminer connection keeps the domain name in my proxy server log, so I wonder if it was the difference between the socks5 implementation?
Maybe the difference between socks5 and socks5h?

**Comment by tangobravo5656** [comment]
I can't using socks5 proxy either but it works fine with gminer,any idea why?

**Comment by trexminer** [comment]
Yes, the miner resolves DNS before connecting to the proxy, we'll fix it in the next version. Thanks for reporting.

**Comment by trexminer** [comment]
Fixed in 0.24.8
