### ISSUE TITLE
No connection, retry after 10 seconds

### ISSUE THREAD

**Issue by Farewellly** [trexminer/T-Rex#889]
yesterday ,i use trex and it report no connection.
here is the log
![微信截图_20211127212833](https://user-images.githubusercontent.com/20672335/143683401-8fac9c22-d7c5-4c68-80ac-31ab1187b605.png)
:

**Comment by Ethirix** [comment]
I got that too, the other day, and now it doesn't say No Connection, but rather... nothing and seems like it works, other than no shares.

**Comment by dmxabc123** [comment]
So am i，how to fix it?

**Comment by demosthenesk** [comment]
so am i, at cruxpool [no connection](https://github.com/trexminer/T-Rex/issues/884#issuecomment-984959199)

**Comment by trexminer** [comment]
@Farewellly Assuming you're in China, they now poison DNS requests, so `asia1.ethermine.org` doesn't resolve to the correct IP. Solutions: proxy, VPN, using connection to IP address directly.

**Comment by demosthenesk** [comment]
> so am i, at cruxpool [no connection](https://github.com/trexminer/T-Rex/issues/884#issuecomment-984959199)

in my case i turned off antivirus....no change...still no connection
i change alternative ports at cruxpool....no change....still no connection

i used gminer and pheonixminer the both work fine...only t-rex has the issue.

**Comment by trexminer** [comment]
@demosthenesk we've had a lot of reports of "no connection" error and it was never due to a bug in T-Rex. Either firewall, antivirus, some other networking issue, pool issue etc. Since other mining software is working, you can rule out pool and general networking issue. If you're using SSL, it could be an invalid certificate too.

**Comment by demosthenesk** [comment]
> @demosthenesk we've had a lot of reports of "no connection" error and it was never due to a bug in T-Rex. Either firewall, antivirus, some other networking issue, pool issue etc. Since other mining software is working, you can rule out pool and general networking issue. If you're using SSL, it could be an invalid certificate too.

all other miners work fine...gminer, pheonix...only t-rex give no connection

**Comment by DIGTURTLE-DGT** [comment]
Hope my answer helps you.add command --no-strict-ssl

**Comment by blyspyder** [comment]
> 

How can i get ip address

**Comment by blyspyder** [comment]
> 

How can I get the ip address and set up the VPN
