### ISSUE TITLE
can't pair device with KEY 000000

### ISSUE THREAD

**Issue by fpasalioglu** [trexminer/T-Rex#89]
20201111 09:31:49 NVML table
20201111 09:31:49 [GPU #0, KEY 000004] Tesla P100-PCIE-16GB
20201111 09:31:49 ERROR: Can't start miner, can't pair device with KEY 000000 [GPU #0, dom:0, bus:0, slot:0], map::at
20201111 09:31:49 WARN: failed to subscribe, stratum_subscribe can't send line

20201111 09:31:49 ERROR: No connection, retry after 10 seconds
20201111 09:31:50 T-Rex finished.

I try to mine qureno.
my command:
./t-rex -a x33 -o url -u worker

benchmark mode:

20201111 09:47:47 WARN: BENCHMARK MODE (x33)
20201111 09:47:47 
20201111 09:47:47 NVML table
20201111 09:47:47 [GPU #0, KEY 000004] Tesla P100-PCIE-16GB
20201111 09:47:47 ERROR: Can't start miner, can't pair device with KEY 000000 [GPU #0, dom:0, bus:0, slot:0], map::at
20201111 09:47:48 T-Rex finished.

**Comment by trexminer** [comment]
Qureno no longer uses `x33`. On the error above though, please provide us with the whole log including the header, where the miner prints out its own version, CUDA toolkit version was used to build it and video driver version. Thanks.

**Comment by fpasalioglu** [comment]
they cancelled the algorithm change. I am trying to mine on Google Colab.
if use cuda 11, I get this error:

20201111 11:05:55 T-Rex NVIDIA GPU miner v0.18.8  -  [CUDA v11.10]
20201111 11:05:55 r.bab80bbb5f1c
20201111 11:05:55 
20201111 11:05:55 NVIDIA Driver v418.67
20201111 11:05:55 CUDA devices available: 1
20201111 11:05:55 
20201111 11:05:55 WARN: BENCHMARK MODE (x33)
20201111 11:05:55 
20201111 11:05:55 NVML table
20201111 11:05:55 [GPU #0, KEY 000004] Tesla P100-PCIE-16GB
20201111 11:05:55 ERROR: Can't start miner, can't pair device with KEY 000000 [GPU #0, dom:0, bus:0, slot:0], map::at
20201111 11:05:56 T-Rex finished.

if I use cuda 10, colab shows nothing.

**Comment by trexminer** [comment]
Ok, CUDA 11.1 build requires a newer video driver. So you can either update the driver or download and use CUDA 10.0 version of t-rex.

**Comment by trexminer** [comment]
Sorry, just noticed what you said about cuda 10 and colab. Well, try 9.1 or 9.2 maybe?

**Comment by fpasalioglu** [comment]
Colab using Cuda 10.1.
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243
 
I only get error on your Cuda 11 version. Other versions don't give a message.

**Comment by trexminer** [comment]
Yes, CUDA 11.1 build won't work because your video drivers are too old. Updating them to 455+ should fix the problem.

**Comment by fpasalioglu** [comment]
updated Cuda 11.1.

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Mon_Oct_12_20:09:46_PDT_2020
Cuda compilation tools, release 11.1, V11.1.105
Build cuda_11.1.TC455_06.29190527_0

tested your Cuda 11.1 version. Still same error

20201111 14:55:48 T-Rex NVIDIA GPU miner v0.18.8  -  [CUDA v11.10]
20201111 14:55:48 r.bab80bbb5f1c
20201111 14:55:48 
20201111 14:55:48 NVIDIA Driver v418.67
20201111 14:55:48 CUDA devices available: 1
20201111 14:55:48 
20201111 14:55:48 WARN: BENCHMARK MODE (x33)
20201111 14:55:48 
20201111 14:55:48 NVML table
20201111 14:55:48 [GPU #0, KEY 000004] Tesla T4
20201111 14:55:48 ERROR: Can't start miner, can't pair device with KEY 000000 [GPU #0, dom:0, bus:0, slot:0], map::at
20201111 14:55:49 T-Rex finished.

**Comment by trexminer** [comment]
> NVIDIA Driver v418.67

like I said, you need to update the video drivers to v455+

**Comment by Sn4kY** [comment]
Hi.
Same with drivers v455.45 

root@host:~/t-rex-0.18.9-linux-cuda11.1# ./ETH-ethermine.sh
20201119 10:53:11 T-Rex NVIDIA GPU miner v0.18.9  -  [CUDA v11.10]
20201119 10:53:11 r.4329cb1ce1ea
20201119 10:53:11
20201119 10:53:11 NVIDIA Driver v455.45.01
20201119 10:53:11 CUDA devices available: 1
20201119 10:53:11
20201119 10:53:11 WARN: DevFee 1% (ethash)
20201119 10:53:11
20201119 10:53:11 URL : stratum+tcp://eu1.ethermine.org:4444
20201119 10:53:11 USER: 0x
20201119 10:53:11 PASS: x
20201119 10:53:11 WRK : rig0
20201119 10:53:11
20201119 10:53:11 Starting on: eu1.ethermine.org:4444
20201119 10:53:11 NVML table
20201119 10:53:11 [GPU #0, KEY 000003] Tesla P100-PCIE-16GB
20201119 10:53:11 ERROR: Can't start miner, can't pair device with KEY 000000 [GPU #0, dom:0, bus:0, slot:0], map::at
20201119 10:53:11 Using protocol: stratum1.
20201119 10:53:11 Authorizing...
20201119 10:53:11 Authorized successfully.
20201119 10:53:11 ethash epoch: 376, block: 11287984, diff: 0.994 = 4.00 Gh
20201119 10:53:12 T-Rex finished.
Killed

**Comment by trexminer** [comment]
Could you please try assembly located here: https://www.dropbox.com/sh/qmlkut9qd6qvdcb/AABo_nx2p96RMygR2vfBskuoa?dl=0
We suppose to fix your problem.

**Comment by trexminer** [comment]
This issue should be fixed in 0.18.11, please give it a try and let us know if it still persists

**Comment by Sn4kY** [comment]
Hi.
yes, work great !
root@host:~/t-rex-0.18.11-linux-cuda10.0# ./ETH-ethermine.sh
20201124 09:15:44 T-Rex NVIDIA GPU miner v0.18.11  -  [CUDA v10.0]
20201124 09:15:44 r.097d5cec7212
20201124 09:15:44
20201124 09:15:44 NVIDIA Driver v455.45.01
20201124 09:15:44 CUDA devices available: 1
20201124 09:15:44
20201124 09:15:44 WARN: DevFee 1% (ethash)
20201124 09:15:44
20201124 09:15:44 URL : stratum+tcp://eu1.ethermine.org:4444
20201124 09:15:44 USER: 0x
20201124 09:15:44 PASS: x
20201124 09:15:44 WRK : rig0
20201124 09:15:44
20201124 09:15:44 Starting on: eu1.ethermine.org:4444
20201124 09:15:44 ApiServer: HTTP server started on 0.0.0.0:4067
20201124 09:15:44 ------------------------------------------------------
20201124 09:15:44 For control navigate to: http://X.X.X.X:4067/trex
20201124 09:15:44 ------------------------------------------------------
20201124 09:15:44 ApiServer: Telnet server started on 0.0.0.0:4068
20201124 09:15:44 Using protocol: stratum1.
20201124 09:15:44 Authorizing...
20201124 09:15:44 Authorized successfully.
20201124 09:15:44 WARN: GPU #0(000003): Tesla P100-PCIE-16GB, intensity set to 22
20201124 09:15:44 ethash epoch: 377, block: 11319883, diff: 0.994 = 4.00 Gh
20201124 09:15:45 WARN: NVML: can't get fan speed for GPU #0, not supported
20201124 09:15:47 GPU #0: generating DAG 3.95 GB for epoch 377 ...
20201124 09:15:50 GPU #0: DAG generated [time: 3506 ms], memory left: 11.70 GB
20201124 09:16:00 ethash epoch: 377, block: 11319884, diff: 0.994 = 4.00 Gh
20201124 09:16:01 ethash epoch: 377, block: 11319885, diff: 0.994 = 4.00 Gh
20201124 09:16:04 ethash epoch: 377, block: 11319886, diff: 0.994 = 4.00 Gh
20201124 09:16:07 GPU #0: using kernel #3
20201124 09:16:22 ethash epoch: 377, block: 11319887, diff: 0.994 = 4.00 Gh
20201124 09:16:29 ethash epoch: 377, block: 11319888, diff: 0.994 = 4.00 Gh
20201124 09:16:34 ethash epoch: 377, block: 11319889, diff: 0.994 = 4.00 Gh
20201124 09:16:35 ethash epoch: 377, block: 11319890, diff: 0.994 = 4.00 Gh
20201124 09:16:42 ethash epoch: 377, block: 11319891, diff: 0.994 = 4.00 Gh
20201124 09:16:42 [ OK ] 1/1 - 36.89 MH/s, 15ms ... GPU #0
`

thanks

**Comment by fpasalioglu** [comment]
@Sn4kY Are you using colab? How did you update cuda and nvidia versions?

**Comment by Miiichal** [comment]
Hello there
since version 19.4 and now in last 19.5 i have this "closed and solved" error - **can't pair device with KEY** 
RTX 3060Ti, trying drivers 457.51 460.89 and 460,97
this error repeats with miner CUDA version 10.0 and 11.0 (no matter what drivers)

**Comment by trexminer** [comment]
Hi @Miiichal 
Could you please run t-rex 0.19.5 and post the full log here like the users above did? Feel free to mask out your username/pass. Thanks.

**Comment by Miiichal** [comment]
![trx](https://user-images.githubusercontent.com/47387162/102854818-9b996e80-4423-11eb-8d4a-2aed3b0ca2a8.png)

**Comment by trexminer** [comment]
@Miiichal Thanks, we'll think about what could be causing it. In the meantime you should be able to run the miner with `--no-nvml` disabling NVML, although you'll lose power consumption / temperature information.
What are your GPUs by the way?

**Comment by Miiichal** [comment]
This pamatere is working as hell :)
My cards are RTX 3060TI - Gainward Phoenix

**Comment by RufenBB** [comment]
Hey tea, Trex, had same issue with Gigabyte Aorus Geforce RTX 3080 Xtreme Waterforce 
Partnr. : GV-N3080AURUSX W-10GD REV2.0
Device ID in GPUZ: 10DE 2216 - 1458 4037

Great work on LHR :) !
