### ISSUE TITLE
Wrong worker name on CrazyPool

### ISSUE THREAD

**Issue by NudeNULL** [trexminer/T-Rex#893]
It doesn't matter what I put after the -w parameter, it will always show worker name "0" in crazypool miner info.
Other tested miners send a correct worker name parameter to the pool, and it displays as it is written in the bat file.

**Comment by trexminer** [comment]
Try putting the worker name in the user parameter like https://eth.crazypool.org suggests:
```
t-rex.exe -a ethash -o stratum2+tcp://us.crazypool.org:3333 -u 0x4F9bEBE3adC3c7f647C0023C60f91AC9dfFA52d5.Worker -p x
```

**Comment by NudeNULL** [comment]
Thanks, it helped!
