### ISSUE TITLE
Previous versions of trex is better!

### ISSUE THREAD

**Issue by Drazescript** [trexminer/T-Rex#894]
So, with version 0.20.3 my worker works flawless with a RTX 3080 TI (65 mhs - eth). Updated to the newest version with LHR unlock and it maxes out at 55 mhs with the same OC. Then some LHR unlock kicks in and i get 3 - 5 mhs and i stays there. Why use a LHR unlock when the old version with no LHR unlock works so much better?

Old version: 0.20.3-win
New version 0.24.7-win

Kind regards Johan

**Comment by trexminer** [comment]
Make sure you're using 472.12 version of video drivers for best results. Let me know if it helps.
Thanks.

**Comment by Drazescript** [comment]
> 

Thank you! Its works great with that version.
Have ~90 mhs now. 

I updated trex on HiveOS aswell, but my 3070 Ti went from 60 mhs to 35 mhs. 
My HiveOS rig use nvidia version 465.31, tried to update it to 472.12 but it cant find that version. 

What version do you recommend with HiveOS?

Thank you for your help, really appreciate it! 
[Capture](https://user-images.githubusercontent.com/66653444/143863727-1d1a2cd7-1d81-4b4e-97de-5280a68d18ea.PNG)

**Comment by trexminer** [comment]
No worries.
Is there a list of available versions? I think any from 470.xx series should be fine.

**Comment by Drazescript** [comment]
> No worries. Is there a list of available versions? I think any from 470.xx series should be fine.

Alright. They have a list of 59 versions, so i guess some of them has to be 470.xx.
Thank you once again and have a lovely day!

**Comment by trexminer** [comment]
Thanks, you too!
