### ISSUE TITLE
Getting error Can't find nonce with device ID=0, GPU #0: not enought free memory to mine...

### ISSUE THREAD

**Issue by janko216** [trexminer/T-Rex#896]
Please, I couldn't find any solution...

I have a NVIDIA Quadro 2000 (5Gb memory), a default ethermine setting (no overlocking, etc.)... Any advice?

**Comment by trexminer** [comment]
If you're using Windows, I'd suggest switching to Linux, it doesn't take as much memory as Windows for itself.

**Comment by M3dic** [comment]
@janko216 https://www.windowscentral.com/how-change-virtual-memory-size-windows-10 Follow up to this and calculate GPU mem * number of GPUs = virtual mem (ex. if one card 5gb => change virtual mem to at least `initial size = 5000MB` and `maximum size = 6000MB`)

**Comment by janko216** [comment]
Yes, I'm using Windows 10, I have already made this setting (I have the initial size 30000 MB)... I guess that I could be more than 5000 MB... Thank you for your advice.

**Comment by PrinceOfParallax** [comment]
I have mine set at 64000mb and the PC already had 32gb ram the PC I am on only has 3 3070s on it.
