### ISSUE TITLE
3070 Ti Founders Edition (GA104 LHR)

### ISSUE THREAD

**Issue by Hotcoffeeman** [trexminer/T-Rex#897]
I have a 3070 Ti Founders Edition (GA104 LHR)

Windows 10 20H2
Using Drivers 471.96
Also tried 496.13 drivers

I've tried PhoenixMiner and T-Rex and for some reason I can't get T-Rex to mine at similar speed and efficiency. I really want to use T-Rex as the web interface etc is really good.

Same overclock with both. Clock -502 Mem +1300 Power 45%. I've tried giving it more power but that just results in a much worse efficiency and my electricity is expensive.

PhoenixMiner:
42 MH/s @ 130W (43 MH/s when the monitors are off)
323 kH/J 
Mining ETH

T-Rex:
Mining at eth.2miners.com:2020, diff: 8.73 G
GPU #0: RTX 3070 Ti - 27.44 MH/s, [LHR 74.0<>] [T:65/90C, P:129W, F:41%, E:218kH/W]
Shares/min: 0
Uptime: 2 mins | Algo: ethash | T-Rex v0.24.7

I've tried all the different settings eg.. --lhr-tune 70 --lhr-autotune-step-size 0.1 etc

Does even 42 MH/s sound about right?

I keep reading posts everywhere that people with 3060's get 50 and I can't get anywhere near that!

I also tried T-Rex with RVN but got around 15 MH/s that seems low?

Thanks

**Comment by AlbyGNinja** [comment]
Bruh
Your settings are COMPLETELY wrong.
First thing first use absolute core clock, set it at 1350.
Second: set memory depending on your silicion lottery starting from: 2400 up to 3000 (on windows is equivalent to +1200 / +1500)
Third: remove EVERY parameter from your bath file. Simply launch miner, in this case t-rex miner.
If you wanna try ALL THESE STUFF directly from bat file you can in this way:
`"C:\<full_path\t-rex.exe" -a ethash -o %pool% -u %wallet% -p x -w %worker% --lock-cclock 1350 --lock-cv 750 --mclock 1200 --fan 70`
Feel free to change memory clock (mclock 1200) increasing if you get less than 55. Normally you should be able to achieve about 60mh, moreover change fan speed depending on your temperatures.
Hope this little guide helps

**Comment by Hotcoffeeman** [comment]
Thanks for the help, unfortunately, it didn't work as expected...

![image](https://user-images.githubusercontent.com/95253114/144149140-9b60004b-184f-4020-87c8-3b79518c6849.png)

![image](https://user-images.githubusercontent.com/95253114/144149174-1651d355-00f3-403b-a1b3-340f0bb31d9d.png)

Whats strange is that it has locked the core clock but the memory only at 625 when I clearly have it as you suggested at 1200...

![image](https://user-images.githubusercontent.com/95253114/144149403-8d7ca812-af52-4e64-85e4-94f322a3dcbf.png)

Setting the fan to 70 just makes loads of noise, doesn't make any difference either.

Any further suggestions welcome!

**Comment by Hotcoffeeman** [comment]
Ok i got it to work by uninstalling MSI Afterburner however although I've got higher hash rate its using more power which is expensive here and therefore the efficiency is the same as PhoenixMiner. With the disadvantage that the fans are much higher so its more noisy - this is my main machine for everything not a separate rig.

![image](https://user-images.githubusercontent.com/95253114/144153085-9ad664bd-fd91-4ee1-8864-d2726bb37e6d.png)

**Comment by trexminer** [comment]
@Hotcoffeeman If you don't want to engage LHR unlock and would rather mine the same way Phoenixminer does, run T-Rex with `--lhr-tune 0`, this will force it to treat your GPU as non-LHR and mine at 42Mh / 130W similar to Phoenix.

**Comment by Hotcoffeeman** [comment]
@trexminer I would like to use LHR unlock but can I improve the efficiency? Or is around 320 kH/J to be expected for my card?

**Comment by trexminer** [comment]
You can try reducing the core clock by using `--lock-cclock` parameter, it'll reduce power consumption and most likely increase efficiency.

**Comment by Hotcoffeeman** [comment]
Seems this card isn't that efficient whatever settings I use. 

What hash rate or efficiency should I get on RVN?

I was on 496.13 drivers but I noticed several people mentioned using 471.96, however I didn't see any difference between them. Which do you recommend?

![image](https://user-images.githubusercontent.com/95253114/144254999-d00f00a8-9343-4265-b836-fdb55e6a4dec.png)

**Comment by AlbyGNinja** [comment]
> Seems this card isn't that efficient whatever settings I use.

The strangest thing is the low hashrate you get, i'm under hive os (but no difference for windows) and this is mine:
As you can see i'm almost at 60mh at an average 175w which is not bad. I live in Italy and believe it or not here the electricity is not cheap at all. I'm taking large profit anyway.
What i suspect looking at your mem temp is you need to repad/repaste your gpu, as always founder editions completely sucks in temperatures, this may causes thermal throttling capping your gpu to a lower hashrate
![image](https://user-images.githubusercontent.com/11650680/144259052-c0d3e292-941e-40e1-815a-8eeea29e9d1f.png)

**Comment by Hotcoffeeman** [comment]
I'm wondering if its because my card is LHR v3 or something, its really new. Only got it 6 months ago, and like you say its Founders Edition which suck but it was all I could get here.

Which exact version of drivers you on?
Is your card got the GA104 chip?

**Comment by AlbyGNinja** [comment]
@Hotcoffeeman I bought mine very recently, like you, it's not V3 or something and yes, it's GA104.
About the driver's version I'm using is the 470.86 which is the last for linux (i'm on hive os)

**Comment by Hotcoffeeman** [comment]
@AlbyGNinja thanks, have you tried mining RVN? Just wondered what hash rate you got with that so i can compare

**Comment by AlbyGNinja** [comment]
> @AlbyGNinja thanks, have you tried mining RVN? Just wondered what hash rate you got with that so i can compare

I'd say between 38 to 40 mh
