### ISSUE TITLE
Can´t run as Administrator

### ISSUE THREAD

**Issue by Cowansss** [trexminer/T-Rex#898]
I can´t run T-rex as an Administrator, it keeps giving me this error;

C:\Windows\system32>SET "STRATUM=stratum+tcp://eu1.ethermine.org:4444"

C:\Windows\system32>SET "WALLET=******"

C:\Windows\system32>t-rex.exe -a ethash -o stratum+tcp://eu1.ethermine.org:4444 -u %WALLET% -p x -w PC --lhr-tune 75.4 --pl 100 --lock-cclock 1500 --mclock 1300
The command "t-rex.exe" is either misspelled or
could not be found.

C:\Windows\system32>pause
Press any key . . .

**Comment by AlbyGNinja** [comment]
When using administrator you need to set the full path for windows, like `"C:\users\name_of_user\desktop\t-rex-0.24.7\t-rex.exe"` THEN followed by all parameters you need

**Comment by trexminer** [comment]
@Cowansss what AlbyGNinja suggested is one of the many ways to solve this.
