### ISSUE TITLE
1x RTX 3080 LHR DUAL MINING CFX (octupus)+ETHASH(Dagger) crashes

### ISSUE THREAD

**Issue by k0ns** [trexminer/T-Rex#902]
It says: Can't find nonce with device, Device does not have enough free memory to hold DAG for epoch 58. required 4.91GB free 4.32GB

also, can i attach the dag-build-mode: 2 command to dual mining? if yes, where, at the end or somewhere in between?
My virtual memory is set to 16000.

**Comment by trexminer** [comment]
Your 3080 doesn't have enough memory to hold DAGs for both ETH and CFX at the same time

**Comment by k0ns** [comment]
can i increase the memory? i mean rtx 3080 is rated to dual mine them

**Comment by k0ns** [comment]
> Your 3080 doesn't have enough memory to hold DAGs for both ETH and CFX at the same time

can i somehow increase the mem? i mean the rtx is rated for it to work

**Comment by trexminer** [comment]
If you're running Windows, you can try switching to Linux, it doesn't consume as much memory as Windows, leaving more available to T-Rex.

**Comment by bluewakin7** [comment]
> If you're running Windows, you can try switching to Linux, it doesn't consume as much memory as Windows, leaving more available to T-Rex.

Is it useful to increase the memory from 4G to 8G? Only ETH?thanks
