### ISSUE TITLE
Select specific GPU

### ISSUE THREAD

**Issue by CRAWLER-V** [trexminer/T-Rex#904]
Hello, I wish to try t-Rex on a laptop with GTX gpu card. The problem is that t-Rex sems to detect only the intel gpu (GPU#0) and so is not compatible and the chopping never begin.

is there a rule for the bat file to tell: start in gpu#1 and no other else?
Thanks.

**Comment by trexminer** [comment]
Hi. Yes, see `--devices` parameter in readme / main github page.
