### ISSUE TITLE
Epoch 330 requires 4.08GB but device has 4.00GB

### ISSUE THREAD

**Issue by CRAWLER-V** [trexminer/T-Rex#906]
Hello this error in red appear when start t-rex. My gpu is a GTX 1050 TI 4GB.
How can i bypass this error?
thanks.

**Comment by DejanRibnikar** [comment]
Buy a GPU with more DRAM. Only solution. (or switch to algorithm with smaller DAG)

**Comment by CRAWLER-V** [comment]
thanks.
