### ISSUE TITLE
Single or multi-instance?

### ISSUE THREAD

**Issue by LupoCri** [trexminer/T-Rex#908]
Hello.

In a rig with many GPUs that are heterogeneous by brand but not by type, what do you recommend? 
Run only one instance of T-Rex for all or one for each brand of GPUs?. 
Thanks for the reply.

LupoCri

**Comment by trexminer** [comment]
If running one instance doesn't cause any problems, stick with that approach.

**Comment by LupoCri** [comment]
Ok.
Thanks for reply.
LC
