### ISSUE TITLE
Virus Warning 

### ISSUE THREAD

**Issue by AnimeTits9** [trexminer/T-Rex#91]
I can't download t-rex-0.18.8-win-cuda11.1.zip or the 10.0 version bc there is a virus warning

**Comment by trexminer** [comment]
I'm afraid there isn't much we can do about it. Read here https://github.com/trexminer/T-Rex#antivirus-alerts

**Comment by Unlifate** [comment]
I am sure you can. There are tons of software out there, which don't want to be reverse engineered. And they don't get a virus warning. Which repacker do you use to protect the code?
