### ISSUE TITLE
watchdog MH/S drop whatchog for restart machine

### ISSUE THREAD

**Issue by vfilzek** [trexminer/T-Rex#912]
Hi, 

Its more a feature request than a issue but we are facing a lot of problem on 2060 hanging below 400mhz state in t-rex and so mining drop below  2 mh/s, so we need to set a watchdog where the MH/S drop bellow a range the machine restart.

please advise this a urgent need for every miner!!!!

**Comment by trexminer** [comment]
See `--script-low-hash` in readme
