### ISSUE TITLE
3080 TI: NVML: can't get power for GPU #1, not supported & "can't get mem/core clock"

### ISSUE THREAD

**Issue by mikeroygray** [trexminer/T-Rex#916]
I'm figuring out how to get decent numbers with my new 3080 TI (Gainward 3080 Ti Phoenix ), I've been testing with the following batch file, currently using the best values I can get in NH's quickminer. 

`SET "STRATUM=stratum+ssl://stratum.eu-west.nicehash.com:33353"
SET "WALLET=3PJfufmVRgFc2F2H4vVJXeDwTnUrmnxwSw.BreeETH3080ti"
"D:\mining\t-rex-0.24.7-win\t-rex.exe" -d 1 --lhr-autotune-mode full -a ethash -o %STRATUM% -u %WALLET% -p x -w rig1  --lock-cclock 1250 --mclock 1300 
pause
`

The miner is doing OK - delivering about the same best numbers I get on NH QM. (80-82 mh/s). Also, it looks like the clock locks are working - for example, if I check afterburner, memory is locked in at +1300. But the warnings I get when I start up seem odd. 

Note: I'm currently getting the same hashrate I can get on QM. Ergo: I'd need to see at least 1.5% improvement to switch!

![Screenshot 2021-12-09 112554](https://user-images.githubusercontent.com/37187713/145379201-034f22c2-f55a-4575-b25b-41a328442bb6.png)

**Comment by trexminer** [comment]
Power and clock readings are retrieved through NVML - for some reason it reports as not supported for your GPU, there isn't much we can do in T-Rex about it. One thing to try is to re-install video drivers.

**Comment by mikeroygray** [comment]
> 

Hmm. Yeah, that was my first guess. I did a complete DDU unstill, then rolled back to 472.12 just to make sure. No dice.

**Comment by mikeroygray** [comment]
> 
Two questions:
- Is this something I (or others with this issue!) should be worried about? I.e., will it have any effect on performance and/or longevity?
- Is this a relatively common issue that you have with some cards - or could it be that something is wromg with the card or its firmware?

**Comment by trexminer** [comment]
1. I believe it's a driver (or NVIDIA lib) related issue and it doesn't affect performance or longevity
2. It's not a very frequent problem but we've seen a few reports similar to yours

**Comment by mikeroygray** [comment]
Huh. I ran DDU again, then updated to latest game ready drivers - the error is gone now, ad I'm getting all the normal values in the mining window.
