### ISSUE TITLE
In HiveOS "api-bind-http": "0" is not working

### ISSUE THREAD

**Issue by b8engl** [trexminer/T-Rex#917]
Program not setting "api-bind-http": "0" in hiveos

![api](https://user-images.githubusercontent.com/29173784/145425042-ebf068f0-0452-4e7d-aaad-0bc033e6f560.png)

```
"api-bind-http": "0"
````
```{
  "pools": [
    {
      "user": "",
      "url": "",
      "pass": "",
      "worker": ""
    }
  ],
  "api-bind-http": "127.0.0.1:4059",
  "_notes": "Generated at Thu Dec 9 15:24:24 GMT 2021"
}
```

**Comment by trexminer** [comment]
HiveOS overwrites `"api-bind-http"` parameter to make sure it's able to access miner's API to report stats in their GUI. There's a `*.sh` script in the miner directory that does that, and you can modify it at your own risk.

**Comment by b8engl** [comment]
oh sorry, i didn't know that hive get the stats from that.
