### ISSUE TITLE
Rtx 390 suddenly low hashrate issue

### ISSUE THREAD

**Issue by Feca94** [trexminer/T-Rex#918]
Hey!

I use the nbminer on my windows11 with 4 rtx390 and suddenly drop my one of card hashrate.. you see in the picture 117.2 to 75.35 after that to 55 and now always there.. the afterburner settings is -300 +1200 and 85 power limit. It's works with 120-hash before the problem..can you  tell me some possible solution for this problem maybe?

thanks for your time!
![3B07ABBA-AC97-49A6-8615-283EA3B14CFC](https://user-images.githubusercontent.com/95885883/145480276-739260d1-0bd0-45a3-9851-ccd014c19da6.jpeg)

![8FABCB68-8FA7-4B71-8E25-82E91E58DA06](https://user-images.githubusercontent.com/95885883/145480266-2cbe5bf9-7431-4892-b469-cac66521dcb1.jpeg)

**Comment by Deadtenor** [comment]
Sir, this is a Wendys.

This is the t-rex miner site.

**Comment by trexminer** [comment]
Yep, wrong miner I'm afraid.
