### ISSUE TITLE
3090 can not work with cuda 8.6

### ISSUE THREAD

**Issue by nhtgrsa43452fd** [trexminer/T-Rex#92]
That's mining error:
20201115 19:26:04 T-Rex NVIDIA GPU miner v0.18.9  -  [CUDA v10.0]
20201115 19:26:04 r.4329cb1ce1ea
20201115 19:26:04
20201115 19:26:04 NVIDIA Driver v457.30
20201115 19:26:04 CUDA devices available: 1
20201115 19:26:04
20201115 19:26:04 WARN: DevFee 1% (x16rv2)

20201115 19:26:04 ERROR: Can't start miner, GPU architecture CC 8.6 is not supported by CUDA v10.0, use T-Rex compiled with CUDA v11.1 or newer
20201115 19:26:04 WARN: failed to subscribe, stratum_subscribe can't send line

20201115 19:26:04 ERROR: No connection, retry after 10 seconds
20201115 19:26:05 T-Rex finished.

That's GPUZ:
General
CUDA Device Name	GeForce RTX 3090
Compute Capability	8.6
Processor Count	82
Cores per Processor	0
GPU Clock Rate	1755.0 MHz
Memory Clock Rate	9751.0 MHz
Memory Bus Width	384
L2 Cache Size	6144 KB
Global Memory Size	24576 MB
Async Engines	2
SP to DP Ratio	1:32
ECC Supported	No
Using TCC Driver	No
Compute Mode	Default
Multi-GPU Board	No (0)
PCI ID	Bus 45, Dev 0, Domain 0
Threads per Multiprocessor	1536
Max Shmem per Multiprocessor	100 KB
Execute Multiple Kernels	Yes
Preemption Supported	Yes

**Comment by nhtgrsa43452fd** [comment]
t-rex V0.18.9

**Comment by trexminer** [comment]
> Can't start miner, GPU architecture CC 8.6 is not supported by CUDA v10.0, use T-Rex compiled with CUDA v11.1 or newer

CUDA 11.1 build should fix the problem

**Comment by nhtgrsa43452fd** [comment]
no,it's new drives for cuda64.dll - NVIDIA CUDA 11.1.114 drive ,iam installed CUDA.

**Comment by nhtgrsa43452fd** [comment]
<img width="651" alt="2" src="https://user-images.githubusercontent.com/40670130/99509101-51564500-29c0-11eb-8278-922597c73b60.PNG">

**Comment by nhtgrsa43452fd** [comment]
did i missing something?

**Comment by trexminer** [comment]
Try CUDA 11.1 build of t-rex: https://github.com/trexminer/T-Rex/releases/download/0.18.9/t-rex-0.18.9-win-cuda11.1.zip

**Comment by nhtgrsa43452fd** [comment]
thats working,thanks
