### ISSUE TITLE
Issues with P-state  "--pstate p0" on 3080ti & 0.24.8

### ISSUE THREAD

**Issue by Faltskog** [trexminer/T-Rex#923]
So, i have 2x 3080ti twins (Gigabyte 3080ti OC Vision) mining at roughly 89-91mh/s at 268-286w with 90TJ temp max. But when i tried the .bat command line "--pstate p0" they went crazy like

"WARN: Can't setup fan speed for [000100] NVAPI_ERROR, code -1"
"T-Rex needs to terminate" (something like that)

And when i took off the "--pstate p0" it said another thing like 

"Gigabyte 3080Ti OC went idle, for 30 secs, 45 secs" and so on. and won't work again no matter what parameter i put in or take off, UNTIL i disconnected all the cables and put it back in... (if this is useful to somebody) and yes i was crazy worried. But now is working as normal.

The thing is that i have also mining a EVGA RTX 2070 Black Edition, and when i set the "--pstate p0" started to work well, to the point that i remove that command and started to mine from 44.10mh/s to 42mh/s...

Other thing that i saw is that on the 3080ti's when the "pstate p0" was on they did 120mh/s each but just for one tick and then stopped working and said what i said above... so strange.

**Comment by trexminer** [comment]
When you force set P0 state, you need to dial down your memory overclock, ideally by the offset between the base clock for P0 and P2 states, otherwise the GPU will just crash.
NVAPI_ERROR is a generic error with no specifics. I'd try rebooting and starting the miner without `--pstate`, then reinstalling drivers, then checking / swapping risers and PSU - in that order.

**Comment by dedizones** [comment]
> When you force set P0 state, you need to dial your memory overclock down, ideally by the offset between the base clocks for P0 and P2 states, otherwise the GPU will just crash.
> NVAPI_ERROR is a generic error with no specifics. I'd try rebooting and starting the miner without `--pstate`, then reinstalling drivers, then checking / swapping risers and PSU - in that order.

yes just remove -400Mhz for security

**Comment by Faltskog** [comment]
Let's make an example shall we?:
t-rex.exe -a ethash -o stratum2+tcp://br.crazypool.org:3333 -u XXXXXXX --pl 100,100 --lock-cclock 1500,1500 --mclock 1240,1350 --fan 65,65 -lhr 73.8,73.8
pause

In this case if i add "--pstate p0" i have to dial the memo down, to let's say to... --mclock 1000,1000? or even more?

**Comment by Faltskog** [comment]
> When you force set P0 state, you need to dial your memory overclock down, ideally by the offset between the base clocks for P0 and P2 states, otherwise the GPU will just crash. NVAPI_ERROR is a generic error with no specifics. I'd try rebooting and starting the miner without `--pstate`, then reinstalling drivers, then checking / swapping risers and PSU - in that order.

Let's make an example shall we?:
t-rex.exe -a ethash -o stratum2+tcp://br.crazypool.org:3333 -u XXXXXXX --pl 100,100 --lock-cclock 1500,1500 --mclock 1240,1350 --fan 65,65 -lhr 73.8,73.8
pause

In this case if i add "--pstate p0" i have to dial the memo down, to let's say to... --mclock 1000,1000? or even more?

**Comment by trexminer** [comment]
@Faltskog Each P state corresponds to a certain base clock - it's GPU specific. So, when you specify `--pstate p0`, your absolute GPU memory clock will become `P0_baseClock + mclock`. When you don't specify `--pstate` it's `P2_baseClock + mclock` - I use P2 here as an example, you need to check what state your GPU is in when mining.
So, to keep the absolute mem clock at the same level, you need to reduce your `--mclock` by `P0_baseClock - P2_baseClock`. What are your base clocks for P0 and P2 I don't know.
You can check the absolute clock value using GPU-Z / HwInfo, or T-Rex WebUI.

**Comment by Faltskog** [comment]
First, thanks for taking the time to elaborate these responses.
Second, how can i know what p-state are my GPU's currently? I have HWiNFO64 & GPU-Z, i look at both from start to bottom, but couldn't find anything, maybe i don't know what to look up for, (at least didn't find anything with p-state word related on them)
Third, what can i achieve from this? stability? more mh/s? less wattage? less memory temp?
Forth, where can i read more of these P-State stuff? So i can approach to you with better questions rather than annoy you like a toddler asking for everything (just because i like this stuff) 😅
From my understading seems like i'm unlocking something from the GPU with p-state p0, independently if it works for mining purposes, can affect in gaming too?

**Comment by Faltskog** [comment]
> @Faltskog Each P state corresponds to a certain base clock - it's GPU specific. So, when you specify `--pstate p0`, your absolute GPU memory clock will become `P0_baseClock + mclock`. When you don't specify `--pstate` it's `P2_baseClock + mclock` - I use P2 here as an example, you need to check what state your GPU is in when mining. So, to keep the absolute mem clock at the same level, you need to reduce your `--mclock` by `P0_baseClock - P2_baseClock`. What are your base clocks for P0 and P2 I don't know. You can check the absolute clock value using GPU-Z / HwInfo, or T-Rex WebUI.

@trexminer First, thanks for taking the time to elaborate these responses.
Second, how can i know what p-state are my GPU's currently? I have HWiNFO64 & GPU-Z, i look at both from start to bottom, but couldn't find anything, maybe i don't know what to look up for, (at least didn't find anything with p-state word related on them)
Third, what can i achieve from this? stability? more mh/s? less wattage? less memory temp?
Forth, where can i read more of these P-State stuff? So i can approach to you with better questions rather than annoy you like a toddler asking for everything (just because i like this stuff) 😅
From my understading seems like i'm unlocking something from the GPU with p-state p0, independently if it works for mining purposes, can affect in gaming too?

**Comment by trexminer** [comment]
No problem :) You can see what state the GPU is in if you run `nvidia-smi` in the terminal. It should print something like this:
![image](https://user-images.githubusercontent.com/44735836/145803477-f9986f8b-ff32-470c-992a-0416f2bbb910.png)
As you can see, both cards are in P8 now.

From https://docs.nvidia.com/gameworks/content/gameworkslibrary/coresdk/nvapi/group__gpupstate.html:
> The GPU performance state APIs are used to get and set various performance levels on a per-GPU basis. P-States are GPU active/executing performance capability and power consumption states.
> P-States range from P0 to P15, with P0 being the highest performance/power state, and P15 being the lowest performance/power state. Each P-State maps to a performance level. Not all P-States are available on a given system. The definition of each P-States are currently as follows:
> P0/P1 - Maximum 3D performance
P2/P3 - Balanced 3D performance-power
P8 - Basic HD video playback
P10 - DVD playback
P12 - Minimum idle power consumption



> Third, what can i achieve from this? stability? more mh/s? less wattage? less memory temp?

I think people force P0 just to get some more stability, because when GPU is in P0 there's no way it can suddenly jump into a lower P-state which would increase its memory clock. If it's in P2 and your absolute clock is already at the max the GPU can handle, a sudden switch to P1 or P0 would likely cause a crash.

**Comment by dedizones** [comment]
`I think people force P0 just to get some more stability, because when GPU is in P0 there's no way it can suddenly jump into a lower P-state which would increase its memory clock. If it's in P2 and your absolute clock is already at the max the GPU can handle, a sudden switch to P1 or P0 would likely cause a crash.`

I am under hiveOS for my part and under linux

I confirm that since he added P0 in the configuration my rigs are not only more stable but also more lively.

The calculation is more straightforward, especially for me who only does SOLO ... I need stability at all levels

**Comment by Faltskog** [comment]
> No problem :) You can see what state the GPU is in if you run `nvidia-smi` in the terminal. It should print something like this: ![image](https://user-images.githubusercontent.com/44735836/145803477-f9986f8b-ff32-470c-992a-0416f2bbb910.png) As you can see, both cards are in P8 now.
> 
> From https://docs.nvidia.com/gameworks/content/gameworkslibrary/coresdk/nvapi/group__gpupstate.html:
> 
> > The GPU performance state APIs are used to get and set various performance levels on a per-GPU basis. P-States are GPU active/executing performance capability and power consumption states.
> > P-States range from P0 to P15, with P0 being the highest performance/power state, and P15 being the lowest performance/power state. Each P-State maps to a performance level. Not all P-States are available on a given system. The definition of each P-States are currently as follows:
> > P0/P1 - Maximum 3D performance
> > P2/P3 - Balanced 3D performance-power
> > P8 - Basic HD video playback
> > P10 - DVD playback
> > P12 - Minimum idle power consumption
> 
> > Third, what can i achieve from this? stability? more mh/s? less wattage? less memory temp?
> 
> I think people force P0 just to get some more stability, because when GPU is in P0 there's no way it can suddenly jump into a lower P-state which would increase its memory clock. If it's in P2 and your absolute clock is already at the max the GPU can handle, a sudden switch to P1 or P0 would likely cause a crash.

Now i'm more curious about, are you mining at P-State P8? If so, why? i mean i see that power consumption 👀 but what about hashrate? 


Back to my topic, this is my 2x 3080ti rig (P2-State)

![bangalter](https://user-images.githubusercontent.com/90661265/145814266-4ec5a69c-6d83-4e4f-97f7-f7514fb68487.png)

And this is gaming PC with RTX 2070 (P0-State) 

![Faltskog](https://user-images.githubusercontent.com/90661265/145814593-94925d4b-bb98-49f3-98f8-fd51f0110bbd.png)

The fact on how P-states works has anything to do with LHR? because i put _**"--pstate p0"**_ on the RTX 2070 and simply worked... and when i remove it, it went from 44mh/s to 42mh/s, so i put back to p0 and went to 44mh/s again.

I guess i have to find the correct absolute clock to work at p-state p0 to see how it works from there, can i ask you, how can i find the absolute clock for my 3080ti's? I double checked all the options availables on GPU-Z and HWiNFO64 and there's nothing on there. 😞 

this is **KIND** of C-States for CPU, could it be?
