### ISSUE TITLE
The log file problem in version 0.24.7, I hope the developer will reply

### ISSUE THREAD

**Issue by dksir47** [trexminer/T-Rex#927]
I added "--log-path" to the configuration. Every time the kernel restarts, there will be no error codes for restarting the kernel in the log, which leads me to wonder why the kernel restarts.

**Comment by trexminer** [comment]
`--log-path` is broken in 0.24.7
0.24.8 fixes it

**Comment by ezequiel1438** [comment]
Hola , no se si es el lugar, sly nuevo recien me hice la cuenta para poder hacer mi consulta. 
resulta que tengo una plaquita chica minando con hiveon en linuex booteable por pendrive, me da un enlase para descargar la version 0.24.8 en .tar.gz o .zip . 
pero que es lo que tengo que hacer  con esos archivos descargados. ?
pd: los archivos los descargue al cel y a mi notebook . No con la pc que tengo minando ,como dije esta minando mediante el buteado desde el pendrivd

**Comment by ezequiel1438** [comment]
que mal escribi.. perdon !!
