### ISSUE TITLE
I found the reason for the slow drop in hashrate.

### ISSUE THREAD

**Issue by bluewakin7** [trexminer/T-Rex#929]
Hi.
When I run bat manually, a CMD window appears, the memory usage is about 900MB, the hashrate will slowly drop, and it will be farther and farther away from the rated hashrate.
When I put the bat file in the auto-start menu, and then restart the computer, the program will run automatically, the memory occupies less than 60MB, and most importantly, the hashrate does not drop anymore.
win10,P104-100,t-rex 0.24.6/7

**Comment by trexminer** [comment]
Thanks for letting us know about the issue you experienced and the fix for it.
