### ISSUE TITLE
Getting some WARNings

### ISSUE THREAD

**Issue by DelaloreGamingHD** [trexminer/T-Rex#93]
Hello!
I am new to mining, so when i start T-rex for mining i get these warnings
![W9jEuAH1JyQ](https://user-images.githubusercontent.com/53839654/99312888-610e4600-2867-11eb-9e90-477a700ea043.png) 
Does it mean, that it is not mining at all?

**Comment by trexminer** [comment]
Hi, your GPU doesn't have enough memory to mine ETH. You may be able to mine RVN with it though.

**Comment by DelaloreGamingHD** [comment]
> Hi, your GPU doesn't have enough memory to mine ETH. You may be able to mine RVN with it though.

Seems like RVN mining works for me 
![Uploading image.png…]()

**Comment by trexminer** [comment]
Glad it worked for you
