### ISSUE TITLE
Please help me stats problem!! here in hiveos with Trex miner v.0.24.8. How to make fix this!!!!! see this screen shots

### ISSUE THREAD

**Issue by ROCKET0101** [trexminer/T-Rex#930]
![InkedScreenshot 2021-12-15 161146](https://user-images.githubusercontent.com/92781808/146173307-2b454186-2897-4e8f-81e8-be6f656dd8c2.jpg)
![InkedScreenshot 2021-12-15 161213](https://user-images.githubusercontent.com/92781808/146173321-05ebb187-fd28-4893-a9de-f06945cbbb71.jpg)
![InkedScreenshot 2021-12-15 161245](https://user-images.githubusercontent.com/92781808/146173326-a0d76bbe-3878-4918-83ed-5ad56fd28ed7.jpg)
![InkedScreenshot 2021-12-15 161322](https://user-images.githubusercontent.com/92781808/146173331-eb14a7b1-62b9-49f4-ac8a-31ef3025adf4.jpg)

**Comment by trexminer** [comment]
The issue appears to have nothing to do with T-Rex. Please direct your question to HiveOS support team.

**Comment by nefgarcias** [comment]
I have the same problem, has it been solved?
