### ISSUE TITLE
Cannot kill the process on Linux

### ISSUE THREAD

**Issue by shuuchen** [trexminer/T-Rex#933]
Hi,

Thank you. I tried t-rex in background with nohup on a Ubuntu but I cannot kill the process.
Once I kill a process with PID, another process emerges and I don't know why.
How to kill the process thoroughly ?

**Comment by trexminer** [comment]
Hi.
T-Rex launches two processes - one is watchdog and another one is the actual miner (former is the parent of the latter). You need to kill the parent process to prevent the miner from recovering itself.

**Comment by shuuchen** [comment]
Thank you. I have closed it.

**Comment by ysl2** [comment]
how to kill watchdog?
