### ISSUE TITLE
How to modify address and improve mining efficiency ?

### ISSUE THREAD

**Issue by shuuchen** [trexminer/T-Rex#934]
Hi,

I have a multi-gpu machine and I am trying to launch t-rex several times, each time with different GPU number specified.
However, it seems that I should use another address. How can I do that ?
```bash
WARN: ApiServer: failed to bind socket 127.0.0.1:4067 (Address already in use), next try in 5 seconds.
```

Actually, I find only 1/6 memory of per GPU is used when running t-rex. I 'd like to improve the efficiency of t-rex, so I want to launch t-rex several times on the same GPU. Any other good ideas for efficiency ?

**Comment by trexminer** [comment]
If you want to launch multiple instances of T-Rex **and** have access to the API or WebUI of each instance, you need to change the API server port number with `--api-bind-http` parameter. It's set to `127.0.0.1:4067` by default.
However, running multiple instances on the same GPU will generally degrade performance.

**Comment by shuuchen** [comment]
I see. Thank you.

**Comment by shuuchen** [comment]
Do you have other suggestions to improve the efficiency ?

**Comment by trexminer** [comment]
That is a very generic question. I recommend joining our Discord server and asking mining community about your specific case.
