### ISSUE TITLE
GPU crash error code

### ISSUE THREAD

**Issue by botland** [trexminer/T-Rex#935]
I'm getting an error probably caused by my overclocking settings and find no way how to determine what the error code "3" stands for :
```
WD: ======== GPU CRASH LIST ========
WD: GPU#0: 3
```
Where can I find an associative array of error codes/labels to help me track down the root cause and its severity ?

**Comment by trexminer** [comment]
`3` is the number of time the GPU#0 crashed, it's not an error code

**Comment by botland** [comment]
oh, that's why :-)
