### ISSUE TITLE
ayuda con la version 0.24.8

### ISSUE THREAD

**Issue by ezequiel1438** [trexminer/T-Rex#936]
Hola, no se si es el lugar, soy nuevo recien me hice la cuenta para poder hacer mi consulta.
resulta que tengo una plaquita chica minando con hiveon en linux booteable por pendrive, en el monitor en la pantalla modo miner screen ,me da un enlase para descargar la versión 0.24.8 en .tar.gz
pero que es lo que tengo que hacer con esos archivos descargados. ?
pd: los archivos los descargue al cel ya mi notebook. No con la pc que tengo minando, como dije esta minando mediante el buteado desde el pendrive no es con windows.

**Comment by trexminer** [comment]
I recommend starting with https://github.com/trexminer/T-Rex/wiki/FAQ
