### ISSUE TITLE
Proxy issue about whether dev fee connenctions via proxy?

### ISSUE THREAD

**Issue by pologuy12138** [trexminer/T-Rex#938]
I wanna hide my true ip, so I attempt to use proxy to do that. But I wonder if dev fee connections via proxy while using proxy mining?
I mentioned gminer 2.7.4 add this feature about "proxy option using for user and dev fee connections". So I wanna make sure if t-rex have had do so. If not, will you guys plan to add this new feature in the fureture?

**Comment by pologuy12138** [comment]
I think t-rex miner is better than gminer for NV cards, so I do not want wo switch to gminer.

**Comment by trexminer** [comment]
If you set `--proxy`, dev fee connections are established through it as well.

**Comment by pologuy12138** [comment]
> If you set `--proxy`, dev fee connections are established through it as well.

Thanks for replaying! Now I can happy mining without worries.
