### ISSUE TITLE
0.24.8 UI not visible in local network

### ISSUE THREAD

**Issue by patriano** [trexminer/T-Rex#939]
I have tried to update trex miner from 0.24.7 to 0.24.8, I have copied all settings and trex UI is not visible in local network now, on 0.24.7 is visible. UI is visible on rig, my settings:
```
.t-rex.exe -a ethash -o stratum+tcp://eu1.ethermine.org:4444 -u XXX -p x -w rig01 --api-bind-http 0.0.0.0:4067 --api-read-only --log-path C:\logs\trex.log
pause
```

**Comment by trexminer** [comment]
It's probably a firewall issue, you typically need to re-add all the rules after updating the miner

**Comment by patriano** [comment]
You are correct, thank you 👍
