### ISSUE TITLE
How to set parameter "no-sni" and "dns-https-server" in hiveos?

### ISSUE THREAD

**Issue by Alibabade** [trexminer/T-Rex#942]
Hi, 
I'm pretty new to t-rex and hiveos.
As the title said, could anyone tell me how to set "no-sni" and "dns-https-server" in hiveos? 
I really appreciate if you could post a pic.
Thanks very much in advance!

**Comment by trexminer** [comment]
https://github.com/trexminer/T-Rex/wiki/FAQ#how-do-i-set-extra-parameters-in-hiveos

So,
```
"no-sni": true
"dns-https-server": "ip_address_of_your_DNS_server_eg_1.1.1.1"
```

**Comment by Alibabade** [comment]
Thanks!!
