### ISSUE TITLE
`lhr-autotune-step-size` not working when `intensity=25`

### ISSUE THREAD

**Issue by jmakov** [trexminer/T-Rex#952]
LHR doesn't change when intensity flag added

**Comment by trexminer** [comment]
Please post the log file

**Comment by jmakov** [comment]
[start_gpu_miner-[1640164546].log](https://github.com/trexminer/T-Rex/files/7761934/start_gpu_miner-.1640164546.log)

**Comment by jmakov** [comment]
Also how come intensity isn't always max? Wouldn't the GPU have higher hashrate with processing more nonces at once?

**Comment by trexminer** [comment]
From the log:
```
20211222 02:32:20 GPU #0: LHR detected. 0.5min since last lock. Unlocking ...
20211222 02:32:40 GPU #0: resuming mining
20211222 02:32:40 GPU #0: changing LHR tuning: 74.0 => 73.9
```
that looks normal assuming you set `lhr-autotune-step-size` to `0.1`

> Also how come intensity isn't always max? Wouldn't the GPU have higher hashrate with processing more nonces at once?

No, it won't necessarily have higher hashrate. Also, changing intensity is not recommended when you mine with LHR cards, it's in the wiki.

**Comment by jmakov** [comment]
What you reference in the log is only at the beginning. LHR is then set to 73.9 for the next 7h 43min and doesn't change.

**Comment by jmakov** [comment]
["It's important not to set intensity values manually as that may interfere with the unlocking algorithm."](https://github.com/trexminer/T-Rex/wiki/LHR). Didn't see this before, thanks for the quick support!

**Comment by trexminer** [comment]
> What you reference in the log is only at the beginning. LHR is then set to 73.9 for the next 7h 43min and doesn't change.

That's correct behaviour (by design).
After decreasing the LHR tune value it didn't hit any LHR locks, so there was no reason for it to go lower. Also, it tried LHR 74 at the very beginning and hit a lock - so there's no point in trying to get it back to 74 either.
