### ISSUE TITLE
WARN: NVML: can't get fan speed for GPU #0, not supported

### ISSUE THREAD

**Issue by burakkp** [trexminer/T-Rex#957]
Hi,

I am facing below issue when run the sh's. How can I solve this? Pop_OS installed on my laptop.

`20211223 17:03:30 GPU #0: intensity 22
20211223 17:03:31 ethash epoch: 462, block: 13862404, diff: 8.73 G
20211223 17:03:31 WARN: NVML: can't get fan speed for GPU #0, not supported
20211223 17:03:31 WARN: NVML: can't get power for GPU #0, not supported
20211223 17:03:34 TREX: Can't find nonce with device [ID=0, GPU #0], GPU #0: not enough free memory to mine ethash at epoch 462
`

**Comment by trexminer** [comment]
fan speed etc is just a warning, the error is 
```
GPU #0: not enough free memory to mine ethash at epoch 462
```

apparently you're trying to mine ethash with a GPU that doesn't have enough VRAM
