### ISSUE TITLE
Can't connect to the mining pool, resolve: Host not found

### ISSUE THREAD

**Issue by ROCKET0101** [trexminer/T-Rex#959]
![20211224_071252.jpg](https://user-images.githubusercontent.com/92781808/147307098-2e664b76-65b7-49e8-8a47-2525eafaea74.jpg)

**Comment by trexminer** [comment]
Seems to be a networking issue, the miner can't resolve `asia2.ethermine.org` through DNS. You can try using DoH: `--dns-https-server 1.1.1.1`.

**Comment by ROCKET0101** [comment]
> Seems to be a networking issue, the miner can't resolve `asia2.ethermine.org` through DNS. You can try using DoH: `--dns-https-server 1.1.1.1`.

Sir how to use this DoH and this command,i  am use hiveos sir.

**Comment by trexminer** [comment]
In HiveOS it would be
```
"dns-https-server": "1.1.1.1"
```
