### ISSUE TITLE
proxy offline and can't connect

### ISSUE THREAD

**Issue by thecxj** [trexminer/T-Rex#963]
I used ccproxy as socks 5 server. T-Rex usually auto offline or can't connect. GMiner and NBMiner is worked OK. So please check it. Thanks.

**Comment by trexminer** [comment]
Please post the log file. Thanks.

**Comment by thecxj** [comment]
20211229 12:53:09 T-Rex NVIDIA GPU miner v0.24.8  -  [Windows]
20211229 12:53:09 r.24882b3a9e07
20211229 12:53:09 
20211229 12:53:09 
20211229 12:53:09 NVIDIA Driver v471.68
20211229 12:53:09 
20211229 12:53:09 + GPU #0: [00:01.0|2489] Gigabyte GeForce RTX 3060 Ti, 8192 MB
20211229 12:53:09 + GPU #1: [00:04.0|2489] Gigabyte GeForce RTX 3060 Ti, 8192 MB
20211229 12:53:09 + GPU #2: [00:05.0|2489] Gigabyte GeForce RTX 3060 Ti, 8192 MB
20211229 12:53:09 + GPU #3: [00:06.0|2489] Gigabyte GeForce RTX 3060 Ti, 8192 MB
20211229 12:53:09 + GPU #4: [00:07.0|2489] Gigabyte GeForce RTX 3060 Ti, 8192 MB
20211229 12:53:09 
20211229 12:53:09 WARN: DevFee 1% (ethash)
20211229 12:53:09 
20211229 12:53:09 URL : stratum+ssl://asia1.ethermine.org:5555
20211229 12:53:09 USER: 0xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
20211229 12:53:09 PASS: 
20211229 12:53:09 WRK : LHR04
20211229 12:53:09 
20211229 12:53:09 WARN: Temperature limit is activated. Limit is set to 70C.
20211229 12:53:09 
20211229 12:53:09 Starting on: asia1.ethermine.org:5555 via proxy: 0.0.0.0:0000
20211229 12:53:09 WARN: API server is not bound to 127.0.0.1, consider setting up API key (see --api-key)
20211229 12:53:09 ApiServer: HTTP server started on 0.0.0.0:10086
20211229 12:53:09 --------------------------------------------------------
20211229 12:53:09 For control navigate to: http://192.168.10.84:10086/trex
20211229 12:53:09 --------------------------------------------------------
20211229 12:53:10 Using protocol: stratum1.
20211229 12:53:10 Authorizing...
20211229 12:53:10 WARN: failed to ethproxy-subscribe on asia1.ethermine.org:5555: can't parse json: 
* Line 1, Column 1
  Syntax error: value, object or array expected.


20211229 12:53:10 ERROR: No connection with asia1.ethermine.org:5555, retry after 10 seconds
20211229 12:53:10 GPU #0: intensity 21.3, fan 85%, mclock 1200MHz, pl 90%, core clock locked 1410MHz
20211229 12:53:10 GPU #1: intensity 21.3, fan 90%, mclock 1200MHz, pl 90%, core clock locked 1410MHz
20211229 12:53:10 GPU #2: intensity 21.3, fan 80%, mclock 1200MHz, pl 90%, core clock locked 1410MHz
20211229 12:53:10 GPU #3: intensity 21.3, fan 80%, mclock 1200MHz, pl 90%, core clock locked 1410MHz
20211229 12:53:10 GPU #4: intensity 21.3, fan 90%, mclock 1200MHz, pl 90%, core clock locked 1410MHz
20211229 12:53:20 Using protocol: stratum1.
20211229 12:53:20 Authorizing...
20211229 12:53:20 WARN: failed to ethproxy-subscribe on asia1.ethermine.org:5555: can't parse json: 
* Line 1, Column 1
  Syntax error: value, object or array expected.


20211229 12:53:20 ERROR: No connection with asia1.ethermine.org:5555, retry after 10 seconds
20211229 12:53:30 Using protocol: stratum1.
20211229 12:53:30 Authorizing...
20211229 12:53:30 WARN: failed to ethproxy-subscribe on asia1.ethermine.org:5555: can't parse json: 
* Line 1, Column 1
  Syntax error: value, object or array expected.


20211229 12:53:30 ERROR: No connection with asia1.ethermine.org:5555, retry after 10 seconds
20211229 12:53:33 WARN: shutdown t-rex, got Ctrl+C from console
20211229 12:53:33 Main loop finished. Cleaning up resources...
20211229 12:53:33 ApiServer: stopped listening on 0.0.0.0:10086
20211229 12:53:39 T-Rex finished.

**Comment by thecxj** [comment]
Tcp is OK, ssl is error.

**Comment by trexminer** [comment]
> Tcp is OK, ssl is error.

try with `--no-strict-ssl` then

**Comment by thecxj** [comment]
it works ok after I add the --no-strict-ssl
