### ISSUE TITLE
T-Rex v0.24.8 keeps shutting down

### ISSUE THREAD

**Issue by Fogwar007** [trexminer/T-Rex#967]
Hello,

My v0.24.8 miner keeps crashing and shutting down with the following errors below. v0.24.0 was stable for months, then I started to get issues with that crashing so I downloaded the latest version - but now I have new errors.

![image](https://user-images.githubusercontent.com/96682210/147652778-474f1053-1adc-4cd9-b015-e10d55396107.png)

Can anyone please help?

**Comment by Miiichal** [comment]
I had this error too...
Realized, that the last version has some problems with the Vidia drivers, **but only with cards RTX 2080**
471.96 - no errors, without issues
497.09 and 497.29 - TRex crashes after few minutes

2080 Super and 2080 Ti - without issues
30xx - without issues

**Comment by trexminer** [comment]
https://github.com/trexminer/T-Rex/wiki/FAQ#what-are-error-codes-15-and-999
