### ISSUE TITLE
Can't find nonce with device ID=0 GPU#0, GPU#0 : not enough free memory to mine ethash at epoch 463

### ISSUE THREAD

**Issue by pxndx25** [trexminer/T-Rex#972]
![image](https://user-images.githubusercontent.com/96892327/147792689-8a564af6-04ce-4425-a9e1-e4a29866b6fb.png)

I have a laptop with 2 gpus
One that is integrated, a intel(R) UHD Graphics Approx. Total Memory 8201 Mb, Display memory 128 Mb, Shared memory 8073
Two that is my main gpu that is Nvidia RTX 3050 ti Laptop GPu With Approx. Total Memory 12063 Mb, Display Memory 3990, Shared Memory 8073

I cannot mine and idk why

**Comment by trexminer** [comment]
3050 Ti only has 4GB of VRAM, you can't mine ETH with it

**Comment by culturedesign** [comment]
![Screenshot 1_4_2022 10_47_11 AM](https://user-images.githubusercontent.com/92207455/148012755-b17f64a1-678e-4c2a-8379-80118020d0dc.png)

**Comment by culturedesign** [comment]
![a79de001-a17d-485a-9e27-72ff315e25dd](https://user-images.githubusercontent.com/92207455/148012941-e500f4e7-1417-4cba-95ed-58f1d48ad189.jpg)
)
