### ISSUE TITLE
stop start ,why  20220106 22:02:24 TREX: T-Rex instance wasn't validated   ? How to solve？

### ISSUE THREAD

**Issue by xiang88123** [trexminer/T-Rex#980]
![MQH4AQ}85I7H`$U4 C4_H~0](https://user-images.githubusercontent.com/56552774/148395392-701c8cd7-6431-4682-80bd-506de774bb23.png)

**Comment by xiang88123** [comment]
This will be displayed after a few minutes of each run, and then restart

**Comment by trexminer** [comment]
see https://github.com/trexminer/T-Rex/wiki/FAQ#what-is-the-instance-wasnt-validated-error
