### ISSUE TITLE
T-rex miner error showing.. 

### ISSUE THREAD

**Issue by rayhaankhan** [trexminer/T-Rex#982]
I'm pretty new to mining.
i just started using T-rex mining on my laptop MSI GTX 1060. 

![Screenshot (132)](https://user-images.githubusercontent.com/72562797/148585655-7fe528aa-f74d-4d2a-b836-ba7c8b816f96.png)

help me please, i try to search for similar error on the internet but couldn't find any. so i don't know what to do.

**Comment by dedizones** [comment]
try other adress pool ? eu or us pool !

**Comment by rayhaankhan** [comment]
> try other adress pool ? eu or us pool !
> 
> 

Thanks, it helped😁
