### ISSUE TITLE
T-Rex instance wasn't validated issue.

### ISSUE THREAD

**Issue by a-triant** [trexminer/T-Rex#984]
In my case, after a power failure, my miner PC self power on, in like a minute it is ready, however my modem need more time to establish an internet connection. As you can see in the screenshot, miner tries to connect while the internet connection is still not available and then exits, as result every time after a power failure I have to connect to the miner and restart manually T-rex.

The solution for this issue will be if the T-rex will check if the internet connection is available or if it successfully connected to pool (which will mean that the connection is available) and only after that to try to connect to the T-rex server.

![InkedScreenshot 2022-01-02 160714](https://user-images.githubusercontent.com/22340405/148660467-51898607-75c0-4823-ba99-6b1f45ba58fa.jpg)

**Comment by trexminer** [comment]
It's a known issue but thanks for reporting. As a workaround you can make a loop in your bat file so that the miner restarts automatically:
```
:start
t-rex.exe -a ethash <blah blah>
goto start
```
