### ISSUE TITLE
how to tell if I'm receiving ETHEREUM? and 

### ISSUE THREAD

**Issue by rayhaankhan** [trexminer/T-Rex#985]
![Screenshot (133)](https://user-images.githubusercontent.com/72562797/148673641-cab29667-9bcd-406a-b4a2-67d441c3ba25.png)

**Comment by trexminer** [comment]
Check your mining pool's (ethermine) dashboard. The pool pays you, not the miner.
The miner is working OK according to the screenshot you provided.
