### ISSUE TITLE
error with etchash

### ISSUE THREAD

**Issue by Z0uden** [trexminer/T-Rex#99]
the program just continue to loop that, someone know what could be the problem?
gtx 950M (4gb)
i7-6700hq
all the program and driver are update
(that's the first time that I try to mine)

C:\Users\simo9\Desktop\t-rex>t-rex.exe -a etchash --coin etc -o stratum+tcp://etc.2miners.com:1010 -u 0x5440385f109c4143A2c50A5CACB4f633bDB41D49 -p x
20201129 01:26:16 T-Rex NVIDIA GPU miner v0.18.11  -  [CUDA v11.10]
20201129 01:26:16 r.2c8851280f45
20201129 01:26:16
20201129 01:26:17 WARN: Unknown vendor id 0x103c of GPU nvml_id=#0
20201129 01:26:17 NVIDIA Driver v452.06
20201129 01:26:17 CUDA devices available: 1
20201129 01:26:17
20201129 01:26:17 WARN: DevFee 1% (etchash)
20201129 01:26:17
20201129 01:26:17 URL : stratum+tcp://etc.2miners.com:1010
20201129 01:26:17 USER: 0x5440385f109c4143A2c50A5CACB4f633bDB41D49
20201129 01:26:17 PASS: x
20201129 01:26:17
20201129 01:26:17 Starting on: etc.2miners.com:1010
20201129 01:26:17 ApiServer: HTTP server started on 0.0.0.0:4067
20201129 01:26:17 ------------------------------------------------------
20201129 01:26:17 For control navigate to: http://192.168.1.22:4067/trex
20201129 01:26:17 ------------------------------------------------------
20201129 01:26:17 ApiServer: Telnet server started on 0.0.0.0:4068
20201129 01:26:17 Using protocol: stratum1.
20201129 01:26:17 Authorizing...
20201129 01:26:17 WARN: GPU #0(000100): GeForce GTX 950M, intensity set to 22
20201129 01:26:17 Authorized successfully.
20201129 01:26:17 etchash epoch: 195, block: 11701119, diff: 1.192 = 8.59 Gh
20201129 01:26:18 WARN: NVML: can't get fan speed for GPU #0, not supported
20201129 01:26:18 WARN: NVML: can't get power for GPU #0, not supported
20201129 01:26:19 GPU #0: generating DAG 2.52 GB for epoch 195(390) ...
20201129 01:26:36 etchash epoch: 195, block: 11701120, diff: 1.192 = 8.59 Gh
20201129 01:26:44 etchash epoch: 195, block: 11701121, diff: 1.192 = 8.59 Gh
20201129 01:26:50 GPU #0: DAG generated [time: 31213 ms], memory left: 835.01 MB
20201129 01:26:52 ERROR: Can't find nonce with device [ID=0, GPU #0], cuda exception in [Ethash::benchmark_kernel, 57], the launch timed out and was terminated
20201129 01:26:52 WARN: Miner is going to shutdown...
20201129 01:26:52 Main loop finished. Cleaning up resources...
20201129 01:26:52 ApiServer: stopped listening on 0.0.0.0:4067
20201129 01:26:52 ApiServer: stopped listening on 0.0.0.0:4068

**Comment by trexminer** [comment]
Hi, try running the miner with `-i 20 --kernel 2` extra parameters and see if it fixes the issue.

**Comment by Z0uden** [comment]
Thank! now is working fine
