### ISSUE TITLE
Problem with the share

### ISSUE THREAD

**Issue by Frezo001** [trexminer/T-Rex#990]
Hi @trexminer,

I'm a novice in the minnig and i've got a problem with my shares and don't know how to solve it

[T:55 C, P:130W, F:31%, E:166kH/W],  0/2 R:100%
Shares/min: 0

WD: 31 mins 38 secs,  shares: 0/2

20220111 12:35:28 [FAIL] 0/3 - Low difficulty, 26ms ... GPU #0
 and after 30 min I have still nothing on binance, is it normal?

**Comment by trexminer** [comment]
Not normal. You could be mining the wrong algorithm. If you post the full log file, I or someone else might be able to help you.

**Comment by Gigamining** [comment]
For Mining on Binance pool you need to setup your miner first otherwise your hasrate is going to someone else account and you're mining for other person, this happens to me, when I checked my Binance pool someone mined for me approx 0.00100 eth.

**Comment by Frezo001** [comment]
Ok i think i know where i did something wrong, instead of writting the code in the ETH-2miners ,I  wrote it in the ETC-2miners

**Comment by trexminer** [comment]
That's what I thought. Mining `etchash` to `ethash` pool. Thanks for letting me know.
